### ISSUE TITLE
0.42.x - error "daemonize.Run: readFromProcess: Decode: EOF" when mounting bucket

### ISSUE THREAD

**Issue by dcosta-clgx** [GoogleCloudPlatform/gcsfuse#1000]
Encountered this error after installing latest version 0.42.1:

```
$ /usr/bin/gcsfuse --implicit-dirs --uid 2003--gid 2003 "bucket-name" /csi_share
2023/03/08 17:17:37.801797 Start gcsfuse/0.42.1 (Go version go1.19.5) for app "" using mount point: /csi_share
2023/03/08 17:17:37.816623 Opening GCS connection...
daemonize.Run: readFromProcess: Decode: EOF
```

Since this had previously worked, I tried downgrading to earlier versions.  The same error occurred with 0.42.0, but the mount succeeded with 0.41.12.

After looking at some other recently reported issues, I also tried using 0.42.1 with the option --enable-storage-client-library=false, in which case the mount succeeded.  I will use this as a workaround, but wanted to report the issue.

System info:
 - OS: CentOS 7
 - Platform GCP VM
 - Version 0.42.1

**Comment by vadymnych** [comment]
have same issue
```
2023-03-07 17:54:58.947 EET
Calling gcsfuse with arguments: --key-file /app/credentials/key.json -o rw --implicit-dirs app /mount/path-mount
2023-03-07 17:54:58.967 EET
2023/03/07 15:54:58.966881 Start gcsfuse/0.42.1 (Go version go1.19.5) for app "" using mount point: /mount/path-mount
2023-03-07 17:54:58.994 EET
2023/03/07 15:54:58.993509 Opening GCS connection...
```

**Comment by zarmomin** [comment]
same here

**Comment by raj-prince** [comment]
@dcosta-clgx , @zarmomin , @ledmil01 

Can you please try running the mount command with --debug_gcs --debug_fs --debug_http and --foreground flags. I want to know the underline error message in this scenario.

Thanks!
-Prince.

**Comment by dcosta-clgx** [comment]
Hi @raj-prince. Here's what I got with the debug switches. Thanks for your help!


`$ /usr/bin/gcsfuse --debug_gcs --debug_fs --debug_http --foreground --implicit-dirs --uid 2003 --gid 2003  my-bucket /XXX
2023/03/10 21:51:11.034961 Start gcsfuse/0.42.1 (Go version go1.19.5) for app "" using mount point: /XXX
2023/03/10 21:51:11.035074 Opening GCS connection...
2023/03/10 21:51:11.037392 Creating a mount at “/XXX”
2023/03/10 21:51:11.037811 Creating a new server...
2023/03/10 21:51:11.037825 Set up root directory for bucket my-bucket
gcs: 2023/03/10 21:51:11.092011 Req              0x0: <- ListObjects("")
gcs: 2023/03/10 21:51:11.129602 Req              0x0: -> ListObjects("") (37.582653ms): OK
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa889ff]

goroutine 1 [running]:
github.com/googlecloudplatform/gcsfuse/internal/storage/storageutil.convertACLRuleToObjectAccessControl(...)
	/tmp/build_gcsfuse_gopath3986937209/src/github.com/googlecloudplatform/gcsfuse/internal/storage/storageutil/object_attrs.go:48
github.com/googlecloudplatform/gcsfuse/internal/storage/storageutil.ObjectAttrsToBucketObject(0xc0008e4000)
	/tmp/build_gcsfuse_gopath3986937209/src/github.com/googlecloudplatform/gcsfuse/internal/storage/storageutil/object_attrs.go:58 +0x5ff
github.com/googlecloudplatform/gcsfuse/internal/storage.(*bucketHandle).ListObjects(0xc0006abd70, {0x11648d0, 0xc00003a1a0}, 0xc00058b5e0)
	/tmp/build_gcsfuse_gopath3986937209/src/github.com/googlecloudplatform/gcsfuse/internal/storage/bucket_handle.go:245 +0x2aa
github.com/googlecloudplatform/gcsfuse/vendor/github.com/jacobsa/gcloud/gcs.(*debugBucket).ListObjects(0xc00053c8a0, {0x11648d0, 0xc00003a1a0}, 0xc00058b5e0)
	/tmp/build_gcsfuse_gopath3986937209/src/github.com/googlecloudplatform/gcsfuse/vendor/github.com/jacobsa/gcloud/gcs/debug_bucket.go:207 +0x16b
github.com/googlecloudplatform/gcsfuse/vendor/github.com/jacobsa/gcloud/gcs/gcscaching.(*fastStatBucket).ListObjects(0xc00040d380, {0x11648d0?, 0xc00003a1a0?}, 0xc00090f101?)
	/tmp/build_gcsfuse_gopath3986937209/src/github.com/googlecloudplatform/gcsfuse/vendor/github.com/jacobsa/gcloud/gcs/gcscaching/fast_stat_bucket.go:219 +0x34
github.com/googlecloudplatform/gcsfuse/internal/gcsx.(*bucketManager).SetUpBucket(0xc000377dd0, {0x11648d0, 0xc00003a1a0}, {0x7ffdb7bab648?, 0x70?})
	/tmp/build_gcsfuse_gopath3986937209/src/github.com/googlecloudplatform/gcsfuse/internal/gcsx/bucket_manager.go:248 +0x5c4
github.com/googlecloudplatform/gcsfuse/internal/fs.NewFileSystem({0x11648d0, 0xc00003a1a0}, 0xc0005df5e8)
	/tmp/build_gcsfuse_gopath3986937209/src/github.com/googlecloudplatform/gcsfuse/internal/fs/fs.go:167 +0x47a
github.com/googlecloudplatform/gcsfuse/internal/fs.NewServer({0x11648d0?, 0xc00003a1a0?}, 0xc0008c15e8)
	/tmp/build_gcsfuse_gopath3986937209/src/github.com/googlecloudplatform/gcsfuse/internal/fs/server.go:28 +0x2f
main.mountWithConn({0x11648d0, 0xc00003a1a0}, {0x7ffdb7bab648, 0x30}, {0x7ffdb7bab679, 0xa}, 0xc0004a06e0, 0x203000?, {0x1159d80, 0xc000014560}, ...)
	/tmp/build_gcsfuse_gopath3986937209/src/github.com/googlecloudplatform/gcsfuse/mount.go:122 +0x4ba
main.mountWithArgs({0x7ffdb7bab648, 0x30}, {0x7ffdb7bab679, 0xa}, 0xc0004a06e0, 0xc0005df788?)
	/tmp/build_gcsfuse_gopath3986937209/src/github.com/googlecloudplatform/gcsfuse/main.go:205 +0x2d2
main.runCLIApp(0x1836d30?)
	/tmp/build_gcsfuse_gopath3986937209/src/github.com/googlecloudplatform/gcsfuse/main.go:369 +0xf25
main.run.func1(0x1?)
	/tmp/build_gcsfuse_gopath3986937209/src/github.com/googlecloudplatform/gcsfuse/main.go:404 +0x25
github.com/googlecloudplatform/gcsfuse/vendor/github.com/urfave/cli.HandleAction({0xcd6640?, 0xc0003b0150?}, 0xc000422700?)
	/tmp/build_gcsfuse_gopath3986937209/src/github.com/googlecloudplatform/gcsfuse/vendor/github.com/urfave/cli/app.go:526 +0x50
github.com/googlecloudplatform/gcsfuse/vendor/github.com/urfave/cli.(*App).Run(0xc000422700, {0xc0000360c0, 0xc, 0xc})
	/tmp/build_gcsfuse_gopath3986937209/src/github.com/googlecloudplatform/gcsfuse/vendor/github.com/urfave/cli/app.go:286 +0x7ca
main.run()
	/tmp/build_gcsfuse_gopath3986937209/src/github.com/googlecloudplatform/gcsfuse/main.go:408 +0xcb
main.main()
	/tmp/build_gcsfuse_gopath3986937209/src/github.com/googlecloudplatform/gcsfuse/main.go:426 +0x4a
`

**Comment by sethiay** [comment]
The fix for this issue has been released in the latest GCSFuse release i.e. **[v0.42.2](https://github.com/GoogleCloudPlatform/gcsfuse/releases/tag/v0.42.2)**. With GCSFuse v0.42.2, you can **skip passing** --enable-storage-client-library=false flag as workaround.
Marking this issue as closed. Please feel free to re-open in case you face the same issue again.

Thanks for your patience !
