### ISSUE TITLE
mount_gcsfuse not respecting bool values when passed to bool flags e.g. enable_storage_client_library

### ISSUE THREAD

**Issue by sethiay** [GoogleCloudPlatform/gcsfuse#1014]
**Description:**
We add entries to the /etc/fstab file using mount_gcsfuse however it doesn't look as though that handles being able to set the value =false to disable it

[gcsfuse/tools/mount_gcsfuse/main.go](https://github.com/GoogleCloudPlatform/gcsfuse/blob/13d73e27d22a51ba5d71286f745ef32e2964cac8/tools/mount_gcsfuse/main.go#L90)

Line 90 in [13d73e2](https://github.com/GoogleCloudPlatform/gcsfuse/commit/13d73e27d22a51ba5d71286f745ef32e2964cac8)

 args = append(args, "--"+strings.Replace(name, "_", "-", -1)) 
I tried

    mount_line = ('%s /sftp/%s/upload gcsfuse rw,' '_netdev,allow_other,uid=%u,gid=%u,enable_storage_client_library=false' % (fuse_bucket, account['user'], uid, gid))

which just ignored the flag

    mount_line = ('%s /sftp/%s/upload gcsfuse rw,' '_netdev,allow_other,uid=%u,gid=%u,--enable-storage-client-library=false' % (fuse_bucket, account['user'], uid, gid))

and this didn't work, it add -o --enable-storage-client-library=false

Am I doing something wrong or is it an issue ? Any advice will be much appreciated

**Additional Information:**
This issue is reported by @WobblyRobbly [here](https://github.com/GoogleCloudPlatform/gcsfuse/issues/982#issuecomment-1462945792).

**Comment by vadlakondaswetha** [comment]
Boolean flags are set as true by default and actual values are not considered.

https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/tools/mount_gcsfuse/main.go#L89
