### ISSUE TITLE
Systemd service cannot access mounted bucket directory: permission denied

### ISSUE THREAD

**Issue by oztasoi** [GoogleCloudPlatform/gcsfuse#1020]
Greetings everyone, I've encountered an issue regarding permissions of a mount directory

```
drwxr-xr-x  5 ibrahim.ozgurcan ibrahim.ozgurcan 4096 Mar 24 16:30 .
drwxr-xr-x 12 ibrahim.ozgurcan ibrahim.ozgurcan 4096 Mar 24 16:18 ..
drwxr-xr-x  2 ibrahim.ozgurcan ibrahim.ozgurcan 4096 Mar 24 16:14 benchmark_01
drwxr-xr-x  2 ibrahim.ozgurcan ibrahim.ozgurcan 4096 Mar 24 16:14 evaluation_PROD
d?????????  ? ?                ?                ?           ?     experiments
```

This `experiments` folder is the mount point of a GCP storage bucket, and I've mounted it with the command below:

```
mkdir /tmp/myfolder/my-python-application/resources/experiments
gcsfuse --implicit-dirs --enable-storage-client-library=false $(cat /tmp/myfolder/misc/bucketname.txt) /tmp/myfolder/my-python-application/resources/experiments
```

I run these commands in an Ansible Playbook task to automate my processes, and as a next step, I configure `systemd` to run my python app, which is a ML training application. In the application, the model needs to load the `config.json` file from a subdirectory of this `experiments` folder, and as a debug, I've added an `ls` command in the service configuration file, but  I encounter this:

```
ls: cannot access '/tmp/myfolder/my-python-application/resources/experiments': Permission denied
```

What could be a possible solution or what would you suggest for me to follow as a next step?
Thanks in advance.

**Comment by Tulsishah** [comment]
Hi @oztasoi , for reaching out to us. 
Can you please run ```gcloud application default login``` or pass key-file of your service account and check if you facing the same problem or not.
If you are still facing problem than please share gcsfuse logs with --debug_gcs and --debug_fuse flags

**Comment by Tulsishah** [comment]
> Maybe there is some problem with the permissions to access the folder? https://serverfault.com/a/217676 suggests `sudo chmod -R g+x <DIR>`

So your problem gets resolved?
If no, please follow the above steps and share the logs.

**Comment by sethiay** [comment]
Closing this issue as we haven't got response for more than 30 days. Please re-open if you are still facing the issue.

**Comment by stevancris** [comment]
I got the same issue when I mounted the bucket GCP to one of the directories on the compute engine, and then I created a file or directory, and got the error "permission denied". How do we solve this issue?

**Comment by ashmeenkaur** [comment]
Hi @stevancris,

Thanks for bringing this issue to our attention. Have you had a chance to try the solution suggested in https://github.com/GoogleCloudPlatform/gcsfuse/issues/1020#issuecomment-1484824663?

If you have already tried this solution, please share the logs with --debug_gcs and --debug_fuse flags.

Thanks,
Ashmeen

**Comment by stevancris** [comment]
I've tried authentication with manual login gcloud command `gcloud auth activate-service-account --key-file serviceaccount.json` then execute command gcsfuse mounting volume. But I tried in other compute engine without gcloud auth login in first step, to execute command gcsfuse with option global key file, it's doing well

**Comment by ashmeenkaur** [comment]
The discrepancy you observed is likely due to the default GCE VM credentials being used when the bucket and GCE VM reside within the same project. This means that explicit authentication using the service account key file is not strictly required in such cases.

Could you also please confirm that the Cloud Storage API was granted full access under the access scope during the VM creation process? (the default scope typically only includes GCS read-only access)

Link to documentation about authentication with gcsfuse is available [here](https://cloud.google.com/storage/docs/gcsfuse-mount#authenticate_requests).
