### ISSUE TITLE
Input/output error [when there is no files] & issues with touch

### ISSUE THREAD

**Issue by akcchoi** [GoogleCloudPlatform/gcsfuse#104]
Hi all,

System: Debian 7.8, VM instance

1. Input/Output error:
After fs is mounted, if there is no files (even with directories) at the top level, I will get Input/Output error:

    mount:
    ......
    ac_test1 on /home/andykc_choi/gcs type fuse (rw,nosuid,nodev,relatime,user_id=1001,group_id=1001,default_permissions)

Now, I try to do something with the mounted fs

    andykc_choi@fuse-1:~/gcs$ ls
    code foo repo t1
    andykc_choi@fuse-1:~/gcs$ rm foo
    andykc_choi@fuse-1:~/gcs$ ls
    ls: reading directory .: Input/output error

    [code, repo and t1 are directories]

Output from gcsfuse:

    fuse: 2015/08/05 09:18:20.810236 *fuseops.ReadDirOp error: readAllEntries: ReadEntries: ListObjects: EOF

2. touch: setting times of `foo': Function not implemented

touch would complain function not implemented (and return 1) despite the file has been created:

    andykc_choi@fuse-1:~/gcs$ touch foo
    touch: setting times of `foo': Function not implemented
    andykc_choi@fuse-1:~/gcs$ echo $?
    1
    andykc_choi@fuse-1:~/gcs$ ls
    code foo repo t1

Many thanks,

Andy

**Comment by jacobsa** [comment]
This was fixed in [v0.6.0](https://github.com/GoogleCloudPlatform/gcsfuse/releases/tag/v0.6.0). Please update by following [these](https://github.com/googlecloudplatform/gcsfuse/blob/master/docs/installing.md) instructions, and let me know if your issue doesn't go away.
