### ISSUE TITLE
--debug_http doesn't work with --enable-storage-client-library=true

### ISSUE THREAD

**Issue by MattIrv** [GoogleCloudPlatform/gcsfuse#1049]
**Describe the bug**

I was trying to debug another issue and finding that the `--debug_http` flag documented in https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/mounting.md doesn't seem to make any difference on the log output when using `--enable-storage-client-library=true`

**To Collect more Debug logs**
1. Please make sure you have no other security, monitoring, background processes which can offend the FUSE process running. Possibly reproduce under a fresh/clean installation.
2. Please rerun with --debug_fuse --debug_fs --debug_gcs --debug_http --foreground as additional flags to enable debug logs.
3. Monitor the logs and please capture screenshots or copy the relevant logs to a file (can use --log-format and --log-file as well).
4. Attach the screenshot or the logs file to the bug report here.
5. If you're using gcsfuse with any other library/tool/process please list out the steps you took to reproduce the issue.

**With default `--enable-storage-client-library`**
  1. `gcsfuse --debug_fuse --debug_fs --debug_gcs --debug_http --foreground _ mp`
  2. `ls mp/<bucket>`
  3. Log output doesn't contain HTTP logs:  [logs-gcs-library.txt](https://github.com/GoogleCloudPlatform/gcsfuse/files/11183943/logs-gcs-library.txt)

It also happens with JSON format logs and when outputting to a log file instead of to stdout

**With `--enable-storage-client-library=false`**
  1. `gcsfuse --debug_fuse --debug_fs --debug_gcs --debug_http --foreground --enable-storage-client-library=false _ mp`
  2. `ls mp/<bucket>`
  3. Log output contains HTTP logs (trimmed):  [logs-gcloud-library.txt](https://github.com/GoogleCloudPlatform/gcsfuse/files/11183947/logs-gcloud-library.txt)

**System (please complete the following information):**
 - OS: Ubuntu 22.04
 - Platform: VM (GCE)
 - Version: 

```
$ gcsfuse -v
gcsfuse version 0.42.3 (Go version go1.19.5)
```

**Comment by raj-prince** [comment]
Hi @MattIrv,

Thanks for reporting!

This is a valid bug that `--debug_http` flag doesn't work with `--enable-storage-client-library=true`. 

To fix this issue, there is a dependency on go-storage-client library team, right now no API available in go-storage-client library using that we can write the traces.

We have created a bug for this issue our side. I'll update this thread, once we finalize something for this issue.

Regards,
Prince Kumar.

**Comment by raj-prince** [comment]
Hi @MattIrv,

We discussed this issue within the team and decided to not support this flag for storage-client library. We have updated the help description for `--debug_http` flag accordingly.

-Prince.
