### ISSUE TITLE
group fuse not created on Debian Jessie

### ISSUE THREAD

**Issue by akcchoi** [GoogleCloudPlatform/gcsfuse#105]
Hi all,

It seems that group "fuse" was not created by the fuse's installation script on the default Jessie VM image, but it is done for Wheezy (back-port) image:

In 7.8 Wheezy back-port:

    $ sudo apt-get install fuse
    Reading package lists... Done
    Building dependency tree Reading state information... Done
    The following NEW packages will be installed: 
    fuse
    0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
    Need to get 74.2 kB of archives.After this operation, 179 kB of additional disk space will be used.
    Get:1 http://security.debian.org/ wheezy/updates/main fuse amd64 2.9.0-2+deb7u2 [74.2 kB]
    Fetched 74.2 kB in 0s (599 kB/s)
    Selecting previously unselected package fuse.
    (Reading database ... 20074 files and directories currently installed.)
    Unpacking fuse (from .../fuse_2.9.0-2+deb7u2_amd64.deb) ...
    Processing triggers for initramfs-tools ...
    update-initramfs: Generating /boot/initrd.img-3.16.0-0.bpo.4-amd64
    /var/tmp/mkinitramfs_lkOQRm/scripts/local-premount/gce-disable-growroot: 7: .: Can't open /scripts/functions
    Processing triggers for man-db ...
    Setting up fuse (2.9.0-2+deb7u2) ...
    Creating fuse group...
    Adding group `fuse' (GID 105) ... 
    Done.
    udev active, skipping device node creation.
    update-initramfs: deferring update (trigger activated)
    Processing triggers for initramfs-tools ...
    update-initramfs: Generating /boot/initrd.img-3.16.0-0.bpo.4-amd64
    /var/tmp/mkinitramfs_YNssRH/scripts/local-premount/gce-disable-growroot: 7: .: Can't open /scripts/functions

In Jessie 8.1:

    sudo apt-get install wget fuse
    Reading package lists... Done
    Building dependency tree 
    Reading state information... Done
    wget is already the newest version.
    The following NEW packages will be installed: 
    fuse
    0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
    Need to get 70.4 kB of archives.After this operation, 112 kB of additional disk space will be used.
    Do you want to continue? [Y/n] 
    Get:1 http://gce_debian_mirror.storage.googleapis.com/ jessie/main fuse amd642.9.3-15+deb8u1 [70.4 kB]
    Fetched 70.4 kB in 0s (538 kB/s)
    Selecting previously unselected package fuse.
    (Reading database ... 18095 files and directories currently installed.)
    Preparing to unpack .../fuse_2.9.3-15+deb8u1_amd64.deb ...
    Unpacking fuse (2.9.3-15+deb8u1) ...
    Processing triggers for man-db (2.7.0.2-5) ...
    Setting up fuse (2.9.3-15+deb8u1) ...
    update-initramfs: deferring update (trigger activated)
    Processing triggers for initramfs-tools (0.120) ...
    update-initramfs: Generating /boot/initrd.img-3.16.0-4-amd64
    /etc/initramfs-tools/scripts/local-premount/gce-disable-growroot: 7: .: Can't open /scripts/functions

it seems that some triggers are not triggered with Jessie.

fuse version:
wheezy: 2.9.0-2+deb7u2
jesssie: 2.9.3-15+deb8u1

Many thanks,
Andy

**Comment by akcchoi** [comment]
Seems that fuse group is no longer required in Jessie:
https://wiki.debian.org/SystemGroups

Perhaps, it would be useful to update the documentation?

**Comment by jacobsa** [comment]
Thanks for the report. I didn't even know a Debian 8 image had been added to GCE. I confirm that `fuse` doesn't exist after setting up a `debian-8` VM, and doesn't need to. Will update the docs.
