### ISSUE TITLE
guard OS specific syscalls with file build tags

### ISSUE THREAD

**Issue by codyoss** [GoogleCloudPlatform/gcsfuse#1078]
I was looking at this repo earlier today to look into an issue and notices some files in the tools .integration_tests dir use syscalls that my m1 mac did not like making it so I could not build the project locally. I would recommend guarding such syscalls with build tags -- or document limitations that this project can only work on linux. But since this was just in the testing dir it seems like boarder compatibility could be achieved by using tags.

**Comment by Tulsishah** [comment]
Hi @codyoss, gcsfuse is not supporting mac os, which is mentioned [here](https://github.com/GoogleCloudPlatform/gcsfuse#supported-operating-systems).
Thanks for your suggestion. We will look into it.

**Comment by sethiay** [comment]
Closing in favor of https://github.com/GoogleCloudPlatform/gcsfuse/issues/1078#issuecomment-1524730158
