### ISSUE TITLE
Include mount.gcsfuse in package?

### ISSUE THREAD

**Issue by saturnism** [GoogleCloudPlatform/gcsfuse#108]
This would be great for fstab integration.

**Comment by jacobsa** [comment]
Good idea; I'll make the release process more amenable to fstab integration.

**Comment by jacobsa** [comment]
@saturnism: Could you please follow the [installation](https://github.com/googlecloudplatform/gcsfuse/blob/master/docs/installing.md) and [mounting](https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/mounting.md) instructions anew and let me know how this works for you?

**Comment by jacobsa** [comment]
(Make sure to follow all of the steps. In particular, you'll need to install `daemon` if you haven't already, and gcsfuse v0.9.0.)

**Comment by saturnism** [comment]
nice! :+1: tested this as well. awesome.
