### ISSUE TITLE
Support renaming

### ISSUE THREAD

**Issue by jacobsa** [GoogleCloudPlatform/gcsfuse#11]
Relevant fuse request struct: [bazilfuse.RenameRequest](http://godoc.org/github.com/jacobsa/bazilfuse#RenameRequest)

Unfortunately we can't do this atomically. So:

* For files, we'll probably want to clone and then delete behind.
* For directories, I guess we want to clone recursively and then delete behind. _Ugh._
* Add both of these to the "surprising behavior" section in [semantics.md](https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/semantics.md).

**Comment by jacobsa** [comment]
This is a bad idea to implement, for the following reasons:

*   We cannot do it atomically. Unfortunately [atomic renaming](http://en.wikipedia.org/wiki/Rename_(computing)) is a file system guarantee that is very frequently relied upon, implicitly or explicitly. So this would be a bug haven.

*   Implementing it as described above means that a single rename operation can be arbitrarily expensive. This isn't a nice attribute for operations to have.

So I'm going to remove the implicit to-do from the readme, and close this as working as intended for now. If there is a user who needs this and is convincing enough, we can consider implementing it and putting it behind an `--unsafe_support_renames` flag or similar.

**Comment by javiercbk** [comment]
Hey guys,

I would be great to document all the caveats of this library. Don't get me wrong, this is a fantastic library BUT I just got bitten by the "no renaming directory" support.

In my opinion a simple entry on the README.md would suffice.

Thanks

**Comment by jacobsa** [comment]
It's already documented [here](https://github.com/googlecloudplatform/gcsfuse/blob/941ac7e9afb3ef89a51100e10b418e1f90c22388/docs/semantics.md#missing-features) in the semantics document, which is important reading if you care about details like this.
