### ISSUE TITLE
Poor error message when mount point doesn't exist on darwin

### ISSUE THREAD

**Issue by jacobsa** [GoogleCloudPlatform/gcsfuse#110]
When mounting without `~/tmp/mp` existing:

    2015/08/07 14:26:38.989904 Mounting file system: Mount: newConnection: Init: Reading init op: EOF

**Comment by kanghq** [comment]
Have a similar issue

csfuse --debug_gcs bucket-name /mnt/storage/
Using mount point: /mnt/storage
Opening GCS connection...
Opening bucket...
Mounting file system...
daemonize.Run: readFromProcess: sub-process: mountWithArgs: mountWithConn: Mount: newConnection: Init: Reading init op: EOF
