### ISSUE TITLE
gcsfuse doesn't install on Ubuntu 14.04.2

### ISSUE THREAD

**Issue by saturnism** [GoogleCloudPlatform/gcsfuse#112]
````
Welcome to Ubuntu 14.04.2 LTS (GNU/Linux 3.16.0-31-generic x86_64)
$ cat /etc/debian_version 
jessie/sid
````

````
apt-get install gcsfuse
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 gcsfuse : Depends: daemon but it is not installable
E: Unable to correct problems, you have held broken packages.
````

**Comment by jacobsa** [comment]
Thanks for the report. I'll look into it soon, but in the meantime you
should be able to download the 0.9.0 deb package from the GitHub releases
page and install it with dpkg. It doesn't include this dependency.

By the way, do you know why it can't install daemon? Is it missing from the
Ubuntu repo on this version?

**Comment by jacobsa** [comment]
@saturnism: I'm unable to reproduce this on a fresh GCE VM running the `ubuntu-14-04` image, whose version looks like this:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty
```

Following the [instructions](https://github.com/googlecloudplatform/gcsfuse/blob/45b9eb9364b5f747c0edfd7fe1c01490b73656df/docs/installing.md#ubuntu-and-debian) works fine there. Can you give me instructions to reproduce?

**Comment by saturnism** [comment]
Sorry just saw that my /etc/apt/sources.list only had a single line:
````
deb http://packages.cloud.google.com/apt gcsfuse-trusty main
````

Not entirely sure how it got there. But I just went through the instruction again on a clean instance and it seemed fun.  Apologies!

**Comment by jacobsa** [comment]
No worries, glad you figured it out.

**Comment by adojaan** [comment]
I got the same problem and I guess why. The cause is probably incorrect copy & paste at the page https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/installing.md. By mistake I copied the command on the second line: echo "deb http://packages.cloud.google.com/apt $GCSFUSE_REPO main" | sudo tee /etc/apt/sources.list.d/gcsfuse.list also only partially (just the visible part)  echo "deb http://packages.cloud.google.com/apt $GCSFUSE_REPO main" | sudo tee /etc/apt/sources.list that resulted in overwriting old sources.lst file!! I got the same error message, and did not notice my mistake before, but when browsing history of latest commands I noticed incomplete command.

**Comment by saturnism** [comment]
ah hah.. that was definitely it! that explains why my source.list had only one line. :)

**Comment by ahjohn** [comment]
I'm experiencing similar issue (daemon dependency error) but with CentOS 7.1 & RHEL 7.1.  I'm following instructions as per https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/installing.md exactly.

RHEL 7.1 error:
sudo yum install gcsfuse
Resolving Dependencies
--> Running transaction check
---> Package gcsfuse.x86_64 0:0.11.1-1 will be installed
--> Processing Dependency: fuse for package: gcsfuse-0.11.1-1.x86_64
--> Processing Dependency: daemon for package: gcsfuse-0.11.1-1.x86_64
--> Running transaction check
---> Package fuse.x86_64 0:2.9.2-5.el7 will be installed
---> Package gcsfuse.x86_64 0:0.11.1-1 will be installed
--> Processing Dependency: daemon for package: gcsfuse-0.11.1-1.x86_64
--> Finished Dependency Resolution
Error: Package: gcsfuse-0.11.1-1.x86_64 (gcsfuse)
           Requires: daemon
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

Can anyone help?  Thanks.
