### ISSUE TITLE
Profile/pressure analisys best practices

### ISSUE THREAD

**Issue by bhack** [GoogleCloudPlatform/gcsfuse#1159]
Can you add a clear list of best practices to test the sidecar resource allocation? From the current documentation it seems to be a little bit "black magic".
It is hard to understand on real workload if the sidecar is under pressure and it requires additional memory and CPU limits.

**Comment by sethiay** [comment]
@bhack We recommend opening an issue under [Cloud Storage FUSE CSI driver repo](https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/issues) if you face any issues related to the driver.

**Comment by bhack** [comment]
Ok, as it is on the same Github org can you migrate the ticket?

**Comment by bhack** [comment]
https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/issues/34
