### ISSUE TITLE
Be clearer in the docs that you should not run as root

### ISSUE THREAD

**Issue by saturnism** [GoogleCloudPlatform/gcsfuse#117]
If you run gcsfuse as root, and mount a bucket, the other users will see something like this below:

$ ls: cannot access /mnt/gcs: Permission denied
total 0
d????????? ? ? ? ?            ? gcs

Secondly, fstab support seems broken:
$ mount /mnt/mymountpoint
 ^-- no errors
$ ls /mnt/mymountpoint
 ^-- empty
$ umount /mnt/mymountpoint
umount: /mnt/mymountpoint/: not mounted

**Comment by jacobsa** [comment]
This is expected—you shouldn't be running as root if you want a mount point that your user can access. I will update the docs to be more explicit about this.

Regarding your fstab issue: because of the way that `mount` wants its helpers to daemonize and return immediately, there is no opportunity to return an error from `mount` itself. If you want to debug, edit `/sbin/mount.gcsfuse` and e.g. set the destination for stderr to something besides `/dev/null` or set the `-f` option to `daemonize`.

**Comment by saturnism** [comment]
2015/08/31 00:23:48 Arg 0: "/usr/bin/mount_gcsfuse"
2015/08/31 00:23:48 Arg 1: "speedy-sunspot-862-bucket"
2015/08/31 00:23:48 Arg 2: "/mnt/gcs"
2015/08/31 00:23:48 Arg 3: "-o"
2015/08/31 00:23:48 Arg 4: "rw,noexec,nosuid,nodev,noauto,user"
2015/08/31 00:23:48 Device: "speedy-sunspot-862-bucket"
2015/08/31 00:23:48 Mount point: "/mnt/gcs"
2015/08/31 00:23:48 Option "noauto": ""
2015/08/31 00:23:48 Option "user": ""
2015/08/31 00:23:48 Option "rw": ""
2015/08/31 00:23:48 Option "noexec": ""
2015/08/31 00:23:48 Option "nosuid": ""
2015/08/31 00:23:48 Option "nodev": ""
2015/08/31 00:23:48 gcsfuse arg: "-o"
2015/08/31 00:23:48 gcsfuse arg: "rw"
2015/08/31 00:23:48 gcsfuse arg: "-o"
2015/08/31 00:23:48 gcsfuse arg: "noexec"
2015/08/31 00:23:48 gcsfuse arg: "-o"
2015/08/31 00:23:48 gcsfuse arg: "nosuid"
2015/08/31 00:23:48 gcsfuse arg: "-o"
2015/08/31 00:23:48 gcsfuse arg: "nodev"
2015/08/31 00:23:48 gcsfuse arg: "-o"
2015/08/31 00:23:48 gcsfuse arg: "noauto"
2015/08/31 00:23:48 gcsfuse arg: "speedy-sunspot-862-bucket"
2015/08/31 00:23:48 gcsfuse arg: "/mnt/gcs"
2015/08/31 00:23:48.342276 mount helper error: fusermount: mount failed: Invalid argument
2015/08/31 00:23:48.342429 Mounting file system: Mount: mount: fusermount: exit status 1
2015/08/31 00:23:48 gcsfuse failed or failed to run: exit status 1

**Comment by saturnism** [comment]
so, the mounting.md fstab example looks like:
````
my-bucket /mount/point gcsfuse rw,noauto,user
````

`noauto` is giving the trouble.
````
$ gcsfuse -o rw -o noexec -o nosuid -o nodev -o noauto speedy-sunspot-862-bucket /mnt/gcs
2015/08/31 00:28:16.048062 mount helper error: fusermount: mount failed: Invalid argument
2015/08/31 00:28:16.048223 Mounting file system: Mount: mount: fusermount: exit status 1
````

Removing `noauto` works but not sure if that's intended.

**Comment by saturnism** [comment]
lastly is the running-as-root behavior consistent w/ other fuse drivers?
or, should we simply fail fast when executing as root?

**Comment by jacobsa** [comment]
Please file a separate issue for each issue you're seeing or question you have. I don't want to lose track of what needs to be done in this one, which I'm reserving for documentation changes.

**Comment by jacobsa** [comment]
(Your [last question](https://github.com/GoogleCloudPlatform/gcsfuse/issues/117#issuecomment-136222738) is on topic. The answer: yes, fuse is made for mounting as an arbitrary user, not root. fuse itself restricts access to only the mounting user (see [here](https://github.com/torvalds/linux/blob/master/Documentation/filesystems/fuse.txt#L100-L103)). This is a security measure.)

**Comment by jacobsa** [comment]
@saturnism: Thanks for giving me the idea of printing a warning at runtime; I hope that will help with this issue, which is a common user confusion.
