### ISSUE TITLE
Install instructions leave system unbootable

### ISSUE THREAD

**Issue by flowlo** [GoogleCloudPlatform/gcsfuse#120]
I followed your install instructions (crucially containing some [`sudo tar -C /`](https://github.com/GoogleCloudPlatform/gcsfuse/blame/master/docs/installing.md#L120)) wiping my root file system in a way that I could not boot anymore.

This is because in Fedora, `/sbin` is just a symlink to `/usr/sbin`, which gets destroyed by untaring the tarball containing `gcsfuse`.

It is very easy to overlook that invocation, and therefore I would ask you to remove it and find a different way to install `gcsfuse` to prevent users from bricking their root filesystem.

Also, seeing a `sudo tar -C /` looks very suspicious.

**Comment by flowlo** [comment]
This is a duplicate of #119, which was reported 33 seconds earlier :open_mouth:

**Comment by jacobsa** [comment]
Thanks for the report, and very sorry for that; I didn't known that such a symlink setup was something I needed to worry about. Following up in #119.
