### ISSUE TITLE
gcsfuse and docker: could not find default credentials.

### ISSUE THREAD

**Issue by kernelt** [GoogleCloudPlatform/gcsfuse#121]
Hi Aaron. Long time "no see" :)
I try to use gcsfuse v0.11.1 in a docker container with fedora 22, but I get the message:
```
[root@test bin]# ./gcsfuse -dir-mode=0770 -file-mode=0770 -o allow_other -uid=1005 -gid=1005 my_bucket /mnt
2015/09/02 21:12:49.523665 getConn: DefaultTokenSource: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
```
However on the docker host machine it's works. 
Is it possible to fix it?

**Comment by jacobsa** [comment]
Hi, see the documentation on credentials [here](https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/mounting.md#credentials). You'll need to either configure your GCE VM with appropriate credentials when creating it (not sure how this interacts with Docker) or put a JSON key file in an appropriate location and point gcsfuse at it using --key-file or the `GOOGLE_APPLICATION_CREDENTIALS` environment variable.

Please let me know whether this works out for you.
