### ISSUE TITLE
gcsfuse 0.12.0 - can't mount with `mount -t gcsfuse`

### ISSUE THREAD

**Issue by saturnism** [GoogleCloudPlatform/gcsfuse#129]
It seems like the mount point is passed in as the bucket name to gcsfuse
```
$ mount -t gcsfuse -o rw,user speedy-sunspot-862-bucket /mnt/speedy-sunspot-862-bucket/
Calling gcsfuse with arguments: -o nodev -o rw -o noexec -o nosuid /mnt/speedy-sunspot-862-bucket /mnt/speedy-sunspot-862-bucket/
Opening GCS connection...
Opening bucket...
daemon.Mount: readFromGcsfuse: gcsfuse: mountFromContext: mount: setUpBucket: OpenBucket: Unknown bucket "/mnt/speedy-sunspot-862-bucket"
```

**Comment by jacobsa** [comment]
I'm unable to reproduce this on OS X (where `mount -t gcsfuse` is allowed by non-root users, unlike Linux). Could you clarify what OS you're running, and paste the output of `gcsfuse -v`?

**Comment by saturnism** [comment]
Not on OS X. This is on Ubuntu.

Will do that once I get a chance!

**Comment by jacobsa** [comment]
(I know you saw it, but for the record still waiting on `gcsfuse-v` and `uname -a` output.)

Any idea how it is that you're not getting a permission error for running `mount -t`? I've never not seen this:
```
$ mount -t gcsfuse -o rw,user speedy-sunspot-862-bucket /mnt/speedy-sunspot-862-bucket/
mount: only root can use "--options" option
```

**Comment by saturnism** [comment]
```
$ gcsfuse -v
gcsfuse version 0.12.0 (Go version go1.5.1)
```
```
$ uname -a
Linux google-machine 3.16.0-31-generic #43~14.04.1-Ubuntu SMP Tue Mar 10 20:13:38 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty
```
```
$ mount -t gcsfuse -o rw,user speedy-sunspot-862-bucket /mnt/speedy-sunspot-862-bucket/
mount: only root can do that
```

I was executing `mount -t ... ` as root :)

Now that you mentioned it, running `sudo mount -t` seems to work:
```
$ sudo mount -t gcsfuse speedy-sunspot-862-bucket /mnt/speedy-sunspot-862-bucket
Calling gcsfuse with arguments: -o rw speedy-sunspot-862-bucket /mnt/speedy-sunspot-862-bucket
Opening GCS connection...
Opening bucket...
Mounting file system...
File system has been successfully mounted.
```

**Comment by jacobsa** [comment]
So I'm confused. Is this working for you now?

**Comment by saturnism** [comment]
Ok, I think I ping pointed a way to reproduce this, both as root or prepending sudo:

1. Suppose the bucket I'm trying to mount is `speedy-sunspot-862-bucket`
1. `mkdir -p /mnt/speedy-sunspot-862-bucket`
1. `cd /mnt`
1. `mount -t gcsfuse speedy-sunspot-862-bucket /mnt/speedy-sunspot-862-bucket`

In which case, _something_ expanded `speedy-sunspot-862-bucket` as a full file path when invoking `gcsfuse`
```
Calling gcsfuse with arguments: -o rw /mnt/speedy-sunspot-862-bucket /mnt/speedy-sunspot-862-bucket
Opening GCS connection...
Opening bucket...
daemon.Mount: readFromGcsfuse: gcsfuse: mountFromContext: mount: setUpBucket: OpenBucket: Unknown bucket "/mnt/speedy-sunspot-862-bucket"
```

**Comment by jacobsa** [comment]
Hah, that's entertaining. It appears `mount` is doing this (not the shell), since I can't reproduce the issue in zsh or bash with this program:

```Go
package main

import (
        "fmt"
        "os"
)

func main() {
        for i, arg := range os.Args {
                fmt.Printf("Arg %d: %q\n", i, arg)
        }
}
```

I guess `mount` takes relative paths and canonicalizes them before sending there through. There's not much I can do here. :-/

**Comment by saturnism** [comment]
I was able to confirm mount is indeed expanding the argument into the full path.

that being said - wouldn't it make sense to always take the last component?

**Comment by jacobsa** [comment]
That's adding surprising behavior to work around surprising behavior, which is often a bad idea.

**Comment by jasper1918** [comment]
Appears this is still an issue using v17.1. Any future plans to include this functionality for linux users?

**Comment by rayfoss** [comment]
Solution: "you'll need to work around it by running gcsfuse in a directory where there is no sub-directory whose name matches the bucket name." -jacobsa
