### ISSUE TITLE
gcs.NotFoundError: googleapi: Error 404 

### ISSUE THREAD

**Issue by kernelt** [GoogleCloudPlatform/gcsfuse#130]
Hi Aaron. 
We have got a new issue. The gcsfuse doesn't displays objects in bucket, if we copy them via gsutil. If we copy objects via "a cp command", everthing is ok and visible. However, if we copy them with gsutil - we don't see them. Strangely, in both cases, we can see all files in google developer console. We can see a following error of gcsfuse if a --debug_gcs option is enable: 
```
2015/09/23 09:26:35.186157 File system has been successfully mounted.
gcs: Req              0x1: <- ListObjects()
gcs: Req              0x1: -> ListObjects() (39.025917ms): OK
gcs: Req              0x2: <- StatObject("user1/")
gcs: Req              0x2: -> StatObject("user1/") (27.096765ms): gcs.NotFoundError: googleapi: Error 404: Not Found, notFound
```
A "user1" dir is dir which copied via gsutil. 
What can it be? Can you check it?

**Comment by jacobsa** [comment]
This is because gsutil doesn't create objects for directories, and gcsfuse by default requires such objects to exist. Please see [this](https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/semantics.md#implicit-directories) section in the documentation.
