### ISSUE TITLE
Slow reads when having multiple reader processes reading an overlapping set of files.

### ISSUE THREAD

**Issue by fmmoret** [GoogleCloudPlatform/gcsfuse#1318]
**Describe the issue**

I'm using the GKE CSI driver w/ `implicit-dirs,max-conns-per-host=100,debug_gcs,debug_fuse`
My bucket has 3 10GiB files (random ML model defined at  node startup) and I have a pool of 4 processes that is each trying to read the files into GPU memory for a GPU dedicated to that process.

I see that the first chunk read is 200mb and then 1mb reads from then on. I think the random reads heuristic is getting triggered.

https://github.com/GoogleCloudPlatform/gcsfuse/blob/19ed094b6612789b09ad4a1df3a2314099c65129/internal/gcsx/random_reader.go#L339C28-L339C29
I believe the random read heuristic here of 2 seeks is too easily triggered when I have multiple processes consuming the same 3 files from start to finish. I imagine the read pattern could easily look like.
To simplify what I think might be happening I will use a compact representation: (Process A|B|C|D)(Chunk 1/2/3/4/n).
E.g. A1 represents the first process fetching chunk 1.

A1, B1, C1, A2, B2, D1, A3, C2, B3, D2, A4, etc.
Note that by the time we're at the end: B3, D2, A4 - it looks like we have a "random" set of reads for 3 non-sequential chunks, despite the reads from the perspective of the owner process (A / B/ C/ D) being totally sequential.

----------------------------
I'll probably just end up syncing to disk manually at init w/o GCSFuse, but it would have been nice if it just happened to work for my workloads.

**System (please complete the following information):**
 - OS: default GKE COS
 - Platform GKE w/ 
 - Version shipped by GKE CSI driver by default

**Additional context**

**SLO:**
24 hrs to respond and 7 days to close the issue.

**Comment by sethiay** [comment]
@fmmoret Thanks for sharing the details. If each of the processes is opening same file and not using the same file handle then each of them should get a separate reader and one reader's random read should not interfere with another reader's sequential read.

Can you please confirm if different processes are using different file handles in your workload ?

**Comment by sethiay** [comment]
@fmmoret Thanks for sharing the logs. From the logs, we can see that the same file handle is being used. This signals that all the processes in your application are using the same file descriptor to read. If that's true, then it is an expected behavior.

Happy to learn more about your use case. And if you decide to use GCSFuse in future, please feel free to reach out in case of any issues.

**Comment by sethiay** [comment]
@fmmoret Apart from checking logs, you can check the application code about whether the open is opened once and then all the processes in the application use the same file descriptor/handle or the processes are opening the files separately.
If it's the former case then the behavior is expected.
