### ISSUE TITLE
Repository missing

### ISSUE THREAD

**Issue by jamespsterling** [GoogleCloudPlatform/gcsfuse#132]
```
W: Failed to fetch http://packages.cloud.google.com/apt/dists/gcsfuse-wheezy/main/binary-amd64/Packages  404  No
t Found [IP: 209.85.147.113 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by jacobsa** [comment]
Please see the first paragraph in [this](https://github.com/googlecloudplatform/gcsfuse/blob/a60587d5e07097e60d1473b68cbadca9c62192e4/docs/installing.md#ubuntu-and-debian) section of the installation docs. Installing via this method is only supported on jessie; for wheezy you'll need to follow the instructions for [other distributions](https://github.com/googlecloudplatform/gcsfuse/blob/a60587d5e07097e60d1473b68cbadca9c62192e4/docs/installing.md#other-distributions).
