### ISSUE TITLE
error: SetMtime: UpdateObject: googleapi: Error 403: Forbidden

### ISSUE THREAD

**Issue by kernelt** [GoogleCloudPlatform/gcsfuse#133]
We have different tools (scripts), which access data stored in buckets. This bucket is mounted to our server via gcsfuse 0.12.0. However, when we run exact same tool sometimes it works, sometimes it does not and returns gcsfuse error:
```
gcsfuse[1427]: fuse: 2015/10/13 14:11:11.019010 *fuseops.SetInodeAttributesOp error: SetMtime: UpdateObject: googleapi: Error 403: Forbidden, forbidden
```
Why this happens? What can we do about it?
Maybe you could add an option to gcsfuse which would allow to ignore these kind of errors so our tools would finish their work? Our web app is crucially dependent on this so your help is essential

**Comment by jacobsa** [comment]
This is an error from GCS indicating that the credentials you're using don't give you permission to update the object's metadata. Try checking bucket and object permissions, and see [here](https://cloud.google.com/storage/docs/access-control) for full GCS documentation.
