### ISSUE TITLE
Mount as user at startup using fstab

### ISSUE THREAD

**Issue by clintcan** [GoogleCloudPlatform/gcsfuse#135]
Hi,

In the documentation, it is written (for fstab):
my-bucket /mount/point gcsfuse rw,noauto,user

I tried removing noauto to make it mount at start.  This doesn't work.  How can I edit fstab in such a way that it mounts the bucket with a specified user id?

**Comment by jacobsa** [comment]
You can probably set the [`allow_other`](https://github.com/torvalds/linux/blob/master/Documentation/filesystems/fuse.txt#L100-L105) fuse option and appropriately set the `--uid` and `--gid` flags to gcsfuse. I would need more detail than "this doesn't work" to know for sure though.

Still: let me urge you to not do this. GCS is not nearly as reliable as local disk, and you're likely to find yourself with a system that hangs on boot if anything goes wrong.

**Comment by clintcan** [comment]
Hi jacobsa,

What I meant was placing in fstab the following:

my-bucket /mount/point gcsfuse rw,uid=www-data,gid=www-data,allow_other

When I do the mount /mount/point command, it fails with an exit code of 1.

I can do the alternative gcsfuse -o allow_other --uid=n --gid=n my-bucket /mount/point with no problems, but I prefer placing it in fstab so that I can just call mount directly.

**Comment by jacobsa** [comment]
I see, thanks. `uid` and `gid` aren't supported in fstab currently. But I'm not sure why you need them. Can you do this

    my-bucket /mount/point gcsfuse rw,noauto

and then just run the mount command as `www-data`?

**Comment by clintcan** [comment]
Ok, the original purpose was to let a user for example root mount the /mount/point with a specific user assigned to that directory.  Anyways, that works for the meantime.  Thanks!

**Comment by jacobsa** [comment]
Sounds good. Keep in mind that you can do this as root using `sudo -u some_user`.

**Comment by guocb** [comment]
Sorry to re-open the discussion about this. But the above comments doesn't answer the question, i.e. mount the bucket when system boot up automatically. Absolutely we can create a init script which call `sudo -u some_user -c 'mount /mnt/mountpoint'`, but is that the only way? I still prefer a single line in `/etc/fstab` which can mount the gcs bucket as a specified user, e.g. `www-data`

**Comment by Tulkis** [comment]
> 
Sorry to re-open the discussion about this. But the above comments doesn't answer the question, i.e. mount the bucket when system boot up automatically. Absolutely we can create a init script which call sudo -u some_user -c 'mount /mnt/mountpoint', but is that the only way? I still prefer a single line in /etc/fstab which can mount the gcs bucket as a specified user, e.g. www-data
> 

Hi, Here I have the same issue, someone can help us?
Regards,
Eduard

**Comment by jacobsa** [comment]
Yes, unless your system supports specifying which user owns the mount helper process in `/etc/fstab`, you will need to write a script that uses `sudo` to accomplish this.
