### ISSUE TITLE
gcsfuse doesn't support mknod(2) and friends

### ISSUE THREAD

**Issue by edwardchuang** [GoogleCloudPlatform/gcsfuse#137]
I've setup a FUSE on GCE instance with following CLI parameters:

```
gcsfuse -o allow_other --implicit-dirs --debug_fuse --uid "80" --gid "80" --limit-ops-per-sec "-1" --debug_gcs <mybucketname> /data/original
```

And trying to export this mountpoint to others by NFS with:

```
/data/original 10.0.0.0/8(rw,sync,no_subtree_check,fsid=0,no_root_squash,anonuid=80,anongid=80)
```

However, once the NFS client mount and create a file using "sudo touch blah", it will shows "I/O error" on client side and shows following error message on GCS fuse debug message:

```
fuse_debug: Op 0x00000005        connection.go:395] <- LookUpInode (parent 1, name "this-operation-might-be-failed")
gcs: Req              0x1: <- ListObjects()
gcs: Req              0x2: <- StatObject("this-operation-might-be-failed")
gcs: Req              0x3: <- StatObject("this-operation-might-be-failed/")
gcs: Req              0x3: -> StatObject("this-operation-might-be-failed/") (49.114935ms): gcs.NotFoundError: googleapi: Error 404: Not Found, notFound
gcs: Req              0x2: -> StatObject("this-operation-might-be-failed") (63.074613ms): gcs.NotFoundError: googleapi: Error 404: Not Found, notFound
gcs: Req              0x1: -> ListObjects() (433.86442ms): OK
fuse_debug: Op 0x00000005        connection.go:476] -> Error: "no such file or directory"
fuse_debug: Op 0x00000006        connection.go:395] <- LookUpInode (parent 1, name "this-operation-might-be-failed")
gcs: Req              0x4: <- ListObjects()
gcs: Req              0x4: -> ListObjects() (32.406251ms): OK
fuse_debug: Op 0x00000006        connection.go:476] -> Error: "no such file or directory"
fuse_debug: Op 0x00000007        connection.go:395] <- LookUpInode (parent 1, name "this-operation-might-be-failed")
gcs: Req              0x5: <- ListObjects()
gcs: Req              0x5: -> ListObjects() (30.796149ms): OK
fuse_debug: Op 0x00000007        connection.go:476] -> Error: "no such file or directory"
fuse_debug: Op 0x00000008        connection.go:395] <- unknown (inode 1, opcode 8)
fuse_debug: Op 0x00000008        connection.go:476] -> Error: "function not implemented"
```

any clue ?

**Comment by jacobsa** [comment]
Opcode 8 is [`FUSE_MKNOD`](https://github.com/torvalds/linux/blob/00c570f4ba43ae73b41fa0a2269c3b0ac20386ef/include/uapi/linux/fuse.h#L324), which I haven't seen sent before when `FUSE_CREATE` is supported. Are you running an old system? (What does `uname -a` show?) What distribution, etc?

**Comment by edwardchuang** [comment]
NFS Client:

FreeBSD aqua 9.3-RELEASE-p24 FreeBSD 9.3-RELEASE-p24 #0: Sat Aug 22 01:54:44 UTC 2015     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64

NFS Server:

Linux nfs-server-1 3.16.0-0.bpo.4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u3~bpo70+1 (2015-08-08) x86_64 GNU/Linux

**Comment by jacobsa** [comment]
Interesting. Does the same thing happen if you touch it locally from the server? What if you don't involve NFS at all?

**Comment by edwardchuang** [comment]
Everything is fine if I create the file locally ... :/ That's really weird.

**Comment by jacobsa** [comment]
I imagine this is due to the NFS server code in the kernel calling into the FUSE VFS layer differently. Will need to trace backwards from `FUSE_MKNOD` to see what can cause it to be sent.

**Comment by jacobsa** [comment]
Here's my theory.

Normally `open(2)` calls into [`lookup_open`](https://github.com/torvalds/linux/blob/v3.16/fs/namei.c#L2803), which [calls](https://github.com/torvalds/linux/blob/v3.16/fs/namei.c#L2823-L2826) `atomic_open` under certain flags and when the directory's inode supports it. For fuse, this eventually calls [`fuse_atomic_open`](https://github.com/torvalds/linux/blob/v3.16/fs/fuse/dir.c#L507), which [calls](https://github.com/torvalds/linux/blob/v3.16/fs/fuse/dir.c#L533) `fuse_create_open` (and [therefore](https://github.com/torvalds/linux/blob/v3.16/fs/fuse/dir.c#L445) sends `FUSE_CREATE`), [unless](https://github.com/torvalds/linux/blob/v3.16/fs/fuse/dir.c#L530-L531) the user space daemon doesn't support `FUSE_CREATE`.

NFS must be either following the same flow with different flags, or calling [`vfs_create`](https://github.com/torvalds/linux/blob/v3.16/fs/namei.c#L2503) (which confusingly [is just `fuse_mknod`](https://github.com/torvalds/linux/blob/v3.16/fs/fuse/dir.c#L636-L640) for fuse) directly. Indeed there are several calls to `vfs_create` in the `nfsd/` directory; for example [here](https://github.com/torvalds/linux/blob/v3.16/fs/nfsd/vfs.c#L1236).

To do:

1. I think it should be easy to reproduce this with `mknod(2)`, which [calls](https://github.com/torvalds/linux/blob/v3.16/fs/namei.c#L3434) `vfs_create`. Write a failing integration test for gcsfuse (don't forget a test for the `EEXIST` behavior of `mknod(2)` as well).

2. Write similar failing integration tests in jacobsa/fuse.

3. Add support for `FUSE_MKNOD` in jacobsa/fuse. Document that it's like `CreateFileOp`, but without opening? Ugh, can we make this interface better somehow?

4. Implement this for gcsfuse.

**Comment by jacobsa** [comment]
Sorry for the delay here; I had a long vacation, and have been consumed with other things since then. I plan to pick this up and finish it soon.

**Comment by jacobsa** [comment]
@edwardchuang: Thanks for your patience. Please update to gcsfuse 0.13.0 and let me know whether this now works or not.

**Comment by edwardchuang** [comment]
@jacobsa Thanks! I am working on it.

**Comment by edwardchuang** [comment]
@jacobsa It works! Thanks for your kindly help.

```
fuse_debug: Op 0x0000007f        connection.go:395] <- LookUpInode (parent 1, name "hello-from-nfs-client-2")
gcs: Req             0x57: <- ListObjects()
gcs: Req             0x58: <- StatObject("hello-from-nfs-client-2")
gcs: Req             0x59: <- StatObject("hello-from-nfs-client-2/")
gcs: Req             0x58: -> StatObject("hello-from-nfs-client-2") (27.774594ms): gcs.NotFoundError: googleapi: Error 404: Not Found, notFound
gcs: Req             0x59: -> StatObject("hello-from-nfs-client-2/") (41.549862ms): gcs.NotFoundError: googleapi: Error 404: Not Found, notFound
gcs: Req             0x57: -> ListObjects() (50.520541ms): OK
fuse_debug: Op 0x0000007f        connection.go:476] -> Error: "no such file or directory"
fuse_debug: Op 0x00000080        connection.go:395] <- LookUpInode (parent 1, name "hello-from-nfs-client-2")
gcs: Req             0x5a: <- ListObjects()
gcs: Req             0x5a: -> ListObjects() (1.158965079s): OK
fuse_debug: Op 0x00000080        connection.go:476] -> Error: "no such file or directory"
fuse_debug: Op 0x00000081        connection.go:395] <- LookUpInode (parent 1, name "hello-from-nfs-client-2")
gcs: Req             0x5b: <- ListObjects()
gcs: Req             0x5b: -> ListObjects() (1.769044453s): OK
fuse_debug: Op 0x00000081        connection.go:476] -> Error: "no such file or directory"
fuse_debug: Op 0x00000082        connection.go:395] <- MkNode
gcs: Req             0x5c: <- CreateObject("hello-from-nfs-client-2")
gcs: Req             0x5c: -> CreateObject("hello-from-nfs-client-2") (3.171215379s): OK
fuse_debug: Op 0x00000082        connection.go:474] -> OK
fuse_debug: Op 0x00000083        connection.go:395] <- GetInodeAttributes (inode 1)
fuse_debug: Op 0x00000083        connection.go:474] -> OK
```

**Comment by jacobsa** [comment]
Great! I'm glad it works.
