### ISSUE TITLE
Installation documentation: lsb_release not available on Debian

### ISSUE THREAD

**Issue by gabipetrovay** [GoogleCloudPlatform/gcsfuse#138]
The [installation script](https://github.com/GoogleCloudPlatform/gcsfuse/blame/master/docs/installing.md#L41) uses `lsb_release` but this is only available in Ubuntu. For Debian one needs to install extra packages for it.

Maybe there is another solution extracting it from `/etc/*-release`?

**Comment by Gibbsdavidl** [comment]
Also, if one wishes to install gcsfuse from within a docker container ... again lsb_release is missing.

**Comment by jacobsa** [comment]
(Sorry for the slow response; vacation.)

Interesting; `lsb_release` is pre-installed in the `debian-7` and `debian-8` images on Google Compute Engine, so I assume you're running somewhere else. How are you installing it?

I'd be happy to take a pull request that adds the appropriate `sudo apt-get install` lines before its use in the instructions, if you can test on your system.

**Comment by Gibbsdavidl** [comment]
Running the Bioconductor docker image.  But no problem, I use the "Other distros" option and it installs fine.
