### ISSUE TITLE
File cp seems to create file, but size in JSON API is zero.

### ISSUE THREAD

**Issue by marcgel** [GoogleCloudPlatform/gcsfuse#14]
Steps for repro:
1. Mount following instructions.
2. Go into mount dir and copy a file "cp foo bar"
3. Using API Explorer and using objects.get method the size of bar is zero (as well as Developer's Console which uses JSON API).
4. "ls -al" does show the file has a size.

Expected JSON API to reflect the size.

**Comment by jacobsa** [comment]
Sorry I didn't recognize it before: this is just issue #13 (closing the file doesn't make it durable). That will be implemented real soon now, and may already work if you update.

**Comment by jacobsa** [comment]
(I take it back: it shouldn't yet work at HEAD. Soon.)

**Comment by jacobsa** [comment]
@marcgel: If you update from HEAD, this should work now.
