### ISSUE TITLE
Advertised inode permissions don't do anything

### ISSUE THREAD

**Issue by tarun360** [GoogleCloudPlatform/gcsfuse#1414]
**Describe the issue**

I ran the following command:
```
$ sudo gcsfuse --uid 1000 --gid 1000 -o allow_other --implicit-dirs --only-dir somedir my-bucket-name /somedir

$ ls -l /somedir/hello.txt
-rw-r--r-- 1 someuser someuser # someuser corresponds to uid 1000

$ sudo -u 2000 echo "2000" > /somedir/hello.txt # doesn't throw error
```

In the above case, 

- The command is run as root (id=0)
- `--allow_other` flag is passed which should allow access to all users.
- both uid and gid is set to 1000 which sets inode permissions (shown using `ls -l` above). 

Should the above not restrict the access to uid 1000 only (even though `--allow_other` is set)? If not, then what's the point of having `--uid` and `--gid` flags if they don't actually do anything?

**Comment by sethiay** [comment]
@tarun360 We were not able to reproduce the issue. Could you please confirm the behavior on your side with the latest GCSFuse version (v1.2.0) ? Also, if the issue still persist, could you please share the following:
 - OS: [e.g. Ubuntu 20.04]
 - Platform [VM, Kubernetes]
 - debug logs (Please rerun with --debug_fuse --debug_gcs --foreground as additional flags to enable debug logs.)

**Comment by sethiay** [comment]
Hey @tarun360 

> I did install v1.2.0 of gcsfuse. I followed the instructions mentioned [here](https://cloud.google.com/storage/docs/gcsfuse-install). On doing gcsfuse --version it gives following output

I tried this and I am able to see the correct version. i.e. v1.2.0.

> OS information:

Thanks, I also tried running similar experiment on the same OS and got permission denied error:

```
# Create new user
sudo useradd testuser
# Get user id corresponding to testuser
# e.g. uid=1001(testuser) gid=1002(testuser) groups=1002(testuser)
id testuser

# Mount
sudo gcsfuse --uid 1001 --gid 1002 -o allow_other --implicit-dirs --only-dir test $BUCKET_NAME $MNT_DIR

# create another user
sudo useradd testuser1
id testuser1

sudo -u 1002 "hey" >> $MNT_DIR/a.txt
# Got the following error
# -bash: mnt/a.txt: Permission denied
```

- Could you please confirm if you are doing similar ? 
- Could you please mention your fuse version (`fusermount --version`) ?
- Could you please share `strace` logs as well `strace sh -c "sudo -u 1002 'hey' >> $MNT_DIR/a.txt"`

**Comment by bjornleffler** [comment]
Are mode and owner attributes supported beyond the defaults?

SetInodeAttributes silently ignores mode. I don't see the owner being set either.
https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/internal/fs/fs.go#L1297

createFile doesn't use the supplied mode.
https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/internal/fs/fs.go#L1415C2-L1415C6

**Comment by sethiay** [comment]
> Are mode and owner attributes supported beyond the defaults?

@bjornleffler , Yes, however they can only be set at the time of mounting (running chmod/chown after mounting will be ignored). Ref: https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/semantics.md#permissions-and-ownership

**Comment by sethiay** [comment]
@tarun360 I think the problem is when  `sudo -u testuser echo "hey" >> a.txt` is executed, then it just execute `echo "hey"` part from user `testuser`, and the other part of command writing to the file i.e. `>> a.txt` is executed from the current user running the whole command.
Given above, can you please try and confirm if running `sudo -u <different user than passed to --uid & --gid flags> sh -c "echo 'hey' >> $MNT_DIR/a.txt"` works as expected i.e. throw permission denied error ?
