### ISSUE TITLE
mounting bucket doesn't show contents

### ISSUE THREAD

**Issue by Gibbsdavidl** [GoogleCloudPlatform/gcsfuse#142]
Hi there,

I'm working with the google genomics team, and we are accessing both public/open data and NIH controlled data. 

With the public/open bucket, gcsfuse is working great. All the directories get listed.

```
# daemon -- gcsfuse isb-cgc-open  /media/open/root@1b71307eaa03:/
# ls /media/open
aliquot_uniq.txt  ccle	cohorts  cwl-examples  genomic-reference  gsk  platforms  tcga-runs
```

But, when trying to access the controlled data, I can see it using gsutil, but not gcsfuse,
even though it shows the mount as being successful.

```
# gsutil ls gs://62f2-xxx-xxx-77/tcga
gs://62f2-xxx-xxx-77/tcga/acc/
gs://62f2-xxx-xxx-f77/tcga/blca/
gs://62f2-xxx-xxx-f77/tcga/brca/
gs://62f2c-xxx-xxx-f77/tcga/cesc/
....
# gcsfuse 62f2-xxx-xxx-4f77  /media/cntl
Opening GCS connection...

WARNING: gcsfuse invoked as root. This will cause all files to be owned by
root. If this is not what you intended, invoke gcsfuse as the user that will
be interacting with the file system.

Opening bucket...
Mounting file system...
File system has been successfully mounted.
^C2015/12/16 19:36:16.480340 Received SIGINT, attempting to unmount...
2015/12/16 19:36:16.511429 Successfully exiting.
...
...
# daemon -- gcsfuse 62f2-xxx-xxx-4f77  /media/cntl
# ls /media/cntl    ### nothing returned here ###
# ls /media/cntl/tcga
ls: cannot access /media/cntl/tcga: No such file or directory
```

Thanks for any help!!  Let me know if you need more information.

**Comment by kahing** [comment]
try using the `--implicit-dirs` option as documented in https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/semantics.md

**Comment by Gibbsdavidl** [comment]
Yay!  That did it. Thanks for your help.

**Comment by cch0** [comment]
@emobortnik  use  **--implicit-dirs**  (with a hyphen, not under score)

**Comment by djbuster** [comment]
> @emobortnik use **--implicit-dirs** (with a hyphen, not under score)

Its not working with hyphen. :(

**Comment by isality** [comment]
--implicit-dirs works for me. Thanks.

**Comment by jossef** [comment]
for `/etc/fstab` fans

```
<bucket id> <path to mount> gcsfuse rw,allow_other,file_mode=777,dir_mode=777,implicit_dirs
```

for instance, mounting bucket `my-bucket` on `/opt/cloud`

```
my-bucket /opt/cloud gcsfuse rw,allow_other,file_mode=777,dir_mode=777,implicit_dirs
```

**Comment by crmacabre** [comment]
Thank you very much guys!

**Comment by samrakshak** [comment]
I had to mount a single bucket in two different k8s pods . Using --implicti-dirs the bucket mounts to one pod but it doesn't mount to the other one ... the command I used is
  command: ["gcsfuse", "--implicit-dirs","-o", "nonempty", {{ .Values.REOURCES_BUCKET_NAME }} ,  {{.Values.RESOURCES_MOUNT_PATH }}]
This mounts on one pod but the same doesn't work for another.

**Comment by samrakshak** [comment]
> not working with hyphen. :(

Did you find a way to make it work?

**Comment by petervangalen** [comment]
I can mount my bucket successfully: 
`gcsfuse --implicit-dirs <bucket> ~/gcsfuse`

This results in the message "File system has been successfully mounted" and indeed I can see folders and files in the terminal. However, when I open it in Finder, I see all the folders but none of the files.

**Comment by jossef** [comment]
> I can mount my bucket successfully: `gcsfuse --implicit-dirs <bucket> ~/gcsfuse`
> 
> This results in the message "File system has been successfully mounted" and indeed I can see folders and files in the terminal. However, when I open it in Finder, I see all the folders but none of the files.

worth trying to remount with file-mode=777 and dir-mode=777

**Comment by roberto-amaralsantos** [comment]
When I run something like `gcsfuse --implicit-dirs <bucket> ~/gcsfuse` I get the following error message: `daemonize.Run: readFromProcess: sub-process: mountWithArgs: mountWithConn: Mount: mount: running /usr/bin/fusermount3: exit status 1`. Any insights why?

**Comment by Tulsishah** [comment]
Thanks, @roberto-amaralsantos, for reaching out to us. If your bucket is already mounted in that folder and you try to mount it again in the same folder without un-mounting it, It will show this error.

**Comment by roberto-amaralsantos** [comment]
@Tulsishah that was exactly the issue! Thanks a lot! Now it works.

**Comment by Tulsishah** [comment]
Hi, @roberto-amaralsantos. Can you please share what kind of error you are facing in that?

**Comment by roberto-amaralsantos** [comment]
@Tulsishah , it does not give me any error messages, it simply does not work. When I look for the bucket after starting the VM and connecting to it, it is not there yet and I have to mount it manually.

**Comment by Tulsishah** [comment]
You can try `sudo umount mount-dir-name` and then `<my-project /home/roberto/remote gcsfuse rw,x-systemd.requires=network-online.target,user`
