### ISSUE TITLE
Mounting a sub folder of a bucket.

### ISSUE THREAD

**Issue by suhas22** [GoogleCloudPlatform/gcsfuse#143]
Hi team,
I was trying to mount a directory from a compute engine instance onto a google bucket, which I am successfull.
But what i am trying to do is, having files directly go into the bucket via sftp from a remote machine, so the remote machine user gets to see the bucket as a folder and the objects inside the bucket as subfolders.
As i will be getting files from multiple remote machines onto the same bucket but to different folders under the bucket, wanted to know if there is a way to mount a object inside the bucket to a user so that the user gets to see only that folder and not list everything that's there in the bucket.

eg: gcsfuse --temp dir /data mybucket/subfolder /foldertomount/

currently we can mount the bucket as a whole, and not a particular folder inside the bucket.

**Comment by jacobsa** [comment]
gcsfuse itself doesn't support this explicitly, but I think perhaps you can do what you want with [bind mounts](http://unix.stackexchange.com/a/198591/118501)? Mount the entire bucket in one place on your file system, then create a bind mount elsewhere that exports only the part of the bucket that you want to export.

(See also #124)

**Comment by suhas22** [comment]
Thanks Aaron,
I will give it a shot and let you know how it goes.

Regards
Suhas.

**Comment by suhas22** [comment]
Hi Aaron,
I tried both the ways but seems like none work, chroot and bind mount.


1) Method 1.
My requirement is basically allow a user to have sftp access to only one
directory under a bucket. ( there are multiple folders inside a bucket and
each folder can be thought as of a client, so no other folder is exposed to
other clients).
And on my machine I have created a user with nologin and have mounted the
whole bucket as this user.

Here is what i did.
1) created a user.
2) created a folder inside the user's home directory like
/home/user/project name/bucketname/ of the bucket.
3) this entire folder structure is owned by that user.
4) then mounted the bucket to the above folder, using gcsfuse
5) come out and disable login for that user.

Then
1) created a folder structure under root as /project name/bucketname/folder
to mount.
2) did a bind --mount /project name/bucketname/folder to mount
 /home/user/project name/bucketname/ .

copied the private key of the remote machine to the above machine. when i
try sftp ing as sftp user@XX.XX.XX.XX i get a permission denied error.


2) Method 2
1) instead of doing a bind mount, I rather mounted the folder bucket
directly to one of the folders and did a chroot change in
/etc/ssh/sshd_config file to point the user to a folder inside the bucket.
2) when i try sftp'ing, i am getting a connection broker pipe error.

Can you please help me here and point me to the correct way of doing it. If
you have any examples that's been done before, it would definately help.

Thanks
Suhas.

**Comment by jacobsa** [comment]
Thanks for the detailed write-up. With method 1, did you perform the bind mount again as the user that will be sftp'ing? What happens if you use `su user` to become that user and try to interact with the bind mount in a shell as that user, taking sftp out of the equation?

**Comment by jacobsa** [comment]
I played around with this a bit on GCE. Here's what I did, which seems like it should work:

1. Set up a user `bob` with SFTP-only access according to [these](http://solderintheveins.co.uk/2011/03/ubuntu-sftp-only-account-how-to/) instructions. Configure the `ChrootDirectory` to be `%h/mount_pount/subfolder` where `subfolder` is the portion of the bucket you want them to see.

2. As a user that _does_ have login and `sudo` access, run `sudo -s -u bob` to become `bob`.

3. As `bob`, run `mkdir ~/mount_point` to create the mount point for the bucket.

4. As `bob`, invoke `gcsfuse my-bucket ~/mount_point` to mount the bucket. (See [this](https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/mounting.md#mount8-and-fstab-compatibility) documentation if you want to make this more permanent).

5. As `bob`, you should now be able to do `ls ~/mount_point/subfolder` to see the contents you care about.

6. Now from another machine you should be able to do `sftp bob@<ip>`.

But you're right; I too see `Write failed: Broken pipe` from the `sftp` command. I assume this is because the sftp daemon running as root attempts to read from `~bob/mount_point/subdir`, but fails because fuse doesn't allow other users to interact with a fuse mount. Bind mounts may be a better way to deal with this; looking...

**Comment by jacobsa** [comment]
Okay, the broken pipe errors correspond to entries like this in `/var/log/auth.log`:

    Dec 22 00:45:44 ubuntu sshd[10776]: fatal: bad ownership or modes for chroot directory "/home/bob/mp2"

The issue is that the mount point is owned by `bob`, but `sshd` [doesn't like that](http://serverfault.com/questions/584986/bad-ownership-or-modes-for-chroot-directory-component) for `ChrootDirectory`. This is true even if you do `mount --bind` over the top of a directory owned by `root` -- it suddenly has the permissions of the source directory.

I'm starting to be convinced that gcsfuse should just offer this as a feature. :-) Will take a look.

**Comment by jacobsa** [comment]
The `--only-dir` flag works as of 62dd0425f4618bb5fc8e1797ea02a1a93852b1ce, and should do what you want. Please let me know if you're able to verify this.

Unfortunately I'm going on vacation 10 minutes from now until the new year, but I will cut a release at that point. Until then you can install at `HEAD` by installing Go 1.6 beta 1 or higher (or Go 1.5 and set `GO15VENDOREXPERIMENT=1`) and running `go get github.com/googlecloudplatform/gcsfuse`.

**Comment by jacobsa** [comment]
This is now available in version 0.14.0. Please let me know if it works for you.

**Comment by suhas22** [comment]
Hi Aaron,
Wishing you a very happy new year.
Thanks for the fix. However I am running into a issue where gcsfuse is not
able to identify mybucket/folder. Initially i thought it was the permission
issue to the folder to which i am trying to mount, but however i was able
to mount the whole bucket itself to that folder.

Details:
1) I have installed fuse on Debian Jessie based on the instructions
https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/installing.md
2) Installed Version 0.15.

What i did :
1) Created a user.
2) added that user to a group.
3) added that user to fuse group.
3) created a temp directory called data under root. (for buffering from
where the data will be written to gcs bucket)
4) created a directory structure under root as /mybucket/folder - similar
to the bucket definition.
5) in /mybucket/folder, the owner of the folder is the user who i created (
for restricting permissions).

logged into that user and issued the command.

gcsfuse --only-dir /data bucketname/folder myfolder/to/mount, i get the
below error.
Using mount point: /myfolder/to/mount
Opening GCS connection...
Opening bucket...
daemonize.Run: readFromProcess: sub-process: mountWithArgs: mountWithConn:
setUpBucket: OpenBucket: Unknown bucket "bucketname/fold"

However if i try to mount the whole bucket, it still works the way it used
to before.

Please let me know if I am doing something wrong here or if version 0.15
does not have the changes incorporated in version 0.14.

**Comment by jacobsa** [comment]
The formatting of your message isn't coming through well, so to confirm I think you ran this:

    gcsfuse --only-dir /data bucketname/folder myfolder/to/mount

But I'm not sure what `/data` is supposed to be there. Did you mean to run this?

    gcsfuse --only-dir folder bucketname myfolder/to/mount

**Comment by suhas22** [comment]
Hi Aaron,
Thanks a lot, Now I am able to mount a particular folder from a bucket, and was successfully able to sftp from a remote machine.
But there are a few challenges faced while changing the chroot directory for that user.

What i did is.
1) created a folder under root - lets call it bucketname. ( this folder is owned by root)
2) created a folder under bucketname - lets call it client name ( this folder is owned by the sftp user who belongs to sftp_group).
3) Issued the below command to mount the bucket.
    > gcsfuse --only-dir clientname bucketname /bucketname/clientname.
          This would successfully mount the bucket/folder.
4) make firewall changes to allow the remote machine to be recognized by the host machine.
5) generate a ssh key on the remote machine, copy it onto the host machine under /user/sftp_user/.ssh/authorized_keys
6) from remote machine issue the command $$ sftp sftp_user@ip of the host machine.
7) sftp successfully, and when i do pwd , it's landing on the /home/sftp_user directory and the user has access to move back and forth to different folders, but when i go to the "bucketname" folder, i get to see only the "clientname" folder listed which is working as expected.

Since the user is free to move around the entire file system, i tired restricting him like below.
made some changes in /etc/ssh/sshd_config file to set the sftp configurations as below.
#SFTP Server setup
Subsystem       sftp    internal-sftp
Match Group sftp_users
ChrootDirectory /bucketname
ForceCommand internal-sftp
AllowTcpForwarding no
PermitTunnel no
X11Forwarding no

Restarted the sftp services, and then tried doing sftp from the remote machine,
I get the below error
$$ sftp -vvvv test_sftp@XXX.XXX.XXX.XXX
OpenSSH_6.6.1, OpenSSL 1.0.1e 11 Feb 2013
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug2: ssh_connect: needpriv 0
debug1: Connecting to 1XXX.XXX.XXX.XXX port 22.
debug1: connect to address XXX.XXX.XXX.XXX port 22: Connection refused
ssh: connect to host XXX.XXX.XXX.XXX port 22: Connection refused
Couldn't read packet: Connection reset by peer

as far as i understand, the chroot directory has to be owned by root and in our case the folder "bucketname" is owned by root, and this should be enough to make the user land on "bucketname" folder. but not sure why it's throwing a connection refused exception. Can you please help ?

**Comment by jacobsa** [comment]
Did you check `/var/log/auth.log` or similar to see what the server is complaining about?

I don't think you're going to be able to make the chroot directory itself the gcsfuse mount point (since it needs to be owned by root as you said), but you should be able to mount as a sub-directory of that. I think this is entirely independent of the `--only-dir` feature (because sshd doesn't know anything about that); you can leave that out of your consideration.

**Comment by suhas22** [comment]
It's kinda weird, beacuse I don't see anything getting printed in /var/log/auth.log.
Just a plan connection refused error on the console while trying to connect.

tried to connect in verbose mode, and this is what i get : 
sftp -vvvv test_sftp@XXX.XXX.XXX.XXX
OpenSSH_6.6.1, OpenSSL 1.0.1e 11 Feb 2013
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug2: ssh_connect: needpriv 0
debug1: Connecting to XXX.XXX.XXX.XXX port 22.
debug1: connect to address XXX.XXX.XXX.XXX port 22: Connection refused
ssh: connect to host XXX.XXX.XXX.XXX port 22: Connection refused
Couldn't read packet: Connection reset by peer

**Comment by jacobsa** [comment]
Sorry, I don't know what to say. It doesn't sound like what you're describing is unique to this feature, or maybe even to gcsfuse at all. If you can show that it's a gcsfuse problem, please open a new issue.

**Comment by svda** [comment]
Did anyone solve this yet? I'm trying to achieve the same setup: mounted a bucket, and pointed the user home to a specific folder in the bucket mount. SFTP conection results in Broken pipe.

**Comment by benpollardcts** [comment]
@svda I've just stumbled across this whilst looking for something and believe I can help.

Create a directory structure for sftp user data. e.g /srv/sftp & /srv/sftp/data 

Create an sftpusers group. Mount the bucket on /srv/sftp with the following options, rw,gid=[gid of sftpusers],dir_mode=775,file_mode=664,allow_other.

Create an example user such with a supplementary group of sftpusers. Set the home dir to be /incoming and create a directory under /srv/sftp with the username e.g /srv/sftp/test_user.  Create the incoming directory /srv/sftp/test_user/incoming.

Create a folder in the mount with the username of the test_user e.g /srv/sftp/data/test_user

You can then bind mount /srv/sftp/data/test_user to /srv/sftp/test_user/incoming

Sftp config
Subsystem sftp  internal-sftp
Match Group sftpusers
    ChrootDirectory /srv/sftp/%u
    ForceCommand internal-sftp
    PasswordAuthentication yes

When you sftp to the server you will be chrooted to /srv/sftp/test_user and the home dir will drop you into /incoming which is writeable. 

Hope this helps.

**Comment by len5** [comment]
Hey!
very very late but...
so,
to mount specific subdirectory of a bucket in a mount point:

--> command
gcsfuse -o option1,option2 --only-dir sub_dirirectory/ -key-file=/path/to/key.json bucket_name /path/to/mount/point
--> fstab
bucket_name /path/to/mount/point gcsfuse rw,user,key_file=/path/to/key.json,only_dir=sub_directory

**Comment by Firedrops** [comment]
> The `--only-dir` flag works as of [62dd042](https://github.com/GoogleCloudPlatform/gcsfuse/commit/62dd0425f4618bb5fc8e1797ea02a1a93852b1ce).

is there somehow a way to combine this with `--implicit-dirs`? For example, I was testing this code on Google Cloud Shell
`gcsfuse --implicit-dirs --only-dir /NewDatabases <bucket_name> /home/<username>/zztest/`
console logs `File system has been succesfully mounted.`, but zztest remains empty. Am I doing something wrong?

**Comment by dbakiu** [comment]
> > The `--only-dir` flag works as of [62dd042](https://github.com/GoogleCloudPlatform/gcsfuse/commit/62dd0425f4618bb5fc8e1797ea02a1a93852b1ce).
> 
> is there somehow a way to combine this with `--implicit-dirs`? For example, I was testing this code on Google Cloud Shell
> `gcsfuse --implicit-dirs --only-dir /NewDatabases <bucket_name> /home/<username>/zztest/`
> console logs `File system has been succesfully mounted.`, but zztest remains empty. Am I doing something wrong?

I'm a tad late with this reply, but perhaps it will be of use to someone:

I'm not sure if --implicit-dirs has anything to do with this, however I had the same problem you did, i.e. an empty folder, and the issue for me was that the subdirectory had a leading slash, meant that instead of: 
`subdirectory/`, I was mounting: `/bucket/**//**subdirectory`, which results in an implicit creation of a folder called "/" in the storage bucket.

**Comment by maciejskorski** [comment]
The flags `--implicit-dirs` and `--only-dir` indeed can be combined by
```bash
gcsfuse --implicit-dirs --only-dir <dir-relative-do-bucket> <bucket> <mount_point>
```

**Comment by Khadija-Bayoud** [comment]
I've been struggling to mount a specific bucket's folder instead of the whole bucket. Thanks to @maciejskorski, I was able to solve this problem.

Simply run: ```gcsfuse --implicit-dirs --only-dir <folder_name> <bucket_name> <mount_dir>```
