### ISSUE TITLE
Doesn't work on FreeBSD?

### ISSUE THREAD

**Issue by Kronuz** [GoogleCloudPlatform/gcsfuse#144]
I tried installing in FreeBSD 10.2, but I got this:

```
# github.com/googlecloudplatform/gcsfuse/vendor/github.com/jacobsa/fuse/fsutil
gcsfuse/vendor/github.com/jacobsa/fuse/fsutil/fsutil.go:56: undefined: fdatasync
# github.com/googlecloudplatform/gcsfuse/vendor/github.com/jacobsa/fuse/internal/fusekernel
gcsfuse/vendor/github.com/jacobsa/fuse/internal/fusekernel/fuse_kernel.go:397: undefined: Attr
```

Any idea if gcsfuse can somehow work there?

**Comment by jacobsa** [comment]
Sorry, FreeBSD is untested and unsupported. If you're willing to take a look at getting jacobsa/fuse to work there I'd be curious to see what is required, but make no promises about supporting it.

**Comment by rogeliozunigarubio** [comment]
I took care of the first issue, fdatasync but I am stuck on what the second one might imply
