### ISSUE TITLE
Work with rsync

### ISSUE THREAD

**Issue by jacobsa** [GoogleCloudPlatform/gcsfuse#15]
I don't yet know what this involves. Try it out with GCS as both a source and a sink, and see what the user experience is like.

**Comment by trollius** [comment]
Hi Aaron,

We tried it out in the following configuration:
we have two servers: one without a bucket and second one with a bucket attached. We tried to copy with rsync data from no-bucket server into the bucket of the second server via network and got a following error:

[user@srv-test ~]$ rsync -aq -4 -e 'ssh -p 22'  /home/user/output/ user@srv-bucket:/bucket/
rsync: failed to set times on "/bucket/": Operation not permitted (1)
rsync: mkstemp "/bucket/.file_test.txt.PDxUdi" failed: Operation not permitted (1)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1165) [sender=3.1.1]

**Comment by jacobsa** [comment]
It appears there are a few issues here:

*   By default, rsync works by staging a temporary file with the correct contents (`.file_test.txt.PDxUdi` above) and then atomically renaming it into place.
    
    Unfortunately we cannot support atomic renaming, because there is no such operation in GCS. Fortunately, we can tell rsync to overwrite the file in place with `--inplace`.

*   By default, rsync tries to preserve modification times, so calls utimes(2) or similar. We [don't support this](https://github.com/googlecloudplatform/gcsfuse/blob/master/docs/semantics.md#modifications) because GCS doesn't offer a way to write to the `updated` field of an object (and any other place we may stash this would be incompatible with other tools). Fortunately we can tell rsync to skip this with `--no-times`.
    
    If we use `--no-times`, it will appear to rsync that the files are always out of sync, because they have different mtimes. So we should also use `--update` to tell it to regard them as in sync if the destination is newer (which it will be after rsync writes/overwrites it in GCS).

*   By default, rsync tries to preserve permissions. But we [don't support](https://github.com/googlecloudplatform/gcsfuse/blob/master/docs/semantics.md#inodes) changing file permissions because this doesn't map in any natural way onto GCS ACLs. Fortunately we can tell rsync to skip this with `--no-perms`.

@trollius: Can you try adding the following flags? (N.b. they must go at the end of what you have already for your command.)

     --inplace --no-times --update --no-perms

**Comment by jacobsa** [comment]
Closing this. @trollius or anybody else, please let me know if the above doesn't work for you.

**Comment by Shardj** [comment]
I found that --no-perms causes 'ftruncate failed on' errors, no clue as to how that makes sense as you'd think it would be the other way around. It seems to work fine without that though and using the others flags you mentioned instead.

**Comment by raj-prince** [comment]
That's great, it's working without the --no-perms. Thanks for letting us know!

All the above comments are pretty old, maybe permission would have fixed by some update in either of the software.
If you want to know the reasoning behind the issue you face while using --no-perms. Please let us know more details about how to reproduce the issue (system information, gcsfuse version, flag to mount the gcsfuse ,etc,.

-Prince
