### ISSUE TITLE
Incomplete listing of files and directories

### ISSUE THREAD

**Issue by finalfenix** [GoogleCloudPlatform/gcsfuse#150]
When mounting a bucket using gcsfuse, the entire contents of the bucket are not listed? Is there a limit on the number of files or directories listed? the debug switches don't seem to provide much insight.

**Comment by jacobsa** [comment]
Hi, please see the note beginning with "If you are mounting a bucket that was populated with objects..." in the readme [here](https://github.com/googlecloudplatform/gcsfuse#invoking-gcsfuse). (Feel free to re-open if this is not your issue.)
