### ISSUE TITLE
add flag to /etc/fstab

### ISSUE THREAD

**Issue by tuanvu216** [GoogleCloudPlatform/gcsfuse#151]
How can I add flag ```--implicit-dirs``` to /etc/fstab. Currently this is what I have
```
my-bucket /mount/point gcsfuse rw,user
```

**Comment by jacobsa** [comment]
This isn't currently supported, but I can make it happen.

Note to self: do this for `--implicit-dirs`, `--dir-mode`, and `--file-mode`. Write integration tests and make sure they work on OS X and Linux.

**Comment by jacobsa** [comment]
As of gcsfuse 0.16.0, you should be able to do this:

    my-bucket /mount/point gcsfuse rw,user,implicit_dirs

**Comment by cecil** [comment]
Hi, I'm running 0.16.0 and am still having problems with dir-mode and file-mode : 

```
[root@cloud-00 /]# gcsfuse --version
gcsfuse version 0.16.0 (Go version go1.5.3)
[root@cloud-00 /]# grep cloud /etc/fstab 
cloud-bucket-12345 /mnt/cloud/ gcsfuse rw,allow_other,file-mode=777,dir-mode=777 0 0
[root@cloud-00 /]# mount /mnt/cloud/
Calling gcsfuse with arguments: -o allow_other -o file-mode=777 -o dir-mode=777 -o rw cloud-bucket-12345 /mnt/cloud/
Using mount point: /mnt/cloud
Opening GCS connection...
Opening bucket...
Mounting file system...
daemonize.Run: readFromProcess: sub-process: mountWithArgs: mountWithConn: Mount: mount: fusermount: exit status 1
running gcsfuse: exit status 1
```

however, this command works fine : 

```
[root@cloud-00 /]# gcsfuse -o allow_other -file-mode=777 -dir-mode=777  cloud-bucket-12345 /mnt/cloud/ 
Using mount point: /mnt/cloud
Opening GCS connection...
Opening bucket...
Mounting file system...
File system has been successfully mounted.
```

Should I create a new issue or can this one be re-opened?

**Comment by jacobsa** [comment]
@cecil: Please note that the fstab options have underscores, not dashes: `file_mode`, `dir_mode`.

**Comment by cecil** [comment]
ah, my mistake. I thought I tried that already. Working fine for me now.
