### ISSUE TITLE
Server Down

### ISSUE THREAD

**Issue by khushal-erginus** [GoogleCloudPlatform/gcsfuse#153]
I am a google cloud user. I want to install sendmail program and used correct command for that. My install does not went through because following URL is not found.

http://us-central1.gce.archive.ubuntu.com/ubuntu/pool/universe/s/sendmail/sendmail-bin_8.14.4-4.1ubuntu1_amd64.deb

Also it seems

us-central1.gce.archive.ubuntu.com is down.

Thanks.

**Comment by khushal-erginus** [comment]
![error](https://cloud.githubusercontent.com/assets/15865253/12545420/19870dbc-c368-11e5-815d-9f10b05c1132.png)

**Comment by jacobsa** [comment]
Sorry, this project doesn't have anything to do with installing software on GCE. Maybe try [Google Compute Engine support](https://cloud.google.com/support/).
