### ISSUE TITLE
Fail to install gcfuse in debian-7

### ISSUE THREAD

**Issue by wubenhe** [GoogleCloudPlatform/gcsfuse#154]
<pre>
W: Failed to fetch http://packages.cloud.google.com/apt/dists/gcsfuse-wheezy/main/binary-amd64/Packages  404  Not Found [IP: 74.125.70.102 80]
</pre>

**Comment by xuwang** [comment]
What was the problem? I am running into the same issue.

**Comment by jacobsa** [comment]
As described [here](https://github.com/googlecloudplatform/gcsfuse/blob/master/docs/installing.md#ubuntu-and-debian-latest-releases), apt-get support is only available for debian jessie. Please use the [generic instructions](https://github.com/googlecloudplatform/gcsfuse/blob/master/docs/installing.md#other-distributions) for older versions.
