### ISSUE TITLE
Set content type based on file extension

### ISSUE THREAD

**Issue by nottix** [GoogleCloudPlatform/gcsfuse#155]
Hi,

i'm trying to copy png and jpeg on a bucket, but it set always the content-type to octetstream instead of image/png or image/jpeg.

Thank you.

**Comment by suhas22** [comment]
Hi There,
We are facing somewhat a similar issue.
As per the code, if content type is not set, then gcsfuse defaults it to octetstream, but in our case for some of the files it is setting to "folder". due to which the streaming jobs from spark fail complaining that the file format is not correct.
We have tested it on both versions 0.12 & 1.15.1

Any help is greatly appreciated.

**Comment by jacobsa** [comment]
gcsfuse doesn't manage GCS metadata for the user (and in general this is impossible or requires error-prone sniffing). If you care about setting these properties, you'll need to set them yourself using the GCS storage browser or the GCS API.

**Comment by nottix** [comment]
Hi @jacobsa 

searching the web i found that similar tool (like s3fs-fuse) support the mapping of the content-type by means of the mapping file. 
gcsfuse currently appears to be the only available tool to use "google cloud storage" with fuse and it lacks of this feature.

Thank you.

**Comment by jacobsa** [comment]
As I said above, you can do this with content sniffing but it's error prone and I think it's not a good decision engineering-wise. Could you say a bit more about why you need this? Again, you can easily set this value using the GCS API.

**Comment by nottix** [comment]
But we can skip content sniffing observing only the file extension, i know that it's error prone but i don't see other ways.

I'm using gcsfuse to map uploads directory of Wordpress to share directory between multiple instances. I have to upload images, directories, text, doc etc.

**Comment by CeccoCQ** [comment]
+1

**Comment by nottix** [comment]
so, @jacobsa do you have any plan to add this feature? 

Thank  you.

**Comment by jacobsa** [comment]
Can you explain why it's important that you have a content type set in GCS? If you're using GCS as a file system it's meaningless, so I assume it's interoperability with some other use. Can you also explain why using the GCS API to set it doesn't work well for you?

**Comment by nottix** [comment]
I'm using gcsfuse to sharing a directory between multiple instance of our Wordpress portal, then it's Wordpress that put files on gcs using gcsfuse and i can't edit content-type via API.

**Comment by jacobsa** [comment]
Thanks, but how about the first question: why is it important that content type be set in the first place?

**Comment by nottix** [comment]
Because the files will be missinterpreted by web browers. A link URL to an image with content-type octetstream can by downloaded and did not view by a browser.

**Comment by jacobsa** [comment]
Okay. I see how pragmatically it's a good idea to set a default based on extension. If gcsfuse gets it wrong the user is no worse off than now -- they must go and use the API to fix it. Thanks for your patience.

**Comment by jacobsa** [comment]
Implementation note: will want to use [`mime.TypeByExtension`](https://golang.org/pkg/mime/#TypeByExtension).

**Comment by nottix** [comment]
thank you @jacobsa 

How long do you think it takes to implement it?

**Comment by jacobsa** [comment]
I'll try to get to it soon.

**Comment by jacobsa** [comment]
Hi all, please try gcsfuse 0.17.0 and let me know how it works for you.

**Comment by nottix** [comment]
It works perfectly, i'll continue to test it. Thank you ;-)
