### ISSUE TITLE
Please don't delete old versions of your Debian packages

### ISSUE THREAD

**Issue by joshk0** [GoogleCloudPlatform/gcsfuse#159]
We use the packages.cloud.google.com APT repository to install gcsfuse in a Docker container build. However, it appears that as soon as a new version is released, the old version is deleted. Could you retain old versions unless they are actually dangerous for human consumption?

We pin it in our Dockerfile for stability -- the changes to gcsfuse 0.14.0, for example, completely broke our glue because we were installing the latest version, and gcsfuse suddenly went to starting in the background compared to the previous release.

(For the record, I would have considered that a major-version change worthy of a new repository URI.)

Thanks!

**Comment by jacobsa** [comment]
Thanks for the report. I was under the impression that the old versions stuck around; will check with the people who run the package hosting system to figure out how to make sure that happens.

As for versioning, make sure to be aware of [this](http://semver.org/#spec-item-4) note from semver.org:

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

Please be sure to read the release notes.

**Comment by jacobsa** [comment]
(Google-internal bug ID: 27321784)

**Comment by joshk0** [comment]
Fair enough about the semantic versioning. Thanks for looking into the erasure issue.

**Comment by jacobsa** [comment]
I've restored all historical versions for apt now. Could you please confirm that this works for you?

**Comment by joshk0** [comment]
Yup, I see them. Thank you!
