### ISSUE TITLE
issue with content-type while creating files via gcsfuse

### ISSUE THREAD

**Issue by kmelevskiy** [GoogleCloudPlatform/gcsfuse#160]
Hi Aaron,
At the moment we are experiencing issue with files and folders in google buckets created with help of gcsfuse. Randomly some files does not have contentType metadata. Therefore this metadata is not presented in backet notification call and API requests. Strangely enough in google console this bucket objects has file icon but type is Folder - not application/octet-stream. 
 This problem starts from 5th Feb and did not exposed before. 
Updating to gcsfuse 0.17.0 did not resolve the issue.

Any idea why it might be happening?

Thank you in advance.

Kind regards,
Andrey

**Comment by jacobsa** [comment]
Hi Andrey, could you please give some additional details? What is the name of the object? Can you reproduce this reliably? Can you post instructions for doing so?

**Comment by kmelevskiy** [comment]
Hi Aaron,
Thanks for your ultra quick response!
Here is the process we follow and addition info below:
1) Mount bucket to local folder via gcsfuse.
2) Run script which create file in the folder.
3) Right after file creation we are getting following bucket notification:

HTTP_X_GOOG_RESOURCE_ID: goERMx0XvbBavEGvtE1UleYPy4w
HTTP_CONTENT_TYPE: application/json; charset=UTF-8
HTTP_X_GOOG_CHANNEL_ID: idna-files-storage-watcher-domain-dev
HTTP_ACCEPT: /
HTTP_CONNECTION: Keep-alive
HTTP_X_GOOG_RESOURCE_STATE: exists
HTTP_ACCEPT_ENCODING: gzip,deflate
HTTP_X_GOOG_MESSAGE_NUMBER: 1787099223
HTTP_USER_AGENT: APIs-Google; (+https://developers.google.com/webmasters/APIs-Google.html)
HTTP_CONTENT_LENGTH: 1093
HTTP_HOST: dev.me
ERROR:search:Notification #1787099223 for channel goERMx0XvbBavEGvtE1UleYPy4w was accepted!
<Storage {
    'updated': '2016-02-25T11:32:42.104Z',
    'name': 'user2/data_for_test/s_index/input/MGsort.mab.iba',
    'timeCreated': '2016-02-25T11:32:42.104Z',
    'generation': '1456399962106000',
    'storageClass': 'STANDARD',
    'md5Hash': 'sx2PD2wLLKm2jIa/IejCtw==',
    'bucket': 'data_dev',
    'kind': 'storage#object',
    'crc32c': 'Z62iqA==',
    'metageneration': '1',
    'mediaLink': 'https://www.googleapis.com/download/storage/v1/b/data_dev/o/user2%2Fdata_for_test%2Fsamtools_index%2Finput%2FMGsort.mab.iba?generation=1456399962106000&alt=media',
    'owner': {
        'entityId': '00b4903a97624a620754853e67cba53494ccd5fd7d15a4c269cd566151a8419b',
        'entity': 'user-00b4903a97624a620754853e67cba53494ccd5fd7d15a4c269cd566151a8419b'},
        'etag': 'CJDRkdPokssCEAE=',
        'metadata': {'gcsfuse_mtime': '2016-02-25T11:32:42.010896917Z'},
        'id': 'data_dev/user2/data_for_test/s_index/input/MGsort.mab.iba/1456399962106000',
        'selfLink': 'https://www.googleapis.com/storage/v1/b/data_dev/o/user2%2Fdata_for_test%2Fsamtools_index%2Finput%2FMGsort.mab.iba',
        'size': '2032'
}>

Additional info:
=================

If we get newly created file object info via API from bucket, there will be no contentType:
{
    u'updated': u'2016-02-25T11:32:42.104Z',
    u'name': u'user2/data_for_test/s_index/input/MGsort.mab.iba',
    u'mediaLink': u'https://www.googleapis.com/download/storage/v1/b/data_dev/o/user2%2Fdata_for_test%2Fsamtools_index%2Finput%2FMGsort.mab.iba?generation=1456399962106000&alt=media',
    u'metadata': {u'gcsfuse_mtime': u'2016-02-25T11:32:42.010896917Z'},
    u'id': u'data_dev/user2/data_for_test/s_index/input/MGsort.mab.iba/1456399962106000',
    u'selfLink': u'https://www.googleapis.com/storage/v1/b/data_dev/o/user2%2Fdata_for_test%2Fsamtools_index%2Finput%2FMGsort.mab.iba',
    u'size': u'2032'
}

However the input file, which has been used by script from point 2) to create new file that we have issue with, have contentType:

{
    u'updated': u'2015-12-18T16:28:30.898Z',
    u'contentType': u'application/octet-stream',
    u'name': u'user2/data_for_test/s_index/input/MGsort.mab',
    u'mediaLink': u'https://www.googleapis.com/download/storage/v1/b/data_dev/o/user2%2Fdata_for_test%2Fsamtools_index%2Finput%2FMGsort.mab?generation=1446733406053000&alt=media',
    u'metadata': {u'projects': u'[18]'},
    u'id': u'data_dev/user2/data_for_test/s_index/input/MGsort.mab/1446733406053000',
    u'selfLink': u'https://www.googleapis.com/storage/v1/b/data_dev/o/user2%2Fdata_for_test%2Fsamtools_index%2Finput%2FMGsort.mab',
    u'size': u'42917447'
}

**Comment by jacobsa** [comment]
I'm sorry, I still don't understand where the bug is. What do you expect to happen that's not happening? Presumably `.iba` isn't a file extension that gcsfuse knows anything about (I've never heard of it either), so it can't set a content type.

**Comment by kmelevskiy** [comment]
No worries. Maybe it is not jcsfuse problem. At the past all files regardless of its extent came with contentType. But at the moment it is random and some of them does not have contentType.
Could you please tell whether gcsfuse itself defines contentType every time when any of files get created or it is done by google bucket service?

**Comment by jacobsa** [comment]
This may be due to upgrading to [version 0.17.0](https://github.com/GoogleCloudPlatform/gcsfuse/releases/tag/v0.17.0), which changed the behavior of gcsfuse with regard to content types. I believe everything previously received `application/octet-stream`. Now:

* Directories get no content type.
* Files with known extensions get the appropriate content type. (For example, `.jpg`. receives `image/jpeg`).
* Other files get no content type.

**Comment by kernelt** [comment]
Hi Aaron. I've just tested this issue with a gcsfuse 0.15.1 to give you debug logs. I copied several times a tar.gz file to mounted bucket and I had a one result http://prntscr.com/a9di2t - the tar.gz file has folder as its content-type. Maybe, google made changes to its API and now a gcsfuse doesn't work properly? There are logs:
**--debug_fuse**
```
fuse_debug: Op 0x000000ba        connection.go:395] <- GetInodeAttributes (inode 154)
fuse_debug: Op 0x000000ba        connection.go:474] -> OK
fuse_debug: Op 0x000000bb        connection.go:395] <- LookUpInode (parent 154, name "abyss-1.9.0.tar.gz")
fuse_debug: Op 0x000000bb        connection.go:476] -> Error: "no such file or directory"
fuse_debug: Op 0x000000bc        connection.go:395] <- LookUpInode (parent 154, name "abyss-1.9.0.tar.gz")
fuse_debug: Op 0x000000bc        connection.go:476] -> Error: "no such file or directory"
fuse_debug: Op 0x000000bd        connection.go:395] <- CreateFile
fuse_debug: Op 0x000000bd        connection.go:474] -> OK
fuse_debug: Op 0x000000be        connection.go:395] <- WriteFile (inode 164, handle 2, offset 0, 65536 bytes)
fuse_debug: Op 0x000000be        connection.go:474] -> OK
fuse_debug: Op 0x000000bf        connection.go:395] <- WriteFile (inode 164, handle 2, offset 65536, 65536 bytes)
fuse_debug: Op 0x000000bf        connection.go:474] -> OK
fuse_debug: Op 0x000000c0        connection.go:395] <- WriteFile (inode 164, handle 2, offset 131072, 65536 bytes)
fuse_debug: Op 0x000000c0        connection.go:474] -> OK
fuse_debug: Op 0x000000c1        connection.go:395] <- WriteFile (inode 164, handle 2, offset 196608, 65536 bytes)
fuse_debug: Op 0x000000c1        connection.go:474] -> OK
fuse_debug: Op 0x000000c2        connection.go:395] <- WriteFile (inode 164, handle 2, offset 262144, 65536 bytes)
fuse_debug: Op 0x000000c2        connection.go:474] -> OK
fuse_debug: Op 0x000000c3        connection.go:395] <- WriteFile (inode 164, handle 2, offset 327680, 65536 bytes)
fuse_debug: Op 0x000000c3        connection.go:474] -> OK
fuse_debug: Op 0x000000c4        connection.go:395] <- WriteFile (inode 164, handle 2, offset 393216, 65536 bytes)
fuse_debug: Op 0x000000c4        connection.go:474] -> OK
fuse_debug: Op 0x000000c5        connection.go:395] <- WriteFile (inode 164, handle 2, offset 458752, 65536 bytes)
fuse_debug: Op 0x000000c5        connection.go:474] -> OK
fuse_debug: Op 0x000000c6        connection.go:395] <- WriteFile (inode 164, handle 2, offset 524288, 65536 bytes)
fuse_debug: Op 0x000000c6        connection.go:474] -> OK
fuse_debug: Op 0x000000c7        connection.go:395] <- WriteFile (inode 164, handle 2, offset 589824, 65536 bytes)
fuse_debug: Op 0x000000c7        connection.go:474] -> OK
fuse_debug: Op 0x000000c8        connection.go:395] <- WriteFile (inode 164, handle 2, offset 655360, 65536 bytes)
fuse_debug: Op 0x000000c8        connection.go:474] -> OK
fuse_debug: Op 0x000000c9        connection.go:395] <- WriteFile (inode 164, handle 2, offset 720896, 65536 bytes)
fuse_debug: Op 0x000000c9        connection.go:474] -> OK
fuse_debug: Op 0x000000ca        connection.go:395] <- WriteFile (inode 164, handle 2, offset 786432, 65536 bytes)
fuse_debug: Op 0x000000ca        connection.go:474] -> OK
fuse_debug: Op 0x000000cb        connection.go:395] <- WriteFile (inode 164, handle 2, offset 851968, 65536 bytes)
fuse_debug: Op 0x000000cb        connection.go:474] -> OK
fuse_debug: Op 0x000000cc        connection.go:395] <- WriteFile (inode 164, handle 2, offset 917504, 65536 bytes)
fuse_debug: Op 0x000000cc        connection.go:474] -> OK
fuse_debug: Op 0x000000cd        connection.go:395] <- WriteFile (inode 164, handle 2, offset 983040, 65536 bytes)
fuse_debug: Op 0x000000cd        connection.go:474] -> OK
fuse_debug: Op 0x000000ce        connection.go:395] <- WriteFile (inode 164, handle 2, offset 1048576, 65536 bytes)
fuse_debug: Op 0x000000ce        connection.go:474] -> OK
fuse_debug: Op 0x000000cf        connection.go:395] <- WriteFile (inode 164, handle 2, offset 1114112, 19369 bytes)
fuse_debug: Op 0x000000cf        connection.go:474] -> OK
fuse_debug: Op 0x000000d0        connection.go:395] <- FlushFile (inode 164)
fuse_debug: Op 0x000000d0        connection.go:474] -> OK
fuse_debug: Op 0x000000d1        connection.go:395] <- ReleaseFileHandle
fuse_debug: Op 0x000000d1        connection.go:474] -> OK
```

**--debug_gcs**
```
gcs: Req              0x1: <- StatObject("user3/")
gcs: Req              0x2: <- ListObjects()
gcs: Req              0x3: <- StatObject("user3")
gcs: Req              0x1: -> StatObject("user3/") (38.264271ms): gcs.NotFoundError: googleapi: Error 404: Not Found, notFound
gcs: Req              0x3: -> StatObject("user3") (82.747603ms): gcs.NotFoundError: googleapi: Error 404: Not Found, notFound
gcs: Req              0x2: -> ListObjects() (135.811697ms): OK
gcs: Req              0x4: <- ListObjects()
gcs: Req              0x4: -> ListObjects() (74.591335ms): OK
gcs: Req              0x5: <- StatObject("user3/abyss-1.9.0.tar.gz/")
gcs: Req              0x6: <- ListObjects()
gcs: Req              0x7: <- StatObject("user3/abyss-1.9.0.tar.gz")
gcs: Req              0x7: -> StatObject("user3/abyss-1.9.0.tar.gz") (33.913935ms): gcs.NotFoundError: googleapi: Error 404: Not Found, notFound
gcs: Req              0x5: -> StatObject("user3/abyss-1.9.0.tar.gz/") (36.370335ms): gcs.NotFoundError: googleapi: Error 404: Not Found, notFound
gcs: Req              0x6: -> ListObjects() (39.248765ms): OK
gcs: Req              0x8: <- ListObjects()
gcs: Req              0x8: -> ListObjects() (40.03776ms): OK
gcs: Req              0x9: <- ListObjects()
gcs: Req              0x9: -> ListObjects() (26.173556ms): OK
gcs: Req              0xa: <- CreateObject("user3/abyss-1.9.0.tar.gz")
gcs: Req              0xa: -> CreateObject("user3/abyss-1.9.0.tar.gz") (167.39552ms): OK
gcs: Req              0xb: <- Read("user3/abyss-1.9.0.tar.gz", <nil>)
gcs: Req              0xb: -> Read("user3/abyss-1.9.0.tar.gz", <nil>) (32.694381ms): OK
gcs: Req              0xc: <- CreateObject("user3/abyss-1.9.0.tar.gz")
gcs: Req              0xc: -> CreateObject("user3/abyss-1.9.0.tar.gz") (276.37326ms): OK
```

**Comment by jacobsa** [comment]
Thanks for the details. The only bug here appears to be that the storage browser incorrectly labels this as type Folder (which is unrelated to gcsfuse). I've filed Google-internal bug 27413601 for this.
