### ISSUE TITLE
fusermount stderr output is lost in background mode

### ISSUE THREAD

**Issue by bshaffer** [GoogleCloudPlatform/gcsfuse#161]
I am trying to mount GCSFuse from Managed VMs. I've followed the installation instructions for [other distributions](https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/installing.md#other-distributions), and have tried everything to get this to work. The `/path/to/targetdir/` is in the `fuse` group, 

```sh
~$ gcsfuse drupal-1233 /path/to/targetdir/
Using mount point: /path/to/targetdir/
Opening GCS connection...
Opening bucket...
Mounting file system...
daemonize.Run: readFromProcess: sub-process: mountWithArgs: mountWithConn: Mount: mount: fusermount: exit status 1
```

I have tried adding all the debug flags and no additional information was provided. I'm pretty stumped and would love some guidance! Is there any way to get this to work or find out what might be wrong here?

```sh
~$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 7.9 (wheezy)
Release:        7.9
Codename:       wheezy
```

**Comment by bshaffer** [comment]
Running `fusermount` on the CLI gives the following error message:

```sh
~$ fusermount -u /path/to/targetdir
fusermount: entry for /path/to/targetdir not found in /etc/mtab
```

**Comment by jacobsa** [comment]
Hi, a few questions:

1. Are you able to run a newer Debian jessie, which is newer and easier to support? (Probably not relevant, but you never know.)

2.  What version of gcsfuse are you running? (Run `gcsfuse -v` to find out.)

3.  Can you give the output of

        gcsfuse --foreground --debug_fuse drupal-1233 /path/to/targetdir/

4.  Consider running something like this to obtain a trace that might tell you more about why `fusermount` is unhappy:

        strace -f -o /tmp/trace gcsfuse --foreground --debug_fuse drupal-1233 /path/to/targetdir/

**Comment by bshaffer** [comment]
@jacobsa thank you for getting back to me! After running the command with `--foreground`, I was able to see the error:

```sh
~$: gcsfuse --foreground --debug_fuse drupal-1233 /path/to/targetdir
Using mount point: /path/to/targetdir
Opening GCS connection...
Opening bucket...
Mounting file system...
2016/02/29 01:32:27.098967 mount helper error: fusermount: mountpoint is not empty
2016/02/29 01:32:27.099123 mount helper error: fusermount: if you are sure this is safe, use the 'nonempty' mount option
mountWithArgs: mountWithConn: Mount: mount: fusermount: exit status 1
```

After removing the contents of the directory, I was able to mount. I didn't realize there was a file in there. 

It's strange that the error did not propagate with the debug flags. But it's working now. Thank you very much!

**Comment by jacobsa** [comment]
Glad it worked. It's a problem that the errors aren't visible though; will fix.
