### ISSUE TITLE
Reinstate tarball binary releases

### ISSUE THREAD

**Issue by dalbani** [GoogleCloudPlatform/gcsfuse#162]
Starting from version 0.12.0, it seems that tarball (binary) releases are no longer provided on GitHub.
In the same context as #111, I'd like to be able to simply download an archive, extract it and use it "as is".

**Comment by jacobsa** [comment]
Tarballs are hard to get right cross-platform, and are therefore dangerous (see #119 and #120). Does it not work for you to download the .deb file and install from that?

**Comment by dalbani** [comment]
Well, provided that I need to extract the archive on CoreOS (i.e. with limited tooling), having a standard `.tar.gz` file is much easier to handle than an `.rpm` or a `.deb`.
I understand that using the tarball produced issues on some systems but that shouldn't be a reason to "ban" it altogether, in my opinion.

**Comment by jacobsa** [comment]
You can of course extract the archive elsewhere and then ship over the files you want, right? If you're just looking for a gcsfuse binary, that part is easy (it's statically linked). The harder part is all the associated system-specific tooling for e.g. `mount` support, which is where the tarballs got into trouble.

Alternatively you could just compile your own:

    go get -v -u github.com/googlecloudplatform/gcsfuse

That will install the binary to `$GOPATH/bin/gcsfuse`, and requires only a working Go 1.6 installation.

**Comment by dalbani** [comment]
Indeed, I only need the `gcsfuse` binary, so I can either manually extract it from `.deb`/`.rpm` or compile it on my local computer, as you've rightly explained.
That's just a (small) step I was trying to avoid with using publicly available tarballs.
But if they introduce broader issues for the project, then let's not bother with it, I was asking just in case :-)

**Comment by jacobsa** [comment]
Yep, they are a bit of an issue unfortunately. Thanks for explaining.
