### ISSUE TITLE
gcsfuse is being discountinued

### ISSUE THREAD

**Issue by Spark2Ignite** [GoogleCloudPlatform/gcsfuse#163]
By reading [here](https://cloud.google.com/storage/docs/gcs-fuse) it says - "Cloud Storage FUSE has been discontinued at the Beta stage. There are no plans to advance it to the GA (“General Availability”) stage, and it is no longer a part of the Google Cloud Storage product"

Is this correct?

**Comment by benchong408** [comment]
Yes. It remains available as an open source project and one of a number of tools that will be available to work with GCS objects with different semantics.

Are you using gcsfuse today? If so, I'd like to understand your use cases, what you like/don't like about it and areas of improvement.

**Comment by Spark2Ignite** [comment]
I use gcsfuse extensively to process data stored in GCS from multiple instances. Each instance works on it's own subset of data and I don't need to copy the data back and forth from the bucket to the local storage. Also, some of the data is shared via NFS, providing convenient access to GCS buckets.

**Comment by benchong408** [comment]
That's great. Thanks for the feedback.

Is there anything that you'd like to see improvements on e.g. performance, latency, ability to support POSIX-style timestamps etc?

Also, do you have concerns about using gcsfuse as an open source tool? We'll like to make more community-supported tools available in the future and would like to understand public opinion on this approach :)

**Comment by Spark2Ignite** [comment]
My only concern with open source solution would be support. If I can't get Google Support when I need it for gcsfuse, I will likely to move somewhere else (like AWS EFS).

**Comment by benchong408** [comment]
Thanks for the feedback!

**Comment by despens** [comment]
Would love to see something like AWS EFS on Google's services as well. Amazon has done a great job with it, and it really lends itself to shared data being processed by multiple computing instances.

**Comment by conradneilands** [comment]
I too require a simple file system method to access cloud buckets. In my case I have legacy systems to support that are not easily migrated to other file access methods

Having this product being discontinued so soon without offering alternatives or future alternative raises a few questions about just how serious you are about offering real competition to AWS. 

Please update this web page https://cloud.google.com/compute/docs/disks/gcs-buckets to say this isn't a supported or maintained file access method. As it may lead a potential customer and in my case a paying real customer to think that this tool was usable for production systems

I have made a huge mistake migrating to a service that can't offer long term support of fundamental tools.

**Comment by benchong408** [comment]
Hi Conrad, the title of this Issue is unfortunate because gcsfuse has not been discontinued.

It continues to be supported (via this github community) and we have been responding to issues.

**Comment by conradneilands** [comment]
Thanks,
So it is safe to use? For how long? Should i be converting my legacy
systems to the supported API's?

I have hundreds of legacy machines ftping data into the bucket via a
compute instance and am not sure how to approach that without a file system
interface. Changing things on the legacy machine side is possible but not
easy.
Cheers
