### ISSUE TITLE
No such host while creating mounts

### ISSUE THREAD

**Issue by ankurkamra-05** [GoogleCloudPlatform/gcsfuse#1633]
I am trying to create mounts on unix box and getting exception as " dial tcp: lookup storage.googleapis.com on 11.0.1.1:53: no such host"

Executing command
 
gcsfuse -o ro,nonempty  --implicit-dirs --only-dir directory_name --stat-cache-ttl 1h --debug_fuse --debug_gcs --debug_http --log-file /fuse_2024.01.19.log bucketName mountPath

Getting below output

I0122 05:39:53.129667 2024/01/22 05:39:53.129609 Start gcsfuse/1.0.1 (Go version go1.20.5) for app "" using mount point: mountPath
Added environment https_proxy: Squid Proxy address
daemonize.Run: readFromProcess: sub-process: mountWithArgs: mountWithConn: fs.NewServer: create file system: SetUpBucket: Error in iterating through objects: Get "https://storage.googleapis.com/storage/v1/b/bucketName/o?alt=json&delimiter=&endOffset=&includeTrailingDelimiter=false&maxResults=1&pageToken=&prefix=path%2F&prettyPrint=false&projection=full&startOffset=&versions=false": dial tcp: lookup storage.googleapis.com on 11.0.1.1:53: no such host

**Comment by ashmeenkaur** [comment]
Hi @ankurkamra-05,

We've recently fixed a [bug](https://github.com/GoogleCloudPlatform/gcsfuse/issues/1541) in GCSFuse (version 1.4.1) that was causing it to ignore proxy settings from environment variable. 
Could you please try upgrading to GCSFuse version 1.4.1 and see if that resolves the issue you are encountering?

Thank you!

**Comment by ankurkamra-05** [comment]
Tried after upgrading to 1.4.1. Below are the logs

{"timestamp":{"seconds":1705997642,"nanos":831404036},"severity":"INFO","message":"Start gcsfuse/1.4.1 (Go version go1.21.5) for app \"\" using mount point: /path\n"}
{"timestamp":{"seconds":1705997642,"nanos":831849294},"severity":"INFO","message":"GCSFuse mount command flags: {\"AppName\":\"\",\"Foreground\":true,\"ConfigFile\":\"\",\"MountOptions\":{},\"DirMode\":493,\"FileMode\":420,\"Uid\":-1,\"Gid\":-1,\"ImplicitDirs\":false,\"OnlyDir\":\"\",\"RenameDirLimit\":0,\"CustomEndpoint\":null,\"BillingProject\":\"\",\"KeyFile\":\"\",\"TokenUrl\":\"\",\"ReuseTokenFromUrl\":true,\"EgressBandwidthLimitBytesPerSecond\":-1,\"OpRateLimitHz\":-1,\"SequentialReadSizeMb\":200,\"MaxRetrySleep\":30000000000,\"StatCacheCapacity\":4096,\"StatCacheTTL\":60000000000,\"TypeCacheTTL\":60000000000,\"HttpClientTimeout\":0,\"MaxRetryDuration\":-1000000000,\"RetryMultiplier\":2,\"LocalFileCache\":false,\"TempDir\":\"\",\"ClientProtocol\":\"http1\",\"MaxConnsPerHost\":100,\"MaxIdleConnsPerHost\":100,\"EnableNonexistentTypeCache\":false,\"StackdriverExportInterval\":0,\"OtelCollectorAddress\":\"\",\"LogFile\":\"logPath\",\"LogFormat\":\"json\",\"ExperimentalEnableJsonRead\":false,\"DebugFuseErrors\":true,\"DebugFuse\":true,\"DebugFS\":true,\"DebugGCS\":true,\"DebugHTTP\":true,\"DebugInvariants\":false,\"DebugMutex\":false}"}
{"timestamp":{"seconds":1705997642,"nanos":831944255},"severity":"INFO","message":"GCSFuse mount config flags: {\"CreateEmptyFile\":false,\"Severity\":\"TRACE\",\"Format\":\"json\",\"FilePath\":\"path",\"LogRotateConfig\":{\"MaxFileSizeMB\":512,\"BackupFileCount\":10,\"Compress\":true}}"}
{"timestamp":{"seconds":1705997642,"nanos":831976213},"severity":"INFO","message":"Creating Storage handle..."}
{"timestamp":{"seconds":1705997642,"nanos":835058616},"severity":"INFO","message":"Creating a mount at \"path"\n"}
{"timestamp":{"seconds":1705997642,"nanos":835094774},"severity":"INFO","message":"Creating a new server...\n"}
{"timestamp":{"seconds":1705997642,"nanos":835136655},"severity":"INFO","message":"Set up root directory for bucket bucket"}
{"timestamp":{"seconds":1705997642,"nanos":835180775},"severity":"TRACE","message":"gcs: Req              0x0: <- ListObjects(\"\")"}
{"timestamp":{"seconds":1705997643,"nanos":90402266},"severity":"TRACE","message":"gcs: Req              0x0: -> ListObjects(\"\") (255.186259ms): OK"}
{"timestamp":{"seconds":1705997643,"nanos":90530237},"severity":"INFO","message":"Mounting file system \"bucket\"..."}
{"timestamp":{"seconds":1705997643,"nanos":90623142},"severity":"TRACE","message":"fuse_debug: Beginning the mounting kickoff process"}
{"timestamp":{"seconds":1705997643,"nanos":90656118},"severity":"TRACE","message":"fuse_debug: Parsing fuse file descriptor"}
{"timestamp":{"seconds":1705997643,"nanos":90678583},"severity":"TRACE","message":"fuse_debug: Preparing for direct mounting"}
{"timestamp":{"seconds":1705997643,"nanos":90863748},"severity":"TRACE","message":"fuse_debug: Successfully opened the /dev/fuse in blocking mode"}
{"timestamp":{"seconds":1705997643,"nanos":90922104},"severity":"TRACE","message":"fuse_debug: Starting the unix mounting"}
{"timestamp":{"seconds":1705997643,"nanos":90965830},"severity":"TRACE","message":"fuse_debug: Directmount failed. Trying fallback."}
{"timestamp":{"seconds":1705997643,"nanos":92015165},"severity":"TRACE","message":"fuse_debug: Creating a socket pair"}
{"timestamp":{"seconds":1705997643,"nanos":92106333},"severity":"TRACE","message":"fuse_debug: Creating files to wrap the sockets"}
{"timestamp":{"seconds":1705997643,"nanos":92139659},"severity":"TRACE","message":"fuse_debug: Starting fusermount/os mount"}
{"timestamp":{"seconds":1705997643,"nanos":98781533},"severity":"TRACE","message":"fuse_debug: Wrapping socket pair in a connection"}
{"timestamp":{"seconds":1705997643,"nanos":98833827},"severity":"TRACE","message":"fuse_debug: Checking that we have a unix domain socket"}
{"timestamp":{"seconds":1705997643,"nanos":98854448},"severity":"TRACE","message":"fuse_debug: Read a message from socket"}
{"timestamp":{"seconds":1705997643,"nanos":98886800},"severity":"TRACE","message":"fuse_debug: Successfully read the socket message."}
{"timestamp":{"seconds":1705997643,"nanos":98904401},"severity":"TRACE","message":"fuse_debug: Converting FD into os.File"}
{"timestamp":{"seconds":1705997643,"nanos":98943128},"severity":"TRACE","message":"fuse_debug: Completed the mounting kickoff process"}
{"timestamp":{"seconds":1705997643,"nanos":98960314},"severity":"TRACE","message":"fuse_debug: Creating a connection object"}
{"timestamp":{"seconds":1705997643,"nanos":99115178},"severity":"TRACE","message":"fuse_debug: Op 0x00000001        connection.go:415] <- init"}
{"timestamp":{"seconds":1705997643,"nanos":99153823},"severity":"TRACE","message":"fuse_debug: Op 0x00000001        connection.go:497] -> OK ()"}
{"timestamp":{"seconds":1705997643,"nanos":99196079},"severity":"ERROR","message":"fuse: writeMessage: invalid argument [80 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]"}
{"timestamp":{"seconds":1705997643,"nanos":99235995},"severity":"ERROR","message":"Error while mounting gcsfuse: mountWithStorageHandle: Mount: newConnection: Init: writeMessage: invalid argument [80 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]\n"}

**Comment by ashmeenkaur** [comment]
Hi @ankurkamra-05, can you please confirm the OS version  you are using?

**Comment by ankurkamra-05** [comment]
Red Hat 7.4

**Comment by ashmeenkaur** [comment]
Unfortunately, GCSFuse isn't fully compatible with RHEL/CentOS 7.5 and lower versions.  Your best solution would be to upgrade your [OS to RHEL 7.9 or later](https://cloud.google.com/storage/docs/gcs-fuse#frameworks-os-architectures) for guaranteed functionality.

Please feel free to re-open in case you run into any other issues.
