### ISSUE TITLE
Error 404 on repository / debian wheezy

### ISSUE THREAD

**Issue by Anthold** [GoogleCloudPlatform/gcsfuse#168]
Hi, here's my problem : 

Err http://packages.cloud.google.com wheezy/main amd64 Packages                                    
  404  Not Found [IP: 74.125.206.100 80]
Machine is on google plateform;

I installed the package manually so it works, but the apt-get solution is not working.

Thanks

**Comment by jacobsa** [comment]
`apt-get` installation is supported only for Debian jessie and above; see [here](https://github.com/googlecloudplatform/gcsfuse/blob/master/docs/installing.md#ubuntu-and-debian-latest-releases). Instead please follow [these instructions](https://github.com/googlecloudplatform/gcsfuse/blob/master/docs/installing.md#other-distributions) to install on wheezy.
