### ISSUE TITLE
`--implicit-dirs` not able to be used in conjunction with `mount -t ...`

### ISSUE THREAD

**Issue by paulcjh** [GoogleCloudPlatform/gcsfuse#1705]
**Describe the issue**
The necessity of `--implicit-dirs` is outlined in various places but it is not able to be used when mounting with the native `mount` option targeting gcsfuse. This makes the scripts provided in following issue #1387. 

1. run `mount -t gcsfuse --implicit-dirs my-bucket local-dir`

**System (please complete the following information):**
 - OS: Ubuntu 22.04

**Comment by raj-prince** [comment]
Did you try the command like this: `sudo mount -t gcsfuse -o rw,allow_other,implicit_dirs=true my-bucket local-dir` ?

**Comment by gargnitingoogle** [comment]
Adding more details to https://github.com/GoogleCloudPlatform/gcsfuse/issues/1705#issuecomment-1941312497.. With mount command, all `-`s in the command flags should be replaced with undescores (`_`s).

Example below:

Wrong usage
-----------
sudo mount -t gcsfuse -o **implicit-dirs** $bucket $mountpath

Error message:
daemonize.Run: readFromProcess: sub-process: mountWithArgs: mountWithStorageHandle: Mount: mount: *invalid argument*

Correct usage
-------------
sudo mount -t gcsfuse -o **implicit_dirs** $bucket $mountpath

Error message: None

**Comment by gargnitingoogle** [comment]
@paulcjh please look at the above comment for solution. 

We'll also be adding the same to our documentation.

**Comment by gargnitingoogle** [comment]
This has now been documented at [GCSFuse cloud documentation](https://cloud.google.com/storage/docs/gcsfuse-mount#mounting_by_using_the_linux_mount_command) .

**Comment by ashmeenkaur** [comment]
Hi @paulcjh 

I am closing this issue as we've provided a fix and documented this on our [official documentation](https://cloud.google.com/storage/docs/gcsfuse-mount#linux-mount). Feel free to reopen this issue if you need further assistance.

Thanks,
Ashmeen
