### ISSUE TITLE
allow setting of public file permission

### ISSUE THREAD

**Issue by triune** [GoogleCloudPlatform/gcsfuse#171]
If I mount a storage bucket locally and then copy a new file over to this bucket, the file will default to having the public permission off. I would like to be able to set this public permission via chmod or some other mechanism.

**Comment by jacobsa** [comment]
Sorry, gcsfuse doesn't support manipulating GCS ACLs. (And indeed posix file system permissions/ownership don't have the expressivity to represent them.)

**Comment by triune** [comment]
Ok, so this can't be done in gcfuse... but is there anyway to programmatically publish a file to the public without having to do so through the cloud console?

**Comment by jacobsa** [comment]
Looks like you could probably use [`ObjectAccessControls.patch`](https://cloud.google.com/storage/docs/json_api/v1/objectAccessControls/patch#parameters), setting `entity` to `allUsers`. But I'm not sure.

**Comment by triune** [comment]
Since all my files are being moved to a gcsfuse mount programmatically, I can update them afterwards with something like this:
gsutil acl set public-read gs://bucket/path/file.ext
So, I don't really need the requested feature here anymore :)
