### ISSUE TITLE
_netdev option should be ignored

### ISSUE THREAD

**Issue by csnook** [GoogleCloudPlatform/gcsfuse#172]
Most Linux distributions support the _netdev flag in /etc/fstab to indicate that a filesystem should not be mounted until after the network is up, even if it's not on the list of filesystems the distribution knows about as being network filesystems. When using this with gcsfuse, the boot sequence correctly ignores the mount the first time it processes fstab, and attempts to mount the filesystem on the second pass. The mount fails because gcsfuse attempts to use the _netdev flag, and keeps failing even when the mount is invoked from the command line, unless calling gcsfuse directly to bypass /etc/fstab.

**Comment by jacobsa** [comment]
Fixed. Please try version 0.18.1.
