### ISSUE TITLE
Input/Output errors

### ISSUE THREAD

**Issue by cswingle** [GoogleCloudPlatform/gcsfuse#174]
I just installed gcsfuse on a "small" VM instance, created a directory and a bucket, then mounted the bucket.  I can see the file in the bucket, but when I try to create a new file from the VM, I get Input/Output error:

    $ gcsfuse -v
    gcsfuse version 0.18.2 (Go version go1.6.2)
    $ mkdir swingleydev_vm
    $ gcsfuse swingleydev_vm /home/cswingle/swingleydev_vm
    Using mount point: /home/cswingle/swingleydev_vm
    Opening GCS connection...
    Opening bucket...
    Mounting file system...
    File system has been successfully mounted.
    $ ls swingleydev_vm/
    README.rst
    $ touch swingleydev_vm/foo.txt
    touch: cannot touch ‘swingleydev_vm/foo.txt’: Input/output error

Here's the mount info:

    $ cat /proc/mounts | grep swingleydev
    swingleydev_vm /home/cswingle/swingleydev_vm fuse rw,nosuid,nodev,relatime,user_id=1000,group_id=1001,default_permissions 0 0

**Comment by jacobsa** [comment]
This is likely a permissions error. Run gcsfuse with `--foreground` (and `--debug_fuse` if necessary) to see the error.

**Comment by cswingle** [comment]
Thanks.  I do see a permissions error with `--foreground` and `--debug_fuse`:

    connection.go:476] -> Error: "CreateChildFile: googleapi: Error 403: Insufficient Permission, insufficientPermissions"

But I guess I'm not sure where the issue is.  I can upload files to the bucket, which implies I have permission on the Google Cloud end.  And the filesystem and mount settings appear to support my ability to write:

    $ ls -l | grep swingleydev
    drwxr-xr-x  1 cswingle cswingle    0 Jun 23 15:03 swingleydev_vm/

    $ $ grep swingleydev /proc/mounts 
    swingleydev_vm /home/cswingle/swingleydev_vm fuse rw,nosuid,nodev,relatime,user_id=1000,group_id=1001,default_permissions 0 0
    $ id
    uid=1000(cswingle) gid=1001(cswingle) groups=1001(cswingle),4(adm),30(dip),44(video),46(plugdev),1000(google-sudoers)
What am I missing?

**Comment by jacobsa** [comment]
You (as in your Google user account) probably has permissions, but it's likely that the credentials you're giving gcsfuse are read-only. If you're not configuring them explicitly, they're coming from the credentials that you told the VM to give the programs it runs (or the defaults for that setting).

See the [documentation](https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/mounting.md#credentials) about credentials. In particular grep for `storage-full`.

**Comment by cswingle** [comment]
My apologies.  You're right.  I misunderstood how authentication was working.  Once I used `gcloud auth login` everything worked as expected.

**Comment by jacobsa** [comment]
Great, glad it worked out.

**Comment by kahing** [comment]
should gcsfuse return `EACCESS` in this case?

**Comment by jacobsa** [comment]
Hard to say. I think that may be even more surprising, since there are no apparent permissions problems at the posix level.

**Comment by ZackPashkin** [comment]
same error

**Comment by AaronAntonopoulos** [comment]
same here!
gcloud auth login didnt help

**Comment by TerraqueoDev** [comment]
same here!! gcloud auth login didnt help

**Comment by kim-sardine** [comment]
Please check your VM's `Cloud API access scopes` in detail page.
It have to have **Write access** for Storage.
you can change scope after you stop VM

**Comment by kylefoley76** [comment]
I'm having the exact same problem.  I have a mounted storage bucket on a gcloud VM instance but I cannot write a file to the storage bucket.  It seems that my problem is that I have not given Google my authentication credentials.  I tried moving the credentials I used on my Mac over to the Linux computer but that so far has had no affect.  Here is the exact syntax:

```
str1 = "/home/kylefoley/byu_corpus_small/codes/My_Project_999.json"
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = str1

key = "9999"
```
I have successfully mounted the storage bucket with gcsfuse and can read files from it but when I try to write files to it I get the following error:
```
Traceback (most recent call last):
  File "build_index.py", line 638, in <module>
    determine_fork()
  File "build_index.py", line 635, in determine_fork
    main_fork(make_changes, len(rem_files), **kwargs)
  File "build_index.py", line 590, in main_fork
    save_iweb_pickle(dct, 'done_forks')
  File "/home/kylefoley/byu_corpus_small/code/byu_globals.py", line 27, in save_iweb_pickle
    pi.save_pickle(obj, name, 1)
  File "/home/kylefoley/byu_corpus_small/code/pickling.py", line 55, in save_pickle
    temp = open(name, "wb")
OSError: [Errno 5] Input/output error: '/mnt/disks/temp_dir/fix_mistakes/done_forks.pkl'
```

When the above wrote:

>My apologies. You're right. I misunderstood how authentication was working. Once I used gcloud auth login everything worked as expected.

 I can't figure out what he means by that. I would think it would have something to do with this module:

`from oauth2client.client import GoogleCredentials`

But I cannot figure out what to do with that module.  By the way my mountpoint is:

`/mnt/disks/temp_dir/`

**Comment by kylefoley76** [comment]
I was able to solve the problem in the following way: I had to go to Cloud API Access Scopes and verify under the VM configuration that it has read write or full access for storage. This involved pressing edit on the gcloud console which lists my instances.  At the bottom of the page, there was the limitation for storage which I changed to 'full'.  That did it.

**Comment by oktbabs** [comment]
touch: cannot touch ‘dada.txt’: Input/output error
Solution:
You must stop the VM instance to edit its API access scopes
Allow default access OR Allow full access to all Cloud APIs OR Set access for each API

**Comment by changtimwu** [comment]
Input/Output error +1

In the same environment, using `gsutil` to access the same bucket works perfectly
```
gsutil ls gs://waymo_open_dataset_v_1_3_1_individual_files/                   
gs://waymo_open_dataset_v_1_3_1_individual_files/domain_adaptation/
gs://waymo_open_dataset_v_1_3_1_individual_files/testing/
gs://waymo_open_dataset_v_1_3_1_individual_files/testing_3d_camera_only_detection/
gs://waymo_open_dataset_v_1_3_1_individual_files/training/
gs://waymo_open_dataset_v_1_3_1_individual_files/validation/

gsutil cp gs://waymo_open_dataset_v_1_3_1_individual_files/testing_3d_camera_only_detection/segment-13205514725944595375_1729_647_1749_647.tfrecord .
Copying gs://waymo_open_dataset_v_1_3_1_individual_files/testing_3d_camera_only_detection/segment-13205514725944595375_1729_647_1749_647.tfrecord...
| [1 files][341.5 MiB/341.5 MiB]    4.5 MiB/s                                   
Operation completed over 1 objects/341.5 MiB.   
```
