### ISSUE TITLE
Directory permissions of mount point show up as questions marks

### ISSUE THREAD

**Issue by timduly4** [GoogleCloudPlatform/gcsfuse#175]
Hi there,

I am following the instructions to connect a cloud storage bucket, per Google Cloud Platform documentation:

https://cloud.google.com/compute/docs/disks/gcs-buckets

I generated an Ubuntu 14.04 LTS trusty instance on the VM.

Everything goes well, including the mounting command:

```
timduly@instance-2:~$ sudo chmod a+w /mnt/gcs-bucket/
timduly@instance-2:~$ sudo gcsfuse tim07 /mnt/gcs-bucket/
Using mount point: /mnt/gcs-bucket
Opening GCS connection...
Opening bucket...
Mounting file system...
File system has been successfully mounted.
```

But, a closer inspection of the directory yields fairly odd permissions on the folder:

```
timduly@instance-2:~$ ll /mnt/
ls: cannot access /mnt/gcs-bucket: Permission denied
total 8
drwxr-xr-x  3 root root 4096 Jun 28 21:12 ./
drwxr-xr-x 23 root root 4096 Jun 28 19:35 ../
d?????????  ? ?    ?       ?            ? gcs-bucket/
```

As a result, I am unable to write to this folder:

```
timduly@instance-2:~$ echo 'Hello, World!' > /mnt/gcs-bucket/hello.txt
-bash: /mnt/gcs-bucket/hello.txt: Permission denied
```

Note that if I unmount, the permissions seem fine:

```
timduly@instance-2:~$ sudo umount /mnt/gcs-bucket
timduly@instance-2:~$ ll /mnt/
total 12
drwxr-xr-x  3 root root 4096 Jun 28 21:12 ./
drwxr-xr-x 23 root root 4096 Jun 28 19:35 ../
drwxrwxrwx  2 root root 4096 Jun 28 21:12 gcs-bucket/
```

Do you have any idea what might be going on here?

Thanks,
Tim

Related:  https://github.com/GoogleCloudPlatform/gcsfuse/issues/1 , but I can't quite determine what was the fix here...

**Comment by jacobsa** [comment]
It's very likely that this is due to running gcsfuse with `sudo`. Please try again without that.

**Comment by timduly4** [comment]
You are correct.  Wow!  The tutorial clearly does *not* use sudo-- I'm not sure how I missed this.

Thanks!

**Comment by jacobsa** [comment]
No worries, it's a common mistake. Glad it works now.

**Comment by bjornleffler** [comment]
Fuse overwrites the permissions on the mounting directory to 755. Changing the permissions before mounting shouldn't do anything.
