### ISSUE TITLE
Executed PHP Script Cannot Access Mounted Drive

### ISSUE THREAD

**Issue by syclone** [GoogleCloudPlatform/gcsfuse#180]
I was able to mount my Google Cloud Storage using the command line below:

`gcsfuse -o allow_other -file-mode=660 -dir-mode=770  --uid=<uid> --gid=<gid> testbucket /path/to/domain/folder`

The group includes the user **apache**. Apache is able to write to the mounted drive like so:

`sudo -u apache echo 'Some Test Text' > /path/to/domain/folder/hello.txt`

**hello.txt** appears in the bucket as expected. However when I execute the below php script I get an error:

`<?php file_put_contents('/path/to/domain/folder/hello.txt', 'Some Test Text');`

PHP Error: **failed to open stream: Permission denied**

`echo exec('whoami');` Returns **apache**

I have been at this for 2 days. I assumed this is a common use for mounting with gcsfuse or something similar to this but, I seem to be the only one on the internet with this issue. I do not know if its an issue with the way I mounted it or the service security of httpd.

**Comment by jacobsa** [comment]
There are a lot of moving parts here. Are you able to reproduce the problem without PHP or even Apache? That would help a lot. Failing that, maybe you could use `strace` to see exactly what system call(s) PHP is making that fail.

**Comment by syclone** [comment]
No. I am able to create files to bucket outside of PHP with the apache user in the terminal. Only when using PHP does it fail. I also tried `fopen` function and I got the same error. I will try running a trace and let you know the output.

**Comment by syclone** [comment]
I did understand how to use the strace but I created a test server and installed xdebug which didnt really provide any additional information. Here is the screen
![xdebug](https://cloud.githubusercontent.com/assets/16844791/17201505/fe9a52e4-545c-11e6-8d92-d4f3fe849c47.png)
shot.

**Comment by jacobsa** [comment]
Sorry, I don't know what to say. PHP must be doing something interesting with how it accesses the file, but without a trace of system calls I couldn't say what.

**Comment by TamalSaha** [comment]
@syclone , In PHP, folders need to have executable bit set for file_put_contents() to work.
