### ISSUE TITLE
-bash: /mnt/gcs-bucket/hello.txt: Input/output error

### ISSUE THREAD

**Issue by gokhandilek** [GoogleCloudPlatform/gcsfuse#185]
I am trying to create a file inside my VM's mounted bucket folder.
I can create folder & upload them via google cloud console and they appear in my VMs bucket folder without any issue.
I tried to create a hello.txt in my VM but I seem to get this error now.
Here is the permission of the /mnt folder
```
user1@testing1:/$ ll /mnt
total 8
drwxr-xr-x  3 root      root           4096 Aug 31 01:16 ./
drwxr-xr-x 25 user1  admin        4096 Aug 30 08:17 ../
drwxr-xr-x  1 user1    user1        0 Aug 31 01:39 gcs-bucket/
user1@testing1:/$ 

```
I do not seem to create files using VM -  I would appreciate if someone can let me know a possible cause.
Thank you.

**Comment by jacobsa** [comment]
Please use `gcsfuse --foreground`, potentially also with `--debug_fuse` to see what's going on here. It's likely that you have read-only access to your bucket, because your VM wasn't created with the appropriate credentials (see [here](https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/mounting.md#credentials)).

**Comment by gokhandilek** [comment]
```
fuse: 2016/08/31 04:44:59.016212 *fuseops.SetInodeAttributesOp error: SetMtime: UpdateObject: googleapi: Error 403:
 Insufficient Permission, insufficientPermissions
```
Do I need to enable more services for this?

Here is the API access scopes:

Cloud API access scopes

BigQuery	Disabled
Bigtable Admin	Disabled
Bigtable Data	Disabled
Cloud Datastore	Enabled
Cloud Logging API	Write Only
Cloud Monitoring API	Write Only
Cloud Pub/Sub	Disabled
Cloud SQL	Disabled
Compute	Disabled
Service Control	Enabled
Service Management	Read Only
Storage	Read Write
Task queue	Disabled
User info	Disabled

**Comment by gokhandilek** [comment]
Ok finally sorted.
I had to give it a key file explicly using the command below:
`gcsfuse --key-file /storage.json --foreground  mybeautifulbucket /mnt/gcs-bucket`

Thank you for your help!
