### ISSUE TITLE
GCSFuse needs to retry fetching application default credentials

### ISSUE THREAD

**Issue by porridge** [GoogleCloudPlatform/gcsfuse#187]
Since the GCE metadata server is not guaranteed do be 100% reliable, gcsfuse can intermittently fail with:

```
mountWithArgs: getConn: DefaultTokenSource: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
```

I don't know about Go libraries, but Python ones do not retry on metadata server unavailability, so you probably need to handle this in the gcsfuse code.

**Comment by porridge** [comment]
See also https://github.com/google/oauth2client/issues/581.

**Comment by jacobsa** [comment]
Thanks for the report. I have two concerns:

1. It definitely seems like this logic should go in the oauth package, rather than each user having to implement it themselves. (If this is a serious problem for you of course as an interim solution gcsfuse could do it).

2. How to distinguish failures to find default credentials due to metadata server flakiness from the credentials just not existing?

**Comment by porridge** [comment]
FWIW, I think I have a temporary workaround in that we now try to launch
gcsfuse a few times. I hope that once it's up it will work for a while?

**Comment by jacobsa** [comment]
As far as I understand it, the metadata server is only contacted once.

**Comment by jacobsa** [comment]
Closing this after >1 month of inactivity, and because I think the logic belongs in the oauth client package. If you've got more to say, please feel free to reopen.

**Comment by porridge** [comment]
From a customer PoV this is a problem with gcsfuse. It's fine to close it
here, but then please file an issue against the oauth client package you're
using. I don't even know which one it is.

**Comment by jacobsa** [comment]
Haven't you already done so? I thought you linked to such a thread above?

**Comment by porridge** [comment]
That was a Python library.

2016-10-20 6:23 GMT+02:00 Aaron Jacobs <notifications@github.com>:

**Comment by kislaykishore** [comment]
@timeyr Could you open a new issue for your use-case?
