### ISSUE TITLE
ln: /sbin/mount_gcsfuse: Operation not permitted

### ISSUE THREAD

**Issue by karan** [GoogleCloudPlatform/gcsfuse#188]
Mac OS X 10.11.6

While following the installations guide:

```
$ brew install homebrew/fuse/gcsfuse
Warning: homebrew/fuse/gcsfuse-0.19.0 already installed

$ sudo ln -s /usr/local/sbin/mount_gcsfuse /sbin
ln: /sbin/mount_gcsfuse: Operation not permitted
```

Basically, I'm trying to create a persistent mount to a gcs bucket (as it is, the mount disappears when my mac sleeps). I *think* I need to use fstab with the `auto` option. Is that right?

**Comment by jacobsa** [comment]
I can't comment on how fstab interacts with Mac sleep, but you do want to link the tool there, yes.

Do you have any idea why you're getting the permission error? Does a file with that name already exist or something? Can you use `dtruss` to figure out what syscall is failing?

**Comment by karan** [comment]
No idea why the permission error.

The file doesn't exist in `/sbin/`.

Will need to `dtruss` in recovery mode.

**Comment by jacobsa** [comment]
Closing after inactivity. If you can root cause this and find it's a gcsfuse bug, please let me know.

**Comment by Antipov-Anton** [comment]
Answer here: https://apple.stackexchange.com/a/196226

It helped me with same problem.
