### ISSUE TITLE
ls: reading directory '.': Input/output error

### ISSUE THREAD

**Issue by nik736** [GoogleCloudPlatform/gcsfuse#190]
Hi,

I am trying to mount my bucket on a newly created ubuntu 16.04 compute instance.

> gcsfuse --debug_gcs --debug_http --debug_fuse --debug_invariants [bucket] mnt
> Using mount point: /home/ubuntu/mnt
> Opening GCS connection...
> Opening bucket...
> Mounting file system...
> File system has been successfully mounted.

But I always get the same error:
`ls: reading directory '.': Input/output error`

> cd mnt
> ubuntu@hostname:~/mnt$ ls
> ls: reading directory '.': Input/output error

What could be the problem?

Thanks! :-)

**Comment by nik736** [comment]
This only happens on Google Cloud Instances. I just spun up a droplet on DigitalOcean and the same commands etc. work absolutely fine. What could be wrong on the GC instances?

**Comment by jacobsa** [comment]
Please run with `--foreground` in addition to the flags you have already in order to see the issue. You likely missed that you need to create your GCE instances with [the `storage-full` access scope](https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/mounting.md#credentials).

**Comment by nik736** [comment]
I simply added the `key_file` param and it works fine now. Thanks!

**Comment by daviddemeij** [comment]
We are experiencing this same issue, but only on the main directory (i.e. `ls ~/gcs`) but not on the subdirectories (i.e. `~/gcs/subdirectory`). 

The issue exists locally as well as on our google cloud instances and only occurs when using `--implicit-dirs` on a specific (large) bucket, for some reason for other buckets we don't get this error. 

I don't know if this is still the right place to ask this question as is this seems a very specific case, but I am curious if you have an idea what the problem may be.

**Comment by daviddemeij** [comment]
Managed to fix this, apparently, there was a directory names `/` in our bucket that `gcsfuse` didn't like, probably an edge case that doesn't really require a fix.
