### ISSUE TITLE
Permission problem

### ISSUE THREAD

**Issue by nik736** [GoogleCloudPlatform/gcsfuse#192]
Hi guys,

I've mounted a bucket and can create files manually without problems. What I want to do now is letting nginx write in the mounted bucket/folder, the problem is that it has no permission to do so:

> *3 dash: error creating fragment file (13: Permission denied), client: 1.2.3.4, server: 0.0.0.0:1935
> 2016/09/26 16:04:42 [error] 18139#0: *3 x: error creating fragment file (13: Permission denied), client: 1.2.3.4, server: 0.0.0.0:1935
> 2016/09/26 16:04:42 [error] 18139#0: *3 x: write() failed (9: Bad file descriptor), client: 1.2.3.4, server: 0.0.0.0:1935
> 2016/09/26 16:04:42 [error] 18139#0: *3 x: error creating xx init file (13: Permission denied), client: 1.2.3.4, server: 0.0.0.0:1935
> 2016/09/26 16:04:42 [error] 18139#0: *3 x: open failed: '/opt/gcs/balbla.xx.bak' (13: Permission denied), client: 1.2.3.4, server: 0.0.0.0:1935

I mounted the bucket with `-o allow_other` for testing purpose, which doesn't change anything. Anyone with an idea? 

I'm on Ubuntu 16.04.

Thanks! :-)

**Comment by jacobsa** [comment]
`allow_other` will allow another user to interact with the file system (please be careful, there are security implications), but it doesn't change the fact that the permissions of all of the files and directories don't allow that users to modify them. You probably want to change `--uid`, `--gid`, `--file-mode`, and/or `--dir-mode`. See [here](https://github.com/googlecloudplatform/gcsfuse/blob/master/docs/semantics.md#inodes).

**Comment by nik736** [comment]
Ah, thanks! I got it working now :-)
