### ISSUE TITLE
gcsfuse is not available on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by kurin** [GoogleCloudPlatform/gcsfuse#202]
I had to grab the .deb from here and add it manually.  It probably ought to be available to apt-get.

**Comment by jacobsa** [comment]
Did you follow the instructions [here](https://github.com/googlecloudplatform/gcsfuse/blob/a1094766078dd421c3e44285183bce1d8d05ce1a/docs/installing.md#ubuntu-and-debian-latest-releases) to set up apt in the appropriate way? I just did so on a fresh GCE instance running the `ubuntu-1604-lts` image, and it worked for me.

**Comment by kurin** [comment]
Oh, no I didn't see that page.  Can gcsfuse not be part of the default cloud repos?

**Comment by kurin** [comment]
So it turns out that the default repos apparently can't be (or otherwise aren't) rehosted by Google with Special Google Packages added in.  Meaning "no."

**Comment by jacobsa** [comment]
Right yeah, you have to set up the repo manually unfortunately.
