### ISSUE TITLE
limit-ops-per-sec unsupported in mount

### ISSUE THREAD

**Issue by ihaque-freenome** [GoogleCloudPlatform/gcsfuse#203]
Passing a `-o limit_ops_per_sec` option to `mount` (or in fstab) fails with

```
$ mount -t gcsfuse -o limit_ops_per_sec=100 REDACTED mountdir
Calling gcsfuse with arguments: -o rw -o limit_ops_per_sec=100 REDACTED mountdir
Using mount point: mountdir
Opening GCS connection...
Opening bucket...
Mounting file system...
daemonize.Run: readFromProcess: sub-process: mountWithArgs: mountWithConn: Mount: mount: running fusermount: exit status 1

stderr:
fusermount: mount failed: Invalid argument

running gcsfuse: exit status 1
```

This seems similar to #183, which was fixed with some special-casing in https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/tools/mount_gcsfuse/main.go. Do additional special cases need to be added for the numeric performance throttling options `limit-ops-per-sec` and `limit-bytes-per-sec`?

**Comment by jacobsa** [comment]
Yes, that's probably what needs to happen. Please feel free to send a pull request.

**Comment by AlexFinn** [comment]
https://github.com/GoogleCloudPlatform/gcsfuse/pull/225
