### ISSUE TITLE
Permissions not taking effect

### ISSUE THREAD

**Issue by cgentilesos** [GoogleCloudPlatform/gcsfuse#205]
I am able to create a mount point and it mounts successfully.

After mounting, I can run an ls command, and get the directory listing for the mount point. I can view a text file running the more command *IF* the file was created after mounting the bucket via gcsfuse. Any other text files do not print out when running the more command.

The main issue however is that when trying to create a new file, delete an existing file, or write to an existing file, I am given a permissions error:

rm: cannot remove 'test.txt': Input/output error

touch: cannot touch 'test.file': Input/output error

Debug message: 

gcs: Req             0x1c: -> StatObject("test.file") (45.663289ms): gcs.NotFoundError: googleapi: Error 404: Not Found, notFound
fuse_debug: Op 0x00000097        connection.go:476] -> Error: "no such file or directory"

Command to load as needed user:

su -s /bin/bash -c 'gcsfuse -o allow_other --file-mode=666 --dir-mode=666  --debug_gcs --debug_http --debug_fuse --debug_invariants --uid 1002 --gid 1002 --foreground bucket /path' backups

Any help would be greatly appreciated

**Comment by jacobsa** [comment]
1. Is it possible that you have some other process touching the bucket concurrently with using gcsfuse? See #200 for a similar issue where it turned out this was the problem.

2. Can you please post a [gist](https://gist.github.com/) of some more complete logs with `--foreground --debug_gcs --debug_fuse`? I'm having trouble understanding your process.

3. Is this reproducible? Please post a minimal way to reproduce it.

**Comment by cgentilesos** [comment]
It looks like I cannot reproduce this on a new standalone instance. The original installation had been on an instance that had s3fs installed and targeting GCS but was not completely removed from the instance. That appears to be the only conflict as both were plain Ubuntu 16.04 installations other than the s3fs installation on the original machine.

**Comment by jacobsa** [comment]
Thanks for the update. Closing; please let me know if you wind up reproducing it again.
