### ISSUE TITLE
Debian Jessie apt Update/Installation Error

### ISSUE THREAD

**Issue by Ropes** [GoogleCloudPlatform/gcsfuse#206]
Running on Debian8 I'm unable to install following the installing.md steps. 

Upon running `apt-get update` I get the following packaging errors:
```
Fetched 1,215 kB in 3s (388 kB/s)
W: Failed to fetch http://packages.cloud.google.com/apt/dists/jessie/main/binary-amd64/Packages  404  Not Found [IP: 216.58.216.174 80]

W: Failed to fetch http://packages.cloud.google.com/apt/dists/jessie/main/binary-i386/Packages  404  Not Found [IP: 216.58.216.174 80]

E: Some index files failed to download. They have been ignored, or old ones used instead.
```

Running Debian 8.6:
```
>lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.6 (jessie)
Release:	8.6
Codename:	jessie
```

How the source is configured:
```
# cat /etc/apt/sources.list.d/gcsfuse.list 
deb http://packages.cloud.google.com/apt jessie main
```

I ran `curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -`
These are the Google related keys currently trusted:
```
# apt-key list 
/etc/apt/trusted.gpg
--------------------
pub   1024D/7FAC5991 2007-03-08
uid                  Google, Inc. Linux Package Signing Key <linux-packages-keymaster@google.com>
sub   2048g/C07CB649 2007-03-08
```
...
```
pub   2048R/A7317B0F 2015-04-03 [expires: 2018-04-02]
uid                  Google Cloud Packages Automatic Signing Key <gc-team@google.com>
```

Any thoughts, I don't think I've deviated from the install steps; perhaps the package endpoint is misconfigured or has been moved?

**Comment by jacobsa** [comment]
I'm unable to reproduce this with a fresh instance on GCE. Here's what I did:

```
gcloud compute instances create debian-8 --scopes storage-full --image-project debian-cloud --image-family debian-8 --machine-type n1-standard-4 --project <redacted> --zone asia-east1-a --boot-disk-size 500GB

gcloud compute ssh --zone asia-east1-a debian-8

export GCSFUSE_REPO=gcsfuse-`lsb_release -c -s`
echo "deb http://packages.cloud.google.com/apt $GCSFUSE_REPO main" | sudo tee /etc/apt/sources.list.d/gcsfuse.list
curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -


sudo apt-get update
sudo apt-get install gcsfuse

gcsfuse -v
```

Can you clarify whether you're running on GCE? If not, you may be on your own for trouble-shooting this, because I don't have easy access to anything else. :-/

**Comment by Ropes** [comment]
Thank you for the quick response!

It was my fault. In the sources list file I had:
`deb http://packages.cloud.google.com/apt jessie main`

However the correct entry is:
```
deb http://packages.cloud.google.com/apt gcsfuse-jessie main
```

I was able to get it working internal to GCE and on an external host!

**Comment by jacobsa** [comment]
Great! Thanks for the update.

**Comment by odigity** [comment]
This mistake is still in the docs.  (install.md)  I just ran into it myself, then found this issue when searching for answers.

**Comment by jacobsa** [comment]
Which mistake? The docs are correct as far as I can tell.

**Comment by odigity** [comment]
Under [Ubuntu/Debian](https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/installing.md#ubuntu-and-debian-latest-releases) in the Install Guide, this:

    export GCSFUSE_REPO=gcsfuse-`lsb_release -c -s`
    echo "deb http://packages.cloud.google.com/apt $GCSFUSE_REPO main" | sudo tee /etc/apt/sources.list.d/gcsfuse.list

Should be this:

    export GCSFUSE_REPO=gcsfuse-`lsb_release -c -s`
    echo "deb http://packages.cloud.google.com/apt gcsfuse-$GCSFUSE_REPO main" | sudo tee /etc/apt/sources.list.d/gcsfuse.list

**Comment by jacobsa** [comment]
You've got a double `gcsfuse-` there—it's already present in the `export GCSFUSE_REPO` line.

Perhaps this is a shell difference? As I said on 2017-01-20, these exact instructions (copied and pasted) worked fine for me.

**Comment by odigity** [comment]
Oh my, you're right -- guess it was a copy/paste error on my part.  Sorry to bother you.

**Comment by willinspire** [comment]
Experiencing the exact same problem. Applying the methods mentioned above to attempt a fix.
