### ISSUE TITLE
Cannot specify temp-dir in fstab

### ISSUE THREAD

**Issue by PhilBrammer** [GoogleCloudPlatform/gcsfuse#208]
It looks like it is not possible to submit a new --temp-dir path when mounting gcsfuse through fstab.  Looking at the source code, it would be great to add another section for trapping something like "temp_dir" as an option and changing it to be similar to the behavior in  https://github.com/GoogleCloudPlatform/gcsfuse/commit/e762043c7daa2b7f01f92852123fd9d8c04adeb3

**Comment by jacobsa** [comment]
Sure, please feel free to send a pull request.

**Comment by PhilBrammer** [comment]
Pull request https://github.com/GoogleCloudPlatform/gcsfuse/pull/209 accepted.
