### ISSUE TITLE
Question on --foreground mode

### ISSUE THREAD

**Issue by geno5150** [GoogleCloudPlatform/gcsfuse#211]
Our current network setup has Internet traffic funneled though a proxy server. As such, we have the proxy defined in environment variables in /etc/environment.  I am able to mount a bucket when running in foreground mode, but get i/o errors when not using the --foreground flag. 

Since there isn't a way (to my knowledge) to dump output without --foreground, my working assumption is that the daemonizing is excluding my environment variables. Is there a way to test this and validate one way or the other?

**Comment by jacobsa** [comment]
I think your theory is correct. The code that sets up the environment and daemonizes is [here](https://github.com/GoogleCloudPlatform/gcsfuse/blob/284558bd039f4859a5fd4b465639fe69725e34a0/main.go#L312-L328)—it preserves only `PATH` and `GOOGLE_APPLICATION_CREDENTIALS`.

The intent of the default daemonization behavior is just to be a convenient default. If you want fancier behaviors such as logging, monitoring, etc., you can use `gcsfuse --foreground` under your favorite daemonizing environment (e.g. daemontools or systemd). I hadn't considered the environment case before, but I think the same applies here.
