### ISSUE TITLE
Not showing folders inside buckets

### ISSUE THREAD

**Issue by afhuertass** [GoogleCloudPlatform/gcsfuse#212]
Hi

I'm wondering if is correct that after using the tool as: 

`gcsfuse` bucket-name /mnt/data`
`
i dont get to see the contents of my bucket ( there is a folder inside my bucket) . is weird because it doesn't give me any error and if i do something like 

echo "hello" > /mnt/data/text.txt 

it work and the object is created inside de bucket, but i need to read the contents of the bucket. 

Thanks for your attention and help

**Comment by jacobsa** [comment]
Please see the information on implicit directories [here](https://github.com/googlecloudplatform/gcsfuse#invoking-gcsfuse) and [here](https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/semantics.md#implicit-directories).
