### ISSUE TITLE
flush cache on demand?

### ISSUE THREAD

**Issue by peixotorms** [GoogleCloudPlatform/gcsfuse#213]
Hi,

I was wondering if is there's any way to flush gcsfuse cache on demand or can this be added as a feature request?

I would like to mount the cloud storage on a group of servers, and use it for keeping the www directory (for nginx/apache) in sync and have those servers cache all php files for 24 hours.

My idea would be to track script updates on the database or redis (when a user updates wordpress or something else) and then trigger a "cache invalidation" request to gcsfuse on all servers that are part of the autoscale group.

Getting the servers and running the command there is not the issue, I would just need to know which command needs to run on each server to flush gcsfuse cache and force it to refresh it's data from the cloud. Having it flush the cache on demand would greatly reduce requests to the cloud, speeding things up.

But I'm also to other ideas, thanks.

**Comment by jacobsa** [comment]
Which sort of cache are you talking about? Does flushing the cache mean to write contents to GCS, or to read contents from GCS?

By the way, I would not advise running a database on top of gcsfuse.

**Comment by peixotorms** [comment]
I'm talking about those referred here: https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/semantics.md#caching

My "original" idea was to not to run a database there but rather to use it as a file storage for the webserver, specifically for "wordpress" php files which would then be available via a mounting point on all servers from the autoscale group... 

This was before doing a little benchmark and the thing is, gcsfuse at roughly 15 iops... nginx and php is quite slow to open all files for the first time.

I was looking into the possibility of having a high value for stat-cache-ttl and type-cache-ttl and then whenever there's a write from one of the server (such as wordpress updates, which are not so frequent) have a way to flush that cache (probably the same as to umount and mount it again... but haven't tried this yet). That way I could run the command on all servers and force them to fetch the files from cloud storage again.

My ultimate goal would be to create something similar like Amazon's EFS... but looks like it's not going to work with gcsfuse due to performance. 

I am aware of glusterfs (but want to avoid dealing with file servers) or I might just use the gsutil to rsync from a master server to google cloud storage and then force another rsync from the other servers on startup or whenever there's a write operation, thus forgetting about gcsfuse.

It's a shame though, because gcsfuse would be a perfect centralized solution to keep the php files in sync if it performs a bit faster. If Google were to have an Amazon EFS alternative that would also be interesting, but guess we have to wait or stick with amazon for now.

**Comment by jacobsa** [comment]
Right, you definitely shouldn't rely on gcsfuse for something that requires a high serial rate of file system operations. (Parallel is probably fine.) It's fundamentally limited by the high latency of GCS operations.

I assume you've seen `--stat-cache-ttl` and `--type-cache-ttl`. I'm not sure I understand why you need on-demand clearing of the cache (and whether you're saying you still need it).

**Comment by peixotorms** [comment]
It's not needed anymore, it was just for testing. Thanks anyway.
