### ISSUE TITLE
gcsfuse command is not working as expected

### ISSUE THREAD

**Issue by pavantrue** [GoogleCloudPlatform/gcsfuse#214]
#1.
As part of our automation, we are mounting one of the folders from google storage to respective instance using gcsfuse command and it worked first time.
CMD: "sudo gcsfuse -o allow_other piman-pp-piman-dev /mnt/pp-share"

When we run same command again, it  says "already mounted" which is good & valid. But, when we do "df -h" we were not able to see mount point which was suppose to exist.

When we re-run gcsfuse command we are ending up with "transport endpoint is not connected". Later, If we do "fusermount -u /mnt/pp-share" then we can see mount is coming back don't know how.

#2. 
Also, there were scenarios where gcsfuse command fails intermittently for the first time with below error, Not sure what exactly this message means
+++++++++++++++++++++++++++++++
sudo gcsfuse -o allow_other piman-pp-piman-dev /mnt/pp-share
+ sudo gcsfuse -o allow_other piman-pp-piman-dev /mnt/pp-share
Using mount point: /mnt/pp-share
Opening GCS connection...
daemonize.Run: readFromProcess: sub-process: mountWithArgs: getConn: DefaultTokenSource: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
+++++++++++++++++++++++++++++++++++

Any help would be very helpful.

**Comment by jacobsa** [comment]
1. It sounds like gcsfuse is exiting. Run it with `--foreground` so that you can see what it's writing to stderr. If that doesn't help you figure out what's going on, using `--debug_fuse` may shed further light.

2. Please see [here](https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/mounting.md#credentials) for documentation on credentials.
