### ISSUE TITLE
feature request: support uid,gid in mount helper for fstab

### ISSUE THREAD

**Issue by morxa** [GoogleCloudPlatform/gcsfuse#219]
With the `gcsfuse` command line tool, I can specify the uid and gid for the owner of the local files. However, when specifying the mount in `/etc/fstab`, uid or gid is not supported. I have the following mount point in my fstab:

    <bucket-name> /mnt/gcs rw,allow_other,key_file=</path/to/key>,uid=<uid>

Mounting the bucket with `mount /mnt/gcs` fails with:

    stderr:
    fusermount: mount failed: Invalid argument
    running gcsfuse: exit status 1

It would be nice if uid and gid were also supported in `/etc/fstab`. My use case: I want to automatically mount my bucket during boot and the files should be owned by a specific user. I can work around this by mounting with a systemd unit (e.g., [this solution](https://gist.github.com/craigafinch/292f98618f8eadc33e9633e6e3b54c05)), but a line in `/etc/fstab` would imho be much cleaner.

**Comment by jacobsa** [comment]
Please feel free to send a pull request along the lines of #182.

**Comment by morxa** [comment]
Fixed in #221.

**Comment by morxa** [comment]
Are there any plans for a release soon? It would be nice to have this feature but I'm reluctant to distribute a pre-release to all our machines manually.

**Comment by jacobsa** [comment]
I've released gcsfuse 0.21.0 just now, containing this change.

**Comment by morxa** [comment]
Awesome, thanks!
