### ISSUE TITLE
lack of sequential consistency guarantees

### ISSUE THREAD

**Issue by romange** [GoogleCloudPlatform/gcsfuse#220]
Hi,

We started using gcsfuse when reading our index data that has multiple files. In order to read consistent results the index consumer polls on "done" file that is written last by index producer also via gcsfuse. Sometimes we see that the inconsistent data is read. Could it be that smaller files will appear earlier in gcs even if were written later? Can we somehow flush the files in gcs before writing the done file?

**Comment by jacobsa** [comment]
Please see [semantics.md](https://github.com/googlecloudplatform/gcsfuse/blob/master/docs/semantics.md) in the documentation for guarantees on consistency. In particular there is no guarantee of consistency across files (this would be impossible to support given the guarantees provided by GCS).
