### ISSUE TITLE
Copying between GCS's caused local tmp out of space

### ISSUE THREAD

**Issue by xmedeko** [GoogleCloudPlatform/gcsfuse#222]
I have copied a few GB file - `cp /mnt/gcs/file1 /mnt/gcs/file2` - and it has causes local tmp out of space. I understand that the `gcsfuse` has to cache the data, but may only a part of the file be cached or may this be documented in the `README.md`? Thanks.

**Comment by jacobsa** [comment]
This is documented in the readme file [here](https://github.com/googlecloudplatform/gcsfuse#downloading-object-contents).

> Note that new and modified files are also fully staged in the local temporary directory until they are written out to GCS due to being closed or fsync'd. Therefore the user must ensure that there is enough free space available to handle staged content when writing large files.

**Comment by xmedeko** [comment]
So, copying from bucket to bucket is same as _new and modified files_ . I was not clear for me. What about to add a sentence like: "Note, this applies to the bucket to bucket copying, too." ?
