### ISSUE TITLE
Error with chtimes and Grafana

### ISSUE THREAD

**Issue by sunshinekitty** [GoogleCloudPlatform/gcsfuse#223]
I'm trying to run Grafana on GKE with GCS as the persistent store at /var/lib/grafana.

However, in doing so Grafana craps out when trying to call [Chtimes](https://golang.org/pkg/os/#Chtimes) due to permissions.  Is it possible somehow to work around this?

Logs from Grafana:
```
t=2017-04-05T03:32:13+0000 lvl=eror msg="Failed to start session" logger=context error="chtimes /var/lib/grafana/sessions/f/a/fa3cb8095e20b2d3: input/output error"
t=2017-04-05T03:32:13+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login status=302 remote_addr=10.0.11.1 time_ms=876ns size=24
t=2017-04-05T03:32:14+0000 lvl=eror msg="Failed to start session" logger=context error="chtimes /var/lib/grafana/sessions/e/8/e89b880d4029dfec: input/output error"
t=2017-04-05T03:32:14+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=10.0.11.1 time_ms=459ns size=29
t=2017-04-05T03:32:14+0000 lvl=eror msg="Failed to start session" logger=context error="chtimes /var/lib/grafana/sessions/d/f/df1d398d10deee5b: input/output error"
t=2017-04-05T03:32:14+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login status=302 remote_addr=10.0.11.1 time_ms=383ns size=24
t=2017-04-05T03:32:15+0000 lvl=eror msg="Failed to start session" logger=context error="chtimes /var/lib/grafana/sessions/b/0/b01a6ccaff11393a: input/output error"
t=2017-04-05T03:32:15+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=10.0.11.1 time_ms=911ns size=29
```

**Comment by jacobsa** [comment]
Are you sure that the problem is permissions? Can you strace your application, or use `gcsfuse --foreground --debug_fuse`, to see what's going on in detail?

**Comment by sunshinekitty** [comment]
These are the relevant logs:

```

**Comment by jacobsa** [comment]
Yeah, that's a permissions error from GCS (not from the kernel or file system). Sounds like your credentials don't allow for [object update](https://cloud.google.com/storage/docs/json_api/v1/objects/update) calls.

**Comment by sunshinekitty** [comment]
I'll close this out, looks like my SA just had read/write and I figured that was enough! Thanks.

**Comment by jacobsa** [comment]
Thanks. For the record, which permission did you need in order to fix this?

**Comment by sunshinekitty** [comment]
The docs say you need `OWNER` permission, I've tried setting this up with bucket ACL's and directly on the SA to no avail.  I'll report back when I know more.

**Comment by sunshinekitty** [comment]
Ended up setting up a separate user with GCS admin access, since authenticating with the Service Account (with the same permissions) wouldn't work in Kubernetes.
