### ISSUE TITLE
Using gcsfuse on a node without an external ip address fails with no error message

### ISSUE THREAD

**Issue by marcosw1** [GoogleCloudPlatform/gcsfuse#228]
Attempting to mount a volume using gcsfuse on an instance that has been launched with no external address (--no-address) results with a "File system has been successfully mounted." message though that's not true.

Here is an example command line:

gcsfuse --foreground --debug_fuse --debug_gcs --debug_http test_data /mnt/gcs

And the output:

Using mount point: /mnt/gcs
Opening GCS connection...
Opening bucket...
gcs: Req              0x0: <- ListObjects()
http: ========== REQUEST:
GET http://www.googleapis.com/storage/v1/b/test_data/o?maxResults=1&projection=full HTTP/1.1
Host: www.googleapis.com
User-Agent: gcsfuse/0.0
Authorization: Bearer ya29.EmROBLjnR3.1415963LljUwxkY89AbsuiGv4e_MlSxnvnYWdfJwGe81D9kNyFFSMO4ml1e52nUmLAwdBv7HWpFjAnvpPTeGt33IzEyH4iqi_hK8niEPTjPyXfH-GvmRvQy6
Accept-Encoding: gzip

gcs: Req              0x0: -> ListObjects() (30.0012666s): Get https://www.googleapis.com/storage/v1/b/test_data/o?maxResults=1&projection=full: dial tcp 173.494.293.95:443: i/o timeout
Mounting file system...
fuse_debug: Op 0x00000001        connection.go:395] <- init
fuse_debug: Op 0x00000001        connection.go:474] -> OK ()
File system has been successfully mounted.

It would be nice if there was an error message instead, particularly if it included the reason for the failure.

**Comment by nafg** [comment]
It's very convenient to be allowed to mount a bucket even before the network becomes reachable. :-1:
