### ISSUE TITLE
Mounted Goolge storage but 755 is on all folders and files

### ISSUE THREAD

**Issue by bertalanimre** [GoogleCloudPlatform/gcsfuse#235]
Hey Forum,

I've mounted my google cloud storage into my CentOS 7 server without any problem as user "bi". Now I want to link this folder to something like /var/www/html/mywebsite/public/uploads So if somebody uploads on my website a picture, and in my PHP I'm putting everything to like /var/www/html/mywebsite/public/uploads/images I want them to be transfered straight to the cloud. However, I've set my server up for security reasong that nginx user has rights to use these files only in /var/www/html/mywebsite Now, I can still link the mounted folder into my uploads folder, but nginx doesn't have write permmissions to write in it. I've added nginx to the group "bi" but the folders have 755 permissions and I can't change them. How can I mount the folder with nginx or allow nginx to write in it??

Thanks in advance!

Bert

**Comment by bertalanimre** [comment]
Nevermind, I've got it. Sorry for duplicated post. 

```
gcsfuse --help
NAME:
   gcsfuse - Mount a GCS bucket locally

USAGE:
   gcsfuse [global options] bucket mountpoint
   
VERSION:
   0.21.0 (Go version go1.8)
   
GLOBAL OPTIONS:
   --foreground                 Stay in the foreground after mounting.
   -o value                     Additional system-specific mount options. Be careful!
   --dir-mode value             Permissions bits for directories, in octal. (default: 755)
   --file-mode value            Permission bits for files, in octal. (default: 644)
   --uid value                  UID owner of all inodes. (default: -1)
   --gid value                  GID owner of all inodes. (default: -1)
   --implicit-dirs              Implicitly define directories based on content. Seedocs/semantics.md
   --only-dir value             Mount only the given directory, relative to the bucket root.
   --key-file value             Absolute path to JSON key file for use with GCS. (default: none, Google application default credentials used)
   --limit-bytes-per-sec value  Bandwidth limit for reading data, measured over a 30-second window. (use -1 for no limit) (default: -1)
   --limit-ops-per-sec value    Operations per second limit, measured over a 30-second window (use -1 for no limit) (default: 5)
   --stat-cache-ttl value       How long to cache StatObject results and inode attributes. (default: 1m0s)
   --type-cache-ttl value       How long to cache name -> file/dir mappings in directory inodes. (default: 1m0s)
   --temp-dir value             Absolute path to temporary directory for local GCS object copies. (default: system default, likely /tmp)
   --debug_fuse                 Enable fuse-related debugging output.
   --debug_gcs                  Print GCS request and timing information.
   --debug_http                 Dump HTTP requests and responses to/from GCS.
   --debug_invariants           Panic when internal invariants are violated.
   --help, -h                   show help
   --version, -v                print the version
```

**Comment by bertalanimre** [comment]
I wish to take it back. The issue still exists. 

I can see the folder with proper permissions when I'm logged in with my own user who I've mounted the folder with. HOWEVER! When I login as another user, I can't see the permissions, not the owner, or any data about the folder. When I try to enger, it sais Permission denied. The folder looks like this:

```
-rw-r--r--   1 nginx nginx  563 Jun 13 15:16 server.php
d?????????   ? ?     ?        ?            ? storage
drwxr-xr-x   5 nginx nginx 4.0K Jun 13 15:16 tests
```

I think this is the reason why I get Internal Server error 500. NginX still can't enter the folder.

**Comment by mcmire** [comment]
@bertalanimre I ran into this issue as well. It looks like you may need to mount the disk with the `allow_other` option, as specified here: https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/mounting.md#access-permissions

**Comment by jacobsa** [comment]
@mcmire has the right answer—fuse disables use by other users by default. There are security implications to overriding this. Please be careful.

**Comment by bertalanimre** [comment]
Cheers Mates!
