### ISSUE TITLE
fusermount: failed to open /dev/fuse: Operation not permitted

### ISSUE THREAD

**Issue by brianfarrar** [GoogleCloudPlatform/gcsfuse#236]
I'm trying to use gcsfuse with Google Cloud Datalab.   The command entered is:

`!gcsfuse --foreground --debug_fuse kaggle-datasets-jbf tsa_datasets`

Here is the result:

> Using mount point: /content/datalab/notebooks/tsa_datasets Opening GCS connection...
> 
> WARNING: gcsfuse invoked as root. This will cause all files to be owned by
> root. If this is not what you intended, invoke gcsfuse as the user that will
> be interacting with the file system.
> 
> Opening bucket...
> Mounting file system...
> mountWithArgs: mountWithConn: Mount: mount: running fusermount: exit status 1
> 
> stderr:
> fusermount: failed to open /dev/fuse: Operation not permitted

Datalab runs as root so that was expected.  I have chmod'ed /dev/fuse to 777 to eliminate that as a question.  I have also changed the group for /dev/fuse to fuse and added root to the group (although it seemed like that should not have mattered.)

Is it possible that gcsfuse just doesn't work inside datalab?

**Comment by jacobsa** [comment]
It's possible, but I don't know one way or the other. I don't see any reason that would be. Are you in a position to use `strace` to figure out in more detail what is failing? Also, are you sure the mount point has appropriate permissions for root to use it?

**Comment by jacobsa** [comment]
(And that there's nothing already mounted there)

**Comment by brianfarrar** [comment]
Hi.  Thanks for your suggestions.  The mount point is owned by root.   Here is a dump from the last page of strace.  Not clear to me what is wrong...

> write(6, "\206\303\1\0\0\1\0\0\0\0\0\0\3www\ngoogleapis\3com\0"..., 36) = 36
read(6, 0xc4200de000, 512)              = -1 EAGAIN (Resource temporarily unavailable)
futex(0xc00590, FUTEX_WAIT, 0, NULL)    = 0
futex(0xc00590, FUTEX_WAIT, 0, NULL)    = 0
epoll_wait(5, {}, 128, 0)               = 0
epoll_wait(5, {{EPOLLOUT, {u32=14945840, u64=140600064347696}}}, 128, -1) = 1
epoll_wait(5, {{EPOLLOUT, {u32=14945840, u64=140600064347696}}}, 128, -1) = 1
epoll_wait(5, {{EPOLLOUT, {u32=14945840, u64=140600064347696}}}, 128, -1) = 1
futex(0xbffbb8, FUTEX_WAKE, 1)          = 1
getsockopt(4, SOL_SOCKET, SO_ERROR, [0], [4]) = 0
futex(0xc4200f0510, FUTEX_WAKE, 1)      = 1
getsockname(4, {sa_family=AF_INET, sin_port=htons(34000), sin_addr=inet_addr("172.17.0.2")}, [16]) = 0
getpeername(4, {sa_family=AF_INET, sin_port=htons(443), sin_addr=inet_addr("209.85.234.95")}, [16]) = 0
setsockopt(4, SOL_TCP, TCP_NODELAY, [1], 4) = 0
futex(0xc42002cd10, FUTEX_WAKE, 1)      = 1
setsockopt(4, SOL_SOCKET, SO_KEEPALIVE, [1], 4) = 0
setsockopt(4, SOL_TCP, TCP_KEEPINTVL, [30], 4) = 0
setsockopt(4, SOL_TCP, TCP_KEEPIDLE, [30], 4) = 0
futex(0xbff598, FUTEX_WAKE, 1)          = 1
futex(0xbff580, FUTEX_WAKE, 1)          = 1
futex(0xc42002cd10, FUTEX_WAKE, 1)      = 1
syscall_318(0xc4202d23c0, 0x20, 0, 0, 0, 0) = 0x20
write(4, "\26\3\1\0\266\1\0\0\262\3\3\3464\21_N\267\2471H\tU\301V1\370\210\374i\310iJ"..., 187) = 187
read(4, 0xc420357000, 1024)             = -1 EAGAIN (Resource temporarily unavailable)
futex(0xc00590, FUTEX_WAIT, 0, NULL)    = 0
epoll_wait(5, {}, 128, 0)               = 0
select(0, NULL, NULL, NULL, {0, 3})     = 0 (Timeout)
futex(0xc00590, FUTEX_WAIT, 0, NULLMounting file system...
)    = 0
epoll_wait(5, {}, 128, 0)               = 0
futex(0xc42002cd10, FUTEX_WAKE, 1)      = 1
epoll_wait(5, {}, 128, 0)               = 0
select(0, NULL, NULL, NULL, {0, 3})     = 0 (Timeout)
futex(0xc00590, FUTEX_WAIT, 0, NULL)    = 0
select(0, NULL, NULL, NULL, {0, 3})     = 0 (Timeout)
futex(0xc4200f0d10, FUTEX_WAKE, 1)      = 1
read(10, "fusermount: failed to open /dev/"..., 512) = 62
read(10, "", 1474)                      = 0
close(10)                               = 0
futex(0xc4200f0510, FUTEX_WAKE, 1)      = 1
close(7)                                = 0
close(6)                                = 0
write(2, "mountWithArgs: mountWithConn: Mo"..., 150mountWithArgs: mountWithConn: Mount: mount: running fusermount: exit status 1

stderr:
fusermount: failed to open /dev/fuse: Operation not permitted

) = 150
exit_group(1)                           = ?
+++ exited with 1 +++

**Comment by jacobsa** [comment]
Sorry, to be clear you'll want to use `strace -f` so you also get the subprocess in there. I would guess you're looking for something returning `EPERM`.

**Comment by brianfarrar** [comment]
Thanks again for your responses.  I appreciate your help 

OK.  Probably should have guessed that the -f switch would make life easier.  

Command:
`!strace -f gcsfuse --foreground --debug_fuse kaggle-datasets-jbf newtsa`

Snippet from stderr:

> [pid  6101] lstat("/content", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
[pid  6101] lstat("/content/datalab", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
[pid  6101] lstat("/content/datalab/notebooks",  <unfinished ...>
[pid  6091] <... select resumed> )      = 0 (Timeout)
[pid  6101] <... lstat resumed> {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
[pid  6091] select(0, NULL, NULL, NULL, {0, 1280} <unfinished ...>
[pid  6101] chdir("/")                  = 0
[pid  6101] getuid()                    = 0
[pid  6101] umask(033)                  = 022
[pid  6101] getuid()                    = 0
[pid  6101] open("/dev/fuse", O_RDWR)   = -1 EPERM (Operation not permitted)
[pid  6101] write(2, "fusermount: failed to open /dev/"..., 62) = 62
[pid  6096] <... read resumed> "fusermount: failed to open /dev/"..., 512) = 62
[pid  6101] getuid()                    = 0
[pid  6096] read(10,  <unfinished ...>
[pid  6101] open("/proc/fs/fuse/dev", O_RDWR <unfinished ...>
[pid  6091] <... select resumed> )      = 0 (Timeout)
[pid  6101] <... open resumed> )        = -1 ENOENT (No such file or directory)
[pid  6091] select(0, NULL, NULL, NULL, {0, 20} <unfinished ...>
[pid  6101] exit_group(1)               = ?
[pid  6091] <... select resumed> )      = 0 (Timeout)
[pid  6091] select(0, NULL, NULL, NULL, {0, 20} <unfinished ...>
[pid  6101] +++ exited with 1 +++
[pid  6090] <... epoll_wait resumed> 7fff6bde2328, 128, -1) = -1 EINTR (Interrupted system call)
[pid  6090] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=6101, si_uid=0, si_status=1, si_utime=0, si_stime=0} ---
[pid  6090] rt_sigreturn()              = -1 EINTR (Interrupted system call)
[pid  6090] epoll_wait(4,  <unfinished ...>
[pid  6096] <... read resumed> "", 1474) = 0
[pid  6095] <... waitid resumed> {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=6101, si_uid=0, si_status=1, si_utime=0, si_stime=0}, WEXITED|WNOWAIT, NULL) = 0
[pid  6096] close(10 <unfinished ...>
[pid  6091] <... select resumed> )      = 0 (Timeout)
[pid  6095] wait4(6101,  <unfinished ...>
[pid  6096] <... close resumed> )       = 0
[pid  6091] select(0, NULL, NULL, NULL, {0, 20} <unfinished ...>
[pid  6095] <... wait4 resumed> [{WIFEXITED(s) && WEXITSTATUS(s) == 1}], 0, {ru_utime={0, 0}, ru_stime={0, 2000}, ...}) = 6101
[pid  6096] futex(0xc42011c510, FUTEX_WAIT, 0, NULL <unfinished ...>
[pid  6095] close(7 <unfinished ...>
[pid  6091] <... select resumed> )      = 0 (Timeout)
[pid  6095] <... close resumed> )       = 0
[pid  6091] select(0, NULL, NULL, NULL, {0, 20} <unfinished ...>
[pid  6095] close(6)                    = 0
[pid  6091] <... select resumed> )      = 0 (Timeout)
[pid  6091] select(0, NULL, NULL, NULL, {0, 20} <unfinished ...>
[pid  6095] write(2, "mountWithArgs: mountWithConn: Mo"..., 150mountWithArgs: mountWithConn: Mount: mount: running fusermount: exit status 1
stderr:
fusermount: failed to open /dev/fuse: Operation not permitted
) = 150
[pid  6095] exit_group(1)               = ?
[pid  6091] <... select resumed> )      = 0 (Timeout)
[pid  6096] +++ exited with 1 +++

Definitely getting the EPERM you predicted about 25% of the way down.  

> [pid  6101] open("/dev/fuse", O_RDWR)   = -1 EPERM (Operation not permitted)

It happens on /dev/fuse, so I feel like we are getting somewhere.  Here is `ls -al /dev/fuse`

> crw-rw-rw- 1 root fuse 10, 229 Jul  6 19:36 /dev/fuse

Its worth noting that I had to create the "fuse" group (it didn't exist) and since Google Datalab runs as root, I then added root to the group (which seems nonsensical, but I tried it both ways and the result is the same).  

Any other thoughts?

**Comment by jacobsa** [comment]
Sorry for the slow response. With that info it seems clear that this isn't a gcsfuse issue, but is rather something that's happening in the kernel itself when handling the `open` call, likely in the fuse code. I would consider asking the fuse mailing list.

**Comment by jacobsa** [comment]
Oh, and #51 may be relevant. Have you tried mounting with `allow_other`? Note that there are security implications. See the [documentation](https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/mounting.md#access-permissions).

**Comment by jacobsa** [comment]
Closed due to lack of activity.

**Comment by djvongola** [comment]
we have the same problem using gsfuse with debian stretch inside a docker container.
installing fuse + gcsfuse it create a fuse device with root:root permission

` ls -lart /dev/fuse
crw-rw---- 1 root root 10, 229 Jan 31 14:52 /dev/fuse`

as suggested in the gcsfuse readme we should use the command with an user different to root but belonging to the fuse group. 
we solve creating a fuse group ( which neither the fuse or the gcsfuse package are creating ) add our user to the fuse group and then changing the group to fuse in the /dev/fuse device.
