### ISSUE TITLE
gcsfuse missing for Ubuntu 16.04 Xenial?

### ISSUE THREAD

**Issue by jfx41** [GoogleCloudPlatform/gcsfuse#237]
I'm trying to install gcsfuse on Ubuntu 16.04 Xenial, but even after adding the repo and apt-get update it still doesn't find the package.  I've barely slept this week, but I'm pretty sure I'm not doing this wrong.

I even tried to install the .deb package, but it's for amd and I'm on i386.

This is what I did (about 20 times):

```
:~$ export GCSFUSE_REPO=gcsfuse-`lsb_release -c -s`
:~$ echo $GCSFUSE_REPO
gcsfuse-xenial
:~$ echo "deb http://packages.cloud.google.com/apt $GCSFUSE_REPO main" | sudo tee /etc/apt/sources.list.d/gcsfuse.list
deb http://packages.cloud.google.com/apt gcsfuse-xenial main
:~$ curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   663  100   663    0     0   2848      0 --:--:-- --:--:-- --:--:--  2857
OK
:~$ sudo apt-get update
Hit:1 http://us.archive.ubuntu.com/ubuntu xenial InRelease
Get:2 http://us.archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]
Get:3 http://us.archive.ubuntu.com/ubuntu xenial-backports InRelease [102 kB]
Get:4 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
Hit:5 http://ppa.launchpad.net/alessandro-strada/ppa/ubuntu xenial InRelease
Hit:6 http://ppa.launchpad.net/git-core/ppa/ubuntu xenial InRelease
Hit:7 http://packages.cloud.google.com/apt gcsfuse-xenial InRelease
Hit:8 http://ppa.launchpad.net/ondrej/php/ubuntu xenial InRelease
Hit:9 http://packages.cloud.google.com/apt cloud-sdk-xenial InRelease
Fetched 306 kB in 0s (384 kB/s)
Reading package lists... Done
:~$ sudo apt-get install gcsfuse
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package gcsfuse
```

Any idea what I'm missing?

Thank you very much for your help!

**Comment by jacobsa** [comment]
Hi, sorry for the slow response. There was a complaint about this in #202, which it seems turned out to be user error. And I verified that it worked for me on GCE.

But I see you are being careful. It seems likely the issue is that you're on i386, for which I don't prepare prebuilt packages. You can probably compile gcsfuse yourself, but I make no guarantees.

**Comment by jfx41** [comment]
@jacobsa Ok, thank you.  I might just see about spinning up a x64 version of the server.  That would probably be a better idea than trying to duplicate this mess on all of the load balance nodes that will be getting spun up.

Thank you.

**Comment by jfx41** [comment]
I got it up and running on a x64 system no problem.  I know I read that multiple file transfers is slower, but I'm getting 1.3KiB using gsutil rsync.  Is that normal?

**Comment by jacobsa** [comment]
Glad to hear it's working now. Sorry, I'll need more detail on the performance issue you're seeing; could you please post a separate issue?
