### ISSUE TITLE
Edit file: Permission denied

### ISSUE THREAD

**Issue by Segflow** [GoogleCloudPlatform/gcsfuse#240]
Hello, 

I don't know if this is an intended behavior or not, i'am using google container engine, my cluster have read_write scope to google storage.

I can mount(and un-mount) my buckets, create files and deletes files, but when i try to edit an existing file i get a permission denied error

```bash
cd MY_BUCKET
touch TEST_FILE # works ok and the file get created in the bucket
rm TEST_FILE # works ok and the file get deleted from the bucket
echo CONTENT1 > TEST_FILE # also works ok
echo CONTENT2 > TEST_FILE # IO Error
```

The error message is the following: 
`fuse: 2017/07/21 09:02:37.346006 *fuseops.SetInodeAttributesOp error: SetMtime: UpdateObject: googleapi: Error 403: Insufficient Permission, insufficientPermissions`

I can't give the cluster `full_control` to the storage due to a security policy.

**Comment by jacobsa** [comment]
Inode attributes (in this case modification time) are stored in object metadata, which according to the documentation [here](https://cloud.google.com/storage/docs/access-control/lists) requires `OWNER` access to read and write. So yes, it seems this is working as intended. Consider using the "full" scope.
