### ISSUE TITLE
GCSFuse version 2.4.0 has a lower Go version that 2.3.X

### ISSUE THREAD

**Issue by donegjookim** [GoogleCloudPlatform/gcsfuse#2403]
**Describe the issue**
GCSFuse version 2.4.0 has a lower Go version that 2.3.X.

Here is what was announced in 2.3.0 release:
![image](https://github.com/user-attachments/assets/4b424119-f536-4baa-817a-c8461387cba5)

go.mod file for v2.3.0:
```
module github.com/googlecloudplatform/gcsfuse/v2

go 1.22
```

go.mod file for v2.4.0:
```
module github.com/googlecloudplatform/gcsfuse/v2

go 1.22.0
```

This is an issue as go version 1.22.4 includes critical vulnerability patches

**Comment by kislaykishore** [comment]
The Go version simply says that the source-code is compatible with Golang v1.22.0 onwards. However, the binary was built with Golang toolchain version 1.22.4 and has fixes for those CVEs. You can see this for yourself if you extract the package and run 
`go version -v <path_to_binary>`.
You should get an output similar to the following:
```
% go version -v gcsfuse_2.4.0_amd64/sbin/mount.gcsfuse 
gcsfuse_2.4.0_amd64/sbin/mount.gcsfuse: go1.22.4
```
