### ISSUE TITLE
gcsfuse does not mount on boot in google app engine as fstab , but mount -a does work

### ISSUE THREAD

**Issue by gusev-genotek** [GoogleCloudPlatform/gcsfuse#241]
I am using gcsfuse in my flexible google app engine application (debian jessie)

I put the following into fstab during the docker build (dockers are a way to deploy in flexible GAE):

```
my-bucket /my-mount-point gcsfuse rw,allow_other
```

and expect the gcsfuse to mount /my-mount-point on container start as the google cloud storage my-bucket
Does not happen.

However, if I ssh into a GAE instance and refresh the mount points via

```
mount -a
```

everything works

```
root@d54083fbe05c:/# mount -a
Calling gcsfuse with arguments: -o rw -o allow_other my-bucket /my-mount-point
Using mount point: /my-mount-point
Opening GCS connection...
Opening bucket...
Mounting file system...
File system has been successfully mounted.
```

**Comment by jacobsa** [comment]
Sorry, I have no clue. This doesn't sound like it's gcsfuse-specific, so you may have better luck seeking AppEngine support or asking on ServerFault. Please report back if you figure it out.

**Comment by nafg** [comment]
This might be the same as #244

**Comment by eighteight** [comment]
@nafg I have upgrade to latest gcsfuse which contains the fix for #244 however, it did not fix this #241 problem. Morever, I put the gcsfuse command in a shell infinite loop on startup, hoping that gcsfuse will mount eventually once the network is available -- sadly that does not change the behaviour.

**Comment by andeplane** [comment]
@eighteight did you ever solve this? I have the same problem and I can't mount on boot :(

**Comment by eighteight** [comment]
@andeplane I created a workaround. GAE recently allows to restart a gaeapp docker image with --privileged flag, so I have a cron job outside of GAE which restarts the gaeapp docker image if it was not started as --privileged.
