### ISSUE TITLE
Allow separating log streams

### ISSUE THREAD

**Issue by alicengiz** [GoogleCloudPlatform/gcsfuse#242]
gcsfuse version: gcsfuse-0.21.0-1.x86_64
kernel version: 3.10.0-514.26.2.el7.x86_64
os version: CentOS Linux release 7.3.1611

We are using gcsfuse to connect google storage with script. On successfully connection it produces log like below:
<pre>
Using mount point: /path/to/mount
Opening GCS connection...
Opening bucket...
Mounting file system...
File system has been successfully mounted.
</pre>
We've tried to remove that log with stardart output pipe to null but we couldn't accomplish. If we pipe standart error to null, we can.
Could you change logs like that into standart error to standart output?

**Comment by jacobsa** [comment]
It seems to me that standard error is the appropriate place for human debugging logs to go, so I think this is working as intended. If you want these to not appear, redirect stderr to `/dev/null`.

**Comment by alicengiz** [comment]
If there is any error (could not mount for example) and we redirect stderr to null, how will we see the logs?

**Comment by jacobsa** [comment]
Agreed, so it seems you do want to see the logging output. So I'm not sure what you're asking for here exactly.

**Comment by alicengiz** [comment]
And also these logs do not seems like debug logs, look like info logs.

**Comment by alicengiz** [comment]
We use gcfuse on cronjob script, and these info logs come when job every run success. We don't want to take these. We want to use it with stdout redirect, and using like this will send logs only if there is any error.

**Comment by jacobsa** [comment]
Thanks, I see.

I don't think this output is appropriate for stdout; it's not something that's intended to e.g. be piped to another command. But I do see it's more "infoy" than "debuggy".

I'm not sure if there's a convention for how to separate logging streams like this for an arbitrary tool that's not coupled to a particular logging/monitoring framework. Would it work for you to e.g. pass separate file descriptors as environment variables saying where to send info versus error logs? Something like

    GCSFUSE_INFO_LOG_FD=1 GCSFUSE_ERROR_LOG_FD=2 gcsfuse [bucket] [mount_point]

**Comment by alicengiz** [comment]
Yes, that will be more functional.

**Comment by dfisek** [comment]
Well, actually there's such a standard. stderr is for *errors* (as the name suggests). An informational output isn't an error. All log outputs aren't errors. Only errors are errors :).

**Comment by jacobsa** [comment]
In my experience, it's not uncommon at all for everything human-directed to be written to stderr, including non-error diagnostic messages. The idea is that you may have piped stdout to another tool, but stderr contains the things the human should still see (including errors, hence its name). [Wikipedia](http://go/wiki/Standard_streams#Standard_error_.28stderr.29) agrees that this includes non-error things.

**Comment by dfisek** [comment]
As the Wikipedia article states, the whole point of stderr is allowing output and errors to be distinguished.

For automated tasks, it's a common practice among system administrators to log (to be used only for debugging purposes) or even totally discard stdout, while having the output of stderr to be mailed to the system administrator (assuming an error occured).

For example, it's very easy to setup Cron to work like that. The only thing you have to do is to assign a MAILTO variable and direct stdout to /dev/null.

When stderr is used for all log output, the best you can do is to first look at the software's exit code, if it returned an error, then mail all the output. However minor errors (which doesn't cause the software to exit abruptly) won't be caught. Of course we assume the software exit code is set correctly.

Anyhow, traditionally it is more common to use stderr for its intended purpose -- which is outputing error.

**Comment by jacobsa** [comment]
Again, "output" often doesn't include messages like this. For any tool that might be part of a pipeline, it would be the opposite of helpful to include these messages in stdout, so stderr would be a better choice.

But I admit this argument doesn't hold much water for gcsfuse, which doesn't have any sort of output that might be part of a pipeline otherwise. So I'll refactor the code to use two logging streams, with this one going to stdout for now. It can be fancier later if necessary for some reason.
