### ISSUE TITLE
Retry idempotent GCS operations

### ISSUE THREAD

**Issue by romange** [GoogleCloudPlatform/gcsfuse#243]
When reading lots of data from gcsfuse we get sporadic io errors. The source files in the GCS do exist and are not changed/mutated in any way. 

gcsfuse log gave us this ( for example):

gcs: Req           0x2b0c: -> StatObject("data/ym=2017-06/dd=05/foo.lst") (24.216647562s): googleapi: got HTTP response code 503 with body:
fuse_debug: Op 0x0008a246        connection.go:481] -> Error: "LookUpChild: statObjectMayNotExist: StatObject: googleapi: got HTTP response code 503 with body: "
fuse: 2017/08/29 07:27:40.790608 *fuseops.LookUpInodeOp error: LookUpChild: statObjectMayNotExist: StatObject: googleapi: got HTTP response code 503 with body:

Is there any retry mechanism in gcsfuse that could overcome those sporadic failures?

**Comment by jacobsa** [comment]
This looks like a transient error from GCS, which of course happens now and then. I'm undecided whether it makes sense to retry these in gcsfuse. The fundamental question is: why is gcsfuse the right place? Why not e.g. in the application using gcsfuse, when it receives `EIO`?

**Comment by jacobsa** [comment]
(And of course in the general case some errors aren't retryable, and some operations aren't idempotent. In this particular case it would be fine though.)

**Comment by romange** [comment]
I think nowdays it's assumed that if file operations fail there is no reason to retry them, i.e. disk layer is usually considered either reliable and good or broken.  Changing all the points where the application uses I/O api and retry them seems to me counter-productive. If gcs-fuse layer is know as the one that fails sometimes I think it makes sense to make it as reliable as (network) disk by retrying upon 50X codes.

**Comment by jie-nuro** [comment]
I can see 503 errors while creating a directory/file in gcsfuse mounted disk:
`fuse_debug: Op 0x00099230        connection.go:481] -> Error: "CreateChildDir: googleapi: got HTTP response code 503 with body: Service Unavailable"`
As @romange suggested, gcs-fuse should do retries on server errors.
Are there any workarounds?
