### ISSUE TITLE
gcsfuse fails to mount when network not yet available

### ISSUE THREAD

**Issue by nafg** [GoogleCloudPlatform/gcsfuse#244]
It seems like in GCE the network is not fully up when `/etc/fstab` is applied. I believe this used to be okay because gcsfuse was "lazy," meaning it only made network calls at operation time, not at mounting time. However, since acf20a12cb88d2f93396c307323c54dfef38f480 (the fix for #228, released in 0.22.0) this is not the case, and if the network is not reachable at mounting time, mounting will fail.

This has caused a few of my servers to fail to start and is a serious issue.

The underlying issue is that acf20a12cb88d2f93396c307323c54dfef38f480 is a seriously breaking and unnecessary change. #228 could have been and should be solved with a simple warning and no behavior change.

Thanks for understanding.

**Comment by jacobsa** [comment]
I think it would be reasonable to downgrade this to just logging a warning, yeah. I'll try to get to it soon, but am a bit swamped.

**Comment by nafg** [comment]
Ok thanks. Meanwhile I'm telling apt to hold the package on 0.21.0.

**Comment by jacobsa** [comment]
I've released 0.23.0, containing the above fix.

**Comment by nafg** [comment]
Thanks!
