### ISSUE TITLE
How to add gcsfuse to Fstab

### ISSUE THREAD

**Issue by d0v1k** [GoogleCloudPlatform/gcsfuse#246]
How can i add the command below to /etc/fstab

sudo gcsfuse --file-mode "770" --dir-mode "770" -o allow_other -o nonempty --uid=998 --gid=996 cloud /home/data

**Comment by AlexFinn** [comment]
`cloud /home/data gcsfuse rw,allow_other,uid=998,gid=996,file_mode=0770,dir_mode=0770,noauto`

You also can read documentation: https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/mounting.md

**Comment by d0v1k** [comment]
Thank you
