### ISSUE TITLE
gcsfuse mount expires

### ISSUE THREAD

**Issue by strin** [GoogleCloudPlatform/gcsfuse#247]
Hi I've been using `gcsfuse` in production setting. I found that the mounted volume will disappear after a period of time. Is it because there is an expiration time set for the mount?

**Comment by AlexFinn** [comment]
Hi, how did you mount the volume?

**Comment by strin** [comment]
The command I am using is 

```
sudo GOOGLE_APPLICATION_CREDENTIALS=/tmp/gclou  d.json gcsfuse --implicit-dirs dummy-dev /mnt/cloudfs
```

**Comment by jacobsa** [comment]
I'm unfamiliar with any reason this would happen. Please gather more evidence (run gcsfuse with the `--foreground` flag, gather logs, etc) if you still think this is a gcsfuse issue.
