### ISSUE TITLE
Accessing Third Party Bucket

### ISSUE THREAD

**Issue by jonathonl** [GoogleCloudPlatform/gcsfuse#251]
I'm trying to access a third party bucket with gcsfuse. My email account has been given access to the bucket. I see that one can have --key-file specify a json file downloaded when creating a service account. Is there a way to authenticate gcsfuse as a normal user instead of a service-account?

**Comment by jacobsa** [comment]
gcsfuse will use whatever the JSON key file or Google application default credentials give it. I think your question is more about GCS: can you get a JSON key file or application default credentials for a person. I would imagine not, but I'm not sure. You probably want to create a service account for the project in question, but I'm no expert on GCP credentials.
