### ISSUE TITLE
Not available on Ubuntu 17.10

### ISSUE THREAD

**Issue by maksymov** [GoogleCloudPlatform/gcsfuse#255]
`«http://packages.cloud.google.com/apt gcsfuse-artful Release»` - no Release file :(

**Comment by jacobsa** [comment]
Working on this in Google-internal bug 70479457.

**Comment by jacobsa** [comment]
This should work now. Please try again and let me know.

**Comment by maksymov** [comment]
!!! It works perfect! Thank you!
