### ISSUE TITLE
Fuse sidecar gets killed and health probe doesn't restart it

### ISSUE THREAD

**Issue by aecc** [GoogleCloudPlatform/gcsfuse#2551]
**Side container just dies and the health6/liveness probe doesn't restart it**

The following logs happen and out of the sudden it dies. I expect the container to fail in the liveness probe and restart but nothing happens and there is no way for me to know if there was an issue or not to take action automatically. The only way I detect this is that the main container produces an exception because it cannot access the volume.

Logs:

"Garbage collection succeeded after deleted 0 objects in 36.496406ms."
E0928 09:11:14.903703       1 logger.go:60] gcsfuse exited with error: signal: killed

**System & Version (please complete the following information):**
 - Version GKE: 1.29.8-gke.1096000	
 - Version sidecar: gke.gcr.io/gcs-fuse-csi-driver-sidecar-mounter:v1.4.3-gke.2@sha256:ba5a1cdc67a7d08968b04034ff981f4e76dbcc1b73015e315487c7487fd9f93c

The main question is not why it did (which is also an uncertainty) but how can we recover from this? the liveness probe (if any) should detect this and restart the container

**Comment by ashmeenkaur** [comment]
Hey @aecc, I think this issue is better suited for https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver. I've created a [duplicate issue](https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/issues/355) in CSI driver repository. Please follow up on the new issue there.

Thanks,
Ashmeen
