### ISSUE TITLE
Files not listing when uploaded through signed url

### ISSUE THREAD

**Issue by FreakTheMighty** [GoogleCloudPlatform/gcsfuse#256]
I'm mounting a bucket like so `gcsfuse some-bucket /bucket/upload`, nothing special. If I create a directory or upload a file through the console the content shows up when I `ls /bucket/upload`. However, when I generate a signed url and upload content through a PUT it only shows up if I upload to the root of the bucket. If the object name contains slashes then nothing shows up when I list the contents of directories.

**Comment by jacobsa** [comment]
This is probably because you haven't created an object for the directory name. See [here](https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/semantics.md#implicit-directories).

**Comment by FreakTheMighty** [comment]
Thanks @jacobsa. Apologies for clearly not RTFM.

**Comment by jacobsa** [comment]
No worries, it's a very involved M.
