### ISSUE TITLE
Fail when oath fails; require a flag to override this behavior

### ISSUE THREAD

**Issue by scolson** [GoogleCloudPlatform/gcsfuse#257]
I have two containers in a kube pod, both with the SYS_ADMIN capability. In one container, gcsfuse mounts great and files are visibile. In the other, gcsfuse thinks it succeeds, but returns IO errors any time a write is attempted.

Cranking up the debugging:
```
# gcsfuse --foreground --debug_gcs --debug_http --debug_fuse --debug_invariants -o nonempty --implicit-dirs --key-file=/etc/iam/iam.json {{bucket}} /www/sites/default/files/
Using mount point: /www/sites/default/files
Opening GCS connection...

WARNING: gcsfuse invoked as root. This will cause all files to be owned by
root. If this is not what you intended, invoke gcsfuse as the user that will
be interacting with the file system.

Opening bucket...
gcs: Req              0x0: <- ListObjects()
gcs: Req              0x0: -> ListObjects() (20.437492ms): Get https://www.googleapis.com/storage/v1/b/{{bucket}}/o?maxResults=1&projection=full: oauth2: cannot fetch token: Post https://accounts.google.com/o/oauth2/token: x509: failed to load system roots and no roots provided
Mounting file system...
fuse_debug: Op 0x00000001        connection.go:395] <- init
fuse_debug: Op 0x00000001        connection.go:474] -> OK ()
File system has been successfully mounted.
```

The container that works is minimal and based on alpine:3.7.

The container that does not work is very minimal and based on nginx:alpine (which looks like it is on 3.5).

So this bug report covers one thing:
**When oauth fails, the mount should also fail**

(To help with someone else's googling for this error, the root cause is likely out of date or missing ssl certs in your image, so pass your hosts ssl certs in as a volume)

**Comment by jacobsa** [comment]
Are you not seeing a [warning](https://github.com/GoogleCloudPlatform/gcsfuse/blob/0f485dbc1e4ed5da8ba54db6b37564dbefb416ef/bucket.go#L137-L144) on stdout? This was changed on purpose in 0f485dbc1e4ed5da8ba54db6b37564dbefb416ef, because in #244 another user complained about the behavior you request (which used to be what happened).

**Comment by scolson** [comment]
Interesting!

No, I get no errors whatsoever. In fact, all of the messages that are output indicate the mount worked properly. I only see the oauth errors when I turn on all the various debug flags. You can see the output in the issue submission, but at no point do I see the warning in that commit.

Is it possible that as networking was working, but ssl was not (outdated certs) that the error wouldn't have been caught at that point?

In my kube cluster, this is being run as a post start command. I was not using the fstab specifically due to all the documentation saying not to and networking wasn't available.

Can I suggest either a lazy or strict mount flag? The use case for wanting it in fstab makes a lot of sense for some, but personally, I'd much rather see it fail hard if it does anything other than fully mount properly. I don't want masked errors (or even worse, pretending it worked when it clearly didn't) when I am bringing up pods/containers that depend on a ReadWriteMany strategy. I would far rather the error were bang in my face so it could bubble up to the health of a deployment. I would be perfectly content if it defaulted to lazy mount but I could override with --strict or --failhard.

**Comment by jacobsa** [comment]
That output appears to be stderr. Are you sure you're not seeing the message on stdout?

Agreed that not being strict should probably require setting a flag.

**Comment by scolson** [comment]
The copy-paste was attached to the container, so it was both stdout and stderr.

BUT, it just occurred to me that the build I was using is quite possibly from before the Sept 4 commit and release as it the binary is statically included and not (yet) created as an artifact in our build process. So I am less worried about the missing error string.

**Comment by raj-prince** [comment]
I tried reproducing this issue, on a lightweight image by removing the ssl server from the image.

**Steps:**
1. Build and run the image - https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/Dockerfile
2. Deleted ssl server by executing the command - `sudo rm -r /etc/ssl/cert/`

```
I0612 04:49:18.714073 Creating a new server...
I0612 04:49:18.714082 Set up root directory for bucket princer-working-dirs
I0612 04:49:18.726125 Error while mounting gcsfuse: mountWithConn: fs.NewServer: create file system: SetUpBucket: Error in iterating through objects: Get "https://storage.googleapis.com/storage/v1/b/princer-working-dirs/o?alt=json&delimiter=&endOffset=&includeTrailingDelimiter=false&maxResults=1&pageToken=&prefix=&prettyPrint=false&projection=full&startOffset=&versions=false": oauth2: cannot fetch token: Post "https://oauth2.googleapis.com/token": tls: failed to verify certificate: x509: certificate signed by unknown authority
mountWithArgs: mountWithConn: fs.NewServer: create file system: SetUpBucket: Error in iterating through objects: Get "https://storage.googleapis.com/storage/v1/b/princer-working-dirs/o?alt=json&delimiter=&endOffset=&includeTrailingDelimiter=false&maxResults=1&pageToken=&prefix=&prettyPrint=false&projection=full&startOffset=&versions=false": oauth2: cannot fetch token: Post "https://oauth2.googleapis.com/token": tls: failed to verify certificate: x509: certificate signed by unknown authority
```

Earlier, gcsfuse used to show warning message, in case any error in Listing during the mount. Now, it started throwing error, which fails the mount process.

Ref: https://github.com/GoogleCloudPlatform/gcsfuse/blob/e08c26b44f2e4a1e1d1da4e08c3ce67130e0f539/internal/gcsx/bucket_manager.go#L234
