### ISSUE TITLE
Can't create acme challenge directories via gcsfuse? 

### ISSUE THREAD

**Issue by arup42** [GoogleCloudPlatform/gcsfuse#261]
I think may not really be a gcsfuse issue, but I don' t know where else to ask:  I was using gcsfuse to assist in the renewal of a letsencrypt ssl certificate, with gcsfuse acting as a distributed storage mechanism to make the challenge file available to all of the N http servers that might receive the http fetch request for the challenge. 

This used to work fine 3 months ago, but no longer does, as attempts to create a directory called "acme-challenge" now fail. With debugging cranked up, it looks like someone consciously decided to break this use case: 

fuse_debug: Op 0x00000022        connection.go:396] <- MkDir (parent 2, name "acme-challenge")
gcs: Req              0xd: <- CreateObject(".well-known/acme-challenge/")
gcs: Req              0xd: -> CreateObject(".well-known/acme-challenge/") (27.112683ms): googleapi: Error 400: ACME HTTP challenges are not supported., invalid
fuse_debug: Op 0x00000022        connection.go:481] -> Error: "CreateChildDir: googleapi: Error 400: ACME HTTP challenges are not supported., invalid"
fuse: 2018/01/31 20:28:13.901100 *fuseops.MkDirOp error: CreateChildDir: googleapi: Error 400: ACME HTTP challenges are not supported., invalid

If I understood that correctly, it sounds like GCS itself is rejecting directories named "acme-challenge/" ?(!)  I searched, but wasn't able to find any announcement or other discussion of this ... Do you know where best to ask about it? Thanks!

**Comment by jacobsa** [comment]
Hah wow, nice find. This does seem like a GCS issue. I'm not on the GCS team
and can't offer any official support, but if you're able to use `--debug_http`
to collect the actual failing HTTP request, redact your auth token, and stick
it in a GitHub gist, I'm happy to report the issue internally for you. I don't
know whether there is a publicly available way to report GCS issues or not.

**Comment by arup42** [comment]
I removed the actual project and bucket names from the url and the post body, removed the Authorization header from the request, and removed the X-Guploader-Uploadid in the response and put the result into a [gist](https://gist.github.com/anonymous/533e205688e951908df8023ae2cefc5c) as you suggested. 

Thanks!

**Comment by jacobsa** [comment]
Thanks. As I said I can't promise anything, but I filed Google-internal bug 72756053 for this.

**Comment by jacobsa** [comment]
Hi, this restriction is now [documented](https://cloud.google.com/storage/docs/naming#objectnames), and was apparently made for security purposes.

**Comment by arup42** [comment]
Thanks for looking into it. I've already worked around the issue, but if they said anything about what the problem was with that prefix, I'd love to know a little more.
