### ISSUE TITLE
wrong option --temp-dir value

### ISSUE THREAD

**Issue by nmorade** [GoogleCloudPlatform/gcsfuse#264]
in gcsfuse manpage we have "--temp-dir value" this option doesn't work in /etc/fstab there is mistake, the working option is temp_dir (with underscore). Can you please correct this bug ?

**Comment by jacobsa** [comment]
This is [working as documented](https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/mounting.md#mount8-and-fstab-compatibility).
