### ISSUE TITLE
Reboot cause reset to all mounted folder 

### ISSUE THREAD

**Issue by grasssnake123** [GoogleCloudPlatform/gcsfuse#266]
I mounted my images folder to a google bucket. The bucket works well and can be shared to several website to serve same images. So there are more than 10 folders on sites public directory that mounted to the same bucket.
The problem is every time my server rebooting, it will also reset all mounted folders connection to the bucket, and I have to remounted all the folders again and again.
Is there any command to make it permanently mounted?
I usually use this command to mount:
`gcsfuse mybucket /path/to/folder`

Thank you.

**Comment by jacobsa** [comment]
gcsfuse is a user-mode process, and like all user processes it is killed when the system reboots. If you want to mount on startup, please see the [fstab](https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/mounting.md#mount8-and-fstab-compatibility) documentation.
