### ISSUE TITLE
service account via compute instance fails, but key works!

### ISSUE THREAD

**Issue by apenney** [GoogleCloudPlatform/gcsfuse#267]
Hi,

I'm trying to figure out how to restrict an instance to be able to read/write from a single bucket, and having an incredibly hard time making this work.

First, I created a service account, and gave it bucket access:

<img width="398" alt="screen shot 2018-02-11 at 2 33 37 pm" src="https://user-images.githubusercontent.com/9492/36077422-afa72bc4-0f38-11e8-8b6a-6b8631b4c1ba.png">

I then attached this service account to my instance:

```
# curl "http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/email" -H "Metadata-Flavor: Google"
bucket-access-for-test2@sftpgateway-f25bdcc8.iam.gserviceaccount.com
```

However, when I use gcsfuse without a key file (snipped for size)

```
root@sftpgateway-test2-b1rb:~# gcsfuse --foreground --debug_gcs --debug_fuse --debug_http cota-test2 /mnt/sftp
Using mount point: /mnt/sftp
Opening GCS connection...

Opening bucket...
gcs: Req              0x0: <- ListObjects()
http: ========== REQUEST:
GET http://www.googleapis.com/storage/v1/b/cota-test2/o?maxResults=1&projection=full HTTP/1.1

http: ========== RESPONSE:
HTTP/2.0 403 Forbidden
Content-Length: 208
Cache-Control: private, max-age=0
Content-Type: application/json; charset=UTF-8
Date: Sun, 11 Feb 2018 19:41:49 GMT
Expires: Sun, 11 Feb 2018 19:41:49 GMT
Server: UploadServer
Vary: Origin
Vary: X-Origin
Www-Authenticate: Bearer realm="https://accounts.google.com/", error=insufficient_scope, scope="https://www.googleapis.com/auth/cloud-platform"
X-Guploader-Uploadid: AEnB2Uq-fxIK90fxASU0fPq_WsOgDefDh06GQxBZqLFWH5VwV-ykK68_PI6xkXoTguTXn-EFEBRCNWvd9h_4TzPzz0LN0dRClakN1CyosgJo6cuF-xt23CY

{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "insufficientPermissions",
    "message": "Insufficient Permission"
   }
  ],
  "code": 403,
  "message": "Insufficient Permission"
 }
}
http: ====================
gcs: Req              0x0: -> ListObjects() (117.952551ms): googleapi: Error 403: Insufficient Permission, insufficientPermissions
mountWithArgs: mountWithConn: setUpBucket: OpenBucket: Bad credentials for bucket "cota-test2". Check the bucket name and your credentials.
```
If I create a key from this service account and upload it:

```
# gcsfuse --foreground --debug_gcs --debug_fuse --debug_http --key-file key.json cota-test2 /mnt/sftp
[snip]
File system has been successfully mounted.
```

Just to verify the key is really from this serviceAccount:

```
  "client_email": "bucket-access-for-test2@sftpgateway-f25bdcc8.iam.gserviceaccount.com",
```

Is there some difference in behavior between the instance metadata attempts at authentication and a key?  It seems like the permissions should be identical, it being the same account.  The "Authorization: Bearer" tokens don't match between the key and the instance serviceAccount, however, and I don't know why that is.

**Comment by jacobsa** [comment]
Hi, just to be 100% sure, did you see the documentation [here](https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/mounting.md) about creating the VM with a service account with `storage-full` access? I believe that's the only supported way to get access to VM-wide credentials for GCS, and I seem to recall that it has to be done at creation time. (That would be a question for GCE support probably.)

**Comment by apenney** [comment]
I didn't realize that would be the only supported method.  I was trying to avoid that specifically as I only wanted to allow access to a single bucket.  Maybe I just don't understand GCP permissions!

I ended up making it work with `storage-full` as a temporary workaround but it sounds like this is the only thing that's supported without dropping a key onto the box.

**Comment by jacobsa** [comment]
It's possible _I_ don't understand GCP permissions, which don't seem particularly well documented. But as far as I know that's the only way for gcsfuse to ask the VM itself for credentials that can be used to access GCS. If you find otherwise please let me know.
