### ISSUE TITLE
Vsftp Access

### ISSUE THREAD

**Issue by fabltd** [GoogleCloudPlatform/gcsfuse#268]
Hello

I am trying to mount  a GCS bucket as the home directory for an FTP server. User logs in downloads files stored on GCS.

GCS bucket can be accessed from terminal. Its mounted using --blind to the FTP home directory but will not show up when an FTP client is connected.

Any idea?

**Comment by jacobsa** [comment]
Sorry, I don't know the first thing about how vsftpd works. If you can phrase this as a problem at the file system API level (use `strace` or `gcsfuse --foreground --debug_fuse` to help) then I can look at it, but otherwise this is beyond my remit.
