### ISSUE TITLE
key-file option is not taken into account when running mount command

### ISSUE THREAD

**Issue by ndsist** [GoogleCloudPlatform/gcsfuse#269]
My aim is to mount a Google bucket at boot time; I am using gcsfuse 0.23.0.
I first tried using gcsfuse to check if my key was correct, running

`gcsfuse --implicit-dirs --key-file=<path_to_json> <bucket> <path>`

and indeed it worked correctly.
Then, in order to check the options I was going to put in fstab file and apparently accordingly to

https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/mounting.md

I tried

`mount -t gcsfuse -o _netdev,allow_other,--file-mode=0666,--implicit-dirs,--key-file=<path_to_json> <bucket> <path>`

but I got

```
Calling gcsfuse with arguments: -o allow_other -o --file-mode=0666 -o --implicit-dirs -o --key-file=<path_to_json> -o rw <bucket> <path>
Using mount point: <path>
Opening GCS connection...
daemonize.Run: readFromProcess: sub-process: mountWithArgs: getConn: DefaultTokenSource: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
running gcsfuse: exit status 1
```

It seems that the key-file option is not take into account. Just as a try, I have modified the fstab file with the very same options and got the same output.
Please notice that googling I have found

https://askubuntu.com/questions/890273/how-to-use-fstab-to-mount-google-bucket-on-local-mounting-point-granting-full-ac
https://stackoverflow.com/a/39047673

which seem related to the same problem.
Am I missing something?

**Comment by jacobsa** [comment]
You have the syntax wrong; instead of `--key-file` you want `key_file`. fstab options don't traditionally have dashes in front of them. Please try this and report back.

**Comment by ndsist** [comment]
Running

`mount -t gcsfuse -o  _netdev,allow_other,implicit_dirs,file_mode=0666,key_file=<path_to_json> <bucket> <path>`

made the folder be mounted correctly.
Besides, I understood I misunderstood the contents of
https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/mounting.md
Thank you very much!
