### ISSUE TITLE
`noauto` with fstab doesn't work in Ubuntu 16.04

### ISSUE THREAD

**Issue by it-svit** [GoogleCloudPlatform/gcsfuse#271]
https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/mounting.md#mount8-and-fstab-compatibility

Above link says that it is necessary to use the following string in `fstab`:
```
my-bucket /mount/point gcsfuse rw,noauto,user
```

But this option doesn't work in Ubuntu 16.04.

The following option works well
```
my-bucket /mount/point gcsfuse rw,user
```

**Comment by nafg** [comment]
What do you mean it "doesn't work"? What exactly happens?

**Comment by it-svit** [comment]
@nafg Bucket is not being mounted on reboot.

**Comment by nafg** [comment]
That's what noauto is supposed to do. https://superuser.com/questions/1038136/what-is-the-noauto-mount-flag-for

**Comment by nafg** [comment]
Actually, at that link it says,

> Afterward, you can run `mount /mount/point` as a non-root user.

> The `noauto` option above specifies that the file system should not be mounted at boot time.
