### ISSUE TITLE
Java file system gets stuck for 15-20 minutes when mounting bucket with gcsfuse

### ISSUE THREAD

**Issue by satishbhor** [GoogleCloudPlatform/gcsfuse#272]
Hi All,
When we are trying to perform any operation on gcfuse mounted bucket directory using JAVA API it get stuck/hang for 15-20 minutes.

sample java FS api

````
java.io.UnixFileSystem.getBooleanAttributes0(Native Method)
java.io.UnixFileSystem.getBooleanAttributes(UnixFileSystem.java:242)
java.io.File.exists(File.java:819)
````
```
java.io.UnixFileSystem.list(Native Method)
java.io.File.list(File.java:1122)
```

**Comment by jacobsa** [comment]
Sorry, this isn't enough information to debug your problem. If you can use some combination of `strace` and `gcsfuse --foreground --debug_fuse` to get some idea of what's going on at the file system API level, I might be able to say more.
