### ISSUE TITLE
Cannot mount a folder which syncing to Google cloud storage

### ISSUE THREAD

**Issue by gamkittisak** [GoogleCloudPlatform/gcsfuse#273]
I want to mount a folder in my container. When I build the image, it got the error:
=====
[Dockerfile]
------------
FROM python:3.6-slim
.
.
.
RUN mkdir /gam-storage
RUN gcsfuse --key-file=/app/key.json gam_storage  /gam-storage 
CMD python /app/main.py 

[Docker build ]
------------
Step 6/8 : RUN mkdir /gam-storage
Step 7/8 : RUN gcsfuse --key-file=/app/key.json gam_storage /gam-storage

Using mount point: /gam-storage
Opening GCS connection...
Opening bucket...
Mounting file system...
daemonize.Run: readFromProcess: sub-process: mountWithArgs: mountWithConn: Mount: mount: running fusermount: exit status 1

stderr:
fusermount: fuse device not found, try 'modprobe fuse' firs

**Comment by jacobsa** [comment]
This seems like a problem with your Docker and/or fuse setup. Unfortunately I'm not able to help you with that, sorry.
