### ISSUE TITLE
When tried to move folder , not reflected in mounted path

### ISSUE THREAD

**Issue by rishin458** [GoogleCloudPlatform/gcsfuse#276]
If I tried to move a file , (cmd: gsutil -m mv cold/x gs://rishiwarm/ ) , the file "x" is moved and is shown using mounted point 
[~/testdir]$ ྿  find /mnt/warm/
/mnt/warm/
/mnt/warm/x

But if I tried to move folder "gsutil -m mv cold gs://rishiwarm/" , the folder "cold/x"  is found if check from browser......but does not shown using mounted path
[~/testdir]$ ྿  find /mnt/warm/
/mnt/warm/

[~/testdir]$ ྿  gcloud -v
Google Cloud SDK 195.0.0
bq 2.0.30
core 2018.03.23
gsutil 4.29

**Comment by jacobsa** [comment]
Please see the documentation on [implicit directories](https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/semantics.md#implicit-directories). In this case you probably need to do `mkdir cold/x`.
