### ISSUE TITLE
Document the use of gcloud auth application-default login

### ISSUE THREAD

**Issue by WyattGorman** [GoogleCloudPlatform/gcsfuse#277]
Please add information about running "gcloud auth application-default login" to register auth credentials as documented on the Google Cloud GCS Fuse documentation here: https://cloud.google.com/storage/docs/gcs-fuse.

**Comment by jacobsa** [comment]
It seems this is already covered by the documentation [here](https://github.com/GoogleCloudPlatform/gcsfuse/blob/bb9b4ee3d557145afed115dd20dde8471ffccef4/README.md#prerequisites) and [here](https://github.com/GoogleCloudPlatform/gcsfuse/blob/f1a018ccd5ceb359f4ec9c72963c45a0a4d9c1eb/docs/mounting.md#credentials).

**Comment by cespare** [comment]
The instructions to run `gcloud auth login` in that documentation are not sufficient; the command `gcloud auth application-default login` is required.

When you run `gcloud auth login`, it does give you a warning that points in this direction:

```
WARNING: `gcloud auth login` no longer writes application default credentials.
If you need to use ADC, see:
  gcloud auth application-default --help
```

**Comment by WyattGorman** [comment]
Good news is that this has been corrected, with the "gcloud auth application-default login" command now appearing in step 2b of the gcsfuse documentation found here: https://cloud.google.com/storage/docs/gcs-fuse

If there are further concerns regarding the documentation please open a new ticket.

**Comment by cespare** [comment]
It has not been corrected in this repo, which is the exact thing this ticket was opened about. (The links you put into the original issue still point at two places in README.md and docs/mounting.md that say `gcloud auth login` rather than `gcloud auth application-default login` which mislead me and caused me to come find this issue in the first place.)
