### ISSUE TITLE
Potential performance improvements

### ISSUE THREAD

**Issue by abagshaw** [GoogleCloudPlatform/gcsfuse#278]
I'm using gcsfuse to mount the `open-images-dataset` for ML training. Performance was sorely lacking so I decided to try out an alternative (https://github.com/kahing/goofys). Setting up goofys to work with a gcs bucket is a bit of a pain (given that it's designed for S3) but it works - and performs drastically better for my use case (reading dozens of small images concurrently from multiple threads).

Any ideas on what goofys is doing differently from gcsfuse that enables this significantly improved performance?

**Comment by jacobsa** [comment]
From the goofyfs readme:

> It's a Filey System instead of a File System because goofys strives for performance first and POSIX second. Particularly things that are difficult to support on S3 or would translate into more than one round-trip would either fail (random writes) or faked (no per-file permission).

This is the opposite of gcsfuse's intended use case, which is as close to posix as is possible with GCS.

**Comment by jacobsa** [comment]
(Of course if you find some performance trick in goofyfs that is applicable in gcsfuse I'm more than happy to hear it. But this is a very open-ended thread, so I've closed it.)

**Comment by kahing** [comment]
I took a quick look at gs://open-images-dataset/train and the files there seem small and it's a flat hierarchy, so it's not immediately clear to me why goofys is faster. Per https://github.com/GoogleCloudPlatform/gcsfuse#downloading-object-contents gcsfuse also streams files on read, so unless gcsfuse stages content to disk first (in case it's modified later) performance should be comparable. @abagshaw is there any hard numbers you could share?

Also happy to take suggestions for how to make using goofys with gcs easier, but that's more relevant at https://github.com/kahing/goofys/issues/new
