### ISSUE TITLE
Mounting fail when building Dockerfile

### ISSUE THREAD

**Issue by rexlow** [GoogleCloudPlatform/gcsfuse#280]
I am trying to mount a storage bucker inside my container during `docker build`.

I've read other threads understood that this may be a privileged problem. It can be solved by adding the `--privileged` flag in the docker run process, but I would like to get the bucket mounted right off the building stage.

Attached to the container, checked that both `fuse` and `gcsfuse` are installed. `GOOGLE_APPLICATION_CREDENTIALS` is set, no problem with accessing Google APIs. Here's the error I am getting.

```
Opening GCS connection...
Opening bucket...
Mounting file system...
daemonize.Run: readFromProcess: sub-process: mountWithArgs: mountWithConn: Mount: mount: running fusermount: exit status 1

stderr:
fusermount: fuse device not found, try 'modprobe fuse' first
```

**Dockerfile**

```
FROM gcr.io/google-appengine/python
.
.
.
ENV GCSFUSE_REPO=gcsfuse-jessie
RUN apt-get update && apt-get install -y ca-certificates \
    && echo "deb http://packages.cloud.google.com/apt $GCSFUSE_REPO main" > /etc/apt/sources.list.d/gcsfuse.list \
    && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - \
    && apt-get update && apt-get install -y gcsfuse

# Config fuse
RUN chmod a+r /etc/fuse.conf
RUN perl -i -pe 's/#user_allow_other/user_allow_other/g' /etc/fuse.conf

# Alter permission
RUN chmod a+w mount-folder

RUN gcsfuse -o --implicit-dirs bucket mount-folder
```

**Comment by jacobsa** [comment]
This sounds like a problem with the interaction between docker and fuse, not anything gcsfuse-specific. Unfortunately I'm not able to offer support for issues with docker, sorry. Please let me know if you find evidence that gcsfuse is doing something wrong here though.

**Comment by wuservices** [comment]
@rexlow  I got here trying to find solutions with gcsfuse + Docker. I found that `--device /dev/fuse --cap-add SYS_ADMIN` also does the trick, but doesn't solve your issue. If you can't see `/dev/fuse` and have some more permissions, it seems like you're just stuck.
