### ISSUE TITLE
Mounted folder and files are not accessible

### ISSUE THREAD

**Issue by eldhoseelias** [GoogleCloudPlatform/gcsfuse#282]
My project URL is  http://siteaddress/app/web/uploads/
Here uploads folder is mounted with google storage bucket using fuse.

Before mount, i can access  http://siteaddress/app/web/uploads/ , and in the browser showing files are folder. But after mounting its shows an **Forbidden** error.

You don't have permission to access /app/web/uploads/ on this server.
Apache/2.2.15 (CentOS) Server at xx.xx.xx.xx Port 80

How to solve this issue.?

**Comment by jacobsa** [comment]
Please see the documentation on implicit directories [here](https://github.com/googlecloudplatform/gcsfuse#invoking-gcsfuse) and [here](https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/semantics.md#implicit-directories).
