### ISSUE TITLE
Apt packages for Ubuntu 18.04

### ISSUE THREAD

**Issue by apenney** [GoogleCloudPlatform/gcsfuse#283]
Hi,

Not sure who builds the packages in the repository currently, but I just tried to rebuild some machines on 18.04 and noticed there are no packages.  I'm happy to contribute if that part of the system is public, otherwise this is a plea to the team to add 18.04! :)

Thanks,

**Comment by jacobsa** [comment]
Thanks for the report. I've added the repo and it should be working now; could you confirm?
