### ISSUE TITLE
Debian 9 support

### ISSUE THREAD

**Issue by sianghung** [GoogleCloudPlatform/gcsfuse#285]
Hi,

I have been using gcsfuse in Google Compute Engine, running on Debian 8, users will upload files to the VM, and I use gcsfuse to mount the folder to a Google Cloud Bucket, was not having any issue until recently, when I upgraded the VM to Debian 9, and I have been having issue with my files in bucket where the file uploaded to bucket became 0 byte. 

I wasn't able to provide a log because the data are sensitive and I haven't setup any logging too. I just wish to know is Debian 9 supported by gcsfuse? Otherwise I will fall back to Debian 8 for now.

**Comment by jacobsa** [comment]
I don't know any reason this shouldn't work, but please let me know if you find something interesting.

**Comment by sianghung** [comment]
I am not sure now as I have already downgraded my VM back to Debian 8, but recently I faced the same issue again where the files became 0 bytes after being synced over to my Google Cloud Bucket. But this time it only happened on a few files out of thousands of files.
