### ISSUE TITLE
Credentials not working for "requester pays" buckets

### ISSUE THREAD

**Issue by ryan-williams** [GoogleCloudPlatform/gcsfuse#286]
I have a service-account JSON file stored in the `GOOGLE_APPLICATION_CREDENTIALS` env var, and ran:

```bash
gcsfuse --foreground --debug_fuse --implicit-dirs <bucket> /tmp/<bucket>
```

I see many `WARNING`s like:

```
WARNING, bucket doesn't appear to work:  googleapi: Error 400: Bucket is requester pays bucket but no user project provided., required
```

Attempting to `ls` the mounted directory gives:

```
ls: reading directory '/tmp/<bucket>/': Input/output error
total 0
```

The docs imply that the credentials I've set above should make this work, but afaict something is broken there. Perhaps I have some incorrect configuration, but thought I'd document here in case anyone else can confirm/deny that they see the same issue.

Running the equivalent command with [`gcsfs`'s `gcsfuse`](http://gcsfs.readthedocs.io/en/latest/fuse.html) seems to work fine, fwiw.

**Comment by ticmigithub** [comment]
i'm having the same problem, any solution for this issue ?

**Comment by MattFaus** [comment]
You probably need to specify `--billing-project`

**Comment by avidullu** [comment]
The --billing-project flag as mentioned by @MattFaus is expected to resolve this issue.
Closing this out. Please reopen/file a new request with logs if you see otherwise.
