### ISSUE TITLE
ambigous error on macos

### ISSUE THREAD

**Issue by medyagh** [GoogleCloudPlatform/gcsfuse#287]
followed the docs, I got this error:

I tried to add all the --debugs but it wouldn't add any more detail than this

```
$ gcsfuse --debug_fuse --debug_gcs --debug_http my-bucket-name ./data/my-bucket-name
Using mount point: /Users/myusername/Desktop/workspace/data/my-bucket-name
Opening GCS connection...
Opening bucket...
Mounting file system...
daemonize.Run: readFromProcess: sub-process: mountWithArgs: mountWithConn: Mount: mount: loadOSXFUSE: exit status 1

```

my gcsfuse verison
```
$ gcsfuse --version
gcsfuse version 0.23.0 (Go version go1.9)
```

fuse version :`3.8.0`

MacOs Version:  High Sierra `10.13.5`

**Comment by jacobsa** [comment]
Unfortunately, this is just the poor user experience of osxfuse, which gives no detail for why it's not working. (Maybe check that the directory doesn't already have something mounted on it?) gcsfuse [passes through](https://github.com/GoogleCloudPlatform/gcsfuse/blob/32bcbb555a2b3f4d05045c3ebc255bb098fee8d3/vendor/github.com/jacobsa/fuse/mount_darwin.go#L62-L69) all error detail that osxfuse gives.
