### ISSUE TITLE
Can't list directorties uploaded via web interface

### ISSUE THREAD

**Issue by grafa** [GoogleCloudPlatform/gcsfuse#289]
I'm not sure if this is a feature or a bug but in the case of bug:

When I upload a file via web interface (browser tool): ...

![image](https://user-images.githubusercontent.com/198654/43447084-ecaf9b6c-94aa-11e8-995c-7614c8582de6.png)

... I can list the file on my machine where the bucket is mounted. But when I do upload a folder I can't. `ls` simply can't see the folder upload via web interface.

When I copy a file from my machine to the mounted disk I can see the file in web interface.

Am I doing something wrong?

**Comment by jacobsa** [comment]
Please see the note about implicit directories [here](https://github.com/googlecloudplatform/gcsfuse#invoking-gcsfuse) and in the semantics file it links to.
