### ISSUE TITLE
Add LICENCE file to apt package

### ISSUE THREAD

**Issue by nmousavi** [GoogleCloudPlatform/gcsfuse#290]
With installing gcsfuse from http://packages.cloud.google.com/apt, no COPYRIGHT file is copied. This is REQUIRED for OSS images installing gcsfuse.

find . -name copyright | grep gcsfuse  returns null
ls /usr/share/doc/gcsfuse/ returns only changelog.gz

**Comment by ashmeenkaur** [comment]
The fix has been merged. This issue will fix in the next released version (v1.0.1).
