### ISSUE TITLE
Transient "reading directory '/mnt/project/': Input/output error" error after restart

### ISSUE THREAD

**Issue by carbocation** [GoogleCloudPlatform/gcsfuse#291]
After rebooting a GCP Ubuntu 18.04 machine and logging in, I try to list the contents of my gcsfuse-mounted folder as a non-root user:
`ls /mnt/project/`

and I get the following error: 
```
ls: reading directory '/mnt/project/': Input/output error
total 0
```

However, if I just keep typing `ls` (8 times in this case), I will eventually see the folder contents:
```
ls /mnt/project/
total 1
... etc
```

My `/etc/fstab` contents:

```sh
project /mnt/project gcsfuse rw,allow_other,implicit_dirs,default_permissions,file_mode=777,dir_mode=777
```

Is there something that I should be doing differently, or is this a known issue after rebooting?

**Comment by carbocation** [comment]
If this is helpful at all, I've now mounted 3 buckets in this way simultaneously, and for each one, the first ~10 seconds or so after I first try to access the bucket, I'm told that there is an input/output error. The fact that I got one of the buckets working had no bearing on the next bucket - each bucket had to wait ~10 seconds after the first access *of that bucket* before it would stop showing that error. Each of them eventually started behaving totally normally.

**Comment by naarkhoo** [comment]
I have a similar problem ... basically the bucket is mounted by can't write anything in

**Comment by mihi314** [comment]
I had exactly the same issue. The cause probably was that after booting, the buckets were mounted before the network was available. Adding `_netdev` to the mount options, as described e.g. [here on stackexchange](https://unix.stackexchange.com/a/349278), makes sytemd mount them only after a network connection is available. Which solves the input/output errors I was getting.

If it solves the issue also for others, it should probably be mentioned in the docs as well.

**Comment by avidullu** [comment]
Thanks @mihi314 for the suggestion. As you recommended, the suggestion has been absorbed in the document as highlighted below
![netdev-doc](https://user-images.githubusercontent.com/1674877/163316871-caad0de9-9bd9-402c-954f-1cd8f0551f4f.png)
