### ISSUE TITLE
Documentation for usage with App Engine

### ISSUE THREAD

**Issue by ydennisy** [GoogleCloudPlatform/gcsfuse#293]
Hello,
It would be great to get some docs as how one would use this with Google App Engine, I am specifically using a nodejs flexible environment.
Thanks,
Dennis

**Comment by bjornleffler** [comment]
I don't think that would work, as AppEngine is a platform where you don't control the underlying system.

I'd recommend you use the official GCS API for NodeJS:
https://cloud.google.com/nodejs/getting-started/using-cloud-storage
