### ISSUE TITLE
Encryption at rest and in transit

### ISSUE THREAD

**Issue by rshade** [GoogleCloudPlatform/gcsfuse#294]
I am assuming gcsfuse does ssl encryption in transit is that right? Is it possible to do encryption at rest also?

**Comment by bjornleffler** [comment]
Connections to GCS always use ssl encryption. You could potentially use some encrypted file system for the temporary storage if you wanted to.

Google Cloud Platform encrypts customer data stored at rest by default, with no additional action required from you. This includes Persistent Disk if you're running a VM on GCE.
https://cloud.google.com/security/encryption-at-rest/
