### ISSUE TITLE
*fuseops.GetXattrOp error: function not implemented

### ISSUE THREAD

**Issue by emobortnik** [GoogleCloudPlatform/gcsfuse#296]
Hello!

I can not get files after mounting.

Here is my fstab string:

images.interatletika.com /storage/images.interatletika.com gcsfuse rw,allow_other,_netdev,noexec,implicit_dirs,uid=1002,gid=1003

i even tried 
images.interatletika.com /storage/images.interatletika.com gcsfuse rw,allow_other,implicit_dirs,uid=1002,gid=1003

ls -lah /storage/images.interatletika.com/
ls: чтение каталога /storage/images.interatletika.com/: Ошибка ввода/вывода
итого 0

after
 gcsfuse --implicit-dirs --foreground -o allow_other --debug_gcs --debug_fuse images.interatletika.com /storage/images.interatletika.com

I can see this in log

fuse_debug: Op 0x00000001        connection.go:396] <- init
fuse_debug: Op 0x00000001        connection.go:479] -> OK ()
File system has been successfully mounted.
fuse_debug: Op 0x00000002        connection.go:396] <- GetInodeAttributes (inode 1)
fuse_debug: Op 0x00000002        connection.go:479] -> OK ()
fuse_debug: Op 0x00000003        connection.go:396] <- GetXattr (inode 1, name "security.selinux", name security.selinux)
fuse_debug: Op 0x00000003        connection.go:481] -> Error: "function not implemented"
fuse: 2018/08/27 16:58:53.547999 *fuseops.GetXattrOp error: function not implemented
fuse_debug: Op 0x00000004        connection.go:396] <- OpenDir (inode 1)
fuse_debug: Op 0x00000004        connection.go:479] -> OK ()
fuse_debug: Op 0x00000005        connection.go:396] <- ReadDir (inode 1)
gcs: Req              0x2: <- ListObjects()
gcs: Req              0x2: -> ListObjects() (152.373295ms): OK
fuse_debug: Op 0x00000005        connection.go:479] -> OK ()
fuse_debug: Op 0x00000006        connection.go:396] <- ReleaseDirHandle
fuse_debug: Op 0x00000006        connection.go:479] -> OK ()

**Comment by avidullu** [comment]
Was resolved in [this commit](https://github.com/GoogleCloudPlatform/gcsfuse/commit/f3ddce5eeacd853b77addfdff4e6754dfac6a43e)
