### ISSUE TITLE
Slash added automaticaly before bucket name with fstab

### ISSUE THREAD

**Issue by bastiendonjon** [GoogleCloudPlatform/gcsfuse#299]
I use this syntax in my fstab : 

```
my_bucket /my_bucket_mount gcsfuse rw,uid=1001,gid=1002
```

But gcsfuse process is launched like this:
```
/usr/bin/gcsfuse --foreground -o rw --uid 1001 --gid 1002 /my_bucket /my_bucket_mount
```
With "/" before "my_bucket", the mount do not work.

It runs on Ubuntu 16

Why does fstab add this / automatically ?

**Comment by jacobsa** [comment]
Sorry, I misunderstood your wording in the first post. Unfortunately I don't have an answer for you—that's up to your linux distribution, not gcsfuse. I can say that I've seen weird things happen if there's a directory that's named the same thing as the bucket (in this case `my_bucket`); you don't have a directory with a matching name in the root directory, your home directory, etc, do you?

**Comment by bastiendonjon** [comment]
Yes. Thanks. That's it !

I had a folder named like the bucket in root directory.

It's fixed.
