### ISSUE TITLE
Copying data from S3 Storage into GCS slow using gcsfuse 

### ISSUE THREAD

**Issue by cindy-pi** [GoogleCloudPlatform/gcsfuse#302]
I am seeing a transfer rate ~ 2.0 MiB/s
Scenario:
Running /bin/aws s3 sync s3://{S3Bucket} /mnt/target

/mnt/target is a gcsfuse mount that is started via my /etc/fstab

Is there some parameter that I am missing to speed up performance?

I am running on a Google Cloud VM.

Here is my fstab entry
{gcs-bucket} /mnt/target gcsfuse rw,noauto,user,key_file=/home/user/gcp/key.json

**Comment by bjornleffler** [comment]
Great question. Generally speaking, there are probably better ways to accomplish this. With GCSFuse, the data needs to be read from S3, written to local disk and finally uploaded to GCS.The bottleneck here is probably writing to local disk (do you have a large PD volume?). The default 10GB PD disk only offers 1.2 MB/s of read/write speed with some bursting. For larger data sets, that will be quite slow.

I'd recommend you look at the Gsutil documentation:
https://cloud.google.com/storage/docs/interoperability
Specifically:
The following command will synchronize data between an Amazon S3 bucket and a Cloud Storage bucket:
gsutil rsync -d -r s3://my-aws-bucket gs://example-bucket

For larger data sets, GCP offers a S3 to GCS transfer service:
https://cloud.google.com/storage-transfer/docs/overview
