### ISSUE TITLE
Folder uploaded by `gsutil` to the bucket cannot seen in the directory mounted by `gcsfuse`

### ISSUE THREAD

**Issue by zkf85** [GoogleCloudPlatform/gcsfuse#303]
The Problem is just as described in the title. Files uploaded by gsutil seems OK, but all folders uploaded by gsutil cannot be seen in the mounted folder.

**Comment by quantitative-technologies** [comment]
Did you read about --implicit-dirs? Basically, if subdirectories are created by something besides gcsfuse then you won't see them in the mounted dir.

**Comment by AmandaHassoun** [comment]
I don't think that's the case because if I manually create folders in the UI, I do see them in the mounted directory. I'm also having the same issue where I create a new folder in a bucket by copying a file into it using `gsutil` yet I don't see it in the mounted directory...

**Comment by quantitative-technologies** [comment]
That sounds exactly like the problem I had. Yes, if you create a directory in the web UI, then it will show up. But if you create a new folder using gsutil without --implicit-dirs, then the folder does not show up.

**Comment by AmandaHassoun** [comment]
I was reading the documentation around using `gcsfuse` with `--implicit-dirs` and it seems to have odd behaviours so I'm not sure what a good workaround should be? Automating the creation of folders in GCS shouldn't be this tricky..
