### ISSUE TITLE
Permission issues 

### ISSUE THREAD

**Issue by usmanakram1996** [GoogleCloudPlatform/gcsfuse#304]
ls -l for the mounted directory of GCS bucket shows this 

**d?????????  ? ?        ?               ?            ? filestore**

how to run this command ?
sudo gcsfuse obe_b_1 /var/www/html/filestore/ -o  --rw --uid=x --gid=x

please help how to set the uid and gid option as it says gcsfuse takes exactly two arguements

**Comment by bjornleffler** [comment]
The options are specified after the gcsfuse command, but before the bucket and mount point.

I would try something like:
sudo gcsfuse -o --rw --uid=x --gid=x obe_b_1 /var/www/html/filestore/
