### ISSUE TITLE
Inconsistency of read-to-write

### ISSUE THREAD

**Issue by zhuo-sun** [GoogleCloudPlatform/gcsfuse#305]
I found a case in which the change to a file from machine B was overridden by the change to the same file from machine A.

It looks the source generation as part of the HttpPost request failed to guarantee the read-to-write consistency in case it was overriding a newer generation. I expected the source generation in the Http requests should work like write-with-version in Zookeeper to prevent unexpected overriding.

Steps to reproduce:
1) Machine A opens a file 
2) Machine B updates the file
3) Machine A edits the open file and saves it
Usually in step 3, it is prompted by the text editor that the source has been changed out of the editor, to avoid unexpected overriding, because by the time of step 3, most likely the change from step 2 is already synced up to Machine A. But when step 3 happens in a time that is really close to the time of step 2, step 3 overrides the change from step 2 without any prompt. 

I expect, in the step 3 above, GCS should return 409 to indicates a conflict since there is already a newer generation/version.

**Comment by jacobsa** [comment]
Hi, have you read the semantics guaranteed by gcsfuse for files [here](https://github.com/googlecloudplatform/gcsfuse/blob/2f9c7089144321e08dc342efd767bfc80acbffa7/docs/semantics.md#file-inodes)? There is explicitly no guarantee for doing anything fancy when there are multiple writers involved. (And in particular I know of know mechanism in the posix API for the file system to tell the application to put up the prompt you describe.)

**Comment by jacobsa** [comment]
The most relevant section is [user-visible semantics](https://github.com/googlecloudplatform/gcsfuse/blob/2f9c7089144321e08dc342efd767bfc80acbffa7/docs/semantics.md#user-visible-semantics):

> The intent of these conventions is to make it appear as though local writes to a file are in-place modifications as with a traditional file system, whereas remote overwrites of a GCS object appear as some other process unlinking the file from its directory and then linking a distinct file using the same name.
> [...]
> Note the following consequence: if machine A opens a file and writes to it, then machine B deletes or replaces its backing object, or updates it metadata, then machine A closes the file, machine A's writes will be lost. This matches the behavior on a single machine when process A opens a file and then process B unlinks it. Process A continues to have a consistent view of the file's contents until it closes the file handle, at which point the contents are lost.

**Comment by zhuo-sun** [comment]
I expect the exact same behavior you described in your comments. However, that is not the case as I showed in the steps to reproduce so I raised this issue.

> When machine A writes a new version of the inode, it uses the generation number that the user on machine A read from as a precondition. The write fails due to the generation number not being current anymore, which is how B's version wins (as intended by the semantics).

**Comment by avidullu** [comment]
@zhuo-sun - Please reopen this issue with real logs which can help us repro this issue and help you with a resolution.
Closing this one out since it's >3 years old and from jacobsa@'s comments this is WAI and also there are no real logs available in the issue to evaluate.
Appreciate your help in improving the project.
