### ISSUE TITLE
Clarification about gcsfuse read mechanism

### ISSUE THREAD

**Issue by sakinaljana** [GoogleCloudPlatform/gcsfuse#306]
Dear @jacobsa and all,

I still not fully understand about how gcsfuse run in the background. To be specific, i need clarity about these point from gcsfuse's README:

> Files that have not been modified are read portion by portion on demand. gcsfuse uses a heuristic to detect when a file is being read sequentially, and will issue fewer, larger read requests to GCS in this case.

The questions are:
(1) Does it means when user read several storage objects from mounted bucket, gcsfuse will download first to local temporary file like new/modified files, then user will able to read the files?
(2) What exactly `read portion` means?

Thank you!

**Comment by bjornleffler** [comment]
- gcsfuse doesn't download data in advance. gcsfuse reads data on-the-fly, as it is requested by the fuse client.
- gcsfuse will read sequentially from GCS, if the fuse client reads are sequential. This increases throughput performance.
