### ISSUE TITLE
--limit-ops-per-sec unclear error message

### ISSUE THREAD

**Issue by gileez** [GoogleCloudPlatform/gcsfuse#307]
Exceeding the ops per sec limitation results in an error of the form:

> *fuseops.LookUpInodeOp error: LookUpChild: objectNamePrefixNonEmpty: ListObjects: context canceled

took us a while to understand the cause. if the limit was reached the error message should notify the user that this is the reason for the context being canceled.

it is also possible that such an error message appears else where and we are not aware of it.
Thanks!

**Comment by bjornleffler** [comment]
That sounds reasonable. I'll bundle this with issue #313
