### ISSUE TITLE
Input/output error with gcsfuse mounted customer managed encrypted storage bucket

### ISSUE THREAD

**Issue by creativeappdevamit** [GoogleCloudPlatform/gcsfuse#311]
I have mounted a customer managed storage bucket using gcsfuse. It does mount the storage bucket with out error but while listing the files its giving ` ls: reading directory '.': Input/output error `. I have cross verified the permissions including cloud KMS encryption and decryption access. 
What am I missing?

**Comment by rsg98** [comment]
I submitted a PR to fix this in one of the dependencies:

https://github.com/jacobsa/gcloud/pull/10

**Comment by avidullu** [comment]
Closing this out as the fix is submitted. Appreciate the help @rsg98 !
