### ISSUE TITLE
Google Cloud Function Triggers Twice On GCSFuse File Creation

### ISSUE THREAD

**Issue by bephinney** [GoogleCloudPlatform/gcsfuse#312]
I have an SFTP server with a GCSFuse file system.  I then have a Google Cloud Function triggering ```onFinalize``` from the GCS Bucket.  The behavior I am seeing is that when I ```put``` a file via SFTP, the cloud function triggers twice.  Sometimes the file is empty for one of the triggers.  Sometimes it is not.  This is probably due to the latency of the Function startup, but it does indicate that the file is created (some kind of "touch") before the content is written.

Is there any configuration to avoid this duplicate file creation event?  Any workarounds?

Configuration:
sftp-server installed on Debian configured with a GCS Fuse file system running as a container in GKE.

**Comment by bjornleffler** [comment]
This is working as intended according to the Semantics documentation:
https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/semantics.md

When a new file is created, gcsfuse creates an empty file. When the data has been written and the file is closed, gcsfuse writes the second version of the file.

I haven't used cloud functions, but a simple workaround would be to check for empty files and ignore those messages.

**Comment by bjornleffler** [comment]
I added this to the documentation today, to clarify the logic around GCS notifications:
https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/semantics.md#pubsub-notifications-on-file-creation
