### ISSUE TITLE
Better error message for invalid credentials

### ISSUE THREAD

**Issue by JuddRogers** [GoogleCloudPlatform/gcsfuse#313]
A GCE customer using gcsfuse got a confusing error when listing a mounted bucket.

VM was up for several days. The initial mount and initial ls and other actions worked fine.

Someone on the customer's team deleted and recreated the service account used to access the bucket.
This broke the connection but the error from gcsfuse was not helpful.

The error:
```
ls: reading directory '/mnt/ABCDEFG/': Input/output error
```

I had them do the same action via `gsutil ls` and they got:
```
Failure: Could not reach metadata service: Not Found
```
The problem was resolved by restarting the VM. Not sure if that fixed the metadata store or cleaned up the connection to the bucket. In either case, surfacing the error from the API would have helped figure out the cause.

**Comment by bjornleffler** [comment]
So the credentials that gcsfuse was using were invalid.

I'll investigate if the error message can be improved to something like "invalid credentials". Just to set your expectations, this is pretty low priority.

**Comment by lezh** [comment]
After v0.33.2 this issue would be surfaced as "Permission denied".
