### ISSUE TITLE
Unable to create mount OSX 

### ISSUE THREAD

**Issue by MovieStoreGuy** [GoogleCloudPlatform/gcsfuse#314]
I have been playing with gcsfuse for today I haven't been able to get it to run on my mac. I have installed view brew and followed the instructions and get the following:

```
csfuse --debug_fuse --foreground <bucketname> ~/.cloud-mount
Using mount point: /Users/sean/.cloud-mount
Opening GCS connection...
Opening bucket...
Mounting file system...
mountWithArgs: mountWithConn: Mount: mount: loadOSXFUSE: exit status 1
```
It doesn't really give me enough to go away and figure out what is wrong. I was wondering if anyone else had experienced this issue?

**Comment by bjornleffler** [comment]
Unfortunately, this is just the poor user experience of osxfuse, which gives no detail for why it's not working. (Maybe check that the directory doesn't already have something mounted on it?) gcsfuse [passes through](https://github.com/GoogleCloudPlatform/gcsfuse/blob/32bcbb555a2b3f4d05045c3ebc255bb098fee8d3/vendor/github.com/jacobsa/fuse/mount_darwin.go#L62-L69) all error detail that osxfuse gives.

**Comment by shiny-steve** [comment]
In case you get here for this error, for me the solution was to make sure that the preference is set in the Security prefs pane.

**Comment by atorres-eqrx** [comment]
@shiny-steve - Can you elaborate?
