### ISSUE TITLE
Adopt the canonical GCS library cloud.google.com/go/storage

### ISSUE THREAD

**Issue by bramp** [GoogleCloudPlatform/gcsfuse#317]
While gcsfuse works well today, it would be nice to use the [canonical GCS library](https://godoc.org/cloud.google.com/go/storage), instead of `github.com/jacobsa/gcloud/gcs`.

The canonical library has improved greatly, and is aiming to be the most performant Go library. Not only would it show support for the library, but it will help the library authors if bug/performance issues are discovered.

**Comment by bjornleffler** [comment]
Agreed. I've wanted to do this for a long time.

We're currently doing some major improvements to gcs fuse. I'd like to move to the official golang API, as it would fix a number of outstanding issues.

**Comment by sethiay** [comment]
Closing this as GCSFuse now use [Go storage client library](https://godoc.org/cloud.google.com/go/storage) for interacting with GCS.

**Comment by bjornleffler** [comment]
Awesome. Thanks for the update!
