### ISSUE TITLE
apt update fails for Ubuntu18.04 Cosmic

### ISSUE THREAD

**Issue by IA-UoK** [GoogleCloudPlatform/gcsfuse#319]
When following the install instructions on an Ubuntu 18.04 cosmic VM on GCP, the apt-update fails saying...
"E: The repository 'http://packages.cloud.google.com/apt gcsfuse-cosmic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default."
The next steps fail as a result.
Any clues?

**Comment by andrew-grasso** [comment]
18.04 is bionic, not cosmic. Try gcsfuse-bionic in your apt source file.

**Comment by PepeCodes** [comment]
To expand on the above comment, the source for gcsfuse is in `/etc/apt/sources.list.d/gcsfuse.list`

Change this line:
`deb http://packages.cloud.google.com/apt gcsfuse-cosmic main`

To:
`deb http://packages.cloud.google.com/apt gcsfuse-bionic main`

Run:
`sudo apt-get update`

Output should be:
```
...        
Get:7 http://packages.cloud.google.com/apt gcsfuse-bionic/main amd64 Packages [1962 B]
Fetched 169 kB in 1s (310 kB/s)                     
Reading package lists... Done
```

And then as per the readme:
`sudo apt-get install gcsfuse`

And bob is your uncle

**Comment by bjornleffler** [comment]
This is on me. I need to create a new repository for the new Debian release.

**Comment by isracostta** [comment]
ok thanks for the return.

When creating, please pass the link.

Thanks!

**Comment by TomGardner** [comment]
Hello @bjornleffler any update on this?  I'm getting the same error for gcsfule-disco:
The repository 'http://packages.cloud.google.com/apt gcsfuse-disco Release' does not have a Release file.

**Comment by kebwi** [comment]
I need a fix for this asap. How do I get around it while waiting for an update?

**Comment by panthar1** [comment]
We also need a fix ASAP. Anyone have a way to resolve this, even if it's a temporary hack?

**Comment by andrew-grasso** [comment]
As a workaround to using the repository, you could just manually install the .deb file. From the instructions in https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/installing.md#older-releases-and-other-distributions (modified for the newer version 28):

```
curl -L -O https://github.com/GoogleCloudPlatform/gcsfuse/releases/download/v0.28.0/gcsfuse_0.28.0_amd64.deb
sudo dpkg --install gcsfuse_0.28.0_amd64.deb
```

**Comment by bjornleffler** [comment]
Still working out the permissions to create new repositories. The procedure changed.

Installing the .deb file, as andrew-grasso@ suggested, should work.

**Comment by bjornleffler** [comment]
This should be fixed. I can install gcsfuse on a Ubuntu 18 VM on GCE.
