### ISSUE TITLE
Error connecting to read only bucket

### ISSUE THREAD

**Issue by kylemcdonald** [GoogleCloudPlatform/gcsfuse#320]
My personal user account has read-only access to a bucket. When I run `gcsfuse -o ro <bucket name> <mount directory>` I get this error:

```
Using mount point: <mount directory>
Opening GCS connection...
Opening bucket...
daemonize.Run: readFromProcess: sub-process: mountWithArgs: mountWithConn: setUpBucket: OpenBucket: Bad credentials for bucket "<bucket name>". Check the bucket name and your credentials.
```

I'm sure that I am authorized and the bucket name is correct because I can run `gsutil ls gs://<bucket name>` or `gsutil cp gs://<bucket name>/<filename> .` and copy a file.

I am running these commands inside a GCE instance that is in a different cloud project than the bucket I am trying to access.

I tried to explicitly set my personal authorized key by adding `--key-file ~/.config/gcloud/legacy_credentials/<my email address>/adc.json` but the output is a different error:

```
...
Opening GCS connection...
daemonize.Run: readFromProcess: sub-process: mountWithArgs: getConn: newTokenSourceFromPath: JWTConfigFromJSON: google: read JWT from JSON credentials: 'type' field is "authorized_user" (expected "service_account")
```

I was able to use gcsfuse to mount a bucket in the same project that I have read/write access to.

I was not able to use gcsfuse to mount a bucket in another project that I have read/write access to. But when I created a read-only service account for that project, and passed that service account json to via `--key-file` I was able to successfully mount the other bucket.

So it seems the issue here is something about `gcsfuse` not correctly using my personal account that I authorized via `gcloud auth login`. `gsutil` seems to be using it correctly.

If I do something terrible and just modify the `adc.json` file to say `service_account` instead of `authorized_user` then `gcsfuse` completes but the directory doesn't really work:

```
$ gcsfuse -o ro --key-file ~/adc-modified.json <bucket name> <folder name>
Using mount point: <folder name>
Opening GCS connection...
Opening bucket...
Mounting file system...
File system has been successfully mounted.
$ ls <folder name>
ls: reading directory '<folder name>': Input/output error
```

Update: I was able to get a service account for this bucket from the same person who gave me access initially, but it would be better if I could use my personal account in the future.

**Comment by ej2catz** [comment]
I'd like to upvote this question...I am consuming a read-only bucket from an application that knows how to grant permission to my personal account but it would be non-trivial to grant to a service account

**Comment by ckpklos** [comment]
@kylemcdonald, @ej2catz Documentation is incomplete, you need to do:
`gcloud auth application-default login`
and login there with your personal account.
I had the same problem and found solution there https://github.com/GoogleCloudPlatform/gcsfuse/issues/277

**Comment by ej2catz** [comment]
@ckpklos Thank you!  I ultimately did figure that out but forgot to report back here

**Comment by avidullu** [comment]
Seems the issue has been fixed so closing this out.
Please feel free to reopen with latest logs if the issue still persists.

**Comment by rubber-ant** [comment]
facing the same issue:

```
sudo gcsfuse      --foreground  --log-format text --debug_fuse --debug_fs --debug_gcs --debug_mutex  --key-file '/home/bobb/.config/gcloud/application_default_credentials.json'   bob_bucket_test  /mnt/bucket/bob_bucket_test
2022/11/22 14:34:04.126354 Start gcsfuse/0.41.8 (Go version go1.18.4) for app "" using mount point: /mnt/bucket/bob_bucket_test
2022/11/22 14:34:04.126427 Opening GCS connection...
2022/11/22 14:34:04.126655 Waiting for connection: GetTokenSource: newTokenSourceFromPath: JWTConfigFromJSON: google: read JWT from JSON credentials: 'type' field is "authorized_user" (expected "service_account")
2022/11/22 14:34:05.127023 Waiting for connection: GetTokenSource: newTokenSourceFromPath: JWTConfigFromJSON: google: read JWT from JSON credentials: 'type' field is "authorized_user" (expected "service_account")
2022/11/22 14:34:06.627791 Waiting for connection: GetTokenSource: newTokenSourceFromPath: JWTConfigFromJSON: google: read JWT from JSON credentials: 'type' field is "authorized_user" (expected "service_account"
```

I can see the object with `bob` user:
```
gsutil ls gs://bob_bucket_test/hello1.txt
gs://bob_bucket_test/hello1.txt
```

```
$ gcsfuse -v
gcsfuse version 0.41.8 (Go version go1.18.4)
```

```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Codename:	focal
```
