### ISSUE TITLE
Good candidate to be used as rpm repo?

### ISSUE THREAD

**Issue by Zest-nikunj** [GoogleCloudPlatform/gcsfuse#321]
We are attempting to use gcsfuse to create a rpm repo in a VM. The idea is to mount a GCS bucket to the VM and use the bucket as a rpm repo. As part of the setup, we are running createrepo command on the mounted path,
command : createrepo /repo1/centos-rpms/

The command results in the below error:

Could not remove  temp metadata dir: .repodata
Error was [Errno 39] Directory not empty: '/repo1/centos-rpms/.repodata'
Please clean up this directory manually.
(process:23466): GLib-CRITICAL **: 07:08:15.440: g_timer_stop: assertion 'timer != NULL' failed
(process:23466): GLib-CRITICAL **: 07:08:15.441: g_timer_destroy: assertion 'timer != NULL' failed
Could not remove  temp metadata dir: .repodata
Error was [Errno 39] Directory not empty: '/repo1/centos-rpms/.repodata'
Please clean up this directory manually.
Traceback (most recent call last):
File "/usr/share/createrepo/genpkgmetadata.py", line 309, in <module>
main(sys.argv[1:])
File "/usr/share/createrepo/genpkgmetadata.py", line 274, in main
mdgen.doRepoMetadata()
File "/usr/lib/python2.7/site-packages/createrepo/__init__.py", line 1014, in doRepoMetadata
gen_func(complete_path, csum)
File "/usr/lib64/python2.7/site-packages/sqlitecachec.py", line 61, in getOtherdata
self.repoid))
TypeError: Can not create remove_changelogs trigger: disk I/O error

Any ideas what is going on here?

**Comment by fedordikarev** [comment]
Not a solution but workaround for that: we use `--outputdir` flag to store repodata locally and update it later using `gsutil -m rsync`:
```bash
$ mount -t fuse.s3fs
s3fs on /mnt/yum-repo-data type fuse.s3fs (rw,nosuid,nodev,relatime,user_id=0,group_id=0)
s3fs on /mnt/yum-repo-cache type fuse.s3fs (rw,nosuid,nodev,relatime,user_id=0,group_id=0)
$ createrepo --cachedir=/mnt/yum-repo-cache/ --update  --outputdir=/tmp/repo-out-s3 /mnt/yum-repo-data/aarch64/RPMS
```

**Comment by avidullu** [comment]
The release [https://github.com/GoogleCloudPlatform/gcsfuse/releases/](page) does show the availability of rpm repo.

Closing this out for now. If you think there is something missing please feel free to reopen/file a new issue.

**Comment by avidullu** [comment]
Reopened to debug more. This seems related to #539 and in general doing git clone in a gcsfuse mounted bucket is failing, even for very small repositories. Will investigate more.

**Comment by marcoa6** [comment]
Update: As of [version 2.1](https://github.com/GoogleCloudPlatform/gcsfuse/releases/tag/v2.1.0) on 23-May-2024, we now offers enhanced control over how GCSfuse responds to interruptions during file system operations.

You can configure GCSFuse to ignore interruptions during file system operations via CLI using **--ignore-interrupts** flag (disabled by default) or via config-file using the following config:
```
file-system:
    ignore-interrupts: true
```
    
Please try with this flag. Once we get enough feedback, we will enable this by default (targeting next month).

**Comment by marcoa6** [comment]
With GCSfuse [v2.3](https://github.com/GoogleCloudPlatform/gcsfuse/releases/tag/v2.3.0) this is now enabled by default. Thank you all for testing and providing feedback!
