### ISSUE TITLE
Consistent "Reader returned ... too few bytes" errors

### ISSUE THREAD

**Issue by oceanful** [GoogleCloudPlatform/gcsfuse#323]
We're using gcsfuse to serve image tiles from pyramidal tiffs, which involves performing many small range reads within the tiff file to understand the layout of each layer in the pyramid.

For certain images, we consistently encounter "Reader returned _n_ too few bytes" errors when reading at a certain offset:

```
fuse_debug: 2019/04/24 05:26:51.094251 Op 0x0000000b        connection.go:396] <- OpenFile (inode 2)
fuse_debug: 2019/04/24 05:26:51.094494 Op 0x0000000b        connection.go:479] -> OK ()
fuse_debug: 2019/04/24 05:26:51.094692 Op 0x0000000c        connection.go:396] <- ReadFile (inode 2, handle 1, offset 1074810880, 4096 bytes)
fuse_debug: 2019/04/24 05:26:51.436272 Op 0x0000000c        connection.go:479] -> OK ()
fuse_debug: 2019/04/24 05:26:51.436705 Op 0x0000000d        connection.go:396] <- ReadFile (inode 2, handle 1, offset 1077432320, 131072 bytes)
fuse_debug: 2019/04/24 05:26:51.754776 Op 0x0000000d        connection.go:479] -> OK ()
fuse_debug: 2019/04/24 05:26:51.755299 Op 0x0000000e        connection.go:396] <- ReadFile (inode 2, handle 1, offset 1077563392, 131072 bytes)
fuse_debug: 2019/04/24 05:26:51.769793 Op 0x0000000e        connection.go:479] -> OK ()

... Many reads later ...

fuse_debug: 2019/04/24 05:26:57.197816 Op 0x00000058        connection.go:396] <- ReadFile (inode 2, handle 1, offset 1404956672, 4096 bytes)
fuse_debug: 2019/04/24 05:26:57.198370 Op 0x00000058        connection.go:479] -> OK ()
fuse_debug: 2019/04/24 05:26:57.198638 Op 0x00000059        connection.go:396] <- ReadFile (inode 2, handle 1, offset 1404952576, 4096 bytes)
fuse_debug: 2019/04/24 05:26:57.431260 Op 0x00000059        connection.go:479] -> OK ()
fuse_debug: 2019/04/24 05:26:57.431448 Op 0x0000005a        connection.go:396] <- ReadFile (inode 2, handle 1, offset 1404960768, 4096 bytes)
fuse_debug: 2019/04/24 05:26:57.432431 Op 0x0000005a        connection.go:481] -> Error: "fh.reader.ReadAt: Reader returned 1037454 too few bytes"
fuse_debug: 2019/04/24 05:26:57.432933 Op 0x0000005b        connection.go:396] <- ReadFile (inode 2, handle 1, offset 1404960768, 4096 bytes)
fuse_debug: 2019/04/24 05:26:57.596907 Op 0x0000005b        connection.go:481] -> Error: "fh.reader.ReadAt: Reader returned 1045646 too few bytes"
```

However, a subsequent read at that offset (done when retrying the image request) always succeeds:

```
fuse_debug: 2019/04/24 05:38:49.046719 Op 0x00000066        connection.go:396] <- OpenFile (inode 2)
fuse_debug: 2019/04/24 05:38:49.046808 Op 0x00000066        connection.go:479] -> OK ()
fuse_debug: 2019/04/24 05:38:49.055250 Op 0x00000067        connection.go:396] <- ReadFile (inode 2, handle 3, offset 1404960768, 4096 bytes)
fuse_debug: 2019/04/24 05:38:49.507636 Op 0x00000067        connection.go:479] -> OK ()
```

The code suggests that the error is `err == io.EOF || err == io.ErrUnexpectedEOF`, but it consistently happens at the same offset and thus isn't a transient error.

Is there some kind of underlying rate limit that gets hit? (We run gcsfuse with the `--limit-ops-per-sec=40960`, and no other interesting options.)

Any other pointers on how to debug this would be appreciated. Thanks!

**Comment by oceanful** [comment]
If it's helpful, the corresponding debug_gcs logs for the failed read look like this:

```
gcs: 2019/04/24 04:54:18.412282 Req             0x13: <- Read("image.tif", [1404960768, 1406009344))
gcs: 2019/04/24 04:54:18.644512 Req             0x13: -> Read("image.tif", [1404960768, 1406009344)) (232.2245ms): OK
```

And the subsequent successful read looks like this:

```
gcs: 2019/04/24 05:01:35.817419 Req             0x16: <- Read("image.tif", [1404960768, 1404963698))
gcs: 2019/04/24 05:01:36.307977 Req             0x16: -> Read("image.tif", [1404960768, 1404963698)) (490.583ms): OK
```

One thing that's slightly curious (and perhaps a clue) is that the image file itself is 1404963698 bytes, and the failing reads are attempting to read 1MB from 1404960768, whereas there are only 2930 bytes left. Could this be a result of the optimization for sequential reads mentioned in the README? 

> gcsfuse uses a heuristic to detect when a file is being read sequentially, and will issue fewer, larger read requests to GCS in this case

**Comment by oceanful** [comment]
I'm new to the code, but in the sequential read optimization in `random_reader.go`, should the adjustment of `end` be capped to `int64(rr.object.Size)`? 

```golang
	end := int64(rr.object.Size)
	if rr.seeks >= minSeeksForRandom {
		averageReadBytes := rr.totalReadBytes / rr.seeks
		if averageReadBytes < maxReadSize {
			randomReadSize := int64(((averageReadBytes / MB) + 1 ) * MB)
			if randomReadSize < minReadSize {
			   randomReadSize = minReadSize
			}
			if randomReadSize > maxReadSize {
			   randomReadSize = maxReadSize
			}
			end = start + randomReadSize
		 }
	}
```

**Comment by jpsondag** [comment]
This commit sounds promising / related:

https://github.com/GoogleCloudPlatform/gcsfuse/commit/dd29ded9d409367594f41801f82a4af8e13dcb5e

**Comment by oceanful** [comment]
Great, thanks @bjornleffler !

I will confirm whether the issue is fixed when the v0.28.0 release is available at https://packages.cloud.google.com/apt/dists.

**Comment by oceanful** [comment]
Friendly ping @bjornleffler. What are the next steps to publish v0.28.0 as an official distro? Anything I can do to help?

**Comment by bjornleffler** [comment]
Oups, sorry for the late reply on this, I never got any notifications.

Yes, that checkin should fix that problem. Let me push version 0.28.0 to the distribution mechanisms.

**Comment by bjornleffler** [comment]
I'm going to ship this in the next few days. Just need to renew my permission to sign rpms with the Google certificate first.

**Comment by oceanful** [comment]
Thanks @bjornleffler. Much appreciated!

**Comment by bjornleffler** [comment]
I just pushed the signed binaries.
