### ISSUE TITLE
not able to mv folders (mv folder1 folder2) 

### ISSUE THREAD

**Issue by rajmeka** [GoogleCloudPlatform/gcsfuse#324]
When I try to run command "mv test1 test2" I am getting "mv: cannot move ‘test1’ to ‘test2’: Function not implemented"

**Comment by Batx** [comment]
same problem with us... Hope someone knows a solution...

**Comment by bjornleffler** [comment]
From the [semantics](https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/semantics.md) documentation:

Renaming directories is not supported. A directory rename cannot be performed atomically in GCS and would therefore be arbitrarily expensive in terms of GCS operations, and for large directories would have high probability of failure, leaving the two directories in an inconsistent state.
