### ISSUE TITLE
move within gcsfuse 

### ISSUE THREAD

**Issue by vivadevp** [GoogleCloudPlatform/gcsfuse#326]
Good Evening,

so basically `mv` from the XFS mount into the fuse mount is working. 

Our Issue is that within the fuse we cannot move files via the mv command… Below the console output:

(int-backup is the fuse mount)

[root@s500 /]# cd int-backup/

[root@s500 int-backup]# ls

filetest_1_1  filetest_3_4  test  test2.txt  testdirect  test.txt

[root@s500 int-backup]# mkdir moveddirectory

[root@s500 int-backup]# ls

filetest_1_1  filetest_3_4  moveddirectory  test  test2.txt  testdirect  test.txt

[root@s500 int-backup]# mv test2.txt testdirect/

[root@s500 int-backup]# mv moveddirectory testdirect/

mv: cannot move ‘moveddirectory’ to ‘testdirect/moveddirectory’: Function not implemented

[root@s500 int-backup]# mv testdirect/ /int-backup/moveddirectory/

mv: cannot move ‘testdirect/’ to ‘/int-backup/moveddirectory/testdirect’: Function not implemented

[root@s500 int-backup]#

Thank you in advance for your answers!

Regards!

**Comment by fuzihaofzh** [comment]
I also meet with this problem. How can it be solved? mv is a very common tool.

**Comment by bjornleffler** [comment]
From https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/semantics.md:

Renaming directories is not supported. A directory rename cannot be performed atomically in GCS and would therefore be arbitrarily expensive in terms of GCS operations, and for large directories would have high probability of failure, leaving the two directories in an inconsistent state.
