### ISSUE TITLE
Auto Mounting on startup via fstab appears to break the VM

### ISSUE THREAD

**Issue by markm00001** [GoogleCloudPlatform/gcsfuse#329]
As of gcsfuse 0.16.0, you should be able to do this:

```
my-bucket /mount/point gcsfuse rw,user,implicit_dirs
```

_Originally posted by @jacobsa in https://github.com/GoogleCloudPlatform/gcsfuse/issues/151#issuecomment-181198379_

**Comment by markm00001** [comment]
Hi I attempted the boot mount through fstab from the original post by jacobsa above with slight modification:

my-bucket /mount/point gcsfuse rw,user,gid=0,uid=0,implicit_dirs

After this I was unable to ssh into the VM and had to discard the VM altogether. Any thoughts on what might have gone wrong would be appreciated

Mark

**Comment by bjornleffler** [comment]
gcs buckets can only be mounted after networking is started. This is a problem when mounting gcsfuse with fstab on boot. The system essentially believes that a required hard drive is missing and refuses to boot.

If this is for a VM on GCE, you should see the relevant error messages in the system console log.

Please see the updated documentation here:
https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/mounting.md
