### ISSUE TITLE
True env var is ignored with GOOGLE_APPLICATION_CREDENTIALS

### ISSUE THREAD

**Issue by rayfoss** [GoogleCloudPlatform/gcsfuse#332]
```
$ gcsfuse --version
gcsfuse version 0.27.0 (Go version go1.12.1)
$ echo $GOOGLE_APPLICATION_CREDENTIALS
/opt/gcp.json
$ gcsfuse my-bucket /mnt2/testing
Using mount point: /mnt2/testing
Opening GCS connection...
daemonize.Run: readFromProcess: sub-process: mountWithArgs: getConn: DefaultTokenSource: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
```

Confusingly, `GOOGLE_APPLICATION_CREDENTIALS=/opt/gcs.json gcsfuse learn-video /mnt2/testing` works 

It seems there is some code looking for the env var in the command string? as opposed to the actual env.

**Comment by configurator** [comment]
Is `GOOGLE_APPLICATION_CREDENTIALS` exported?

If you just run in bash
```bash
PARAM=value
command
```
the `PARAM` is not passed to the command.

Instead, you must run:
```bash
export PARAM=value
command
```

**Comment by rayfoss** [comment]
The light of deno scripts has made weak. I wasn't born in shell scripts, I merely adopted them.

Thanks
