### ISSUE TITLE
mv file operations for CMEK buckets not supported

### ISSUE THREAD

**Issue by rsg98** [GoogleCloudPlatform/gcsfuse#336]
``mv file1 file2`` operations on CMEK (Customer Managed Encryption Key) buckets do not appear to be supported by the underlying Cloud KMS API.

```
gcs: 2019/06/28 13:08:15.640132 Req              0xd: -> CopyObject("testfile-1", "testfile-2") (120.514817ms): googleapi: Error 400: Operation with Cloud KMS is not supported., invalid
fuse_debug: 2019/06/28 13:08:15.640413 Op 0x00000037        connection.go:481] -> Error: "CloneToChildFile: googleapi: Error 400: Operation with Cloud KMS is not supported., invalid"
fuse: 2019/06/28 13:08:15.640510 *fuseops.RenameOp error: CloneToChildFile: googleapi: Error 400: Operation with Cloud KMS is not supported., invalid
```

Adding copy-then-delete-original logic to gcsfuse might be a hacky workaround?  (Although that would involve being able to detect CMEK buckets without a performance penalty for all non-CMEK buckets)

**Comment by sanjaytiwari18** [comment]
Hi any solved this issue yet? 
I can not read or create file after mounting bucket which is encrypted by CMEK

**Comment by bjornleffler** [comment]
CMEK isn't supported.

I've had a number of requests recently, so I'm going to look into it this week.

**Comment by bjornleffler** [comment]
Can you please try CMEK with version 0.31.0? Download from the release page.

Thanks,
Bjorn

**Comment by avidullu** [comment]
As recommended please download the latest version and retry.

**Comment by avidullu** [comment]
Closing this out due to inactivity. Please reopen or file new issue with logs and we'll be happy to investigate.
