### ISSUE TITLE
Device not configured errors when using mounted bucket

### ISSUE THREAD

**Issue by fonnesbeck** [GoogleCloudPlatform/gcsfuse#337]
I've been trying to use gcsfuse to mount buckets and access the files therein. However, I consistently get problems reliably accessing data. When mounting via:

    gcsfuse <bucket_name> <local_directory>

It appears to open the bucket and mount the file system. However, accessing one of the files with Python  ended up giving me the following:

    OSError: [Errno 6] Device not configured: '<file_name>'

When I go back to the shell and attempt to manipulate the directory (even `ls`) returns a `Device not configured` error.

Running 0.27.0 on macOS.

**Comment by fonnesbeck** [comment]
Any ideas here?

**Comment by avidullu** [comment]
Can you please retry with the latest version 0.40 and see if the issue still exists.

**Comment by avidullu** [comment]
Please retry with the latest release of gcsfuse 0.41 and report back if you still see the same issue.
