### ISSUE TITLE
apt packges for Ubuntu 19.04 (disco)

### ISSUE THREAD

**Issue by abotzki** [GoogleCloudPlatform/gcsfuse#344]
Hi,

As far as I see there are no apt packages for ubuntu 19.04 on https://packages.cloud.google.com/apt/dists. 

Would it be possible to add them?

Thanks a lot.

**Comment by ftrotter** [comment]
Perhaps this could be merged with my issue to support 20.04
https://github.com/GoogleCloudPlatform/gcsfuse/issues/391

Into a "support Ubuntu" ticket?

**Comment by bjornleffler** [comment]
Let me push a new build this week. I've been lazy in building new .deb packages, since there haven't been any major changes recently.

**Comment by bjornleffler** [comment]
This is fixed for Ubuntu 20, but we didn't create a repository for Ubuntu 19, which is "eoan".

I don't have the permissions to create new repositories, so I asked another team to do it.

**Comment by bjornleffler** [comment]
This should be fixed. I can install gcsfuse on a Ubuntu 19 VM.
