### ISSUE TITLE
debian 10 buster repo

### ISSUE THREAD

**Issue by sherkhonovc8** [GoogleCloudPlatform/gcsfuse#348]
Debian buster is now stable, can we possibly have a repo for it?

**Comment by Lord-Y** [comment]
Any news?

**Comment by bjornleffler** [comment]
Great idea. Let me look into how to set this up.

**Comment by gallacci** [comment]
Also needs the gcsfuse on buster! Any news?

**Comment by Lord-Y** [comment]
@bjornleffler let us down :-( . I also talk to I also talk to some Google people at my work and they don't know who can make it

**Comment by bjornleffler** [comment]
Sorry for the radio silence. I've been out of the office for a while.

Working on this. Need to create the new buster repo.

**Comment by dubcl** [comment]
Hi, any update?, Cheers.

**Comment by bjornleffler** [comment]
I don't have the credentials to create the new repository, so I've asked a different team to do that.

**Comment by bjornleffler** [comment]
We created a buster repository, that uses the same binary as the ones released for stretch. Please give it a try.

Until there is some kind of breaking change in buster, we will only have one binary release for all Debian releases.

**Comment by Lord-Y** [comment]
Thx @bjornleffler , it's working 👍

**Comment by dubcl** [comment]
Confirmed, work perfect, thanks @bjornleffler
