### ISSUE TITLE
gcsfuse hangs when trying to list files in the bucket

### ISSUE THREAD

**Issue by sridhar** [GoogleCloudPlatform/gcsfuse#349]
I have mounted my by storage bucket using the following command:
$gcsfuse --implicit-dirs --foreground --debug_fuse GCS_bucket GCS_mount_point/

Both the VM accessing it and the storage buckets are in the same region. (which is why I'm using --implicit-dirs, as I understand there there is no cost of access).

I noticed that for directories with lesser files, the access was very slow, and 'ls' just hangs if the directory contains large number of files. The following is printed on the foreground when ls is being run:
```
...
use_debug: 2019/08/23 15:31:31.667767 Op 0x00000137        connection.go:481] -> Error: "no such file or directory"
fuse_debug: 2019/08/23 15:31:31.667898 Op 0x00000138        connection.go:396] <- LookUpInode (parent 1, name "x86_64")
fuse_debug: 2019/08/23 15:31:31.681053 Op 0x00000138        connection.go:481] -> Error: "no such file or directory"
fuse_debug: 2019/08/23 15:31:31.681224 Op 0x00000139        connection.go:396] <- LookUpInode (parent 1, name "x86_64")
fuse_debug: 2019/08/23 15:31:31.694115 Op 0x00000139        connection.go:481] -> Error: "no such file or directory"
fuse_debug: 2019/08/23 15:31:31.694280 Op 0x0000013a        connection.go:396] <- LookUpInode (parent 1, name "x86_64")
fuse_debug: 2019/08/23 15:31:31.707285 Op 0x0000013a        connection.go:481] -> Error: "no such file or directory"
fuse_debug: 2019/08/23 15:31:31.707408 Op 0x0000013b        connection.go:396] <- LookUpInode (parent 1, name "x86_64")
fuse_debug: 2019/08/23 15:31:31.721139 Op 0x0000013b        connection.go:481] -> Error: "no such file or directory"
fuse_debug: 2019/08/23 15:31:31.721282 Op 0x0000013c        connection.go:396] <- LookUpInode (parent 1, name "avx512_1")
...
```

My directory doesn't have these files (infact, it only has 2 subdirectories).

**Comment by dougcouvillion** [comment]
I'm having similar issues running gsfuse in a Vagrant VM for development purposes.  The VM is Centos 7.

My bucket has a large number of subdirectories.  When I run `ls` it hangs.

If I try to access a file within a subdirectory of the mount point it frequently hangs or produces an error saying the object doesn't exist.  If I then `cd` into the subdirectory I can access the object.

**Comment by joebarrero** [comment]
I'm experiencing the same issue within an increasing number of times that I need to umount -f and reconnect.

**Comment by jay-efx** [comment]
me too.. I am having the same issue.

**Comment by mc-zact** [comment]
Having a similar issue with docker (kubernets) the directories mounted with GCS fuse hang on ls/cd; usually "restarting" pods that are affected by this fixes it but it comes back often.

**Comment by avidullu** [comment]
There have been [recent improvements](https://github.com/GoogleCloudPlatform/gcsfuse/pull/651/commits/5da5be1f8c97a1dae19053d06437e3457d17ad6f) in the listing of large directories and also other changes to improve the throughput between GCS and GCSFuse.

Since this issue is old and many commenters, I'll hope someone gets back with some responses and will keep this open till then.

Please try to build from source and let us know if you still encounter this issue.

**Comment by mc-zact** [comment]
We've been dealing with this with a cron job that remounts GCS fuse on hanged states (basically tries to do a ls every 5 mins, if hanged we remount, I will see If we can test without the scripts but since the hangs were somewhat random, might take a while to confirm.

**Comment by avidullu** [comment]
Thanks @mc-zact for the quick turnaround! 
Will really appreciate if you could let us know that this is still an issue after improvement via #652

**Comment by avidullu** [comment]
Please retry with the latest release 0.41 and you should see measurable improvements in the listing performance for large directories. 
Feel free to reopen this or open a new issue for us to investigate more.
Thanks for the help in making gcsfuse better!

**Comment by mc-zact** [comment]
Sorry I didn't have much time to properly test this, but I can say that looking at logs it does seem that the hang state has not been happening for the last few weeks, so this is either fixed or we got lucky :)

**Comment by avidullu** [comment]
I'll take that as a sign that things have improved to your satisfaction :)
Will keep this issue closed. Please reopen this or a new one in case you hit a similar wall.
Thanks for the prompt responses in helping us improve gcsfuse!
