### ISSUE TITLE
Error Mounting buckets on Mac OS

### ISSUE THREAD

**Issue by kanghq** [GoogleCloudPlatform/gcsfuse#351]
osxfuse 3.0.12
gcsfuse:0.28.1 (Go version go1.12.7)
Mac OS:10.14.5

Trying to mount the google storage bucket but return an ambiguous error.
gcsfuse bucket-name /mnt/dsstorage/

Using mount point: /mnt/dsstorage
Opening GCS connection...
Opening bucket...
Mounting file system...
daemonize.Run: readFromProcess: sub-process: mountWithArgs: mountWithConn: Mount: newConnection: Init: Reading init op: EOF

**Comment by kanghq** [comment]
problem solved by changing the owner of the mount point.
Would you please make the error message more helpful?
It's hard to debug now.

**Comment by avidullu** [comment]
Closing the issue since @kanghq commented that it was resolved.Thanks for reporting the issue and the resolution for the benefit of others in the community!
