### ISSUE TITLE
 project on arm architecture does not build

### ISSUE THREAD

**Issue by Samoha94** [GoogleCloudPlatform/gcsfuse#354]
I have raspberry, trying to build gcsfuse, but the compiler writes :  

"# github.com/googlecloudplatform/gcsfuse/vendor/github.com/jacobsa/fuse/internal/buffer
vendor / github.com / jacobsa / fuse / internal / buffer / runtime.go: 24: 6: missing function body
vendor / github.com / jacobsa / fuse / internal / buffer / runtime.go: 29: 6: missing function body
"

**Comment by GAZ082** [comment]
Hi @Samoha94 , why did you close the issue, found a solution? I'm in the same spot you were.
