### ISSUE TITLE
Dont list all folders in bucket

### ISSUE THREAD

**Issue by Arthur290680** [GoogleCloudPlatform/gcsfuse#356]
I have a bucket with 5 folders and when I mounted with gcsfuse only showed me 3 folders!

I was following this:

https://cloud.google.com/storage/docs/gcs-fuse

**Comment by bjornleffler** [comment]
Are the directories empty? If so, you need to use "Implicit directories".

See the semantics document for more details.
https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/semantics.md

**Comment by mikegleasonjr** [comment]
Thanks this was the issue for me when uploading artifacts from cloud builder, it wouldn't see the directories created.
