### ISSUE TITLE
Fails to Close file on SFTP Server after upload

### ISSUE THREAD

**Issue by yuvraj2987** [GoogleCloudPlatform/gcsfuse#357]
I have setup sftp server in Kubernetes based on [mikeghen/kubernetes-gcs-sftp](https://github.com/mikeghen/kubernetes-gcs-sftp) project. The server is mounting user's sub directories using gcsfuse with Chroot as described in this issue (https://github.com/GoogleCloudPlatform/gcsfuse/issues/345).

It used to work fine. But recently upload have started getting error while closing the file.
`sftp> ls -ltr
sftp> put README .
Uploading README to /inbox/./README
README                                                                                                     100%   29     0.1KB/s   00:00
Couldn't close file: Failure
sftp>`

I tried to run strace on the running process and got following output
![image](https://user-images.githubusercontent.com/4722567/67981042-00b95180-fbdd-11e9-8d50-d5b0c6bf776a.png)

any ideas why sftp is failing to close the file?

I even tried to simulate the file upload using [gsutil](https://cloud.google.com/storage/docs/gsutil) with the service-account. There weren't any issue while running
`
gsutil cp test1 gs://mounted-bucket/
`
So not an issue with account permissions

**Comment by bjornleffler** [comment]
Thanks for reporting this. I'll have a look.

**Comment by brookemckim** [comment]
Seeing the same issue. Let me know what more debug output I can provide.

**Comment by brookemckim** [comment]
`sftp -f <server>`

Connecting with the -f flag seems to fix the issue

```
  -f      Requests that files be flushed to disk immediately after trans‐
             fer.  When uploading files, this feature is only enabled if the
             server implements the "fsync@openssh.com" extension.
```

**Comment by torbjornvatn** [comment]
@bjornleffler Any news on this issue, I'm also getting this

**Comment by jindrichskupa** [comment]
Check retention policy on bucket. The sftp/fuse doesn't work with retention turned on.

**Comment by sethiay** [comment]
We highly recommend using [Cloud Storage FUSE CSI driver](https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/cloud-storage-fuse-csi-driver) for mounting with gcsfuse on GKE/K8s.
Please let us know if that works for you. And feel free to open issue under [Cloud Storage FUSE CSI driver repo](https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/issues) if you face any issues related to the driver.
