### ISSUE TITLE
gcsfuse failing to mount buckets

### ISSUE THREAD

**Issue by jessewebb** [GoogleCloudPlatform/gcsfuse#360]
It seems google APIs forces SSL, but gcsfuse still uses HTTP. Now gcsfuse won't mount a bucket.

```
gcsfuse --foreground --debug_gcs --debug_http test-bucket /opt/media
```

Output:
```
Using mount point: /opt/media
Opening GCS connection...

WARNING: gcsfuse invoked as root. This will cause all files to be owned by
root. If this is not what you intended, invoke gcsfuse as the user that will
be interacting with the file system.

Opening bucket...
gcs: 2019/11/14 19:20:56.410523 Req              0x0: <- ListObjects()
http: ========== REQUEST:
GET http://www.googleapis.com/storage/v1/b/gs-test-bucket/o?maxResults=1&projection=full HTTP/1.1
Host: www.googleapis.com
User-Agent: gcsfuse/0.0
Authorization: Bearer ------
Accept-Encoding: gzip

gcs: 2019/11/14 19:20:56.847904 Req              0x0: -> ListObjects() (437.3799ms): Get https://www.googleapis.com/storage/v1/b/gs-test-bucket/o?maxResults=1&projection=full: DumpResponse: stream error: stream ID 1; PROTOCOL_ERROR
gcs: 2019/11/14 19:20:56.848198 Req              0x1: <- ListObjects()

```

**Comment by jessewebb** [comment]
I tried the same request in Postman to:  
http://www.googleapis.com/storage/v1/b/gs-test-bucket/o?maxResults=1&projection=full

It gives the response:
`SSL is required to perform this operation.`

Using `https` instead works properly.

**Comment by jtownley** [comment]
gcsfuse just stopped working for me today in multiple environments.

**Comment by jessewebb** [comment]
Maybe this problem isn't related to HTTP/HTTPS? Maybe it doesn't use HTTP, but does in fact use HTTPS, even though it prints HTTP?

Early in the output, it prints `"GET http://www.googleapis.com"` but then later it prints `"Get https://www.googleapis.com"`.

Also, if you run the command without the `--debug_http` flag, it prints the response code of "400":
```
googleapi: got HTTP response code 400
```
But when I try to hit the API in Postman with HTTP, it responds 403.

Regardless, gcsfuse is failing to mount to any bucket for me, and the error message seem unhelpful and misleading.

**Comment by jessewebb** [comment]
We figured out a solution. We were using a docker image based off of alpine:3.5 with golang 1.7.3 installed using apk. Once we upgraded to alpine:3.10 and installed golang 1.12, gcsfuse started working again!
