### ISSUE TITLE
GCSfuse and kubernetes conflict

### ISSUE THREAD

**Issue by brcoghe** [GoogleCloudPlatform/gcsfuse#366]
I'm running a flask application that serves an ML model that loads in a wordembeddings file (2GB) on k8s. This file is being loaded with gcsfuse and we have the application running for about 2 years.

Since a recent restart of the pod, this setup is not working anymore while nothing has changed in our code/deployment settings. While debugging, I notice that we even have the problem with the following dockerfile that does not even use the python script:

`Dockerfile:

FROM levkuznetsov/gcsfuse-docker
RUN apt-get update && apt-get install -y \
    build-essential
COPY . /app
WORKDIR /app
RUN /bin/bash -c "mkdir -p /app/wordembeddingtest"
COPY ./serviceacc.json /
ADD /serviceacc.json /etc/gcloud/serviceacc.json
ADD /serviceacc.json /etc/gcloud/service-account.json
EXPOSE 8080
ENTRYPOINT  ["/bin/bash", "-c", "gcsfuse bucket_name wordembeddingtest ; ls wordembeddingtest"]
`

What is even more strange, is that we have other deployments that use the same set-up, and they can be restarted and still work..

The logs show the following error:

![image](https://user-images.githubusercontent.com/40390679/70619375-365a4d00-1c15-11ea-8034-6d23638c478d.png)

And with --foreground --debug_invariants --debug_http --debug_gcs --debug_fuse we get the following:
![image](https://user-images.githubusercontent.com/40390679/70619277-fa26ec80-1c14-11ea-9e76-d02bfd2a9676.png)

![image](https://user-images.githubusercontent.com/40390679/70619533-7faa9c80-1c15-11ea-9c65-d99638d5eaa1.png)

What I have checked so far:

Service account permissions are ok

What I have tried so far:

1. Different storage bucket
2. gcsfuse command with Implicit-dirs, -o allow_other
3. Different kubernetes cluster
4. Other mount folder locations

This issue seems to be related to issue #357 which also suddenly started occuring since beginning of november..

**Comment by brcoghe** [comment]
As extra info, the garbage collector also fails with the same DumpResponse error..

**Comment by sethiay** [comment]
We highly recommend using [Cloud Storage FUSE CSI driver](https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/cloud-storage-fuse-csi-driver) for mounting with gcsfuse on GKE/K8s. 
Please let us know if that works for you. And feel free to open issue under [Cloud Storage FUSE CSI driver repo](https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/issues) if you face any issues related to the driver.
