### ISSUE TITLE
Bucket lifcycle rules can delete intermediate directories

### ISSUE THREAD

**Issue by neuroid** [GoogleCloudPlatform/gcsfuse#368]
Hi,

Enabling a bucket lifecycle rule which deletes objects older than X can delete intermediate directories, leaving files inaccessible. I'm guessing that switching to `--implicit-dirs` would solve this. However, perhaps gcsfuse could offer an option to create directory objects with a temporary hold, or different storage class.

**Comment by bjornleffler** [comment]
That's an interesting question, no one has ever asked me about gcsfuse and lifecycle before.

Have you tried this? --implicit-dirs will probably solve the problem, since it does an additional lookup. Bucket lifecycle is effectively just another client that manipulates the same gcs bucket.

**Comment by avidullu** [comment]
As recommended --implicit-dirs is the right way to approach this issue.
Please let us know if that doesn't work for you.
