### ISSUE TITLE
File system-related commands hang while writing a large file

### ISSUE THREAD

**Issue by jacobsa** [GoogleCloudPlatform/gcsfuse#37]
User report:

>  when copying files with cp to a mounted bucket, all other commands hang
> (e.g. df -h), until the file is not entirely copied.

This is probably due to #23; confirm when that is fixed. This probably should not require setting `GOMAXPROCS` greater than one, assuming the Go scheduler doesn't starve goroutines. I could be wrong.

**Comment by jacobsa** [comment]
Now that #23 is fixed, I can't reproduce this at 39ee09c543d255dc64daf6a5fcad07a364c88277. Will ask user for instructions to reproduce.

**Comment by jacobsa** [comment]
@trollius: Can you update from HEAD and see if you've still got the issue? If so, please provide detailed instructions on what you do to reproduce it. Thanks!

**Comment by trollius** [comment]
@jacobsa 
we tested and all looks good! we simultaneously copied 2 files (5Gb each) into the same bucket and there were no hanging of system commands during this copying process

**Comment by jacobsa** [comment]
@trollius: Great! For my curiosity: did you happen to record performance numbers when you tested?
