### ISSUE TITLE
Credential problems not reported during initial mount

### ISSUE THREAD

**Issue by jamesob** [GoogleCloudPlatform/gcsfuse#370]
I run gcsfuse after authenticating via `gcloud auth login`, which appears to work without issue:

```
Sat 28 13:58 james/src/Miser master* (622e33b)
$ gcsfuse mybucket ~/mnt/mybucket

Using mount point: /home/james/mnt/mybucket
Opening GCS connection...
Opening bucket...
Mounting file system...
File system has been successfully mounted.
```

But then when I go to use the filesystem, I get this nondescript error:

```
(127) Sat 28 13:59 james/src/Miser master* (622e33b)
$ touch ~/mnt/mybucket/hello

touch: cannot touch '/home/james/mnt/mybucket/hello': Input/output error
```

I then run gcsfuse in the foreground with debugging to find that there's an apparent issue with my credentials:

```
$ gcsfuse --foreground --debug_gcs mybucket ~/mnt/mybucket

Using mount point: /home/james/mnt/mybucket
Opening GCS connection...
Opening bucket...
gcs: 2019/12/28 14:05:41.934565 Req              0x0: <- ListObjects()
gcs: 2019/12/28 14:05:42.185403 Req              0x0: -> ListObjects() (250.809262ms): Get https://www.googleapis.com/storage/v1/b/mybucket/o?maxResults=1&projection=full: oauth2: cannot fetch token: 400 Bad Request
Response: {
  "error": "invalid_grant",
  "error_description": "Bad Request"
}
...
```

I fixed the issue by running `gcloud auth application-default login`, which I guess creates a local .json file with the credentials.

Is there some way you could detect the 400 Bad Request response after initialization and report an error?

Possibly related: https://github.com/GoogleCloudPlatform/gcsfuse/issues/313

**Comment by bjornleffler** [comment]
Thanks for reporting this. I'll have a look when I'm back at the office.

**Comment by lezh** [comment]
After v0.33.2 this issue would be surfaced as "Permission denied".
