### ISSUE TITLE
mv command crashing with gcsfuse

### ISSUE THREAD

**Issue by nmatrai** [GoogleCloudPlatform/gcsfuse#374]
Hi

There seems to be an issue with gcsfuse when using the 'mv' command. I am mounting a bucket in a GCP instance using a startup-script, but when I try to transfer a log file to the bucket using mv command after a long time the system crashes and wont go forward with the script. 
However it works perfectly by using copy+delete (cp to bucket, rm from original folder)

Any clue on that?

**Comment by justindujardin** [comment]
@nmatrai moving files in/out of the mount is an unsupported operation. Sorry, I don't know why, but it's part of the test suite: https://github.com/GoogleCloudPlatform/gcsfuse/blob/6ab0a79f97b7481b23c3724cd0c4b323f0627d69/internal/fs/local_modifications_test.go#L2438-L2470

**Comment by matty111** [comment]
Does the Problem still exists ? 

I tried now and mv operation in a filesystem mounted with gcsfuse works

**Comment by lezh** [comment]
Cross-device mv is not supported intentionally because gcsfuse should not make modifications outside  its own file system.
