### ISSUE TITLE
gcsfuse crashes when LFTP service tries to write a file.

### ISSUE THREAD

**Issue by usama-masood** [GoogleCloudPlatform/gcsfuse#375]
LFTP is installed on a gcloud VM in dev environment. It is working fine.

When same thing is replicated in another VM QA environment. It started behaving weird.

`lftp sftp://cdint-qa:"password"@server.com  -e "set sftp:auto-confirm yes;  mirror --verbose --delete /cdint-qa/SFTP-Egress/Sales ~/gcsBucket/GCP-Ingress/Sales ;  bye"`

I tried copying files to local directory of VM
`lftp sftp://cdint-qa:"password"@server.com  -e "set sftp:auto-confirm yes;  mirror --verbose --delete /cdint-qa/SFTP-Egress/Sales ~/`

It worked fine and then I copied them to GCP storage:
`cp -r Sales/ ~/gcsBucket/GCP-Ingress/Sales`

Files were copied to GCP.

But direct copy to mounted `~/gcsBucket` hangs the output and ssh session breaks.

On ssh again. I figured out that `~/gcsBucket` is unmounted

**Comment by usama-masood** [comment]
Update: It also breaks the mounted path.

On again SSH, I had to remount the path before doing anything.

**Comment by avidullu** [comment]
Could you please share some logs for the operations you were doing?
Running gcsfuse with --foreground,  --log-file, --debug_fuse, --debug_fs, --debug_gcs should definitely give us enough information to understand what is happening.
