### ISSUE TITLE
VM Crushes when Jupyter Lab save files to the mounted drive via gcsfuse

### ISSUE THREAD

**Issue by edwin-yan** [GoogleCloudPlatform/gcsfuse#376]
**My Current Set Up:**
I created a script in rc.local that automatically mount google storage bucket to my VM in Google Compute Engine. Then, it sets the mounted drive as working directory and launches Jupyter Lab. My set up is very convenient, because other users can just get my output from Google Storage. It worked great in the past 2-3 years.

**Issue:**
However, around few days ago, VM freezes and automatically reboots everytime when I try to save a file (text/notebook/etc.) in Jupyter Lab to the mounted drive.

**Troubleshoot Procedure:**
The VM first had issue uses Intel Cascade Lake platform (n2-highmem). I downgraded it to old CPU platform (n1-highmem), and still have the issue.

I own another VM with the same set up, but it has not been use for few months, so I can guarantee that VM hasn't change anything recently. It worked fine originally. Since this VM is in east region while my another VM is in west region. I originally though it is because of the region in GCP. Then, I did sudo apt-get upgrade on the 2nd VM. After reboot, same issue now. 

**Update 1:**  I upgraded to the latest release 0.29 (which is not available in APT-GET yet). Still the same issue. VM crushes and reboots when Jupyter Lab try to save the file

**Update 2:**  I downgraded old release 0.23, still no luck. Now I am wondering if this may be caused by any other packages/dependencies. 

**Update 3:**  Created a new VM based on the hard drive snapshot made on May 2019. Everything works. Any suggestions on the further steps I can take to figure out what caused the issue. 

_The version of few packages_
gcsfuse:  both are 0.23 (Go 1.9) now
fusermount: both are 2.9.7 now
Google Cloud SDK: 277.0.0 vs 239.0.0 (snapshot)
bq: 2.0.52 vs 2.0.42 (snapshot)
core: 2020.01.17 vs 2019.03.17  (snapshot)
gsutil: 4.47 vs 4.39 (snapshot)

PS: I personally feel my issue is similar to the another open issue: https://github.com/GoogleCloudPlatform/gcsfuse/issues/372

**Comment by Dmitry1987** [comment]
wow I plan to use this in jupyter as well... sounds bad

**Comment by Bluesn0w** [comment]
Well, let's put that way. It worked great in the past 2 years. It is very convenient because the files can be shared to someone else via Google Storage easily. The Implicit directories may not work (too slow), so you need to create the folder in VM not the other way around. Other than that, it is really convenient. However, I am not quite sure what is breaking it now, so I am trying to get some help here.

**Comment by Hitobat** [comment]
I get a similar problem. Could it be some API is changed?

**Comment by Bluesn0w** [comment]
I have left my prior company, so I don't know if has been resolved or not. Before I left, I made a temporary solution. I increased the size of SSD on the VM, then I copied all of the files over. Last, I set up a syncing process to sync the files to GCS every hour. Not ideal but works.

**Comment by Hitobat** [comment]
I found that manually if I mv a file from hard disk to GCSfuse it will crash. But cp will work fine.
I don't know the solution relating to Jupyter Lab, but for my own case I now avoid all mv command.

**Comment by nikuzz** [comment]
I think it's something related to Linux kernel 5
I test it in Ubuntu on GCP installing only the deb package, no more no less: https://github.com/GoogleCloudPlatform/gcsfuse/releases/download/v0.29.0/gcsfuse_0.29.0_amd64.deb

Ubuntu 18.04 LTS (ubuntu-1804-bionic-v20200317 image, 5.0.0-1033-gcp #34-Ubuntu SMP Tue Mar 3 04:36:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux), crash on "mv" / editing with "vi"
Ubuntu 16.04 LTS (ubuntu-1604-xenial-v20200317 image, 4.15.0-1058-gcp #62-Ubuntu SMP Mon Mar 2 05:29:31 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux), no problems

**Comment by Bluesn0w** [comment]
@nikuzz Thanks for sharing! It's likily cased by the new Linux kernel. I am no longer with my prior company. My new company uses Azure instead, so I am not able to verify that any more. I will leave the issue open until it is solved then. Glad to hear that you found it works on kernel 4.

**Comment by nikuzz** [comment]
With version 0.32 on Ubuntu 20.04.1 LTS (GNU/Linux 5.4.0-1032-gcp x86_64) seems that there is no problems.

**Comment by lezh** [comment]
Close due to no update recorded.
