### ISSUE TITLE
build on arm, raspbian

### ISSUE THREAD

**Issue by Samoha94** [GoogleCloudPlatform/gcsfuse#378]
I have raspberry, trying to build gcsfuse, but the compiler writes :

"# github.com/googlecloudplatform/gcsfuse/vendor/github.com/jacobsa/fuse/internal/buffer
vendor / github.com / jacobsa / fuse / internal / buffer / runtime.go: 24: 6: missing function body
vendor / github.com / jacobsa / fuse / internal / buffer / runtime.go: 29: 6: missing function body
"

**Comment by rogerherger** [comment]
Similar problem here: tried to build from source for arm on rasbperry using go as described in [installing.md](https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/installing.md), but failed. Folder 'v2' does no longer exist in https://github.com/cpuguy83/go-md2man/

**Comment by gaul** [comment]
Can you share more about your configuration?  Using a Raspberry Pi 4 and Debian 10.0 with Go 1.16.2 I successfully ran:

```
go install -mod=readonly
```

**Comment by avidullu** [comment]
Could you share about the configuration used? Also retry with the latest repo release and 1.16+ version of go as @gaul recommends worked for them.

**Comment by avidullu** [comment]
Closing out due to inactivity and a suggested fix.
