### ISSUE TITLE
cannot read files if the folder is uploaded

### ISSUE THREAD

**Issue by kylefoley76** [GoogleCloudPlatform/gcsfuse#380]
In the following screen shot, what appears on the top half is an image of how my google console appears.  As you can see, there is a folder there named `fix_mistakes`.  In the bottom half, you can see in the terminal that the storage bucket successfully mounted and all of the folders and files appear after typing the command `ls` with the exception of the folder `fix_mistakes`.  This is because I uploaded the folder and its files by pressing the button in console.cloud.google.com `upload_folder`.  When I create the folder with console.cloud.google.com, then upload files into the folder I can read the files on terminal.  I have a feeling that this is not what the programmers intended.
<img width="564" alt="Screen Shot 2020-02-06 at 3 20 31 AM" src="https://user-images.githubusercontent.com/16620676/73933763-06849a00-4892-11ea-9fec-b2ae24ca25b9.png">

**Comment by richp10** [comment]
@kylefoley76 - did you find a solution to this, I am having the same problem.

**Comment by richp10** [comment]
@kylefoley76 run with --implicit-dirs fixes this..

**Comment by bjornleffler** [comment]
Please see the semantics documentation for a full explanation.
https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/semantics.md
