### ISSUE TITLE
Dependency resolution error when building from a tag

### ISSUE THREAD

**Issue by lwrobel1** [GoogleCloudPlatform/gcsfuse#382]
e.g.
`go get -u -ldflags "-X main.gcsfuseVersion=v0.29.0" github.com/googlecloudplatform/gcsfuse@v0.29.0`

results in:

`go: github.com/googlecloudplatform/gcsfuse imports
        github.com/codegangsta/cli: github.com/codegangsta/cli@v1.22.3: parsing go.mod:
        module declares its path as: github.com/urfave/cli
                but was required as: github.com/codegangsta/cli`

Repo of dependency in question has been moved. Issue doesn't occur when building from HEAD (without @v0.29.0)

**Comment by bjornleffler** [comment]
Thanks for reporting this. I've been meaning to clean up the dependencies.

**Comment by lezh** [comment]
No longer an issue.

**Comment by parasavelli** [comment]
I still see the issue while trying to install on Mac.

$go get -u github.com/Masterminds/glide
go: downloading github.com/Masterminds/glide v0.13.3
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: downloading gopkg.in/yaml.v2 v2.4.0
go: downloading github.com/Masterminds/semver v1.5.0
go: downloading github.com/Masterminds/vcs v1.13.1
go: downloading github.com/codegangsta/cli v1.22.5
go get: github.com/codegangsta/cli@none updating to
	github.com/codegangsta/cli@v1.22.5: parsing go.mod:
	module declares its path as: github.com/urfave/cli
	        but was required as: github.com/codegangsta/cli

**Comment by kapad** [comment]
> I still see the issue while trying to install on Mac.
> 
> $go get -u github.com/Masterminds/glide
> go: downloading github.com/Masterminds/glide v0.13.3
> go: downloading github.com/mitchellh/go-homedir v1.1.0
> go: downloading gopkg.in/yaml.v2 v2.4.0
> go: downloading github.com/Masterminds/semver v1.5.0
> go: downloading github.com/Masterminds/vcs v1.13.1
> go: downloading github.com/codegangsta/cli v1.22.5
> go get: github.com/codegangsta/cli@none updating to
> github.com/codegangsta/cli@v1.22.5: parsing go.mod:
> module declares its path as: github.com/urfave/cli
> but was required as: github.com/codegangsta/cli

Do you have any workaround for this issue? I'm also facing the same problem when running make bootstrap for a rather old version of helm.
