### ISSUE TITLE
Please add instructions for mounting storage buckets without write access 

### ISSUE THREAD

**Issue by ftrotter** [GoogleCloudPlatform/gcsfuse#384]
I would like to prevent write access using gcfuse mounted directory. 

It would be helpful for the mounting instructions to completely cover how to get the local file system permissions to work and interact with the access control system in google storage. 

I do not need the answer in response to this issue, the answer should be a permanent part of the documentation as a indication that this type of functionality is supported by this project.

Regards,
-FT

**Comment by sandes** [comment]
it's clear. Using **--file-mode** & **--dir-mode**
