### ISSUE TITLE
ListObject behaviour and ls

### ISSUE THREAD

**Issue by sadortun** [GoogleCloudPlatform/gcsfuse#387]
Hello Guys,

I am having a very simple problem, and i am not sure if its a bug, or a normal behaviour.

```
/usr/local/bin/gcsfuse --stat-cache-ttl 1h --type-cache-ttl 1h --stat-cache-capacity 10000 --debug_http --implicit-dirs --foreground --uid 100 --gid 101 -o allow_other -file-mode=666 -dir-mode=777 --only-dir mnt my_bucket /mnt/bucket  |grep -E  "GET|PUT|PATCH|POST"
```

Then  performing multiple `ls /mnt/bucket/a/b/c/d/e/f/` (every few seconds, and the folder tree exist)

## Expected behaviour
1. The first `ls` generate all needed requests to retreive the objects in the directory
2. Starting at the second `ls`  inodes are cached, and either no requests are made, or a single request is made to lookup for folder `f/`

## Current behaviour
All `ls` generate 25+ requests.

Is it normal ? Is there a way to reduce the number of requests ?

Ref https://github.com/jacobsa/gcloud/blob/master/gcs/gcscaching/fast_stat_bucket.go#L224

Thanks,
Samuel

/cc @jacobsa

**Comment by kumowoon1025** [comment]
Depends mostly on your shell and how it globs/completes and the actual directory structure of your bucket, e.g. are those actual existing directories or do you have a file named a/b/c/d/e/f? Or b/c/d/e/f in directory a? etc. etc.

>Is it normal ? Is there a way to reduce the number of requests ?

I think it is expected with `--implicit-dirs` and just how directory structure is realized in the very abstract form gcs takes.
