### ISSUE TITLE
Please support Ubuntu 20.04

### ISSUE THREAD

**Issue by ftrotter** [GoogleCloudPlatform/gcsfuse#391]
The lsb_release -c -s command returns: 
focal

which does not seem to work... so the Ubuntu install fails...

-FT

**Comment by bjornleffler** [comment]
Let me push a new build this week. I've been lazy in building new .deb packages, since there haven't been any major changes recently.

**Comment by hmoravec** [comment]
@bjornleffler Any updates on this?

**Comment by jpnarkinsky** [comment]
Likewise.

**Comment by bjornleffler** [comment]
Oups, I added this to my todo list, but never got to it.

The current Debian release seems to be 'buster', for which I have published .deb files. Why isn't Ubuntu 20 picking that up? I thought Ubuntu would just pick up the .deb files from Debian. I don't think we've ever published .deb files specifically for Ubuntu.

**Comment by bjornleffler** [comment]
As a workaround, just download and install the .deb file.

I only build a single .deb release file and send that to all repositories. Once the Ubuntu 20 repository is available (I've requested the creation, but don't have the privilege to create it myself), it will have the same .deb file.

**Comment by bjornleffler** [comment]
We've created the new repo. Installing on Ubuntu 20 works for my test VM on GCE.

root@ubuntu20:~# apt-get install gcsfuse
...
Get:1 http://packages.cloud.google.com/apt gcsfuse-focal/main amd64 gcsfuse amd64 0.28.1 [4274 kB]
...
