### ISSUE TITLE
gcs fuse with CMEK encrypted bucket 

### ISSUE THREAD

**Issue by sanjaytiwari18** [GoogleCloudPlatform/gcsfuse#392]
Hi,
Any operation in bucket which is CMEK encrypted is giving following error :+1: 
ls: reading directory  .: Input/output error 
I have created .boto file in my home with encryption_key value but still same issue.
@jacobsa  have you merged following pull request with original package : 
https://github.com/jacobsa/gcloud/pull/10 

I am working on CentOS and using following base url mentioned in documents : 

baseurl=https://packages.cloud.google.com/yum/repos/gcsfuse-el7-x86_64

**Comment by WahyuMW** [comment]
I'm using CSEK to the some object in my bucket and I get error when try to ls it : 
 `gcs.NotFoundError: googleapi: Error 404: No such object: my-bucket`.
I can ls objects that are not encrypted. I already set encryption_key in /etc/boto.cfg. Does this problem also apply to CSEK ?

**Comment by bjornleffler** [comment]
CSEK isn't supported by GCS Fuse at the moment.

I think the solution is to upgrade the GCS client to use the public golang gcs SDK.

**Comment by bjornleffler** [comment]
Can you please try CMEK with version 0.31.0? Download from the release page.

Thanks,
Bjorn

**Comment by surabhianan** [comment]
@bjornleffler I could not find the version 0.31.0 anywhere in the google cloud website for any flavor of gcsfuse(binary-amd64)-
https://packages.cloud.google.com/apt/dists/

The latest I could find is 0.30.0 as of today -
https://packages.cloud.google.com/apt/dists/gcsfuse-artful/main/binary-amd64/Packages

So does this version supports Listing object (or using ls command) for CMEK encrypted buckets ?
My issue is I can persist data or even read content of specific file but not use "ls" command for CMEK bucket.

**Comment by bjornleffler** [comment]
Please download the binaries here:
https://github.com/GoogleCloudPlatform/gcsfuse/releases/tag/v0.31.0

The new release has a lot of changes, so I haven't pushed it to the repositories as the current release yet.

**Comment by surabhianan** [comment]
Thanks @bjornleffler for blazing fast reply... It might be hard to access this api from restricted space(behaviour of project) . But i have one request that will this version resolve issue of error while Listing objects from the bucket (using ls command) ? I get input/output error .

**Comment by bjornleffler** [comment]
I haven't had the time to test this myself and I've never used CMEK.

I was told that CMEK support could be added if the supporting modules were updated. I just updated all the modules, so there's a chance that it works now.

**Comment by dmilan77** [comment]
Does CMEK encryption work with 0.31 release ?

**Comment by yeahydq** [comment]
i try with 0.3.1 version, still didn't work for the CMEK

**Comment by veerahemannthnag** [comment]
Hi , I'm also receiving same erorr. Could not list objects for CMEK encrypted buckets.

**Comment by lezh** [comment]
The support for CMEK encrypted bucket was introduced in v0.32.0.
Please upgrade to [v0.33.2](https://github.com/GoogleCloudPlatform/gcsfuse/releases/tag/v0.33.2).
