### ISSUE TITLE
[Question] How does gcsfuse handle concurrent access?

### ISSUE THREAD

**Issue by theCalcaholic** [GoogleCloudPlatform/gcsfuse#399]
The documentation for gsutil states, that concurrency in GCS needs to be handled by the client/application:

https://cloud.google.com/storage/docs/gsutil/addlhelp/ObjectVersioningandConcurrencyControl#concurrency-control

I'm wondering whether or not this is this taken care of in the implementation of gcsfuse, since I didn't find anything in the docs regarding this topic? If so, how is the behaviour of gcsfuse considering concurrent access to a gcs object?

In any case, thanks for this super useful tool!

**Comment by bjornleffler** [comment]
gcsfuse has some optimisations to handle concurrent reads to the same file. That's about it. Anything else needs to be handled by the application.
