### ISSUE TITLE
Fusermount's is not working as expected with multiple mounts

### ISSUE THREAD

**Issue by chethanuk** [GoogleCloudPlatform/gcsfuse#404]
K8s pods stuck at `Terminating` because unmounting of multiple folders is not working properly..

Stuck at `Stopping container gcsfuse`

```bash
until fusermount -u $MULTIPLE_MOUNT
```

**Comment by sethiay** [comment]
We highly recommend using [Cloud Storage FUSE CSI driver](https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/cloud-storage-fuse-csi-driver) for mounting with gcsfuse on GKE/K8s. And feel free to open issue under [Cloud Storage FUSE CSI driver repo](https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/issues) if you face any issues related to the driver.
