### ISSUE TITLE
Ghetto google3

### ISSUE THREAD

**Issue by dhanna11** [GoogleCloudPlatform/gcsfuse#406]
Say an enterprising x-google intern missed his dev environment and wanted to prototype using this + bazel for a more productive development environment at his new company.

Is gcsfuse appropriate for this use case? Or would something like Filestore/NFS be more appropriate?

Thanks.

**Comment by bjornleffler** [comment]
I wouldn't recommend gcsfuse for active development. Compiling would probably be very slow.

Filestore would work fine. But so would local disk with a (git) repository in a safe place.
