### ISSUE TITLE
Cannot access data of a bucket mounted on an instance.

### ISSUE THREAD

**Issue by shristishreya1276** [GoogleCloudPlatform/gcsfuse#409]
Hi,
I was using aws and spacenet dataset before which I transferred to Google Cloud using "Data Transfer Service" [here.](https://console.cloud.google.com/transfer/cloud/config?project=footprint-280609&authuser=1) Now, when I tried to mount the bucket on top of my VM instance then I cannot see the data when I do `ls` on that directory. It shows me the size occupied by the mounted bucket is zero which is not possible as when I check the bucket storage in the google cloud console, it clearly shows me the data.
The problem can be due to the fact that data transferred to bucket by means other than mounting on an VM instance (and writing on that mounted partition) then it can have trouble showing the data. 

I however, tried to mount with the following  `--implicit-dirs` flag and I wasn't even able to `ls` into the mounted directory. It showed me `ls: Input/Output Error.`
Finally, I thought to use the aws CLI to directly download the data inside the mounted directory but I was hit with another error this time and it was 
`cannot open path of the working directory: Permission denied`.

Is there some way for me to access the data already transferred using the "Data Transfer Service" or if that's not possible then how can I get around the error of using AWS CLI (mentioned in the previous paragraph) to download data directly onto the mounted disk. Keep in mind that this dataset is about ~100GBs.

**Comment by bjornleffler** [comment]
This sounds like a GCS permission problem.

Does the VM have GCS permissions? Can you "gsutil ls" the bucket from the VM?

**Comment by lezh** [comment]
You may provide gcsfuse with a service account key file using `--key-file`. The service account must enable the scope of GCS access.
