### ISSUE TITLE
Support interrupt requests from fuse

### ISSUE THREAD

**Issue by jacobsa** [GoogleCloudPlatform/gcsfuse#41]
If you start a very large copy into a mounted bucket with `cp`, kill it, then attempt to Ctrl-C the gcsfuse process, it will refuse to unmount if it made it to the `Flush` stage because it the request is still in progress. You simply have to wait for it to finish, or take more drastic measures.

However, on OS X and Linux an `Interrupt` request does come through. We just respond `ENOSYS` to it. So we need to plumb through support for cancelling the associated context when this is received, and set up the GCS package to pay attention to cancelled contexts (probably using `http.Transport.CancelRequest`). Test the latter by starting large uploads and downloads, cancelling them, and timing the duration until the bucket returns in error.

**Comment by trollius** [comment]
I guess it is related to the issue I filed:) - sorry if it pretty much a duplicate:
https://github.com/GoogleCloudPlatform/gcsfuse/issues/42

**Comment by jacobsa** [comment]
@trollius: No worries, I appreciate the report either way. Would rather have duplicates than miss something.

**Comment by jacobsa** [comment]
Testing plan:

* Create samples/interruptfs.
  * Has a single file as its contents.
  * ReadFileOp blocks until cancelled.
  * Advertises method to wait for a read to be in progress.
  * Test spawns commands that read from a file, waits for them to be in progress, then kills them.

**Comment by jacobsa** [comment]
Still to do: GCS support, as in the original comment.

**Comment by jacobsa** [comment]
As far as I can tell, this works well.
