### ISSUE TITLE
FR: Access GCS from K8s Persistent Volume

### ISSUE THREAD

**Issue by rmgogogo** [GoogleCloudPlatform/gcsfuse#413]
NFS (Filestore) allows it.
https://cloud.google.com/filestore/docs/accessing-fileshares

Is it possible we provide similar solution for GCS? 

Reason:
1. Current gcsfuse solution requires special permission. 
2. It also requires user container to have the gcsfuse binary.

Related ticket.
https://github.com/GoogleCloudPlatform/gcsfuse/issues/328

**Comment by lezh** [comment]
Yes. This can be achieved by CSI. 
You may refer to https://github.com/ofek/csi-gcs/ which already implements a CSI driver using gcsfuse.
