### ISSUE TITLE
Interrupt copying with ctrl+c

### ISSUE THREAD

**Issue by trollius** [GoogleCloudPlatform/gcsfuse#42]
a) if we do ctrl+c during copying of a file into a bucket (interrupt/cancel -cp command), then copying is not immediately cancelled (-cp still copies the file). Our guess is that when we do ctrl+c for -cp, gcsfuse will start copying of the data into a bucket which it has already put into gcsproxy.temp_dir. So, it seems that with ctrl+c we interrupt copying of files into gcsproxy.temp_dir, but the next step of copying (from  gcsproxy.temp_dir into a bucket ) stays uninterrupted. 
b) the example above results in gcsproxy.temp_dir being uncleaned, unlike for un-interrupted copying (i.e. when we didn't try to stop the process with ctrl+c)

**Comment by jacobsa** [comment]
As you saw, I believe this is due to #42. Will leave this open to confirm afterward.

Are you sure about b) above (the temporary directory not being cleaned up)? Does it get cleaned up after the uninterruptible flush eventually completes? Once you kill the gcsfuse process?

**Comment by jacobsa** [comment]
@trollius: I believe this is fixed now. Please update with `go get -u` and confirm.
