### ISSUE TITLE
Connection started going really slow

### ISSUE THREAD

**Issue by fireseal199** [GoogleCloudPlatform/gcsfuse#420]
This used to work just fine but in the last two weeks it has been noticed that the connection seems to have slowed down significantly. Performing ls -l takes around 10 minutes. There are about 4000 files in that folder totaling about 250GiB. Performing the same command in Cloud Shell takes seconds.

The gcsfuse is mounted through fstab with: gcsbucketname /localfolder/gcsbucketname gcsfuse rw,noauto,allow_other,nosuid,nodev,relatime,user_id=11111,group_id=111,default_permissions

user_id and group_id changed to all 1's.

The mount is on a GCE VM and the storage bucket is a coldline bucket.

**Comment by bjornleffler** [comment]
This is not expected. Have you tried rebooting the VM? Have you tried on a different VM?

**Comment by co60ca** [comment]
We ran into this a lot. If you increase the ops/second beyond 5 is the issue resolved?

https://github.com/GoogleCloudPlatform/gcsfuse#rate-limiting

> If you would like to rate limit traffic to/from GCS in order to set limits on your GCS spending on behalf of gcsfuse, you can do so:
> 
> The flag --limit-ops-per-sec controls the rate at which gcsfuse will send requests to GCS.
> The flag --limit-bytes-per-sec controls the egress bandwidth from gcsfuse to GCS.
> All rate limiting is approximate, and is performed over an 8-hour window. By default, requests are limited to 5 per second. There is no limit applied to bandwidth by default.

`ls` on most systems I've seen will actually run `ls -l` which will also statx, and getxattr the files as it goes through. Therefore, for each file it will use at least two operations. In fstab you do this via `limit_ops_per_sec=1000`.

**Comment by avidullu** [comment]
There have been recent improvements in the APIs used by GCSFuse to list large directories from GCS and also the number of connections which improve throughput.
Could you please repeat this with the latest version (preferrably built at master) and get back to us if the listing still takes a much longer time?

**Comment by avidullu** [comment]
Please retry this with the latest release (0.41) of gcsfuse which has improved the performance of large directory listing.
Feel free to reopen this issue or file a new one with some bucket and timing numbers for us to investigate.
Thanks for helping improve gcsfuse.
