### ISSUE TITLE
Slow and out of sync problem (cache problem?)

### ISSUE THREAD

**Issue by i2dcarrasco** [GoogleCloudPlatform/gcsfuse#421]
Hello,

I'm trying to migrate a Magento 2 to GKE, but is not prepared for stateless systems. To solve this problem I'm trying to mount some folders using gcfuse to be shared across all magento fronts.

I know that mounted filesystems are slow, so for solve this problem I've configured my Nginx to ask first to the storage and only ask to Magento if doesn't exists. For example, when a cache file doesn't exists, then the nginx asks for that file to Magento, that creates the file on mounted paths and then file should exists in following requests. Doesn't work 100% because Nginx sometimes returns the storage 404 error instead to ask to Magento, but that doesn't cares right now.

My problem is that mounted filesystem is really slow, and looks like even is not caching the filelist, because on every ls takes a long time to return the files. With this porblem, the magento instance works really slow and of course is not production ready.

Also another problem I've seen, is that some files were written to FS and exists when I list the files with ls, but those files are not in bucket, so every time I try to open those files, then the nginx asks to Magento again.

Is there any way to speed up the filesystem?.

I want this because an NFS pod is not the best for an HA system.

Thanks!

**Comment by bjornleffler** [comment]
(I've never heard of Magento 2 before. I assume it's some kind of web serving stack under the hood?)

So you have Nginx (an http proxy) that is backed by a gcs fuse "file system", which in turn is backed by GCS? Could you make nginx talk directly to GCS?

Maybe using something like this project?
https://github.com/daichirata/gcsproxy

**Comment by avidullu** [comment]
Labelling this with pending customer action since a workaround has been proposed.
(Pending customer action issues are closed after 2 weeks of inactivity.)
