### ISSUE TITLE
Error mounting bucket with 0.31

### ISSUE THREAD

**Issue by neyz** [GoogleCloudPlatform/gcsfuse#424]
Since 0.31 came out our projects using gcsfuse built from sources can't mount buckets :

 Exec lifecycle hook ([gcsfuse --key-file /root/secret/key.json -o allow_other,nonempty,rw --uid 33 --gid 33 xxxx /var/www/html/web/uploads]) for Container "xxxx-api-develop" in Pod "xxxx-api-develop-5694d6d65c-q5p8q_dev(fbe997c4-ccd0-11ea-b864-42010a840013)" failed - error: command 'gcsfuse --key-file /root/secret/key.json -o allow_other,nonempty,rw --uid 33 --gid 33 xxxx /var/www/html/web/uploads' exited with 1: daemonize.Run: readFromProcess: sub-process: mountWithArgs: mountWithConn: Mount: mount: invalid argument
, message: "Using mount point: /var/www/html/web/uploads\nOpening GCS connection...\nOpening bucket...\nMounting file system...\ndaemonize.Run: readFromProcess: sub-process: mountWithArgs: mountWithConn: Mount: mount: invalid argument\n

The mount arguments have not changed, it had been working for months

**Comment by VengefulAncient** [comment]
Thank you for posting this, I was about to do so myself.

We just ran into exactly the same issue. I worked around this by removing `-o allow_other,nonempty` (we didn't use `rw`, just these two), and luckily this happened on staging first. It seems like any `-o` option breaks it now.

**Comment by VengefulAncient** [comment]
Strange: I just ran `gcsfuse --version` on the affected containers and it claims to still be `0.29.0`. But the breakage definitely started happening only today after some of our containers with `gcsfuse` got rebuilt. Could it be that the breaking change somehow got backported?

**Comment by neyz** [comment]
i was building using a really simple "go get" command which always takes the latest release to then copy the binary file into my main container.

i then tried building by forcing the version like "go get -u github.com/googlecloudplatform/gcsfuse@v0.30.0" but that didn't work.

as a workaround i went back to installing the .deb version of 0.30 and all is fine now

**Comment by arankine-as** [comment]
We are also seeing this issue.

**Comment by bjornleffler** [comment]
Thanks for reporting this. The 0.31 version has major changes. That's the reason why I haven't published the release files yet, other than the ones you can download from the github web page.

**Comment by bjornleffler** [comment]
@arankine-as @neyz @VengefulAncient 
Which versions of golang are you using?

**Comment by bjornleffler** [comment]
I cannot reproduce any of the reported problems:
- I've built from head with various versions of golang: [1.15.x - 1.10.x] all worked. 1.9.7 has build problems, which is why I upgraded the build version of golang.
- "golang --version" always reports "gcsfuse version unknown (Go version ...)" when building from source.
- "golang --version" reports the correct version for 
- I tried the options "allow_other,nonempty,rw", but that didn't matter.
- Fuse on debian required the "user_allow_other" option in /etc/fuse.conf.

What Linux distributions are you using? I tried all this on Debian 9.

**Comment by sshrdp** [comment]
Also it would be also helpful to know what Linux version you're using?

**Comment by VengefulAncient** [comment]
Alpine 3.11 (docker container on GKE). Go 1.14.3, building from source. `gcsfuse` version was supposed to be pinned to 0.29.0 but apparently that was ignored.

**Comment by lbt05** [comment]
I got the same issue in docker. I tried to install from source for 3 versions: v0.31.0 , v0.30.0 and v0.29.0, but get the same error 
```
daemonize.Run: readFromProcess: sub-process: mountWithArgs: mountWithConn: Mount: mount: invalid argument
```

**Comment by rikkegammelmark** [comment]
Same issue here on Alpine. We get gcsfuse from go get, so the latest version. We resolved the issue by remove `-o nonempty`.

**Comment by JoshuaDeanEssium** [comment]
Same issue. was anyone able to fix it? removing options fails as well

**Comment by lezh** [comment]
I tested the latest version. Did not see any issue like this.

Ubuntu: 18.04
Gcsfuse: gcsfuse version 0.32.0 (Go version go1.15.3)

```
$ echo "user_allow_other" | sudo tee -a /etc/fuse.conf
user_allow_other

$ gcsfuse -o allow_other,nonempty,rw --uid 33 --gid 33 --implicit-dirs ~/gcs
Using mount point: /home/lezh/gcs
Opening GCS connection...
Mounting file system...
File system has been successfully mounted.
```

**Comment by lezh** [comment]
Version 0.31 and later contains [this change](https://github.com/jacobsa/fuse/commit/b6e2754edfa8ac864bd26efe8541ebf2ee6563eb) in a dependency library, which upgrades the `fusermount` to `fusermount3` when the latter is available. 

The options used by `fusermount` and `fusermount3` are different. Option `nonempty` is supported by `fusermount`, but not `fusermount3`. So, when the OS has `fusermount3` installed and `nonempty` used, the mounting will fail.

Simple fix: Remove `nonempty` when upgrading `gcsfuse` to v0.31 or later.

**Comment by manoadamro** [comment]
This just happened today out of nowhere, having been using it with no problems for weeks then suddenlt, this error.
