### ISSUE TITLE
Loading latency

### ISSUE THREAD

**Issue by victorca25** [GoogleCloudPlatform/gcsfuse#425]
I want to use a bucket as the static content directory for a Wordpress site ('wp-content/uploads'). 

Everything works fine with gcsfuse, except that when loading a page with more than a couple images, it takes a long time to "fetch" and show them. For example, this happens in the Admin media gallery and the front page, where images appear to be loading in groups of 6, before each waiting cycle. Opening individual posts with one to three images works fine.

I can't find specific documentation on that behaviour, so I wonder if it's expected.  Is there any recommendation on how to reduce the waiting times? This is a single instance WP, with a single VM that will be using the bucket as mount point.

**Comment by bjornleffler** [comment]
How many files are in the directory? What's a "long time"?

**Comment by victorca25** [comment]
The full directory has 80k files and it takes about 10 seconds to load each group of six images. When there's a single image (let's say, a blog post), there's no waiting time.

**Comment by bjornleffler** [comment]
I would strongly discourage anyone from having 80k files in a single directory, even on a regular file system. GCS fuse is much slower than a regular file system for metadata operations, such as listing files.

I would suggest trimming the directory if the content is transient. Or organising the 80k files into sub directories.

**Comment by victorca25** [comment]
Yes, that's the total of files in the directory/share, but they are sorted in directories using Wordpress' default, they are divided by year and by month per year, each subdirectory contains at most around 600 files and the smallest one 32 files.

**Comment by lezh** [comment]
https://github.com/GoogleCloudPlatform/gcsfuse/pull/412
might have solved this issue.
