### ISSUE TITLE
Issues with GCSFuse when GCP Instance is Resumed

### ISSUE THREAD

**Issue by agosto-lorinronken** [GoogleCloudPlatform/gcsfuse#426]
Hello,

I first want to apologize if this is a duplicate ticket.  I was not able to find anything similar on current open/closed issues but maybe I missed something.

I am using GCS Fuse on a GCP Ubuntu Instance to automount a GCS Bucket on boot.  Everything works as expected with no current issues.  I am handling the automount with an entry in `/etc/fstab`.  Lately, we have been experimenting with a beta GCP feature allowing you to `suspend` a GCP instance.  More documentation on this can be found [here](https://cloud.google.com/compute/docs/instances/suspend-resume-instance).  

Essentially, the suspend is storing state into memory and powering off the VM -- to my understanding this is very similar behavior to how a traditional PC would be put in hibernate or sleep mode.

The problem I encounter is when I resume the instance from `suspend` after its been suspended for at least 15+ minutes, the mount point gives me the following error when I attempt to interact with the directory: 
```
ls: reading directory '.': Input/output error
```
I suspect this issue is due to the fact then when the GCP Instance is put as `suspended`, network access is shut off which caused the GCS Fuse Mount point to break.  If I run a `sudo mount -a` the problem persists.  The only way I have found to fix this is to umount/remount the bucket or reboot the machine.

Does anyone have any thoughts on this particular issues or ways I could resolve it?  Just as a side note, my `/etc/fstab` entry can be found below:
```
gcs-bucket /mount/point gcsfuse rw,_netdev,allow_other,implicit_dirs
```

Let me if you need any additional information.

Thank you!

**Comment by bjornleffler** [comment]
Thanks for reporting this. It sounds like the network connection is broken.

**Comment by agosto-lorinronken** [comment]
For the time being I just wrote a `.bash_login` script and placed it in `/etc/skel` so that all users receive it.  All the script does is unmount the bucket and remounts it at login.  This works for now as I also have a `.bash_logout` script that suspends the users workstations when they log out of it (thus disconnecting the network).  If anyone has any better ideas however please let me know!

**Comment by bjornleffler** [comment]
Thanks for the update. GCS Fuse should detect and fix this. I'll look into it.

**Comment by sethiay** [comment]
@agosto-lorinronken You can try adding `_netdev` option to the gcsfuse mount entry in `/etc/fstab` file. That waits for the network devices to start before attempting to mount gcsfuse. See [troubleshooting doc](https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/troubleshooting.md) for more details and issues.
