### ISSUE TITLE
directories disappear when using gsutil mv

### ISSUE THREAD

**Issue by sniklaus** [GoogleCloudPlatform/gcsfuse#430]
I was just moving a directory using `gsutil mv gs://my_bucket/oldprefix gs://my_bucket/newprefix` and gcsfuse does not show the new directory with the name `newprefix`. I can `mkdir newprefix && cd newprefix && ls` just fine but now it does not show any subdirectories. I first have to `mkdir` each folder once before I am able to access it again (the files in it are preserved, and all folders show correctly in the GCP webinterface). Unfortunately, my directory has thousands of subdirectories so my data is essentially inaccessible using gcsfuse now. Any advice? Thanks!

**Comment by lezh** [comment]
Have you tried `--implicit-dirs`?

**Comment by sniklaus** [comment]
I think so if I remember correctly, without luck. I am afraid that I am unable to test this again though since I have stopped using GCP altogether, my apologies.

**Comment by lezh** [comment]
I can't reproduce this. The best practice is to avoid renaming directories as it's not atomic and can get arbitrarily expensive.
