### ISSUE TITLE
Error connection to Bucket

### ISSUE THREAD

**Issue by manik-jindal** [GoogleCloudPlatform/gcsfuse#458]
When trying to mount the bucket to my local folder using the command gcsfuse --key-file "path-to-key"  "bucket-name"  "path-where-to-mount"
**Giving this error**
Using mount point: <mount directory>
Opening GCS connection...
Opening bucket...
daemonize.Run: readFromProcess: sub-process: mountWithArgs getConnection:DefaultTokenSource: google: couldnot find DefaultCredentials

**Comment by manik-jindal** [comment]
I am also using the same key file which I have generated from the Google Cloud Platform

**Comment by lezh** [comment]
Which gcsfuse version?

**Comment by manik-jindal** [comment]
gcsfuse version 0.32.0 (Go version go1.15.3)

**Comment by lezh** [comment]
I could not reproduce the issue. It works perfectly in my case
```
gcsfuse --implicit-dirs --key-file=$HOME/keys/my-key.json ~/gcs
```

**Comment by manik-jindal** [comment]
okay

**Comment by lezh** [comment]
No further action needed.
