### ISSUE TITLE
Mount cross project GCS in GCE

### ISSUE THREAD

**Issue by Zhanglin2017** [GoogleCloudPlatform/gcsfuse#459]
Hi there,

I'm trying to mount a GCS from another project and get this error.
`Opening GCS connection...
daemonize.Run: readFromProcess: sub-process: mountWithArgs: mountWithConn: fs.NewServer: SetUpBucket: OpenBucket: Unknown bucket "gs://xxxxxxxx"`

Probably, permission and API part is not a problem. Since I can browse and download files from that bucket through gsutil command. 

Any help is appreciated.

**Comment by lezh** [comment]
What version are you using? What's the command and arguments that trigger the error?
The bucket name should not contain "gs://".

**Comment by Zhanglin2017** [comment]
@lezh My bad. I tried the one without "gs://" and it worked.
