### ISSUE TITLE
Setting GCSFUSE to automount doesn't seem to write /etc/fstab

### ISSUE THREAD

**Issue by theCrius** [GoogleCloudPlatform/gcsfuse#464]
Hi there,

first time using this tool so bear with me if I'm doing something stupid.
A colleague of mine was experimenting with it but gave up after being unable to figure out how to do this. I stepped in and I must say I'm confused as well.

I've a bucket set up. I've a VM with a shared directory so that everyone can access it if it has an user on the VM. The VM service account has `full access` to the Storage APIs.

Following the documentation here: https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/mounting.md

What I tried has been:
- Login with my user
- `gcsfuse my-storage-bucket /my/path/`
- Checking that I can access the content. All good.
- `fusermount -u /my/path` to unmount it
- Check that it was unmounted. All good.

Then I decided to set it up so I could have this VM automatically mount the bucket.

- Login with my user
- `/sbin/mount.gcsfuse` which asked me 2 params to work.
- `/sbin/mount.gcsfuse my-storage-bucket /my/path/`. Success.
- Checking `/etc/fstab` but no new line was there.

Maybe I am mistaken but I expected to see something there as the following lines of the readme says:

`On both OS X and Linux, you can also add entries to your /etc/fstab file like the following`

The syntax of that command is not really clear compared to the readme as well. Looking around online it seems you can specify some options with the flag `-o` but the full list of options seems to escape me. Is there a reference somewhere that I'm missing?

Also mention of this syntax for example: `my-bucket /mount/point gcsfuse rw,noauto,user` don't seems to be matching anything I can read in the mounting.md file to be honest.

`/sbin/mount.gcsfuse` expect 2 parameters and that one has 3 even if you consider using the `rw,noauto,user` after the `-o` flag.

Can someone clarify or point toward a more detailed documentation? I'm willing to help update that readme after that as well.

**Comment by andrew-grasso** [comment]
The line you're referencing from the documentation `my-bucket /mount/point gcsfuse rw,noauto,user` is a literal example of a line that you could add to fstab, not a command to update fstab. Once that line is in fstab, mount will reference fstab to mount the filesystem at boot, or by simply running the mount command against the specified mount point:  `mount /mount/point`

Hopefully that helps.

**Comment by theCrius** [comment]
Thank you @andrew-grasso, I'll try that in the next days.
I got a little cautious as the first time that I followed that path, the fstab file got corrupted. Luckily I had an image of the disk prior to that change.

**Comment by andrew-grasso** [comment]
@theCrius - Now that you mention it, I do remember running into issues where the system would fail to boot when mounting a gcsfuse filesystem from fstab. I just took a look at the config I'm using and noticed that I have included the `_netdev` option to make sure that the gcsfuse filesystem doesn't try to mount before networking comes up. (More info here: https://man7.org/linux/man-pages/man8/mount.8.html) 

My full fstab line, with all my options looks like this:

`my-gcs-bucket-name /var/local/my-mount-point gcsfuse rw,_netdev,allow_other,uid=123,gid=126,file_mode=0660,dir_mode=0775,temp_dir=/var/local/local-disk/gcsfuse-spool`

It should all be on one line, although it may wrap here. The allow_other, uid, and gid options allow for custom mount permissions. More info on that here: https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/mounting.md#access-permissions

**Comment by theCrius** [comment]
Thank you so much for the further details Andrew, I have quite a bit of fires to put out in these days and didn't have the time to go back to gcfuse :)

**Comment by theCrius** [comment]
Resurrecting this as I finally managed to get back to it.

What I've tried now is:

- Run `/sbin/mount.gcsfuse my-bucket-name /my/mounting/point/`
- Response from the command:
```
Calling gcsfuse with arguments: my-bucket-name /my/mounting/point/
2021/05/17 11:18:21.854993 Using mount point: /my/mounting/point
2021/05/17 11:18:21.864591 Opening GCS connection...
2021/05/17 11:18:22.124373 Mounting file system "my-bucket-name"...
2021/05/17 11:18:22.131325 File system has been successfully mounted.
```

Now I was expecting to see a new line in `/etc/fstab` but there are the same previous two lines:

```
# /etc/fstab: static file system information
UUID=ece608be-d123-4838-8ffb-ddd0a9d4bfd5 / ext4 rw,discard,errors=remount-ro,x-systemd.growfs 0 1
UUID=C5BB-3D66 /boot/efi vfat defaults 0 0
```

Last time, when I corrupted the fstab file, I tried adding a line manually, something alone the line of 

```
my-gcs-bucket-name /var/local/my-mount-point gcsfuse rw,_netdev,allow_other,uid=123,gid=126,file_mode=0660,dir_mode=0775,temp_dir=/var/local/local-disk/gcsfuse-spool
```

As @andrew-grasso suggested but, as I said, that break the fstab file.
System is a freshly created Debian 10.x with only gcsfuse added via apt-get. It seems like I need to have a UUID of sort specified but most of all I don't understand why nothing is being written in the fstab file.
