### ISSUE TITLE
GCSFuse Cross-Project

### ISSUE THREAD

**Issue by daniels1996** [GoogleCloudPlatform/gcsfuse#465]
Currently trying to setup GCSFuse cross projects and am unable to mount to the bucket.
Context:
There is a Service Account in GCP with 'Owner' Permissions for the project with the Storage Bucket. There is a SEPARATE project for all of our K8s where I have created an IAM-Policy-Binding between the k8's service account for the namespace and the previously mentioned SA for the project. I have also annotated the K8s service account with:
`iam.gke.io/gcp-service-account=<name of storage bucket SA>.iam.gserviceaccount.com`

This setup allowed me to successfully mount the bucket in a Sandbox Project where the k8s and bucket were in the same project. Now, however, I am unable to replicate in our Dev environment.

I AM able to gsutil copy and remove items from the bucket in the current setup cross-project, but I am unable to mount.

Error Code:
```
`Opening GCS connection...
Opening bucket...
Mounting file system...
daemonize.Run: readFromProcess: sub-process: mountWithArgs: mountWithConn: Mount: mount: running fusermount: exit status 1

stderr:
fusermount: fuse device not found, try 'modprobe fuse' first`
```

Any help would be greatly appreciated, thank you!

**Comment by lezh** [comment]
The error message indicates that `fuse` is not available. 

Did you have the fuse device mounted in the container? Something like this in the pod spec
```
      volumes:
      - hostPath:
          path: /dev/fuse
        name: fuse-device
```

Meanwhile, did you set the security context of the container? Something like this in the container spec:
```
        securityContext:
          privileged: true
```

**Comment by lezh** [comment]
Close due to no update.
