### ISSUE TITLE
File operations fail with Input/output error

### ISSUE THREAD

**Issue by JunchengL** [GoogleCloudPlatform/gcsfuse#466]
Hello all,

I have used gcsfuse to mount a bucket on a GCE instance (centos 7 system). There are some people send files to my bucket by using some cloud functions. And I can directly take these files in my GCE instance with gcsfuse mount. 

All works perfectly before, last friday someone send me a csv file and when I try to do some operations with it such as 'mv, cat, cksum etc...' I always have a 'Input/Output' error. In the meantime, I can access other files in the same bucket. I only get the IO errors for this csv file.

What is strange is that if I download the csv file from GCP console, and I re upload it to my bucket, I can do all file operations without error.

Do you think this can be a problem related to GCSFuse or maybe there is something wrong with the file?

Thank you.

Regards,

Juncheng

**Comment by JunchengL** [comment]
![image](https://user-images.githubusercontent.com/37217311/100633607-979b9480-332e-11eb-8cde-186f781bc512.png)
In GCP console the file in error is the first one, and the 2nd file is another csv with no error. 
Although both files are in .csv, the 'Type' for these files are different

**Comment by lezh** [comment]
It's probably not the type of the file. There might be a lot of other reasons that it failed. 

Did you use a service account for the gcsfuse mount? If you don't specify the `key-file` option, it will use the GCE instance's service account by default. Thus, if the file is not configured to be available to the GCE instance, the gcsfuse may fail to read or write. 

One simply way to verify it is to use `gsutil` to access the file on the same instance. If `gsutil` also fails, we can be sure that the it's a permission issue.

**Comment by ilyasskallida** [comment]
Hello,
Many thanks @lezh for your answer, yes we always have the same issue even if we use gsutil:
$ gsutil cp file_date.csv gs://bucket_name
Copying file://file_date.csv [Content-Type=text/csv]...
OSError: Input/output error.0 B]

**Comment by JunchengL** [comment]
As @ilyasskallida said, we have tested gsutil for the csv file, it is not working. But for another test file it works.

I don't specify the ``key-file` option when I do gcsfuse mount. But the service account used by my GCE instance do has``storage admin` role in my project and it has full access to Storage in Cloud API access scopes.

If it's a permission issue, why my actions only fail for these kind of csv file?

![image](https://user-images.githubusercontent.com/37217311/100715461-8480d700-33b7-11eb-8b03-f200fd2f4ba5.png)

**Comment by lezh** [comment]
If `gsutil` fails on that file, then it's not a `gcsfuse` issue. Please [report it](https://cloud.google.com/support/docs/issue-trackers) to GCS instead. Without the access to your bucket, I can't debug it. 

Closing because it's not related to `gcsfuse`.
