### ISSUE TITLE
Please add support for 100+ MB/s throughput per VM from ~100 of VMs at the same time

### ISSUE THREAD

**Issue by ktropin-g** [GoogleCloudPlatform/gcsfuse#47]
We have a scenario where we need to load GBs of data to ~100 of VMs at the same time. And having 100+ MB/s throughput to each VM would make E2E workload very fast, and would allow us to switch to gcsfuse!

Thank you!

**Comment by jacobsa** [comment]
Could you give a bit more detail about what you're trying to do and what performance you're seeing now? In other words, what is gcsfuse not doing that you need it to do?

Writing a file to gcsfuse from Compute Engine should happen at a _decent_ speed at the moment; something on the order of a few hundred megabits per second. That puts the object into GCS, where you could download it concurrently to wherever you want, including multiple VMs.

**Comment by jacobsa** [comment]
Closing this for now, because there's nothing actionable. Please feel free to re-open with answers to the above.
