### ISSUE TITLE
Can't mount bucket 

### ISSUE THREAD

**Issue by mllano20** [GoogleCloudPlatform/gcsfuse#471]
I'm trying to mount the bucket locally using the following command:

gcsfuse -o nonempty --key-file /home/user/key.json --log-file /home/user/bucket/a.log --implicit-dirs warden-retail /home/user/bucket

but I'm getting this message

Using mount point: /home/user/bucket
Opening GCS connection...
daemonize.Run: readFromProcess: Decode: EOF
 
Any ideas?

I used the same command in a kubernetes pod and it works.

**Comment by lezh** [comment]
Check https://github.com/GoogleCloudPlatform/gcsfuse/issues/424

Please remove `nonempty`

**Comment by mllano20** [comment]
I tried with <code> gcsfuse  --key-file /home/user/key.json --log-file /home/user/bucket/a.log  bucket-name /home/user/bucket</>, still getting same message.

**Comment by lezh** [comment]
I can't reproduce it. Can you check the error message again with `--foreground`? That message can be more meaningful.

**Comment by mllano20** [comment]
Running
<code> gcsfuse  --foreground  --key-file /home/user/key.json  bucket-name /home/user/bucket</code>

I get this:

<code>
Using mount point: /home/user/bucket
Opening GCS connection...
panic: Cannot connect to GCS: dialing: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.

goroutine 1 [running]:
github.com/googlecloudplatform/gcsfuse/internal/gcsx.NewBucketManager(0x0, 0x0, 0x0, 0x0, 0xbff0000000000000, 0x4014000000000000, 0x1000, 0xdf8475800, 0x200000, 0xc48c41, ...)
	/tmp/build_gcsfuse_gopath715650293/src/github.com/googlecloudplatform/gcsfuse/internal/gcsx/bucket_manager.go:91 +0x237
main.mountWithConn(0xd29040, 0xc0000384c8, 0x7fffcb26a12b, 0xd, 0x7fffcb26a139, 0x14, 0xc00013e000, 0xd17e00, 0xc0001108a0, 0xc00012a320, ...)
	/tmp/build_gcsfuse_gopath715650293/src/github.com/googlecloudplatform/gcsfuse/mount.go:94 +0x232
main.mountWithArgs(0x7fffcb26a12b, 0xd, 0x7fffcb26a139, 0x14, 0xc00013e000, 0xc00012a320, 0x1, 0x28, 0x0)
	/tmp/build_gcsfuse_gopath715650293/src/github.com/googlecloudplatform/gcsfuse/main.go:280 +0x1e5
main.runCLIApp(0xc00013c000, 0x0, 0x0)
	/tmp/build_gcsfuse_gopath715650293/src/github.com/googlecloudplatform/gcsfuse/main.go:408 +0xca5
main.run.func1(0xc00013c000)
	/tmp/build_gcsfuse_gopath715650293/src/github.com/googlecloudplatform/gcsfuse/main.go:444 +0x34
github.com/googlecloudplatform/gcsfuse/vendor/github.com/urfave/cli.HandleAction(0xb126a0, 0xc0001220f0, 0xc00013c000, 0x0, 0x0)
	/tmp/build_gcsfuse_gopath715650293/src/github.com/googlecloudplatform/gcsfuse/vendor/github.com/urfave/cli/app.go:528 +0x58
github.com/googlecloudplatform/gcsfuse/vendor/github.com/urfave/cli.(*App).Run(0xc000130000, 0xc0000321e0, 0x6, 0x6, 0x0, 0x0)
	/tmp/build_gcsfuse_gopath715650293/src/github.com/googlecloudplatform/gcsfuse/vendor/github.com/urfave/cli/app.go:288 +0x655
main.run(0xc000000000, 0xc76d90)
	/tmp/build_gcsfuse_gopath715650293/src/github.com/googlecloudplatform/gcsfuse/main.go:448 +0xce
main.main()
	/tmp/build_gcsfuse_gopath715650293/src/github.com/googlecloudplatform/gcsfuse/main.go:466 +0x6f
</code>

I'm using the same key that's working on the kubernetes pod

**Comment by lezh** [comment]
I found this bug. The `storage.NewClient` does not take in the `key-file`. When you run it on GKE, the metadata server can authenticate. However, when you run it locally, the authentication fails.

It should use `WithTokenSource` to authenticate. 

I'll work on a fix.
