### ISSUE TITLE
gcsfuse 0.32.0 daemonize.Run: readFromProcess: Decode: EOF

### ISSUE THREAD

**Issue by ColinBooen** [GoogleCloudPlatform/gcsfuse#478]
We are using the following extract from our dockerfile:

RUN	export GCSFUSE_REPO=gcsfuse-stretch && \
	echo "deb http://packages.cloud.google.com/apt $GCSFUSE_REPO main" | tee /etc/apt/sources.list.d/gcsfuse.list && \
	curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - && \
	echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && \
	curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg  add - && \
	apt-get update && \
	apt-get install google-cloud-sdk gcsfuse=0.32.0 -y

If we lock gcsfuse to 0.30.0 or before then everything works fine, we can save and serve files as required. When we try with 0.32.0 we get the following error:

Using mount point: /app/bucket
Opening GCS connection...
daemonize.Run: readFromProcess: Decode: EOF

and it fails to load.

**Comment by lezh** [comment]
What are the args used to mount gcsfuse?
Is there extra message under the 3 lines you mentioned?

**Comment by lefte** [comment]
> What are the args used to mount gcsfuse?
> Is there extra message under the 3 lines you mentioned?

I'm having the same issue, my arguments are:

`gcsfuse --key-file mykeyfile --dir-mode 755 --file-mode 755 --uid 33 --gid 33 --limit-ops-per-sec -1 -o nonempty mystoragebucketname /var/www/html/pub/media`

Even adding all of the debug flags (`--debug_fuse`, `--debug_gcs`, `--debug_http`, or `--debug_invariants`), individually or together, returns no additional information, just the same `daemonize.Run: readFromProcess: Decode: EOF` message. I'm using Ubuntu 16.04.7 LTS inside a Docker container as well.

**Comment by mvoitko** [comment]
@lefte the problem is with -o nonempty option

**Comment by lefte** [comment]
> @lefte the problem is with -o nonempty option

I don't think so, eliminating it does not resolve the error, same message

**Comment by lefte** [comment]
I just confirmed that running the same exact arguments and command using version 0.30.0 does resolve the problem, so at least I have a workaround for now. _FYI for anyone else having the same issue, until it gets resolved._

**Comment by lefte** [comment]
Ah, new additional information, I see issue #471 recommended running with `--foreground` for more debug information, which returns:

```
panic: Cannot connect to GCS: dialing: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.

goroutine 1 [running]:
github.com/googlecloudplatform/gcsfuse/internal/gcsx.NewBucketManager(0x0, 0x0, 0x0, 0x0, 0xbff0000000000000, 0xbff0000000000000, 0x1000, 0xdf8475800, 0x200000, 0xc48c41, ...)
	/tmp/build_gcsfuse_gopath715650293/src/github.com/googlecloudplatform/gcsfuse/internal/gcsx/bucket_manager.go:91 +0x237
main.mountWithConn(0xd29040, 0xc0001323b8, 0x7fff96de89a9, 0xd, 0x7fff96de89b7, 0x17, 0xc0002d61c0, 0xd17e00, 0xc000394780, 0xc0001454f0, ...)
	/tmp/build_gcsfuse_gopath715650293/src/github.com/googlecloudplatform/gcsfuse/mount.go:94 +0x232
main.mountWithArgs(0x7fff96de89a9, 0xd, 0x7fff96de89b7, 0x17, 0xc0002d61c0, 0xc0001454f0, 0x1, 0x2b, 0x0)
	/tmp/build_gcsfuse_gopath715650293/src/github.com/googlecloudplatform/gcsfuse/main.go:280 +0x1e5
main.runCLIApp(0xc0001a6dc0, 0x0, 0x0)
	/tmp/build_gcsfuse_gopath715650293/src/github.com/googlecloudplatform/gcsfuse/main.go:408 +0xca5
main.run.func1(0xc0001a6dc0)
	/tmp/build_gcsfuse_gopath715650293/src/github.com/googlecloudplatform/gcsfuse/main.go:444 +0x34
github.com/googlecloudplatform/gcsfuse/vendor/github.com/urfave/cli.HandleAction(0xb126a0, 0xc0002d10b0, 0xc0001a6dc0, 0x0, 0x0)
	/tmp/build_gcsfuse_gopath715650293/src/github.com/googlecloudplatform/gcsfuse/vendor/github.com/urfave/cli/app.go:528 +0x58
github.com/googlecloudplatform/gcsfuse/vendor/github.com/urfave/cli.(*App).Run(0xc0001bbc00, 0xc000138000, 0x12, 0x12, 0x0, 0x0)
	/tmp/build_gcsfuse_gopath715650293/src/github.com/googlecloudplatform/gcsfuse/vendor/github.com/urfave/cli/app.go:288 +0x655
main.run(0xc000000000, 0xc76d90)
	/tmp/build_gcsfuse_gopath715650293/src/github.com/googlecloudplatform/gcsfuse/main.go:448 +0xce
main.main()
	/tmp/build_gcsfuse_gopath715650293/src/github.com/googlecloudplatform/gcsfuse/main.go:466 +0x6f
```

so, it might be related?

**Comment by ColinBooen** [comment]
There is no extra message in the error apart from pod closing and starting again.
The command with args we use to mount are `gcsfuse --key-file $KEYPATH $BUCKET $DIR`
Adding `--foreground` as Erik suggested gives:
Using mount point: /app/bucket

WARNING: gcsfuse invoked as root. This will cause all files to be owned by
root. If this is not what you intended, invoke gcsfuse as the user that will
be interacting with the file system.
```
Opening GCS connection...
panic: Cannot connect to GCS: dialing: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.

goroutine 1 [running]:
github.com/googlecloudplatform/gcsfuse/internal/gcsx.NewBucketManager(0x0, 0x0, 0x0, 0x0, 0xbff0000000000000, 0x4014000000000000, 0x1000, 0xdf8475800, 0x200000, 0xc48c41, ...)
        /tmp/build_gcsfuse_gopath715650293/src/github.com/googlecloudplatform/gcsfuse/internal/gcsx/bucket_manager.go:91 +0x237
main.mountWithConn(0xd29040, 0xc0000ba3b8, 0x7ffd0baa879e, 0x15, 0x7ffd0baa87b4, 0xb, 0xc0003a2000, 0xd17e00, 0xc00007e8d0, 0xc00007c5a0, ...)
        /tmp/build_gcsfuse_gopath715650293/src/github.com/googlecloudplatform/gcsfuse/mount.go:94 +0x232
main.mountWithArgs(0x7ffd0baa879e, 0x15, 0x7ffd0baa87b4, 0xb, 0xc0003a2000, 0xc00007c5a0, 0x1, 0x1f, 0x0)
        /tmp/build_gcsfuse_gopath715650293/src/github.com/googlecloudplatform/gcsfuse/main.go:280 +0x1e5
main.runCLIApp(0xc0003a0000, 0x0, 0x0)
        /tmp/build_gcsfuse_gopath715650293/src/github.com/googlecloudplatform/gcsfuse/main.go:408 +0xca5
main.run.func1(0xc0003a0000)
        /tmp/build_gcsfuse_gopath715650293/src/github.com/googlecloudplatform/gcsfuse/main.go:444 +0x34
github.com/googlecloudplatform/gcsfuse/vendor/github.com/urfave/cli.HandleAction(0xb126a0, 0xc000042370, 0xc0003a0000, 0x0, 0x0)
        /tmp/build_gcsfuse_gopath715650293/src/github.com/googlecloudplatform/gcsfuse/vendor/github.com/urfave/cli/app.go:528 +0x58
github.com/googlecloudplatform/gcsfuse/vendor/github.com/urfave/cli.(*App).Run(0xc000398000, 0xc0000be120, 0x6, 0x6, 0x0, 0x0)
        /tmp/build_gcsfuse_gopath715650293/src/github.com/googlecloudplatform/gcsfuse/vendor/github.com/urfave/cli/app.go:288 +0x655
main.run(0xc000000000, 0xc76d90)
        /tmp/build_gcsfuse_gopath715650293/src/github.com/googlecloudplatform/gcsfuse/main.go:448 +0xce
main.main()
        /tmp/build_gcsfuse_gopath715650293/src/github.com/googlecloudplatform/gcsfuse/main.go:466 +0x6f

```

**Comment by lezh** [comment]
Please upgrade to 0.33.0 that includes #472.
