### ISSUE TITLE
File operation fails when there are a large number of files in the mount directory

### ISSUE THREAD

**Issue by hikarusi** [GoogleCloudPlatform/gcsfuse#483]
I have mounted my storage bucket using the following command:

`gcsfuse --only-dir data/ gcs_bucket /data`

there are 130,000 files in the mount directory and total file size is 60 GiB.

When I try to rename the file in the mount directory with the `mv` command, I get no response and the network disconnects.

If I was using the `ls` command it would fail as well.

Is there a limit to the number of files or file size in the mount directory?

**Comment by co60ca** [comment]
Fuse responds to the OS requests for certain function calls, if using `\ls` it will only request the file names but with `ls -l` which is normally aliased on many systems it will run statx and getxattr for ever single file which will require many round-trips to the GCS bucket.

I'm wondering what you mean by "network disconnects". And exactly what mv. (Like `mv /data/file1 mv /data/file2` and are they files or folders?

I'd also suggest [increasing your ops limit which is set to 5 by default](https://github.com/GoogleCloudPlatform/gcsfuse#rate-limiting) which would probably cause issues with your `ls` command.

**Comment by fradeve** [comment]
Nothing really important to add, except the fact that the suggestion in @co60ca's post above has been really helpful in my case, as removing the ops limit (or increasing it from its default of 5) indeed solves the issue.

**Comment by mcall52** [comment]
I wanted to chime in and say I was having this same problem. I had a bucket with 5001 files and another bucket with 60K and if I ran `ls` on either one my command would fail and the gcsfuse process was killed (though the mount was still there). I fixed the problem by increasing the resources for my kubernetes deployment (CPU and Memory). Go is pretty efficient when making calls to GCS so it didn't need too much but I was way under-provisioned (75m CPU and 75Mi). Just wanted to put this out there in case it helps anyone else.

**Comment by co60ca** [comment]
> I wanted to chime in and say I was having this same problem. I had a bucket with 5001 files and another bucket with 60K and if I ran `ls` on either one my command would fail and the gcsfuse process was killed (though the mount was still there). I fixed the problem by increasing the resources for my kubernetes deployment (CPU and Memory). Go is pretty efficient when making calls to GCS so it didn't need too much but I was way under-provisioned (75m CPU and 75Mi). Just wanted to put this out there in case it helps anyone else.

Thats interesting, when we were testing this we didn't run into resource problems (at least we thought) and similar symptoms seemed completely random.

**Comment by avidullu** [comment]
We have made some recent changes to gcsfuse to speed up large directory listing.
Could you build from master (unreleased yet) and check if that helps?

**Comment by avidullu** [comment]
Please retry with the latest version (0.41) of gcsfuse which has improved the large directory listing performance.
Will keep this bug open for another week to hear inputs.
We've heard on separate threads that users have observed measurable improvements in the latencies for large directory listing lately.

**Comment by sarathreddy154** [comment]
Do we have any limitation with GCS Fuse on how many number of file requests it can handle?

We are having one GCS Bucket with 300K files mounted on JupyterLab application .When we try to open that mounted folder from JupyterLab we are getting 502 error.
We are using  version 0.41.1 of Gcs Fuse in our environment

**Comment by avidullu** [comment]
Listing >100K files has not been tested and may take a very long time to the degree that the request may fail.
Please consider organizing the files into subdirectories which should help with the performance.
