### ISSUE TITLE
breaking update 0.33.0 exits gcsfuse with status 203

### ISSUE THREAD

**Issue by MarinaMurashev** [GoogleCloudPlatform/gcsfuse#485]
The following command works on ubuntu on v0.32.0 but not on v0.33.0:
`/usr/bin/gcsfuse --foreground -o allow_other -o nonempty my-bucket-name /home/ubuntu/my-bucket-name (code=exited, status=203/`

I install gcsfuse with `apt install gcsfuse`, with the following in my `/etc/apt/sources.list.d/gcsfuse.list` file: 
```
deb http://packages.cloud.google.com/apt gcsfuse-bionic main
```

**Comment by lezh** [comment]
I can't reproduce this on Ubuntu 18.04. It works here.

What's the error message?
Do you have `user_allow_other` set in `/etc/fuse.conf`?

**Comment by MarinaMurashev** [comment]
Here's my fuse.conf:
```
# /etc/fuse.conf - Configuration file for Filesystem in Userspace (FUSE)

# Set the maximum number of FUSE mounts allowed to non-root users.
# The default is 1000.
#mount_max = 1000

# Allow non-root users to specify the allow_other or allow_root mount options.
user_allow_other
```

And I'm on a Google cloud ubuntu-1804-bionic-v20210119a image

**Comment by lezh** [comment]
I tried the same thing. It works.

I used `sudo apt-get install gcsfuse`. Then `which gcsfuse` shows `/bin/gcsfuse`. 


```
$ gcsfuse --foreground -o allow_other -o nonempty $BUCKET $HOME/gcs
...
File system has been successfully mounted.
```

A couple of things you may check:
1. Is the directory owned by the user who is mounting gcsfuse?
2. Is the gcsfuse version 0.33.0?
3. What if `-o nonempty` is removed?

**Comment by lezh** [comment]
Close due to no further update.
