### ISSUE TITLE
0.33.0 package path issues

### ISSUE THREAD

**Issue by louisvernon** [GoogleCloudPlatform/gcsfuse#487]
The 0.33.0 deb and rpm packages install gcsfuse to `/bin/gcsfuse`. In prior packages (at least 0.32.0) it was installed to `/usr/bin/gcsfuse`.

`findGcsfuse` explicitly checks `/usr/bin/gcsfuse`, but not `/bin/gcsfuse`. 

This appeared to break fstab mounting on my system, with the following error: 
```
findGcsfuse: Can't find a usable executable.
```
https://github.com/GoogleCloudPlatform/gcsfuse/blob/cb87f2ca6ed3706b02e851ce828fa762e9089dbc/tools/mount_gcsfuse/find.go#L58-L62

**Comment by wenxiaohe** [comment]
Same problem. Downgraded to 0.32.0 and no problem.

**Comment by lezh** [comment]
This issue is fixed in [v0.33.1](https://github.com/GoogleCloudPlatform/gcsfuse/releases/tag/v0.33.1)
