### ISSUE TITLE
tmp_dir set to a non-existing folder

### ISSUE THREAD

**Issue by trollius** [GoogleCloudPlatform/gcsfuse#49]
when mounting a bucket with gcsfuse if option tmp_dir is set to a non-existing folder, then bucket is still mounted, but will raise an IO error when trying to copy files and all files will have 0 filesize.

**Comment by jacobsa** [comment]
This can't be fixed perfectly, in the sense that even if the directory existed when the mount happened it could be deleted. But it's worth adding a sanity check before mounting. Will do.
