### ISSUE TITLE
GCS fuse sub directory sync not working with remote bucket path

### ISSUE THREAD

**Issue by vish91** [GoogleCloudPlatform/gcsfuse#491]
gcsfuse version 0.28.1 (Go version go1.9.7)

Experiencing an issue when gcsfuse is setup it seems to be working as expected. 
But if we go ahead and use gsutil to create a subdirectory in gs:// location, that same path doesn't exist yet on my mount. 

We usually have to run a mkdir to create that dir with same name in the mnt path and once the dir is craeted now gcsfuse will start showing all the files in that mnt path. 

e.g in gcs we have : ```gs://test/dir1/dir2/```  <- contains 4 files in that location
now i upload <dir3> inside <dir2> with 2 new files i.e gs://test/dir1/dir2/dir3/file1 and gs://test/dir1/dir2/dir3/file2

I don't see these files or dir <dir3> on my mnt path. 
But if I run ```mkdir -p /mnt/test/dir1/dir2/dir3```
and now if I do an `ls` now I will start seeing that the <dir3> exists and <file1> and <file2> exist in that location. 

Any reason to why this sync doesn't happen or if it slow when the bucket mounted has too many files under it ? 

Thanks

**Comment by lezh** [comment]
Can you verify the issue on 0.33.2 the latest version?

**Comment by lezh** [comment]
Close due to no further update.
