### ISSUE TITLE
gcsfuse not compatible with GKE Autopilot

### ISSUE THREAD

**Issue by sandeep-khanna** [GoogleCloudPlatform/gcsfuse#497]
Google Kubernetes Engine (GKE) Autopilot does not support privileged containers. This breaks my Kubernetes deployments.

Review this link - https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-overview#linux_workload_limitations

I use gcsfuse to mount a Google Cloud Storage bucket from a shell script during container (demo-app) startup.

```
# Mounting /mnt/gcs using Google Cloud Storage Fuse (gcsfuse) utility requires root user privileges
echo "Mounting media folder using Google Cloud Storage Bucket '${CLOUDSTORAGE_BUCKET_NAME}'"
gcsfuse -o ro -o allow_other --only-dir gcs --implicit-dirs ${CLOUDSTORAGE_BUCKET_NAME} /mnt/gcs
```

Here is an error received during deployment:

```
Error from server ([denied by autogke-default-linux-capabilities] linux capability <{"SYS_ADMIN"}> on container <demo-app> not allowed; Autopilot only allows the capabilities: <["SETPCAP", "MKNOD", "AUDIT_WRITE", "CHOWN", "NET_RAW", "DAC_OVERRIDE", "FOWNER", "FSETID", "KILL", "SETGID", "SETUID", "NET_BIND_SERVICE", "SYS_CHROOT", "SETFCAP"]>. Requesting user: <abc@qwerty.com> and groups: <["system:authenticated"]>
[denied by autogke-disallow-privilege] container <demo-app> is privileged; not allowed in Autopilot.
```

Any alternatives or workarounds?

**Comment by lezh** [comment]
Have you considered using https://github.com/ofek/csi-gcs?

**Comment by chenwei791129** [comment]
> Have you considered using https://github.com/ofek/csi-gcs?

but this project still in Pre-release, not ready for prod?

**Comment by lezh** [comment]
The support of a persistent volume on Kubernetes is beyond the scope of the Gcsfuse project. Currently, https://github.com/ofek/csi-gcs might be your best choice in the open source market.
