### ISSUE TITLE
Sort out permissions, ownership, and access story

### ISSUE THREAD

**Issue by trollius** [GoogleCloudPlatform/gcsfuse#50]
when bucket is mounted the rights of the mounted folder are: owner - root, group - root. But because the access permission to folder is 700, our application can't access this folder. Can it be fixed? because our application works under different unprivileged user (not with root privileges). If we try to do chmod or chown we have an error function is not implemented.

**Comment by jacobsa** [comment]
The intent is that you run gcsfuse as the user that will be accessing the mount point, at which point you should see that user as the owner. (If not, this is a bug; please let me know.) Are you able to run gcsfuse as the unprivileged user? This is probably a good idea for independent security reasons, too.

**Comment by trollius** [comment]
Hi Aaron,

we could mount bucket with unprivileged user (not root), but then root user doesn't have any rights on the mounted folder (can't go into the folder). So only the mounted user has access
[root@srv ~]# sudo -u web ./gcsfuse -bucket=test -key_file=/home/file-xxxxxxxxxxxxx.json -temp_dir=/home/gcsfuse_tmp --mount_point /data
[root@srv ~]# ls -ld /data 
ls: cannot access /data: Permission denied
[root@srv ~]# sudo -u web ls /data
drwx------ 1 web web      0 aug 30  1754 file1
drwx------ 1 web web      0 aug 30  1754 file2
[root@srv ~]# ls -l / | grep data
ls: cannot access /data: Permission denied
d??????????   ? ?    ?        ?            ? data
Even if we copy file with 775 access rights, inside the bucket from gcsfuse we see this file as 700.
So is there any way that root user could also get an access to the mounted bucket?

**Comment by jacobsa** [comment]
This is because fuse by default restricts access (in the kernel, not in the file system implementation) to only the mounting user. This applies even to root, who can't by default use the file system.

It makes sense to make this configurable. I think the way to go is:

*   Default behavior:
    *   Access for other users is off, as with the fuse default.
    *   Everything is owned by the UID/GID of the mounting process.
    *   Files have permissions `0644`.
    *   Directories have permissions `0755`.

*   Allow configuring:
    *   Set the `allow_root` option to allow the root user in particular to access the file system.
    *   Set the `allow_other` option to allow all other users to access the file system.
    *   Set default file and directory permissions bits.
    *   Set the UID/GID owning all files and directories.

So by default only the mounting user can access the file system, and they can't accidentally execute files. But they can relax any of these restrictions if desired.

**Comment by jacobsa** [comment]
(For the record, I'm taking inspiration from the options supported by other file systems documented in `man mount`.)

**Comment by jacobsa** [comment]
Verified on OS X that root can't access the mount before, but can after setting `allow_root`.

**Comment by jacobsa** [comment]
Plan:

* Add a field that lets you pass arbitrary mount options to fuse in fuse.MountConfig. Document that it is for expert use only, and may invalidate other guarantees of the package.

* Add a `--mount_options` flag to gcsfuse that is similarly documented. Update the mount helper to pass unknown options on to this flag.

* Update semantics.md to reflect the ownership semantics and configuration stuff documented [above](https://github.com/GoogleCloudPlatform/gcsfuse/issues/50#issuecomment-103240577).

* Add integration tests reflecting the intended behavior for everything that can be tested without switching users.

* Make them pass by implementing the stuff described above.

**Comment by jacobsa** [comment]
@trollius: I think you should have what you need now, but mounting under the unprivileged user using `-o allow_root` (which you may have to configure unprivileged to be allowed to use depending on your system). If root needs to be able to modify things as well, you may need to also set `--file_mode` and `--dir_mode`.

**Comment by trollius** [comment]
Hello Aaron,

This is really great you have added this option! it is exactly what is needed - yet, still some bugs sneak around:

1) when we tried to use  -o allow_root we got a following message:
2015/05/19 09:28:22.936398 Mount:bazilfuse.Mount: fusermount: "fusermount: option allow_root only allowed if 'user_allow_other' is set in /etc/fuse.conf\n", exit status 1

2) when we set an option user_allow_other in /etc/fuse.conf, gcsfuse complained about wrong option -o allow_root
2015/05/19 09:29:33.606858 Mount:bazilfuse.Mount: fusermount: "fusermount: mount failed: Invalid argument\n", exit status 1

3) when we removed -o allow_root then bucket connected correctly. 

For testing we used fuse-2.9.3-4.fc21.x86_64

Do you know what might cause this?

**Comment by jacobsa** [comment]
Looks like you filed #51; continuing there.
