### ISSUE TITLE
Cannot brew install osxfuse

### ISSUE THREAD

**Issue by chsher** [GoogleCloudPlatform/gcsfuse#501]
I am trying to install gcsfuse on a MacOS Catalina (10.15.7) but am running into the following error when I try to run `brew install --cask osxfuse`:

`chown: /usr/local/lib/sentinel.dylib: Operation not permitted`

I tried uninstalling/reinstalling homebrew, but no luck. What should I do?

**Comment by lezh** [comment]
Gcsfuse on homebrew is being [deprecated](https://github.com/Homebrew/homebrew-core/pull/64491). Please consider building from source instead.
