### ISSUE TITLE
GCSFuse v0.33.2 - Large objects (11GB) upload to GCSBucket Fails

### ISSUE THREAD

**Issue by jxb696** [GoogleCloudPlatform/gcsfuse#505]
Team, 
Receiving below errors when we try to upload 11 GB file to bucket, Also, filesystem is going into "????????" as we can't list the objects available in the bucket. This requires "umount" and "mount" back again to see the objects in the bucket. But, still the upload is not working. 
Error 1 - Transport endpoint is not connected
Error 2 - Software caused connection abort

Thanks,
Jaykishan Bairagi

**Comment by jxb696** [comment]
Thank you, any estimated date when this fix will be released?

**Comment by gaul** [comment]
This will need review in the gcloud module then updating the vedored dependency.  You can help with the former by applying the suggested PR and reporting whether it addresses your symptoms.
