### ISSUE TITLE
allow_root invalid argument

### ISSUE THREAD

**Issue by trollius** [GoogleCloudPlatform/gcsfuse#51]
Hello Aaron,

This is really great you have added this option! it is exactly what is needed - yet, still some bugs sneak around:

1) when we tried to use -o allow_root we got a following message:
2015/05/19 09:28:22.936398 Mount:bazilfuse.Mount: fusermount: "fusermount: option allow_root only allowed if 'user_allow_other' is set in /etc/fuse.conf\n", exit status 1

2) when we set an option user_allow_other in /etc/fuse.conf, gcsfuse complained about wrong option -o allow_root
2015/05/19 09:29:33.606858 Mount:bazilfuse.Mount: fusermount: "fusermount: mount failed: Invalid argument\n", exit status 1

3) we also tried -o=allow_root (just in case it is a syntax issue) - still no success

4) when we removed -o allow_root then bucket connected correctly.

For testing we used fuse-2.9.3-4.fc21.x86_64

Do you know what might cause this?

**Comment by jacobsa** [comment]
(For the record, this is a follow-up from #50. Looking now.)

**Comment by jacobsa** [comment]
This appears to be a bug in fusermount, which is not accepting the `allow_root` option (with the same error it would give for any junk option name), despite `man fuse` listing it as supported. I've started a [thread](http://sourceforge.net/p/fuse/mailman/message/34127030/) on fuse-devel about this, but unfortunately my luck with getting responses on fuse-devel is not great. In the meantime you can use `allow_other`, but note that this will allow any user to access the file system.

**Comment by trollius** [comment]
thanks Aaron! with allow_other it worked!
