### ISSUE TITLE
GCSFuse v0.33.2 - CMEK encrypted bucket objects/sub-directories Listing issue

### ISSUE THREAD

**Issue by jxb696** [GoogleCloudPlatform/gcsfuse#515]
This behavior was identified on GCSFuse v0.33.2 (This version was released to fix listing of objects/directories on CMEK encrypted buckets) but the bucket listing was working for few days after upgrading to this version of GCSFuse and today we identified a new issue with this version, when our file transmission failed of "sub-directory not available" under the same CMEK encrypted bucket. 

When I performed "gsutil ls on the bucket" I was able to list all the objects/directories. When we created a directory with same name we were able to list all the objects attached to the directory. Why was this directory in the bucket was not available on the mounted server using GCSFuse but available when performed GCSUTIL? Please let us know if there's a possible fix for this issue?

Thanks,
Jaykishan Bairagi

**Comment by lezh** [comment]
Have you enabled [implicit dirs](https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/semantics.md#implicit-directories)?
