### ISSUE TITLE
error listing mounted directory: ListObjects: toObjects: toObject: Unexpected Md5Hash field

### ISSUE THREAD

**Issue by dakoner** [GoogleCloudPlatform/gcsfuse#52]
I am using Google Compute Engine running a VM (default Debian image).  I have installed Go as well as gcsfuse (from git head) based on documentation from: https://github.com/GoogleCloudPlatform/gcsfuse

I can mount a directory:

$ gcsfuse --key_file key.json --bucket my-test-bucket --mount_point /data --fuse.debug                                                                                                
2015/05/19 23:02:56.808281 Initializing GCS connection.
2015/05/19 23:02:56.808475 Opening a bazilfuse connection.
2015/05/19 23:02:56.810162 File system has been successfully mounted.
2015/05/19 23:02:56.810592 Op 0x00000000        connection.go:319] <- Init [ID=0x1 Node=0x0 Uid=0 Gid=0 Pid=0] 7.23 ra=131072 fl=InitAsyncRead+InitPosixLocks+InitAtomicTrunc+InitExportSupport+InitBigWrites+InitDontMask+InitSpliceWrite+InitSpliceMove+InitSpliceRead+InitFlockLocks+InitAutoInvalData+InitDoReaddirplus+InitReaddirplusAuto+InitAsyncDIO+InitWritebackCache+InitNoOpenSupport
2015/05/19 23:02:56.810954 Op 0x00000000         common_op.go:154] -> Init {MaxReadahead:131072 Flags:InitBigWrites MaxWrite:2097152}

But, as soon as I try to list the contents of the mounted directory I get:
$ ls /data
ls: reading directory /data: Input/output error

The debug output is here:

2015/05/19 23:02:59.455564 Op 0x00000001        connection.go:319] <- Getattr [ID=0x2 Node=0x1 Uid=1000 Gid=1000 Pid=22387]
2015/05/19 23:02:59.456040 Op 0x00000001         common_op.go:154] -> Getattr {AttrValid:0 Attr:{Inode:1 Size:0 Blocks:0 Atime:0001-01-01 00:00:00 +0000 UTC Mtime:0001-01-01 00:00:00 +0000 UTC Ctime:0001-01-01 00:00:00 +0000 UTC Crtime:0001-01-01 00:00:00 +0000 UTC Mode:drwxr-xr-x Nlink:1 Uid:1000 Gid:1000 Rdev:0 Flags:0}}
2015/05/19 23:02:59.456466 Op 0x00000002        connection.go:319] <- Getattr [ID=0x3 Node=0x1 Uid=1000 Gid=1000 Pid=22387]
2015/05/19 23:02:59.456924 Op 0x00000002         common_op.go:154] -> Getattr {AttrValid:0 Attr:{Inode:1 Size:0 Blocks:0 Atime:0001-01-01 00:00:00 +0000 UTC Mtime:0001-01-01 00:00:00 +0000 UTC Ctime:0001-01-01 00:00:00 +0000 UTC Crtime:0001-01-01 00:00:00 +0000 UTC Mode:drwxr-xr-x Nlink:1 Uid:1000 Gid:1000 Rdev:0 Flags:0}}
2015/05/19 23:02:59.457124 Op 0x00000003        connection.go:319] <- Open [ID=0x4 Node=0x1 Uid=1000 Gid=1000 Pid=22387] dir=true fl=OpenReadOnly+0x10800
2015/05/19 23:02:59.457501 Op 0x00000003         common_op.go:154] -> Open {Handle:0 Flags:0}
2015/05/19 23:02:59.457627 Op 0x00000004        connection.go:319] <- Read [ID=0x5 Node=0x1 Uid=1000 Gid=1000 Pid=22387] 0x0 4096 @0x0 dir=true
2015/05/19 23:02:59.619914 Op 0x00000004         common_op.go:131] -> (ReadDir(inode=1)) error: readAllEntries: ReadEntries: ListObjects: toObjects: toObject: Unexpected Md5Hash field: 
2015/05/19 23:02:59.620324 Op 0x00000005        connection.go:319] <- Release [ID=0x6 Node=0x1 Uid=0 Gid=0 Pid=0] 0x0 fl=OpenReadOnly+0x10800 rfl=0 owner=0x0
2015/05/19 23:02:59.620587 Op 0x00000005         common_op.go:148] -> (ReleaseDirHandle(inode=1)) OK

**Comment by jacobsa** [comment]
As you speculated off-thread, this is because composite objects don't have an `md5Hash` field in GCS (but the gcloud package expects to always have one). Will open a gcloud bug and fix.

**Comment by jacobsa** [comment]
Blocked on jacobsa/gcloud#6.

**Comment by jacobsa** [comment]
This works for me now. Please update with `go get -u` and confirm.

**Comment by dakoner** [comment]
It's fixed for me.  Thanks.
