### ISSUE TITLE
Change timestamp in logfiles to human readable format

### ISSUE THREAD

**Issue by OliverDBA** [GoogleCloudPlatform/gcsfuse#523]
Hi all,

when running gcsfuse in the background with debug_gs all the timestamps are only in the Unix timestamp format.
How can I change it to a human readable date / time format? I t would make reading the logfile a lot easier

Current version 0.34.1

**Comment by lezh** [comment]
Have you tried `--log-format=text`?

**Comment by OliverDBA** [comment]
unfortunately this setting has no impact

**Comment by lezh** [comment]
Can you include the arguments used for mounting gcsfuse to help reproduce it? Otherwise, I don't actually know what this issue is about.

**Comment by OliverDBA** [comment]
Mount options in /etc/fstab
my-bucket /u02/rman gcsfuse x-systemd.requires=home.mount,_netdev,rw,log_format=text,debug_gcs,debug_fuse,log_file=/home/oracle/fstab.log,limit_ops_per_sec=50,implicit_dirs,uid=oracle,gid=oinstall,allow_other,key_file=/home/oracle/mykey.json

Logifle looks like this:
{"name":"root","levelname":"INFO","severity":"INFO","message":"OpenBucket(\"my-bucket\", \"\")\n","timestampSeconds":1618256331,"timestampNanos":551664275}

If I mount without the logfile name, the output to standard out is
Calling gcsfuse with arguments: --key-file /home/oracle/mykey.json -o rw --uid 801 --gid 801 -o allow_other --log-format text --debug_fuse my-bucket /u02/rman
2021/04/26 18:11:31.142020 Using mount point: /u02/rman
2021/04/26 18:11:31.148861 Opening GCS connection...
2021/04/26 18:11:31.334568 Mounting file system "my-bucket"...
2021/04/26 18:11:31.334951 File system has been successfully mounted.
