### ISSUE TITLE
No files after "File system has been successfully mounted."

### ISSUE THREAD

**Issue by bayerlse** [GoogleCloudPlatform/gcsfuse#524]
When I run `gcsfuse <mount-folder> <bucket-name>.`

I get the message _"File system has been successfully mounted."_ 
But no files are within the directory, when trying to `ls` or accessing them by code.

How can I achieve to have the bucket mounted correctly?

**Comment by lezh** [comment]
Sometimes it's because you did not enable implicit directory. 
Please check https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/semantics.md and make sure you understand the options needed for mounting a bucket.

**Comment by bayerlse** [comment]
I tried it, but it took 15 minutes to have the process finished, which is too long to have a nice sync :(

**Comment by lezh** [comment]
> it took 15 minutes to have the process finished

What does that mean? Do you see a significant delay introduced by `--implicit-dir`?

**Comment by avidullu** [comment]
@bayerlse Can you please share the exact logs screenshot for us to be able to help you?

**Comment by avidullu** [comment]
Closing out due to inactivity. Please reopen or file a new issue with the debug flags (--foreground --debug_fs --debug_fuse --debug_gcs --debug_http) which will help us investigate deeper into the logs.
