### ISSUE TITLE
Multiple sessions for one bucket

### ISSUE THREAD

**Issue by OliverDBA** [GoogleCloudPlatform/gcsfuse#525]
Hi,

if I run a backup job in one terminal session (Oracle rman with 2 streams), then running a 
  ls 
command on the same directory takes a long time and sometimes just times out after 2 minutes.
Is there any configuration to enable this listing? Current mount options
rw,debug_gcs,debug_fuse,debug_fs,log_format=text,stat_cache_ttl=5m,type_cache_ttl=5m,log_file=/home/oracle/gcsfuse.log,max_retry_sleep=0,uid=oracle,gid=oinstall,allow_other

**Comment by lezh** [comment]
What version?

**Comment by OliverDBA** [comment]
0.35.0

**Comment by avidullu** [comment]
Can you run gcsfuse from head (master) and retry? There have been some recent changes to directory listing performance improvement.
