### ISSUE TITLE
GCSfuse Cannot remove object on mounted GCP storage 

### ISSUE THREAD

**Issue by asadkhan34** [GoogleCloudPlatform/gcsfuse#526]
Bucket was mounted successfully , but I want to remove these lock files which were made by Borg ( backup utility ) when i tried to remove them it gives following error , i tried to unmount and mount the bucket again but still the same issue.

FYI : VM instance have Allow full access to all Cloud APIs , so this doesn't seem to be permission issue 

 
rm: cannot remove 'lock.exclusive/west-camronview.4712-0': Input/output error

Please assist what could be the possible solution here

**Comment by lezh** [comment]
```
gcsfuse --foreground --debug_gcs --implicit-dir $BUCKET $DIR
```

This would print the logs that help you diagnose the internal error.

**Comment by avidullu** [comment]
Do you have the logs available to investigate further?

**Comment by avidullu** [comment]
Closing out due to inactivity.
