### ISSUE TITLE
GCSFuse v0.34.1.1 - Unable to list objects of CMEK Google/Encrypted buckets. 

### ISSUE THREAD

**Issue by bjaykishan** [GoogleCloudPlatform/gcsfuse#527]
Hello Team,
 We are using GCSFuse v0.34.1.1 for GCS and encountering issues listing objects of Google/CMEK encrypted buckets on RHEL. The directory was visible from GCP Storage browser (GCP Console). Please let us know if this was remediated in any latest release. 

Thanks,
Jaykishan Bairagi

**Comment by lezh** [comment]
CMEK is already supported in newer versions.
