### ISSUE TITLE
gcsfuse daemonization

### ISSUE THREAD

**Issue by trollius** [GoogleCloudPlatform/gcsfuse#53]
Hello Aaron,

we think it would be great to have an option for running gcsfuse as a linux daemon. Do you think it is feasible?

Anna

**Comment by jacobsa** [comment]
See [docs/mounting.md](https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/mounting.md) for this. It's not technically feasible to do in Go, and it seems the new fashion is to use daemonizing wrappers anyway. That lets you set it up in whatever way you prefer.
