### ISSUE TITLE
Cannot launch a saved jupyter notebook from gcsfuse bucket

### ISSUE THREAD

**Issue by Schmidtbit** [GoogleCloudPlatform/gcsfuse#531]
I have used gcsfuse to attach a bucket with saved jupyter notebooks onto my VM. I am currently using the jupyter lab interface via an ssh tunnel into my VM to manuever the file system. If I copy a jupyter notebook to outside the bucket I can launch it. However, it won't launch from inside the bucket. Is this a known issue with a work around? I get an "Unhandled error" message.

**Comment by avidullu** [comment]
Could you please post the logs as you see them for us to be able to understand the issue better?
Along with that the details of the flags which you passed to gcsfuse at startup and the logs would help
(--foreground, --debug_fuse, --debug_fs etc. will be helpful to use at init which can give more detailed logs for us to support you)

**Comment by avidullu** [comment]
Seems similar to #562 so closing this out in favor of that since it has more pointers.
