### ISSUE TITLE
Permission denied message even though a file is created.

### ISSUE THREAD

**Issue by iamchriswick** [GoogleCloudPlatform/gcsfuse#532]
After mounting my bucket on boot with:

`my_bucket-01 /home/user/my-bucket gcsfuse rw,x-systemd.requires=network-online.target,user`

I get the following feedback when touching a new file:

`touch: setting times of '/home/user/my-bucket/test.md': Permission denied`

When running ls `/home/user/my-bucket/` the file is shown to exist.

What is causing this?

**Comment by lezh** [comment]
https://cloud.google.com/storage/docs/access-control/iam-permissions

Changing the metadata of a file requires a different permission than reading or writing a file.

It seems you need to acquire storage.objects.update permission.

**Comment by iamchriswick** [comment]
@lezh No, actually I needed to mount my bucket with permissions:

`'echo $BUCKETNAME' /mnt/buckets/'echo $BUCKETNAME' gcsfuse rw,_netdev,allow_other,uid='echo $MYUID',gid='echo $MYGID'`
