### ISSUE TITLE
gcsfuse v0.35 running into file access errors

### ISSUE THREAD

**Issue by vish91** [GoogleCloudPlatform/gcsfuse#534]
Hello, 

Did something change w.r.t to GCS file access limits ? 
We moved from v0.28 to 0.35 and are running into some silent errors. 

Use case: using gcsfuse to access files on multiple machines in parallel.. upwards of 100 jobs spin up 1000 machines which try to access some file by byte range requests or entire file to download ? 

Since this is production level traffic for us it is difficult for us to capture and send you exact metrics unless gcsfuse has some additional logging flag feature we can enable that can help us find the exact problem... but on surface it looks like some ops limit. 

Buckets are mounted using:
```
mkdir /buckets/$bucket_name
gcsfuse $bucket_name /buckets/$bucket_name
```

**Comment by lezh** [comment]
What's the syndrome? Does it return errors?

What's the trigger?

Is your workload read only or read + write?

**Comment by vish91** [comment]
hey @lezh  it fails on the top level operation as if the bucket got unmounted. 
We reverted back quickly so I'll have to dig more, but what we saw was: 
the bucket was mounted but the files do not seem to be accessible any more and doesn't exists in folder. 

Workload is read only.

**Comment by lezh** [comment]
Does the issue happen consistently on all the jobs at the beginning? Or, it happens to some jobs and after a while?

**Comment by vish91** [comment]
wouldn't say all.. but seemed to be happening on most of them.. or in some cases even retries were getting successful.. 
anything you can suggest I can read in changelog or any README ? 
coz everything seems to be working fine when we reverted back to v0.28

**Comment by lezh** [comment]
You can try to use `--debug_gcs` or `--debug_fuse` to log internal error messages. This is expensive for heavy traffic.

**Comment by lezh** [comment]
Close due to no further update.
