### ISSUE TITLE
Installing an older version on Ubuntu Focal

### ISSUE THREAD

**Issue by vish91** [GoogleCloudPlatform/gcsfuse#535]
hello, 
Need some help with the installation steps if we want to install a specific older version of gcsfuse ? 

Using steps from Readme: 
```
RUN export GCSFUSE_REPO=gcsfuse-`lsb_release -c -s` && \
    echo "deb http://packages.cloud.google.com/apt $GCSFUSE_REPO main" | tee /etc/apt/sources.list.d/gcsfuse.list && \
    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - && \
    apt-get update -y && \
    apt-get install -y gcsfuse 
```

Which always installs the latest version , but I would like to install an older release . for example v0.28.1

From Readme,
I see this step for older releases https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/installing.md#older-releases-and-other-distributions
but shouldn't it be possible to just run it in our dockerfile as 

```
RUN export GCSFUSE_REPO=gcsfuse-`lsb_release -c -s` && \
    echo "deb http://packages.cloud.google.com/apt $GCSFUSE_REPO main" | tee /etc/apt/sources.list.d/gcsfuse.list && \
    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - && \
    apt-get update -y && \
    apt-get install -y gcsfuse=0.28.1 -V
```

**Comment by bjornleffler** [comment]
We only build two version of gcsfuse: one for Debian and one for Centos.

For a particular version of gcsfuse, all the debian packages are the same, even though we distribute them for the different Debian releases. You should be able to install any version. Please see the Debian documentation for how to do this.

**Comment by vish91** [comment]
@bjornleffler  could you please point me to what documentation are you referring to ? 
Coz these are the steps from https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/installing.md#ubuntu-and-debian-latest-releases  and I am not able to change the version with the apt-get install command.

**Comment by vish91** [comment]
Q2: 
Something that is also missing from v0.28.1 is the manual outputs for distributions i.e .deb and .rpm , I don't see them for this specific version which is doesn't allow us to execute the manual steps for older or other releases as mentioned in the doc. https://github.com/GoogleCloudPlatform/gcsfuse/releases/tag/v0.28.1

Since that release exists can we please have the specific distribution files for that version uploaded so we don't have to upgrade or downgrade and keep it matched to out production system which is currently running v0.28.1

**Comment by lezh** [comment]
You can download the deb package from https://github.com/GoogleCloudPlatform/gcsfuse/releases

Then install it with apt-get. 
```
apt-get install gcsfuse.deb
```

**Comment by vish91** [comment]
@lezh could you please tell me where do I find the deb package or v0.28.1

**Comment by lezh** [comment]
@vish91 It's not on the list of https://github.com/GoogleCloudPlatform/gcsfuse/releases. So, it's only a tag, not a formal release.

**Comment by vish91** [comment]
Gotcha and downloading the deb package and installing will require installing libfuse separately ? 
is there a specific version dependency between the two ? 
Trying to understand since our legacy system is on gcsfuse v 0.28.1 and libfuse v2.9.9-3. 
So being careful while upgrading or installing both separately. Can't update to the latest because as I reported yesterday there are some issues there with gcsfuse's behavior so we can't upgrade to the latest by default.
