### ISSUE TITLE
Using git clone in a mounted bucket

### ISSUE THREAD

**Issue by AmrMKayid** [GoogleCloudPlatform/gcsfuse#539]
I've mounted a bucket using gcsfuse and I'm trying to clone a big repo to the bucket but I couldn't do that and received the errors in the image below

<img width="1586" alt="Screen Shot 2021-06-16 at 7 18 51 PM" src="https://user-images.githubusercontent.com/18689888/122264461-da424a00-ced7-11eb-8d78-2ad5feef8305.png">

**Comment by sethiay** [comment]
Using git clone in gcsfuse mount is not a supported use-case of gcsfuse. Closing this for the same reason.

**Comment by sethiay** [comment]
This is same as https://github.com/GoogleCloudPlatform/gcsfuse/issues/1016.

**Comment by ashmeenkaur** [comment]
This issue appears to be the same as the one reported in https://github.com/GoogleCloudPlatform/gcsfuse/issues/1016. I'm closing this issue as a duplicate.
