### ISSUE TITLE
gcsfuse logging options

### ISSUE THREAD

**Issue by trollius** [GoogleCloudPlatform/gcsfuse#54]
Another feature we think would be great is to have some sort of logging option for gcsfuse for ease of administration. As an example in the log:

1. what gcsfuse does at a current moment (basic operations without debugging)
2. which files bucket works with 
3. data copying speed
4. full destination path in a bucket (for a file which is copied into a bucket)
5. status of file transfer for each file (e.g success, failed, interrupted) 

In addition, it would be great to have a full debugging option.

**Comment by jacobsa** [comment]
Have you tried `--gcs.debug` and `--fuse.debug`?

**Comment by trollius** [comment]
Hi Aaron!

--gcs.debug exactly resolved our 1,2,4,5 points - thanks a lot!
--fuse.debug - this one is kind of harder to get through so we will track --gcs.debug for now until we are more familiar with fuse :) 

Thanks again!
