### ISSUE TITLE
CentOS and Red Hat Repo

### ISSUE THREAD

**Issue by JellyGong** [GoogleCloudPlatform/gcsfuse#540]
I found the latest version is 0.28.1 in CentOS and Red Hat repo. Could you please add recent release? That will be very helpful 😀

**Comment by JellyGong** [comment]
Never mind. I followed the ["Older releases and other distributions"](https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/installing.md#older-releases-and-other-distributions) in installation doc and got 0.35. To install the dependency FUSE, its [documentation](https://github.com/libfuse/libfuse#installation) only mention using Meson and Ninja to build and install the program. It seems like `yum install fuse` also works. The latter way is easier.

**Comment by Tobrek** [comment]
It would be nice if the newest version also would be available in the yum repository, mentioned in https://github.com/GoogleCloudPlatform/gcsfuse/blob/v0.36.0/docs/installing.md#centos-and-red-hat-latest-releases.
0.28.1, which is the currently latest version at the repository, is 2 years old.

**Comment by mambor177** [comment]
Will there be any traction on updating the yum repository with newer versions of gcsfuse?

**Comment by avidullu** [comment]
There was an issue previously which avoided publishing the latest versions.
With the latest 0.41 release you should see the latest version in the rpm repos.
