### ISSUE TITLE
gcsfuse init fails with "panic: Page size is unexpectedly (big number)" with macFUSE + arm64/m1

### ISSUE THREAD

**Issue by grisaitis** [GoogleCloudPlatform/gcsfuse#548]
* macOS 11.5.1 (20G80)
* arm64 / apple m1 silicon
* macFUSE version 4.1.2, installed with `pkg`
* built `go` from source
* built `gcsfuse` from source w/ GOPATH=$HOME/go
* and:
```
➜  ~ which go
/usr/local/go/bin/go
➜  ~ go version
go version go1.16.6 darwin/arm64
➜  ~ which gcsfuse
/Users/william/go/bin/gcsfuse
➜  ~ gcsfuse
panic: Page size is unexpectedly 16384

goroutine 1 [running]:
github.com/googlecloudplatform/gcsfuse/vendor/github.com/jacobsa/fuse/internal/buffer.init.0()
        /Users/william/go/src/github.com/googlecloudplatform/gcsfuse/vendor/github.com/jacobsa/fuse/internal/buffer/in_message.go:33 +0xb8
```

any idea what could be causing this?

there's a related issue with macFUSE 4.1.0 (https://github.com/GoogleCloudPlatform/gcsfuse/issues/514) but that seems to be an issue with naming or looking up the name of the macFUSE dependency. my problem seems more system related. 

maybe yet another arm64 compat issue?

**Comment by gaul** [comment]
@grisaitis Could you test the proposed PR?  I don't have the correct hardware to test this myself.

**Comment by grisaitis** [comment]
Sorry, can you describe the steps for how to do this? I have no experience with `go mod` or dependency management in go projects. :/

i tried modifying `go.mod` in `$GOPATH/src/github.com/googlecloudplatform/gcsfuse` like this:

```
diff --git a/go.mod b/go.mod
index bc92a903..8cbab7ad 100644
--- a/go.mod
+++ b/go.mod
@@ -6,7 +6,7 @@ require (
        cloud.google.com/go/storage v1.16.0
        github.com/go-kit/kit v0.10.0 // indirect
        github.com/jacobsa/daemonize v0.0.0-20160101105449-e460293e890f
-       github.com/jacobsa/fuse v0.0.0-20210805062233-5d146b000c70
+       github.com/gaul/fuse page-size
        github.com/jacobsa/gcloud v0.0.0-20210611094250-93436725bc18
        github.com/jacobsa/oglematchers v0.0.0-20150720000706-141901ea67cd
        github.com/jacobsa/oglemock v0.0.0-20150831005832-e94d794d06ff
```

but `go build` fails. also tried `go build -mod=mod` and `go build -mod=readonly` but... i don't think i have any idea what i'm doing lol.

**Comment by grisaitis** [comment]
Nevermind, figured it out 🙂  just had to add a `replace` directive in `go.mod` followed by `go install`:

```
diff --git a/go.mod b/go.mod
...
+
+replace github.com/jacobsa/fuse => github.com/gaul/fuse page-size
```

and the error went away! looks good:

```
➜  ~ gcsfuse 
gcsfuse takes one or two arguments. Run `gcsfuse --help` for more info.
```

that said, now i encounter #514 🙁 

```
➜  ~ gcsfuse my_bucket ~/buckets/my_bucket
2021/08/11 14:07:56.545540 Using mount point: /Users/william/buckets/my_bucket
2021/08/11 14:07:56.563442 Opening GCS connection...
2021/08/11 14:07:56.971758 Mounting file system "my_bucket"...
daemonize.Run: readFromProcess: sub-process: mountWithArgs: mountWithConn: Mount: mount: cannot locate OSXFUSE
```

despite macFUSE existing on my system:

```
➜  ~ ls -l /Library/Filesystems/macfuse.fs/Contents/Resources/
total 4032
-rw-r--r--  1 root  wheel    22847 May 16 16:55 License.rtf
-rw-r--r--  1 root  wheel  1708546 May 16 16:55 Volume.icns
-rwsr-xr-x  1 root  wheel   153232 May 16 16:56 load_macfuse
-rwsr-xr-x  1 root  wheel   171728 May 16 16:56 mount_macfuse
drwxr-xr-x  3 root  wheel       96 Jul 29 14:26 uninstall_macfuse.app
```

**Comment by grisaitis** [comment]
@stapelberg, i see you accepted @gaul's PR https://github.com/jacobsa/fuse/pull/102 which fixed the page size issue

in order for that change to take effect in this project, do you need to update the version of the `jacobsa/fuse` dependency here? is that as simple as modifying the version hash in `gcsfuse/go.mod`? i'm not a gopher but it seems like that hash is generated by soemthing else maybe... 

asking as i would love to be able to build `gcsfuse` from source on my arm64 mac and have things work without having to modify `go.mod`.

**Comment by gaul** [comment]
@grisaitis could you test with the latest master?
