### ISSUE TITLE
The repository 'http://packages.cloud.google.com/apt gcsfuse-bullseye Release' does not have a Release file

### ISSUE THREAD

**Issue by McMac** [GoogleCloudPlatform/gcsfuse#553]
Looks like the release for Debian bullseye is no longer working (it worked before!) 

https://packages.cloud.google.com/apt/dists

is not listing bullseye (anymore):

![image](https://user-images.githubusercontent.com/219912/133112559-44bec785-908b-405c-a49e-d42d390f6463.png)

Trying to build a Docker image from openjdk:11-jre-slim

Resulting in

```
#5 9.601 Hit:1 http://deb.debian.org/debian bullseye InRelease
#5 9.601 Hit:2 http://deb.debian.org/debian bullseye-updates InRelease
#5 9.607 Hit:3 http://security.debian.org/debian-security bullseye-security InRelease
#5 9.762 Ign:4 http://packages.cloud.google.com/apt gcsfuse-bullseye InRelease
#5 9.924 Err:5 http://packages.cloud.google.com/apt gcsfuse-bullseye Release
#5 9.924   404  Not Found [IP: 216.58.215.238 80]
#5 9.951 Reading package lists...
#5 10.50 E: The repository 'http://packages.cloud.google.com/apt gcsfuse-bullseye Release' does not have a Release file.
```

**Comment by cometta** [comment]
I faced this issue too

**Comment by lezh** [comment]
You can use gcsfuse-jessie instead. They're the same.

**Comment by JackKelly** [comment]
I had a similar problem when trying to install `gcsfuse` on ubuntu 21.04 hirsute:

```
jack@data-processing:~$ sudo apt update
...
Ign:6 http://packages.cloud.google.com/apt gcsfuse-hirsute InRelease
Err:7 http://packages.cloud.google.com/apt gcsfuse-hirsute Release
  404  Not Found [IP: 108.177.127.139 80]
Reading package lists... Done
E: The repository 'http://packages.cloud.google.com/apt gcsfuse-hirsute Release' does not have a Release file.
```

I got it working by replacing `hirsute` with `focal` (20.04) in `/etc/apt/sources.list.d/gcsfuse.list` and running `sudo apt update` again.

**Comment by avidullu** [comment]
buster or jessie would work as suggested. closing this out.
Please feel free to reopen/create a new issue in case you want us to look into more.

We might file a new request to have a bullseye repository later.

**Comment by avidullu** [comment]
@6SwC Could you please post the exact commands you ran before this?
