### ISSUE TITLE
Not generating the mount.gcsfuse mount(8) helper when building from the source

### ISSUE THREAD

**Issue by fa-mc** [GoogleCloudPlatform/gcsfuse#556]
I built gcsfuse from source on a Synology DS920+ NAS. My go version is go1.17.1 linux/amd64. I ran the command `GO111MODULE=auto go get -u github.com/googlecloudplatform/gcsfuse` under root, the process generated the gcsfuse binary to $GOPATH/bin directory, however it did not generate the /sbin/mount.gcsfuse mount(8) helper. For now I managed to get fstab working by copying the /sbin/mount.gcsfuse file from a Debian distribution.

Could you please advise if the build command is expected to generate the mount(8) helper?

**Comment by lezh** [comment]
To get mount.gcsfuse, you need to run
https://github.com/GoogleCloudPlatform/gcsfuse/tree/master/tools/build_gcsfuse

**Comment by VengefulAncient** [comment]
I second this. Please add this to `installing.md`. The suggested process for building from source is not suitable as it is, `mount.gcsfuse` is crucial and `mounting.md` seems to agree.
