### ISSUE TITLE
Cannot Ctrl+C gcsfuse after lazy unmount while operation in progress

### ISSUE THREAD

**Issue by aalexgabi** [GoogleCloudPlatform/gcsfuse#557]
1. Mount
```
gcsfuse --foreground <bucket> <mount_folder>
```
2. Make a big file
```
dd if=/dev/urandom bs=1MB of=<mount_folder>/10G status=progress
```
3. Drop caches to make next read slow
```
echo 3 | sudo tee /proc/sys/vm/drop_caches 
```
4. In another terminal launch long read operation
```
dd if=<mount_folder>/10G bs=1M of=/dev/null status=progress
```
5. In a third terminal unmount in lazy mode
```
fusermount -uz <mount_folder>
```
6. gcsfuse does not exit
7. trying to use Ctrl+C in the terminal in which it's launched shows:

```
^C2021/09/29 12:17:15.947486 Received SIGINT, attempting to unmount...
2021/09/29 12:17:15.948746 Failed to unmount in response to SIGINT: exit status 1: /usr/bin/fusermount: entry for /home/user/<edited> not found in /etc/mtab
```
I had to kill the process to end it

**Comment by avidullu** [comment]
gcsfuse is primarily supposed to run as a daemon process. You seem to be running in --foreground mode and the Ctrl-C is unable possibly due to the pending writes which are happening due to the large file write which possibly didn't complete. 

Can you please highlight what you're trying to achieve? And what issue do you see with gcsfuse?

**Comment by aalexgabi** [comment]
This happened during testing of gcsfuse. We ended up using rclone mount as it seems to be more reliable and never gets stuck but unfortunately it does not handle kernel file caching.

Not sure exactly what's the protocol in linux when doing a lazy unmount.
Unmounting while operations are in progress should return read/write error to writer, unmount and gcsfuse should exit.

The main point of this issue is that there seems to be a bug in gcsfuse which does not handle exiting correctly.
When gcsfuse works in foreground it should handle signals properly and exit. A sigkill should never be required by the user.

Why gcsfuse does not exit after the unmount?

**Comment by avidullu** [comment]
Thanks for the inputs. We'll investigate into why gcsfuse does not respect the force unmount

**Comment by vadlakondaswetha** [comment]
ctrl+c on gcsfuse works similar to umount operation i.e, unmounts only if the mount point is not busy.

In this specific case, fusermount -uz itself implies that unmount only after all operations currently running on mount point are stopped. Then trying to do ctrl+c on gcsfuse is doing unmount again whereas the entry from /etc/mtab is already removed by fusermount. So you need to wait for all operations to be done or kill the application invoking the operations.
