### ISSUE TITLE
`ls` on mount root stopped working

### ISSUE THREAD

**Issue by Carrotman42** [GoogleCloudPlatform/gcsfuse#564]
At some point in the past I was able to `ls` the root of the mount and get all (pseudo) directories. Now `ls` complains: `ls: reading directory '/gs/MY_BUCKET_MOUNT/': Input/output error`

I can list other non-root directories, e.g. if I had a file `gs://bucket/a/b`, `ls /gs/bucket/a` will correctly show the `b` file.

Note that I am passing `--implicit-dirs`. I updated to the tip-of-tree of this repo (70695b53a6) just now and retried but the issue persists.

Perhaps something changed in our bucket which caused this problem to pop up? It definitely worked in the past, but it stopped working without me changing the version that was running (as far as I know).

**Comment by lezh** [comment]
Glad this is solved
