### ISSUE TITLE
--key-file flag only works if --foreground flag is given

### ISSUE THREAD

**Issue by bdeck8317** [GoogleCloudPlatform/gcsfuse#565]
If I run gcsfuse without `--foreground`  flag `.json` file doesn't work as my keyfile.

`gcsfuse --key-file ucla-adhd-325715-fae2d49c02b4.json --implicit-dirs fmriprep work/fmriprep_out/
Using mount point: /home/bdeck8317_gmail_com/work/fmriprep_out
Opening GCS connection...
daemonize.Run: readFromProcess: sub-process: mountWithArgs: getConn: newTokenSourceFromPath: ReadFile("ucla-adhd-325715-fae2d49c02b4.json"): open ucla-adhd-325715-fae2d49c02b4.json: no such file or directory
[bdeck8317_gmail_com@controls-login0 ~]$ `

However, if `--foreground` is given then, `--key-file` works.
`
gcsfuse --key-file ucla-adhd-325715-fae2d49c02b4.json --implicit-dirs --foreground  fmriprep work/fmriprep_out/
Using mount point: /home/bdeck8317_gmail_com/work/fmriprep_out
Opening GCS connection...
Opening bucket...
Mounting file system...
File system has been successfully mounted.
`

However, I need to mount buckets using a slurm cluster so this is not an option as it would cause the compute instances to hang.

Any ideas?

**Comment by lezh** [comment]
You need to specify the full path of the key file when `--foreground` is not given.
