### ISSUE TITLE
Dynamic mounting doesn't work: gcsfuse takes exactly two arguments

### ISSUE THREAD

**Issue by rogerbock** [GoogleCloudPlatform/gcsfuse#568]
The documentation gives this example:

```
mkdir /path/to/mount/point
gcsfuse /path/to/mount/point
```

However, when I try the same commands, I get:

```gcsfuse takes exactly two arguments. Run `gcsfuse --help` for more info.```

What am I doing wrong?  This is in a container built with the following commands:

```
RUN echo "deb http://packages.cloud.google.com/apt gcsfuse-jessie main" | tee /etc/apt/sources.list.d/gcsfuse.list
RUN curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
RUN apt-get update
RUN apt-get install -y gcsfuse
```

Thank you!

**Comment by lezh** [comment]
Your gcsfuse is an old version. Please upgrade.

**Comment by rogerbock** [comment]
@lezh sorry if this is a naive question, but is the above code not grabbing the latest version?  If not, how do I go about getting the latest version?
