### ISSUE TITLE
Option for a --quite flag for forground daemons

### ISSUE THREAD

**Issue by fregster** [GoogleCloudPlatform/gcsfuse#578]
Issue:
Many people require GCSFuse to run as a foreground process especially within Docker instances and for example under SupervisorD
This causes excessive logging output that is of little value in production systems.

Example:
When using stat caching:
Not retrying StatObject("Some/File/Or/Folder/") after error of type *gcs.NotFoundError ("gcs.NotFoundError: googleapi: Error 404: No such object: Some/File/Or/Folder/, notFound"): &gcs.NotFoundError{Err:(*googleapi.Error)(0xc0000a4360)}

Request:
Add a --quite flag to suppress informational logs only when running in foreground

Value:
Stops me generating an average 10GB of logs per day in a production GKE docker container
Removes the need for hacky PID monitoring wrapping scripts to support Docker / SupervisorD in production

**Comment by lezh** [comment]
Can you try [v0.39.2](https://github.com/GoogleCloudPlatform/gcsfuse/releases/tag/v0.39.2)? It removes the logging noise in the dependency library.

**Comment by lezh** [comment]
With the logging noise reduced, this should not be necessary.
