### ISSUE TITLE
rsync issue

### ISSUE THREAD

**Issue by trollius** [GoogleCloudPlatform/gcsfuse#58]
Hi Aaron,

We tried it out in the following configuration:
we have two servers: one without a bucket and second one with a bucket attached. We tried to copy with rsync data from no-bucket server into the bucket of the second server via network and got a following error:

[user@srv-test ~]$ rsync -aq -4 -e 'ssh -p 22' /home/user/output/ user@srv-bucket:/bucket/
rsync: failed to set times on "/bucket/": Operation not permitted (1)
rsync: mkstemp "/bucket/.file_test.txt.PDxUdi" failed: Operation not permitted (1)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1165) [sender=3.1.1]

**Comment by jacobsa** [comment]
It's a known issue (#15) that rsync doesn't work. I would recommend using `gsutil rsync` for now.

**Comment by seonghobae** [comment]
@jacobsa How about traditional rsync protocol? The gsutil rsync currently not support any traditional rsync protocols. For example,  rsync -rtlzv --delete cran.r-project.org::CRAN /dir/on/local/disc

**Comment by jacobsa** [comment]
Sorry, I'm not sure what exactly you're asking for. What are you imagining that gcsfuse would do?

**Comment by seonghobae** [comment]
Make a local mirror of CRAN (http://cran.r-project.org). They are supporting rsync protocol only. So, I want to download their master data into my bucket.

**Comment by jacobsa** [comment]
See issue #15 linked above—rsync should work now. Though be aware that because it doesn't parallelize across files, it's not particularly fast.
