### ISSUE TITLE
Unable to list file system getting connection refused after succefull mount

### ISSUE THREAD

**Issue by cammorca** [GoogleCloudPlatform/gcsfuse#583]
Hello,

I am trying to mount a bucket on a redhat server. I get a successfull mount but when I try to ls I get connection refused and the file system does not shows up in df 
# gcsfuse  --foreground --key-file /root/key.json  transfert-apollo /test
2021/12/22 17:41:53.820567 Start gcsfuse/0.39.2 (Go version go1.17.5) for app "" using mount point: /test
2021/12/22 17:41:53.820630 Opening GCS connection...
2021/12/22 17:41:53.820991 Creating a mount at "/test"

WARNING: gcsfuse invoked as root. This will cause all files to be owned by
root. If this is not what you intended, invoke gcsfuse as the user that will
be interacting with the file system.
2021/12/22 17:41:53.821316 Creating a new server...
2021/12/22 17:41:53.821325 Set up root directory for bucket transfert-apollo
2021/12/22 17:41:53.821329 OpenBucket("transfert-apollo", "")
2021/12/22 17:41:54.051963 Mounting file system "transfert-apollo"...
fuse: 2021/12/22 17:41:54.053103 writeMessage: invalid argument [80 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 7 0 0 0 22 0 0 0 0 0 16 0 32 0 65 0 12 0 9 0 0 0 16 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
2021/12/22 17:41:54.053132 File system has been successfully mounted.

# ls /test
ls: cannot access /test: Connection refused

No sure if the message I get "writeMessage: invalid argument " is normal.
Am I missing something ?

Thanks for your help

**Comment by cammorca** [comment]
Sorry forgot my issue.
Went back to 0.30.0 release and it works fine on my server

**Comment by surjikal** [comment]
Getting the exact same issue.

**Comment by avidullu** [comment]
Can you also pass --debug_fuse --debug_fs to the commandline with the latest version and let us know the logs so we can take a look?

**Comment by scommerot** [comment]
Can this be reopened?  I noticed the same error.
Before on Centos7 with version 0.35.0-1.x86_64, I did not have any issue. After I upgraded to version 0.36 (and even latest 0.41.1 has the same issue), I have that 'connection error' issue.

When using the debug, I see the same:
I0511 11:58:22.159048 OpenBucket("dasinfra-sap-business-sbx4-treasury-inbound", "")
D0511 11:58:22.159297 gcs: Req              0x0: <- ListObjects("")
D0511 11:58:22.250366 gcs: Req              0x0: -> ListObjects("") (91.061032ms): OK
D0511 11:58:22.251071 gcs: Req              0x1: <- ListObjects("")
D0511 11:58:22.284047 gcs: Req              0x1: -> ListObjects("") (32.969651ms): OK
N0511 11:58:22.284791 Mounting file system "dasinfra-sap-business-sbx4-treasury-inbound"...
D0511 11:58:22.289599 fuse_debug: Op 0x00000001        connection.go:416] <- init
D0511 11:58:22.290692 fuse_debug: Op 0x00000001        connection.go:498] -> OK ()
E0511 11:58:22.292100 fuse: writeMessage: invalid argument [80 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 7 0 0 0 22 0 0 0 0 0 16 0 32 0 65 0 12 0 9 0 0 0 16 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
N0511 11:58:22.293007 File system has been successfully mounted.



--- by stracing ls /mnt I can see the 
stat() call on the path  returns the error:

**Comment by avidullu** [comment]
Can reopen and try to reproduce on 0.41.1

**Comment by wadexu007** [comment]
Getting the exact same issue.

**Comment by sethiay** [comment]
Please let us know if you are still facing the issue with latest version of GCSFuse. If you are, then please also share the logs by mounting `gcsfuse` with `--debug_fuse --debug_fs --debug_gcs --debug_http --foreground`  flags.

**Comment by vadlakondaswetha** [comment]
Closing this as there is no response from the customer. Please reopen with logs incase you are still facing the issue.
