### ISSUE TITLE
gcsfuse reports success if mounting to a non-existent folder, debug flags hide errors

### ISSUE THREAD

**Issue by bzip2** [GoogleCloudPlatform/gcsfuse#589]
gcsfuse is great. I won't quibble about too many files open, but it shouldn't be so difficult to discover that you've misspelled the name of the bucket. It should be as easy as discovering that you've misspelled the name of the local directory. Even if you use debug_http, debug_fs, debug_fuse and/or debug_gcs (alone or in combination), gcsfuse reports success, without any indication of a problem:

> asdf@asdf:~$ gcsfuse --implicit-dirs --debug_http  --debug_fs --debug_fuse --debug_gcs foo fuse_to_bucket
> [date/time] Start gcsfuse/0.39.2 (Go version go1.17.5) for app "" using mount point: /home/asdf/fuse_to_bucket
> [date/time] Opening GCS connection...
> [date/time] Mounting file system "foo"...
> [date/time] **File system has been successfully mounted**.

If you look for files, permission is denied. After wasting time looking into service account permissions, here's how you find a clue:

> asdf@asdf:~$ gcsfuse --implicit-dirs **--foreground** foo fuse_to_bucket
> [...]
> [date/time] OpenBucket("foo", "")
> **WARNING, bucket doesn't appear to work:**  not retrying ListObjects(""): googleapi: Error 403: 123467890-compute_at_developer.gserviceaccount.com does not have storage.objects.list access to the Google Cloud Storage bucket., forbidden
> [date/time] Mounting file system "foo"...
> [date/time] File system has been successfully mounted.

If you misspell the local folder, you know immediately, without any debug flags:

> asdf@asdf:~$ gcsfuse --implicit-dirs foo somedir
> [date/time] Start gcsfuse/0.39.2 (Go version go1.17.5) for app "" using mount point: /home/asdf/somedir
> [date/time] Opening GCS connection...
> [date/time] Mounting file system "foo"...
> daemonize.Run: readFromProcess: sub-process: mountWithArgs: mountWithConn: Mount: stat /home/asdf/somedir: **no such file or directory**

Incidentally, I would also want to know by default about forbidden access rights to an existing folder. 

Version: 0.39.2 (Go version go1.17.5)

Where this happened: Google Cloud instance running Debian GNU/Linux 10 (buster)

Thanks!

**Comment by NWOdlk** [comment]
Can verify. Same issue here

**Comment by DavidLKing** [comment]
Can verify. Same issue here

**Comment by lezh** [comment]
This is an expected behavior. Gcsfuse has no way to tell if the bucket name is misspelled or actually intended. If the access is denied, it reports "Permission Denied".
