### ISSUE TITLE
Input/output error

### ISSUE THREAD

**Issue by vtrubets** [GoogleCloudPlatform/gcsfuse#59]
I'm receiving an Input/output error when attempting to access a mounted bucket.

The mounting appears to work:

    $ /home/vasya/go/bin/gcsfuse --key_file client_secret_1008716305589-3feumltnud52bo062jqgimof3t0uesri.apps.googleusercontent.com.json --bucket gs-fuse-test --mount_point /home/vasya/gs-fuse-test/
    2015/05/22 17:51:30.522507 Warning: low file rlimit of 1024 will cause cached content to be frequently evicted. Consider raising with `ulimit -n`.
    2015/05/22 17:51:30.523118 Initializing GCS connection.
    2015/05/22 17:51:30.525259 File system has been successfully mounted.

However, access fails:

    $ ls gs-fuse-test/
    ls: reading directory gs-fuse-test/: Input/output error

I'm using a n1-highcpu-16 machine type running the latest debian backports image ("backports-debian-7-wheezy-v20150423"; Debian, Debian GNU/Linux, 7.8 (wheezy), amd64 with backports kernel and SSH packages built on 2015-04-23). I have a default 10GB HDD Persistent Disk as storage.

Any thoughts about how to start picking this apart?

**Comment by jacobsa** [comment]
Hi, this is likely an authorization error (due to the wrong key or wrong bucket name). Can you try running with `--fuse.debug`? The output may be obvious.

**Comment by vtrubets** [comment]
Thanks for helping out with this!

The debugging output shows that it is indeed an authorization error.

Executing the same `ls gs-fuse-test/` command shows:

    2015/05/23 00:51:49.431505 Op 0x00000011         common_op.go:131] -> (ReadDir(inode=1)) error: readAllEntries: ReadEntries: ListObjects: Get https://www.googleapis.com/storage/v1/b/gs-fuse-test/o?delimiter=%2F&projection=full: private key should be a PEM or plain PKSC1 or PKCS8; parse error: asn1: syntax error: sequence truncated

This is my error. I am using a Client ID generated for a native application and not a service account. I'll talk to the project owner and get an appropriate Client ID.

**Comment by vtrubets** [comment]
Everything works with a proper service account Client ID.

Thanks again for taking a look at this jacob.
