### ISSUE TITLE
I mounted it using gcsfuse, but I can't see the contents of the bucket.

### ISSUE THREAD

**Issue by lsrrrrr** [GoogleCloudPlatform/gcsfuse#596]
I have a GCS Bucket mounted using gcsfuse on my VM, but I can't see the contents of the Bucket for some unknown reason.

Not only the capacity is not visible, but also read/write (ls, etc.) is not possible.

I created a new bucket, mounted it, and solved it temporarily.
However, the existing bucket is not yet visible after mounting.

Please tell me the cause and solution.

**Comment by lezh** [comment]
Did you specify `--implicit-dirs`? Check out the [mounting.md](https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/mounting.md)

**Comment by lezh** [comment]
This one documents the implicit dirs behaviors: https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/semantics.md#implicit-directories
