### ISSUE TITLE
Directory renaming feature broken and unit tests failing

### ISSUE THREAD

**Issue by thepenguinco** [GoogleCloudPlatform/gcsfuse#600]
[https://github.com/GoogleCloudPlatform/gcsfuse/pull/597](https://github.com/GoogleCloudPlatform/gcsfuse/pull/597) breaks directory renaming feature and causes unit tests in local_modifications_test.go to fail.

Run go test ./... in the gcsfuse directory to reproduce the issue.

**Comment by gaul** [comment]
Can you share your symptoms?  When I run `go test ./...` it seems like the tests hang with a zombie `fs.test` process.  Is it true that CI no longer runs the tests?  This seems like a regression from 2dee82339ae07fc8f2d8b2a7b592c560ab2ce2b4.

**Comment by lezh** [comment]
"Directory not empty" error occurs when renaming directory.

```
> git checkout v0.39.2
> go run .  --implicit-dirs --rename-dir-limit=100 gcsfuse-tests /gcs
> mv /gcs/d1/ /gcs/d2/
# success

> git checkout master
> go run .  --implicit-dirs --rename-dir-limit=100 gcsfuse-tests /gcs
> mv /gcs/d2/ /gcs/d1/
mv: cannot move '/gcs/d2/' to '/gcs/d1/': Directory not empty
```
