### ISSUE TITLE
Add arm64 support

### ISSUE THREAD

**Issue by kamilgregorczyk** [GoogleCloudPlatform/gcsfuse#619]
Have you considered adding support from arm64? I can't find a release for it, and installing gcsfuse from apt-get doesn't seem to work as it can't find the right package

**Comment by avidullu** [comment]
Does [this comment](https://github.com/GoogleCloudPlatform/gcsfuse/issues/378#issuecomment-806288959) help you in achieving what you're looking for?

**Comment by avidullu** [comment]
Closing due to inacticity and a suggested fix.
