### ISSUE TITLE
any changes done on GCS using gsutils do not sync with gcsfuse

### ISSUE THREAD

**Issue by rl55** [GoogleCloudPlatform/gcsfuse#621]
**Problem statement:** If a directory or file is created or moved using gsutils, gcsfuse does not show the changes even when implicit_dirs option is used to mount gcs 

**Steps to replicate:**
1. Mount a GCS bucket using gcsfuse. For example, in /etc/fstab -
_bucketname_ _mountpoint_ gcsfuse rw,implicit_dirs,x-systemd.requires=network-online.target,allow_other,uid=1004,gid=1005,key_file=_path to serviceaccount credentials json_

testbukcet /testbucket gcsfuse rw,implicit_dirs,x-systemd.requires=network-online.target,allow_other,uid=1004,gid=1005,key_file=/opt/gcsfuse/gcs_serviceaccount.json

2. Using gsutil, create a directory on the gcsbucket. For example: gsutil cp test.csv gs://testbucket/testfolder
3. Check for the newly created directory and file via the mapped drive/gcsfuse. For example: ls -la /testbucket

**Expected:** All changes on gcs made using gsutils must be reflected in the mounted gcsbucket via gcsfuse. On executing the above step 3, I should see testfolder under testbucket and a test.csv under testfolder.

**Actual:** From the cloud storage console, I can see the newly created testfolder on testbucket GCS bucket. But, I do not see the testfolder when I do ls /testbucket

**Comment by lezh** [comment]
Which Gcsfuse version is used? What is the OS?

**Comment by rl55** [comment]
GCS version: gcsfuse version 0.28.1 (Go version go1.9.7)
OS: Centos 7 kernel 3.10.0-1160.24.1.el7.x86_64

**Comment by avidullu** [comment]
Have you tried running with a latest version on go (1.16+) and gcsfuse (0.40) ?
Could you let us know if you observe the same behaviour with the recent builds?
