### ISSUE TITLE
Flaky tests in CI

### ISSUE THREAD

**Issue by thepenguinco** [GoogleCloudPlatform/gcsfuse#629]
Integration and unit tests are hanging in CI.

See example: https://github.com/GoogleCloudPlatform/gcsfuse/runs/5483547081?check_suite_focus=true

Running tests locally with go run ./... seems to pass all test cases without hanging.

**Comment by avidullu** [comment]
The recent pull request [here](https://github.com/GoogleCloudPlatform/gcsfuse/pull/651) passed successfully. Will keep this open if this reoccurs.

**Comment by sethiay** [comment]
Marking this issue closed as the fix mentioned in https://github.com/GoogleCloudPlatform/gcsfuse/issues/629#issuecomment-1099012965 had been released in v0.41.7 https://github.com/GoogleCloudPlatform/gcsfuse/releases/tag/v0.41.1. @thepenguinco, please feel free to open if the issue reoccurs.

**Comment by sethiay** [comment]
Closing as Integration and unit tests are no longer flaky.
