### ISSUE TITLE
"touch: setting times of 'my_file': Input/output error"

### ISSUE THREAD

**Issue by sromero89** [GoogleCloudPlatform/gcsfuse#637]
Every time the command "touch my_file" is executed this error is thrown "touch: setting times of 'my_file': Input/output error". I managed to mount the bucket correctly and indeed when I run the command the file is created in the bucket, but I always get the same error. I can read files with no problem (when I do I don't get the error), but the problem is with the "touch" command, I always get the same error. I am mounting the bucket on a GCE that has the scopes of GCS enabled (Full access) and I gave the Storage Admin role to the GCE's Service Account. In the same way, I explicitly added the SA to the users with bucket permissions and I always get the same result.

**Comment by thepenguinco** [comment]
What version and OS are you using?
Have you tried updating to the latest gcsfuse version? I am not able to reproduce this issue.

**Comment by avidullu** [comment]
Have you tried changing the contents of any existing file in the bucket when you have it mounted with gcsfuse?
If you can't save those changes, then would seem like you may not have write permissions for the bucket.

**Comment by avidullu** [comment]
Closing out due to inactivity.
