### ISSUE TITLE
Does GCSFUSE have restrictions on use?

### ISSUE THREAD

**Issue by MaggieLee2017** [GoogleCloudPlatform/gcsfuse#653]
Hi,
I want mount Cloud Storage buckets as file systems on Ubuntu system.
Ｗhen writing the test, after several tests in different scenarios, 5 can be successful, but when 10 tests are done, it will fail (Transport endpoint is not connected)
Referring to the report of gcsfuse, there are ERRORs as shown in the screenshot below. This type of error is repeatedly reported.
Does this mean that this is the upper limit of gcsfuse?
Or is there any other way we can avoid this error!

Thank you.

[thumbnail_image001](https://user-images.githubusercontent.com/34962564/163318042-cfd299e5-2b66-4b27-a4a4-88cd77791883.png)

**Comment by avidullu** [comment]
Thanks for reporting the issue.
Your screenshot does not show the "Transport endpoint is not connected" error. Could you please post a larger log?

Also the transport endpoint error is related to the connectivity loss issues. If your tests are very network heavy maybe try inserting a delay in between them to see if the error still persists?

**Comment by MaggieLee2017** [comment]
Hi,
Supplement more information such as attached three pictures.

1.The data starts to be stored, some files start to appear 0k, 'df -h' will show a question mark when viewing the disk.
2.disk 1 is the mount point of our device.
3.Unusual file size found, error found in list folder.

Thank you.

![2](https://user-images.githubusercontent.com/34962564/163334092-6d51c37b-2bd1-46d6-9dcb-73b796d10aee.png)
![3](https://user-images.githubusercontent.com/34962564/163334098-dd5a2932-9e2a-4b23-aa59-6cd4a79f0d4a.png)
![1](https://user-images.githubusercontent.com/34962564/163334080-45b3e54d-7227-464a-8bb8-d7a01d3c758d.png)

**Comment by MaggieLee2017** [comment]
@avidullu Can you understand what I'm trying to say?
I really want to use this tool.

**Comment by avidullu** [comment]
Would it be possible for you to run gcsfuse in debug mode by providing --foreground, --implicit-dirs, --debug_fs, --debug_fuse, --debug_gcs flags to the mount command? It will omit more logs for us to investigate.

**Comment by avidullu** [comment]
Additionally could you mount gcsfuse as a non root user?

**Comment by MaggieLee2017** [comment]
@avidullu  Thanks for the suggestion, I will tell you after trying it here.

**Comment by raj-prince** [comment]
Probable reason: GCSFuse would be crashing after some operations, due to that it shows error as "Transport endpoint is not connected". We have fixed a few similar crashes in gcsfuse, most probably this issue would have been fixed as part of that.

To know the exact reason we require gcsfuse logs which can be extracted by mounting gcsfuse fuse with`--debug_fuse` and `--debug_gcs` flag with the mount command.

Closing this issue as there is no response for a year. @MaggieLee2017 please feel free to open and attach the gcsfuse logs if you find it again.
