### ISSUE TITLE
too many open file descriptors when trying to copy files from one folder to another in a mounted bucket

### ISSUE THREAD

**Issue by rbavery** [GoogleCloudPlatform/gcsfuse#655]
I have a mounted directory that is mounted with the implicit dirs option

```
gcsfuse --implicit-dirs cv2-training data-cv2/
```

and I'm trying to copy some folders (about 90, each with a few pngs in each) from one folder to another

```
mv data-cv2/S1A* data-cv2/Coincident
```

but this results in an error. 

```
mv: cannot move 'data-cv2/S1A_IW_GRDH_1SDV_20210727T223312_20210727T223334_038969_049919_B9C1' to 'data-cv2/Coincident/S1A_IW_GRDH_1SDV_20210727T223312_20210727T223334_038969_049919_B9C1': Too many open files
mv: cannot move 'data-cv2/S1A_IW_GRDH_1SDV_20210820T223133_20210820T223158_039319_04A4B4_90DA' to 'data-cv2/Coincident/S1A_IW_GRDH_1SDV_20210820T223133_20210820T223158_039319_04A4B4_90DA': Too many open files
mv: cannot move 'data-cv2/S1A_IW_GRDH_1SDV_20210829T035235_20210829T035300_039439_04A8C6_48A7' to 'data-cv2/Coincident/S1A_IW_GRDH_1SDV_20210829T035235_20210829T035300_039439_04A8C6_48A7': Too many open files
....
```

I don't have files open by any other process so not sure why this is occurring, I've running this after a fresh reboot of my VM.

I'm using 
```
# gcsfuse --version
gcsfuse version 0.40.0 (Go version go1.17.6)
```

**Comment by avidullu** [comment]
Have you tried the --rename-dir-limit tip [suggested here](https://github.com/GoogleCloudPlatform/gcsfuse/issues/644#issuecomment-1082235633)

**Comment by sethiay** [comment]
Assuming that https://github.com/GoogleCloudPlatform/gcsfuse/issues/655#issuecomment-1104720094 worked. Closing this issue, please re-open if you still face the issue.
