### ISSUE TITLE
fusermount: exit status 1

### ISSUE THREAD

**Issue by lappazos** [GoogleCloudPlatform/gcsfuse#661]
i'm trying to mount a folder on Cloud run container, and getting 
`daemonize.Run: readFromProcess: sub-process: mountWithArgs: mountWithConn: Mount: mount: running /bin/fusermount: exit status 1`

I'm following this [guide](https://cloud.google.com/run/docs/tutorials/network-filesystems-fuse#cloudrun_fs_script-python).
I checked, and user is root, as so the ownership of the folder (which I created with mkdir just before calling to gcsfuse), so it doesn't appear to be [that bug](https://serverfault.com/questions/1085763/unable-to-mount-fs-as-a-non-root-user)

**Comment by avidullu** [comment]
Can you please enable --foreground --debug_fs --debug_fuse to the gcsfuse mount command and share the logs?

**Comment by lappazos** [comment]
Solved - i think the problem was both the missing roles/storage.objectAdmin, 
and in the deploy command, I was missing the beta, and the 2nd generatino

**Comment by avidullu** [comment]
Appreciate the turnaround!
