### ISSUE TITLE
--implicit-dirs behaviour changes when bucket name has gs:// specified

### ISSUE THREAD

**Issue by lfearnley** [GoogleCloudPlatform/gcsfuse#672]
Unexpected behaviour (to me at least) - showing implicit directories seems to fail in 0.41.1 if the bucket name is specified as gs://<bucket_name>/, but not when specified as <bucket_name>.

bl_202205_lbd is a bucket with two empty folders and a third folder containing a text file. The folders were created and the text file was uploaded via the storage browser.

gcsfuse with --implicit-dirs shows the directories as expected with bucket name `bl_202205_lbd`:

    fearnley_l@instance-1:~$ gcsfuse --implicit-dirs bl_202205_lbd bl_202205_lbd/
    2022/05/13 03:22:30.756615 Start gcsfuse/0.41.1 (Go version go1.17.6) for app "" using mount point: /home/fearnley_l/bl_202205_lbd
    2022/05/13 03:22:30.773782 Opening GCS connection...
    2022/05/13 03:22:30.901324 Mounting file system "bl_202205_lbd"...
    2022/05/13 03:22:30.907367 File system has been successfully mounted.
    fearnley_l@instance-1:~$ ls -l bl_202205_lbd/
    total 0
    drwxr-xr-x 1 fearnley_l fearnley_l 0 May 13 03:22 core
    drwxr-xr-x 1 fearnley_l fearnley_l 0 May 13 03:22 results
    drwxr-xr-x 1 fearnley_l fearnley_l 0 May 13 03:22 tmp

But not with `gs://bl_202205_lbd/`:

    fearnley_l@instance-1:~$ gcsfuse --implicit-dirs gs://bl_202205_lbd/ bl_202205_lbd/
    2022/05/13 03:22:46.643456 Start gcsfuse/0.41.1 (Go version go1.17.6) for app "" using mount point: /home/fearnley_l/bl_202205_lbd
    2022/05/13 03:22:46.658841 Opening GCS connection...
    2022/05/13 03:22:46.946711 Mounting file system "gs://bl_202205_lbd/"...
    2022/05/13 03:22:46.954113 File system has been successfully mounted.
    fearnley_l@instance-1:~$ ls -l bl_202205_lbd/
    total 0

**Comment by avidullu** [comment]
That's expected behaviour. PTAL at https://github.com/GoogleCloudPlatform/gcsfuse#invoking-gcsfuse which calls out how to invoke gcsfuse and it mentions 'bucket_name' without any protocols.

**Comment by lfearnley** [comment]
Sorry for the reopen - can tag this as a request if more appropriate - should gcsfuse fail explicitly if a protocol is specified in the bucket name?
