### ISSUE TITLE
Upgrade Go runtime to 1.17.12 or 1.18.4 to mitigate CVE vulnerabilities

### ISSUE THREAD

**Issue by sshcherbakov** [GoogleCloudPlatform/gcsfuse#728]
gcsfuse in its current version is being flagged as a source of multiple Critical CVE vulnerabilities by the security vulnerability scanners such as JFrog XRay or Google on-demand Artifactory Registry scanning because of its dependency on the outdated Go language runtime.

Please upgrade the Go runtime to the latest 1.17.x or 1.18.x versions.

**Comment by avidullu** [comment]
Updated to 1.18.4
