### ISSUE TITLE
--op_rate_limit_hz isn't entirely clear

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcsfuse#73]
I know 1hz is a "cycle/op per second" but I don't know if the majority of our users would understand this.

Maybe we should consider making this parameter something more explicit? Some options:

- `--limit-ops-per-sec`
- `--limit-qps`
- `--limit-ops` (where "ops" here means "**o**perations **p**er **s**econd"

?

**Comment by jacobsa** [comment]
Agreed, will go for `--limit-ops-per-sec` and `--limit-bytes-per-sec`.
