### ISSUE TITLE
System file type/ProxMox Backup Server

### ISSUE THREAD

**Issue by mounssim** [GoogleCloudPlatform/gcsfuse#733]
Hello,

I have mounted GCS with gcsfuse to ProxMox Backup Server /Debian, however I am not able to read/write into it, I am getting the bellow error:

mkdir: cannot create directory ‘/mnt/GCPStorage/Test’: Input/output error

I thin ProxMox is not able to read /write to the mount since the fs type is "fuse.gcsfuse "
Could you please help me,

**Comment by vadlakondaswetha** [comment]
Hi,

Couple of questions:
1. Can you list down the steps of how you mounted gcs to ProxMox Backup server and what operations you have performed after that.
2. When you say you are not able to read/write into the mounted folder -> how are you doing the reads/write using some tool or just via command line.
3. Please share the complete logs of gcsfuse by enabling --debug_http, --debug_fs, --debug_fuse, --debug_gcs.
4. I thin ProxMox is not able to read /write to the mount since the fs type is "fuse.gcsfuse " -> IMO fuse type shouldn't matter. Accessing gcsfuse mounted directory should be similar to accessing any other directory on the machine.

**Comment by mounssim** [comment]
@avidullu thanks for your reply and sorry for the late reply, please see the details bellow as requested:
1. Can you list down the steps of how you mounted gcs to ProxMox Backup server and what operations you have performed after that.

Created a bucket and a service account with Admin Role for the Bucket
root@dw-pbs001:/usr/local/sbin# cat my-startup.sh
#!/bin/sh
export GOOGLE_APPLICATION_CREDENTIALS=/mnt/gcptoken.json
gcsfuse my-bucket/PBSBackups /mnt/GCPStorage/ type ext4

#crontab
@reboot  /usr/local/sbin/my-startup.sh

# we can see that the bucket is mounted
root@dw-pbs001:/usr/local/sbin# df -Th
Filesystem                           Type          Size  Used Avail Use% Mounted on
darewise-nas-backup-infra/PBSBackups fuse.gcsfuse  1.0P     0  1.0P   0% /mnt/GCPStorage
tmpfs                                tmpfs         375M   20K  375M   1% /run/user/0

2. When you say you are not able to read/write into the mounted folder -> how are you doing the reads/write using some tool or just via command line.

Using command line and PBS/ProxMox Backup Server I got the error see bellow:
root@dw-pbs001:/mnt/GCPStorage# mkdir test
mkdir: cannot create directory ‘test’: Input/output error

or when I try to create a datastore within PBS GUI interface or command line again.

3. Please share the complete logs of gcsfuse by enabling --debug_http, --debug_fs, --debug_fuse, --debug_gcs.
Could you please tell how to enable them?

**Comment by vadlakondaswetha** [comment]
in the mount step you should pass these flags. i.e., 
gcsfuse --debug_fs --debug_gcs --debug_fuse --debug_http my-bucket/PBSBackups /mnt/GCPStorage/  

Also use --log-file=output.json and --log-format=json to export logs to a file.

**Comment by mounssim** [comment]
@vadlakondaswetha thanks for your reply.
I made the changes, I am sorry, may I know where are the logs are exported to "--log-file=output.json and --log-format=json"?

**Comment by vadlakondaswetha** [comment]
They should be exported to a file named output.json. if you are not able to find the file because of relative path please provide the absolute path so that you can find the file, something like ~/Desktop/output.json.

**Comment by mounssim** [comment]
@vadlakondaswetha, 
after I added the options the mount command is not working anymore:
gcsfuse --debug_fs --debug_gcs --debug_fuse --debug_http --log-file=~/Desktop/output.json --log-format=json my-bucket/PBSBackups /mnt/GCPStorage/

**Comment by vadlakondaswetha** [comment]
Sorry, right now path starting with ~ is not working. Try giving any absolute path without ~.

Also can you tell if gcsfuse without ProxMax backup server is working fine. Right now we don't support running gcsfuse in conjuction with other tools.

**Comment by mounssim** [comment]
Hello @vadlakondaswetha ,
please see bellow the logs:

{"name":"root","levelname":"INFO","severity":"INFO","message":"Start gcsfuse/0.41.4 (Go version go1.17.6) for app \"\" using mount point: /mnt/GCPStorage\n","timestampSeconds":1660202124,"timestampNanos":84460583}
{"name":"root","levelname":"NOTICE","severity":"NOTICE","message":"Opening GCS connection...\n","timestampSeconds":1660202124,"timestampNanos":84621981}
{"name":"root","levelname":"INFO","severity":"INFO","message":"Creating a mount at \"/mnt/GCPStorage\"\n","timestampSeconds":1660202124,"timestampNanos":85380262}
{"name":"root","levelname":"INFO","severity":"INFO","message":"Creating a new server...\n","timestampSeconds":1660202124,"timestampNanos":85973409}
{"name":"root","levelname":"INFO","severity":"INFO","message":"Set up root directory for bucket my-bucket/PBSBackups\n","timestampSeconds":1660202124,"timestampNanos":86000748}
{"name":"root","levelname":"INFO","severity":"INFO","message":"OpenBucket(\"my-bucket/PBSBackups\", \"\")\n","timestampSeconds":1660202124,"timestampNanos":86016295}
{"name":"root","levelname":"DEBUG","severity":"DEBUG","message":"gcs: Req              0x0: \u003c- ListObjects(\"\")\n","timestampSeconds":1660202124,"timestampNanos":86050191}
{"name":"root","levelname":"DEBUG","severity":"DEBUG","message":"http: ========== REQUEST:\nGET http://storage.googleapis.com:443/storage/v1/b/my-bucket%2FPBSBackups/o?maxResults=1\u0026projection=full HTTP/1.1\r\nHost: storage.googleapis.com:443\r\nUser-Agent: gcsfuse/0.41.4 (Go version go1.17.6) \r\nAuthorization: Bearer ya29.c.b0AXv0zTNMzOdetTnllXnzh2A8WTBMdsWROcr4S-QIe5KDhSOxurP4A4pzVP6z26zV31kS4CKW2QUMzHoe07uQb48m4iFk8UEmqq4zHKka5vkPfLOFqi27L7AykZVEk_OJwOTEREWt1knZZWAyr0umRt8TmLccv0Fbwqg2IIzNwa38CQplf_ldX_jr2o1N5UxY9lrvw2P9_5zyAPMZAvZS8b21snUio2o........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................\r\nAccept-Encoding: gzip\r\n\r\n","timestampSeconds":1660202124,"timestampNanos":184636597}
{"name":"root","levelname":"DEBUG","severity":"DEBUG","message":"http: ========== RESPONSE:\nHTTP/2.0 404 Not Found\r\nContent-Length: 247\r\nAlt-Svc: h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"\r\nCache-Control: no-cache, no-store, max-age=0, must-revalidate\r\nContent-Type: application/json; charset=UTF-8\r\nDate: Thu, 11 Aug 2022 07:15:24 GMT\r\nExpires: Mon, 01 Jan 1990 00:00:00 GMT\r\nPragma: no-cache\r\nServer: UploadServer\r\nVary: Origin\r\nVary: X-Origin\r\nX-Guploader-Uploadid: ADPycdtAI_YSBuRm5EQ3tDVxYFQbvUpRlRiw0ofuZwFfGm_4mrTCbvE6RXtGsFfAL4yZoX15VnPgX7ksCwhluPoK1x_3VkX08nrs\r\n\r\n{\n  \"error\": {\n    \"code\": 404,\n    \"message\": \"The specified bucket does not exist.\",\n    \"errors\": [\n      {\n        \"message\": \"The specified bucket does not exist.\",\n        \"domain\": \"global\",\n        \"reason\": \"notFound\"\n      }\n    ]\n  }\n}\n","timestampSeconds":1660202124,"timestampNanos":600658737}
{"name":"root","levelname":"DEBUG","severity":"DEBUG","message":"http: ====================\n","timestampSeconds":1660202124,"timestampNanos":600742752}
{"name":"root","levelname":"DEBUG","severity":"DEBUG","message":"gcs: Req              0x0: -\u003e ListObjects(\"\") (514.851725ms): not retrying ListObjects(\"\"): googleapi: Error 404: The specified bucket does not exist., notFound\n","timestampSeconds":1660202124,"timestampNanos":600905321}
{"name":"root","levelname":"DEBUG","severity":"DEBUG","message":"gcs: Req              0x1: \u003c- ListObjects(\"\")\n","timestampSeconds":1660202124,"timestampNanos":600959492}
{"name":"root","levelname":"DEBUG","severity":"DEBUG","message":"http: ========== REQUEST:\nGET http://storage.googleapis.com:443/storage/v1/b/my-bucket%2FPBSBackups/o?maxResults=1\u0026projection=full HTTP/1.1\r\nHost: storage.googleapis.com:443\r\nUser-Agent: gcsfuse/0.41.4 (Go version go1.17.6) \r\nAuthorization: Bearer ya29.c.b0AXv0zTNMzOdetTnllXnzh2A8WTBMdsWROcr4S-QIe5KDhSOxurP4A4pzVP6z26zV31kS4CKW2QUMzHoe07uQb48m4iFk8UEmqq4zHKka5vkPfLOFqi27L7AykZVEk_OJwOTEREWt1knZZWAyr0umRt8TmLccv0Fbwqg2IIzNwa38CQplf_ldX_jr2o1N5UxY9lrvw2P9_5zyAPMZAvZS8b21snUio2o........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................\r\nAccept-Encoding: gzip\r\n\r\n","timestampSeconds":1660202124,"timestampNanos":601209938}
{"name":"root","levelname":"DEBUG","severity":"DEBUG","message":"http: ========== RESPONSE:\nHTTP/2.0 404 Not Found\r\nContent-Length: 247\r\nAlt-Svc: h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"\r\nCache-Control: no-cache, no-store, max-age=0, must-revalidate\r\nContent-Type: application/json; charset=UTF-8\r\nDate: Thu, 11 Aug 2022 07:15:25 GMT\r\nExpires: Mon, 01 Jan 1990 00:00:00 GMT\r\nPragma: no-cache\r\nServer: UploadServer\r\nVary: Origin\r\nVary: X-Origin\r\nX-Guploader-Uploadid: ADPycdtEPwHrnLuDOQNcvAkjpDvHQss9MLl9osEymXL0BsadVCfkgyGp8CmkWEIofPZMlQxDHa3uv0wrqeEQy5UBSr00F9uLW7aM\r\n\r\n{\n  \"error\": {\n    \"code\": 404,\n    \"message\": \"The specified bucket does not exist.\",\n    \"errors\": [\n      {\n        \"message\": \"The specified bucket does not exist.\",\n        \"domain\": \"global\",\n        \"reason\": \"notFound\"\n      }\n    ]\n  }\n}\n","timestampSeconds":1660202124,"timestampNanos":890482263}
{"name":"root","levelname":"DEBUG","severity":"DEBUG","message":"http: ====================\n","timestampSeconds":1660202124,"timestampNanos":890523393}
{"name":"root","levelname":"DEBUG","severity":"DEBUG","message":"gcs: Req              0x1: -\u003e ListObjects(\"\") (289.620616ms): not retrying ListObjects(\"\"): googleapi: Error 404: The specified bucket does not exist., notFound\n","timestampSeconds":1660202124,"timestampNanos":890582513}
{"name":"root","levelname":"NOTICE","severity":"NOTICE","message":"Mounting file system \"my-bucket/PBSBackups\"...\n","timestampSeconds":1660202124,"timestampNanos":890622571}
{"name":"root","levelname":"DEBUG","severity":"DEBUG","message":"fuse_debug: Op 0x00000002        connection.go:416] \u003c- init\n","timestampSeconds":1660202124,"timestampNanos":893619000}
{"name":"root","levelname":"DEBUG","severity":"DEBUG","message":"fuse_debug: Op 0x00000002        connection.go:498] -\u003e OK ()\n","timestampSeconds":1660202124,"timestampNanos":893687660}
{"name":"root","levelname":"NOTICE","severity":"NOTICE","message":"File system has been successfully mounted.\n","timestampSeconds":1660202124,"timestampNanos":893733729}
{"name":"root","levelname":"INFO","severity":"INFO","message":"Starting a garbage collection run.\n","timestampSeconds":1660202724,"timestampNanos":891841279}
{"name":"root","levelname":"DEBUG","severity":"DEBUG","message":"gcs: Req              0x2: \u003c- ListObjects(\".gcsfuse_tmp/\")\n","timestampSeconds":1660202724,"timestampNanos":892078296}
{"name":"root","levelname":"DEBUG","severity":"DEBUG","message":"http: ========== REQUEST:\nGET http://storage.googleapis.com:443/storage/v1/b/my-bucket%2FPBSBackups/o?prefix=.gcsfuse_tmp%2F\u0026projection=full HTTP/1.1\r\nHost: storage.googleapis.com:443\r\nUser-Agent: gcsfuse/0.41.4 (Go version go1.17.6) \r\nAuthorization: Bearer ya29.c.b0AXv0zTNMzOdetTnllXnzh2A8WTBMdsWROcr4S-QIe5KDhSOxurP4A4pzVP6z26zV31kS4CKW2QUMzHoe07uQb48m4iFk8UEmqq4zHKka5vkPfLOFqi27L7AykZVEk_OJwOTEREWt1knZZWAyr0umRt8TmLccv0Fbwqg2IIzNwa38CQplf_ldX_jr2o1N5UxY9lrvw2P9_5zyAPMZAvZS8b21snUio2o........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................\r\nAccept-Encoding: gzip\r\n\r\n","timestampSeconds":1660202724,"timestampNanos":892339404}
{"name":"root","levelname":"DEBUG","severity":"DEBUG","message":"http: ========== RESPONSE:\nHTTP/2.0 404 Not Found\r\nContent-Length: 247\r\nAlt-Svc: h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"\r\nCache-Control: no-cache, no-store, max-age=0, must-revalidate\r\nContent-Type: application/json; charset=UTF-8\r\nDate: Thu, 11 Aug 2022 07:25:25 GMT\r\nExpires: Mon, 01 Jan 1990 00:00:00 GMT\r\nPragma: no-cache\r\nServer: UploadServer\r\nVary: Origin\r\nVary: X-Origin\r\nX-Guploader-Uploadid: ADPycdvstZBA4LKMt7cf1gQjIfO5nhWaKyjKR3zvPq-Y2DB-HJmQCjnRx-bGyTbvzn9U8PSqSldk4BS7AsvivdqNKhvIOjcdPaBh\r\n\r\n{\n  \"error\": {\n    \"code\": 404,\n    \"message\": \"The specified bucket does not exist.\",\n    \"errors\": [\n      {\n        \"message\": \"The specified bucket does not exist.\",\n        \"domain\": \"global\",\n        \"reason\": \"notFound\"\n      }\n    ]\n  }\n}\n","timestampSeconds":1660202725,"timestampNanos":522421957}
{"name":"root","levelname":"DEBUG","severity":"DEBUG","message":"http: ====================\n","timestampSeconds":1660202725,"timestampNanos":522544137}
{"name":"root","levelname":"DEBUG","severity":"DEBUG","message":"gcs: Req              0x2: -\u003e ListObjects(\".gcsfuse_tmp/\") (630.536875ms): not retrying ListObjects(\".gcsfuse_tmp/\"): googleapi: Error 404: The specified bucket does not exist., notFound\n","timestampSeconds":1660202725,"timestampNanos":522612263}
{"name":"root","levelname":"INFO","severity":"INFO","message":"Garbage collection failed after deleting 0 objects in 630.675185ms, with error: ListPrefix: ListObjects: not retrying ListObjects(\".gcsfuse_tmp/\"): googleapi: Error 404: The specified bucket does not exist., notFound\n","timestampSeconds":1660202725,"timestampNanos":522664671}
{"name":"root","levelname":"INFO","severity":"INFO","message":"Starting a garbage collection run.\n","timestampSeconds":1660203324,"timestampNanos":891018481}
{"name":"root","levelname":"DEBUG","severity":"DEBUG","message":"gcs: Req              0x3: \u003c- ListObjects(\".gcsfuse_tmp/\")\n","timestampSeconds":1660203324,"timestampNanos":891173349}
{"name":"root","levelname":"DEBUG","severity":"DEBUG","message":"http: ========== REQUEST:\nGET http://storage.googleapis.com:443/storage/v1/b/my-bucket%2FPBSBackups/o?prefix=.gcsfuse_tmp%2F\u0026projection=full HTTP/1.1\r\nHost: storage.googleapis.com:443\r\nUser-Agent: gcsfuse/0.41.4 (Go version go1.17.6) \r\nAuthorization: Bearer ya29.c.b0AXv0zTNMzOdetTnllXnzh2A8WTBMdsWROcr4S-QIe5KDhSOxurP4A4pzVP6z26zV31kS4CKW2QUMzHoe07uQb48m4iFk8UEmqq4zHKka5vkPfLOFqi27L7AykZVEk_OJwOTEREWt1knZZWAyr0umRt8TmLccv0Fbwqg2IIzNwa38CQplf_ldX_jr2o1N5UxY9lrvw2P9_5zyAPMZAvZS8b21snUio2o........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................\r\nAccept-Encoding: gzip\r\n\r\n","timestampSeconds":1660203324,"timestampNanos":891387656}
{"name":"root","levelname":"DEBUG","severity":"DEBUG","message":"http: ========== RESPONSE:\nHTTP/2.0 404 Not Found\r\nContent-Length: 247\r\nAlt-Svc: h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"\r\nCache-Control: no-cache, no-store, max-age=0, must-revalidate\r\nContent-Type: application/json; charset=UTF-8\r\nDate: Thu, 11 Aug 2022 07:35:25 GMT\r\nExpires: Mon, 01 Jan 1990 00:00:00 GMT\r\nPragma: no-cache\r\nServer: UploadServer\r\nVary: Origin\r\nVary: X-Origin\r\nX-Guploader-Uploadid: ADPycdvrxNW8fdSWw8KdgBvu00sspRZT8Y5byfJklwyhBLG3KoYTVba8buNQe4t-ghBaz5-cs4DOYdCCHYYK03UCdsbFqUO6v7hf\r\n\r\n{\n  \"error\": {\n    \"code\": 404,\n    \"message\": \"The specified bucket does not exist.\",\n    \"errors\": [\n      {\n        \"message\": \"The specified bucket does not exist.\",\n        \"domain\": \"global\",\n        \"reason\": \"notFound\"\n      }\n    ]\n  }\n}\n","timestampSeconds":1660203325,"timestampNanos":393338518}
{"name":"root","levelname":"DEBUG","severity":"DEBUG","message":"http: ====================\n","timestampSeconds":1660203325,"timestampNanos":393440556}
{"name":"root","levelname":"DEBUG","severity":"DEBUG","message":"gcs: Req              0x3: -\u003e ListObjects(\".gcsfuse_tmp/\") (502.37015ms): not retrying ListObjects(\".gcsfuse_tmp/\"): googleapi: Error 404: The specified bucket does not exist., notFound\n","timestampSeconds":1660203325,"timestampNanos":393542299}
{"name":"root","levelname":"INFO","severity":"INFO","message":"Garbage collection failed after deleting 0 objects in 502.501003ms, with error: ListPrefix: ListObjects: not retrying ListObjects(\".gcsfuse_tmp/\"): googleapi: Error 404: The specified bucket does not exist., notFound\n","timestampSeconds":1660203325,"timestampNanos":393610711}
{"name":"root","levelname":"INFO","severity":"INFO","message":"Starting a garbage collection run.\n","timestampSeconds":1660203924,"timestampNanos":894368974}
{"name":"root","levelname":"DEBUG","severity":"DEBUG","message":"gcs: Req              0x4: \u003c- ListObjects(\".gcsfuse_tmp/\")\n","timestampSeconds":1660203924,"timestampNanos":894587324}
{"name":"root","levelname":"DEBUG","severity":"DEBUG","message":"http: ========== REQUEST:\nGET http://storage.googleapis.com:443/storage/v1/b/my-bucket%2FPBSBackups/o?prefix=.gcsfuse_tmp%2F\u0026projection=full HTTP/1.1\r\nHost: storage.googleapis.com:443\r\nUser-Agent: gcsfuse/0.41.4 (Go version go1.17.6) \r\nAuthorization: Bearer ya29.c.b0AXv0zTNMzOdetTnllXnzh2A8WTBMdsWROcr4S-QIe5KDhSOxurP4A4pzVP6z26zV31kS4CKW2QUMzHoe07uQb48m4iFk8UEmqq4zHKka5vkPfLOFqi27L7AykZVEk_OJwOTEREWt1knZZWAyr0umRt8TmLccv0Fbwqg2IIzNwa38CQplf_ldX_jr2o1N5UxY9lrvw2P9_5zyAPMZAvZS8b21snUio2o........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................\r\nAccept-Encoding: gzip\r\n\r\n","timestampSeconds":1660203924,"timestampNanos":894869992}
{"name":"root","levelname":"DEBUG","severity":"DEBUG","message":"http: ========== RESPONSE:\nHTTP/2.0 404 Not Found\r\nContent-Length: 247\r\nAlt-Svc: h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"\r\nCache-Control: no-cache, no-store, max-age=0, must-revalidate\r\nContent-Type: application/json; charset=UTF-8\r\nDate: Thu, 11 Aug 2022 07:45:25 GMT\r\nExpires: Mon, 01 Jan 1990 00:00:00 GMT\r\nPragma: no-cache\r\nServer: UploadServer\r\nVary: Origin\r\nVary: X-Origin\r\nX-Guploader-Uploadid: ADPycdtWrMQJn664zd9d2i33jzpP-lP9FA6VlZHBg9W-GdtyXwijt1Rr9Po2G1ja65KndCKaAoM_iZuVNodrRUDNvxrwi-bzNR3N\r\n\r\n{\n  \"error\": {\n    \"code\": 404,\n    \"message\": \"The specified bucket does not exist.\",\n    \"errors\": [\n      {\n        \"message\": \"The specified bucket does not exist.\",\n        \"domain\": \"global\",\n        \"reason\": \"notFound\"\n      }\n    ]\n  }\n}\n","timestampSeconds":1660203925,"timestampNanos":579999564}
{"name":"root","levelname":"DEBUG","severity":"DEBUG","message":"http: ====================\n","timestampSeconds":1660203925,"timestampNanos":580132281}
{"name":"root","levelname":"DEBUG","severity":"DEBUG","message":"gcs: Req              0x4: -\u003e ListObjects(\".gcsfuse_tmp/\") (685.649326ms): not retrying ListObjects(\".gcsfuse_tmp/\"): googleapi: Error 404: The specified bucket does not exist., notFound\n","timestampSeconds":1660203925,"timestampNanos":580234715}
{"name":"root","levelname":"INFO","severity":"INFO","message":"Garbage collection failed after deleting 0 objects in 685.791776ms, with error: ListPrefix: ListObjects: not retrying ListObjects(\".gcsfuse_tmp/\"): googleapi: Error 404: The specified bucket does not exist., notFound\n","timestampSeconds":1660203925,"timestampNanos":580309758}
{"name":"root","levelname":"DEBUG","severity":"DEBUG","message":"fuse_debug: Op 0x00000004        connection.go:416] \u003c- GetInodeAttributes (inode 1, PID 1002)\n","timestampSeconds":1660204381,"timestampNanos":758025033}
{"name":"root","levelname":"DEBUG","severity":"DEBUG","message":"debug_fs: GetInodeAttributes(1): \u003cnil\u003e\n","timestampSeconds":1660204381,"timestampNanos":758366106}
{"name":"root","levelname":"DEBUG","severity":"DEBUG","message":"fuse_debug: Op 0x00000004        connection.go:498] -\u003e OK ()\n","timestampSeconds":1660204381,"timestampNanos":758540894}
{"name":"root","levelname":"DEBUG","severity":"DEBUG","message":"fuse_debug: Op 0x00000006        connection.go:416] \u003c- StatFS\n","timestampSeconds":1660204381,"timestampNanos":759629118}
{"name":"root","levelname":"DEBUG","severity":"DEBUG","message":"debug_fs: StatFS(): \u003cnil\u003e\n","timestampSeconds":1660204381,"timestampNanos":759775728}
{"name":"root","levelname":"DEBUG","severity":"DEBUG","message":"fuse_debug: Op 0x00000006        connection.go:498] -\u003e OK ()\n","timestampSeconds":1660204381,"timestampNanos":759891180}
{"name":"root","levelname":"DEBUG","severity":"DEBUG","message":"fuse_debug: Op 0x00000008        connection.go:416] \u003c- StatFS\n","timestampSeconds":1660204390,"timestampNanos":510279624}
{"name":"root","levelname":"DEBUG","severity":"DEBUG","message":"debug_fs: StatFS(): \u003cnil\u003e\n","timestampSeconds":1660204390,"timestampNanos":510485853}
{"name":"root","levelname":"DEBUG","severity":"DEBUG","message":"fuse_debug: Op 0x00000008        connection.go:498] -\u003e OK ()\n","timestampSeconds":1660204390,"timestampNanos":510617441}
{"name":"root","levelname":"DEBUG","severity":"DEBUG","message":"fuse_debug: Op 0x0000000a        connection.go:416] \u003c- LookUpInode (parent 1, name \"Test\", PID 1014)\n","timestampSeconds":1660204432,"timestampNanos":156124695}
{"name":"root","levelname":"DEBUG","severity":"DEBUG","message":"gcs: Req              0x5: \u003c- StatObject(\"Test/\")\n","timestampSeconds":1660204432,"timestampNanos":156346436}
{"name":"root","levelname":"DEBUG","severity":"DEBUG","message":"gcs: Req              0x6: \u003c- StatObject(\"Test\")\n","timestampSeconds":1660204432,"timestampNanos":156869290}
{"name":"root","levelname":"DEBUG","severity":"DEBUG","message":"http: ========== REQUEST:\nGET http://storage.googleapis.com:443/storage/v1/b/my-bucket%2FPBSBackups/o/Test%2F?projection=full HTTP/1.1\r\nHost: storage.googleapis.com:443\r\nUser-Agent: gcsfuse/0.41.4 (Go version go1.17.6) \r\nAuthorization: Bearer ya29.c.b0AXv0zTNMzOdetTnllXnzh2A8WTBMdsWROcr4S-QIe5KDhSOxurP4A4pzVP6z26zV31kS4CKW2QUMzHoe07uQb48m4iFk8UEmqq4zHKka5vkPfLOFqi27L7AykZVEk_OJwOTEREWt1knZZWAyr0umRt8TmLccv0Fbwqg2IIzNwa38CQplf_ldX_jr2o1N5UxY9lrvw2P9_5zyAPMZAvZS8b21snUio2o........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................\r\nAccept-Encoding: gzip\r\n\r\n","timestampSeconds":1660204432,"timestampNanos":157036976}
{"name":"root","levelname":"DEBUG","severity":"DEBUG","message":"http: ========== REQUEST:\nGET http://storage.googleapis.com:443/storage/v1/b/my-bucket%2FPBSBackups/o/Test?projection=full HTTP/1.1\r\nHost: storage.googleapis.com:443\r\nUser-Agent: gcsfuse/0.41.4 (Go version go1.17.6) \r\nAuthorization: Bearer ya29.c.b0AXv0zTNMzOdetTnllXnzh2A8WTBMdsWROcr4S-QIe5KDhSOxurP4A4pzVP6z26zV31kS4CKW2QUMzHoe07uQb48m4iFk8UEmqq4zHKka5vkPfLOFqi27L7AykZVEk_OJwOTEREWt1knZZWAyr0umRt8TmLccv0Fbwqg2IIzNwa38CQplf_ldX_jr2o1N5UxY9lrvw2P9_5zyAPMZAvZS8b21snUio2o........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................\r\nAccept-Encoding: gzip\r\n\r\n","timestampSeconds":1660204432,"timestampNanos":157275837}
{"name":"root","levelname":"DEBUG","severity":"DEBUG","message":"http: ========== RESPONSE:\nHTTP/2.0 400 Bad Request\r\nContent-Length: 292\r\nAlt-Svc: h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"\r\nCache-Control: no-cache, no-store, max-age=0, must-revalidate\r\nContent-Type: application/json; charset=UTF-8\r\nDate: Thu, 11 Aug 2022 07:53:52 GMT\r\nExpires: Mon, 01 Jan 1990 00:00:00 GMT\r\nPragma: no-cache\r\nServer: UploadServer\r\nVary: Origin\r\nVary: X-Origin\r\nX-Guploader-Uploadid: ADPycdusf_uZDWJmBQFt8nIEf7SzNMU9DTgKSi56x7p0ibKzf-jLvCBooLrsF7_zy7IfakVn0N4ULI8A5IT8SWPZN9YQ\r\n\r\n{\n  \"error\": {\n    \"code\": 400,\n    \"message\": \"Invalid bucket name: 'my-bucket/PBSBackups'\",\n    \"errors\": [\n      {\n        \"message\": \"Invalid bucket name: 'my-bucket/PBSBackups'\",\n        \"domain\": \"global\",\n        \"reason\": \"invalid\"\n      }\n    ]\n  }\n}\n","timestampSeconds":1660204432,"timestampNanos":436040819}
{"name":"root","levelname":"DEBUG","severity":"DEBUG","message":"http: ====================\n","timestampSeconds":1660204432,"timestampNanos":436135655}
{"name":"root","levelname":"DEBUG","severity":"DEBUG","message":"gcs: Req              0x6: -\u003e StatObject(\"Test\") (279.839854ms): not retrying StatObject(\"Test\"): googleapi: Error 400: Invalid bucket name: 'my-bucket/PBSBackups', invalid\n","timestampSeconds":1660204432,"timestampNanos":436210621}
{"name":"root","levelname":"DEBUG","severity":"DEBUG","message":"gcs: Req              0x5: -\u003e StatObject(\"Test/\") (279.941898ms): not retrying StatObject(\"Test/\"): Get \"https://storage.googleapis.com:443/storage/v1/b/my-bucket%2FPBSBackups/o/Test%2F?projection=full\": net/http: request canceled\n","timestampSeconds":1660204432,"timestampNanos":436284665}
{"name":"root","levelname":"DEBUG","severity":"DEBUG","message":"debug_fs: LookUpInode(1, \"Test\"): StatObject: not retrying StatObject(\"Test\"): googleapi: Error 400: Invalid bucket name: 'my-bucket/PBSBackups', invalid\n","timestampSeconds":1660204432,"timestampNanos":436313686}
{"name":"root","levelname":"ERROR","severity":"ERROR","message":"LookUpInode: input/output error, StatObject: not retrying StatObject(\"Test\"): googleapi: Error 400: Invalid bucket name: 'my-bucket/PBSBackups', invalid\n","timestampSeconds":1660204432,"timestampNanos":436334019}
{"name":"root","levelname":"DEBUG","severity":"DEBUG","message":"fuse_debug: Op 0x0000000a        connection.go:500] -\u003e Error: \"input/output error\"\n","timestampSeconds":1660204432,"timestampNanos":436378589}
{"name":"root","levelname":"ERROR","severity":"ERROR","message":"fuse: *fuseops.LookUpInodeOp error: input/output error\n","timestampSeconds":1660204432,"timestampNanos":436391767}


Thank you so much for your help.

**Comment by vadlakondaswetha** [comment]
Error says bucket name is invalid
```
Error 400: Invalid bucket name: 'my-bucket/PBSBackups'
```

Are you trying to mount a specific directory inside the bucket?  You should just pass the bucket name like my-bucket and not any sub-directory within the bucket.  In case you want to mount a specific directory under a bucket , use --only-dir=<directory-name> flag.

**Comment by mounssim** [comment]
Yes, "PBSBackups" is a directory within "my-bucket". what will be my flag in that case?

**Comment by vadlakondaswetha** [comment]
Use this command:

gcsfuse --debug_fs --debug_gcs --debug_fuse --debug_http --log-file=output.json --log-format=json --only-dir=PBSBackups my-bucket /mnt/GCPStorage/

**Comment by mounssim** [comment]
Hello @vadlakondaswetha,

Thanks a lot for your help all works good with gcsfuse but can't create a datastore which point that mount point.

at one point you said that you are not supporting 
![image](https://user-images.githubusercontent.com/103421662/184843786-71b864a8-9250-41e8-b44a-5f579e8ba96f.png)

Does that mean I can't use it all?

**Comment by vadlakondaswetha** [comment]
We haven't explicitly tested running GCSFuse with ProxMox backup server.  If you share the gcsfuse logs, it will help us understand what is causing the issue from GCSFuse side. Depending on the issue/fix and priority we can take it up as a bug or feature request.

**Comment by mounssim** [comment]
Please find refreshed logs:
[logs.zip](https://github.com/GoogleCloudPlatform/gcsfuse/files/9350531/logs.zip)

**Comment by mounssim** [comment]
@vadlakondaswetha and this what I have as error with PBS /GUI
![image](https://user-images.githubusercontent.com/103421662/184883227-c618a7e0-9a3d-4dd8-b88e-8537e3dc609a.png)

**Comment by mounssim** [comment]
@vadlakondaswetha I mange to create a datastore by adding --file-mode and --dir-mode to the mount command.
now I am having another issue which is related to atime this what they said on the proxmox forum:
![image](https://user-images.githubusercontent.com/103421662/185176333-529dadc3-5665-4c35-9627-b1aff6448008.png)

What do you think?

**Comment by vadlakondaswetha** [comment]
atime is currently not handled by gcsfuse: https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/semantics.md#missing-features  

GCS object by definition doesn't have atime property (https://cloud.google.com/storage/docs/json_api/v1/objects#resource-representations) and its becomes complex to handle it from gcsfuse side. Hence we are not supporting it and doesn't have any immediate plans to support it.

**Comment by avidullu** [comment]
Closing this issue since atime is not currently in scope for being added in gcsfuse.
Please reopen the bug or file a new one in case you need more help.
