### ISSUE TITLE
Use dashes instead of underscores in parameter names

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcsfuse#74]
I know a lot of Google-owned command-line tools use underscores for their parameter names, however GNU's standard is to separate arguments with dashes:

> Long options consist of ‘--’ followed by a name made of alphanumeric characters and dashes. Option names are typically one to three words long, with hyphens to separate words.

See http://www.gnu.org/software/libc/manual/html_node/Argument-Syntax.html

**Comment by jacobsa** [comment]
Nice catch, thanks. You're right that I let a Google-ism creep in.
