### ISSUE TITLE
Mounted bucket doesn't list files and folders created by a BigQuery export

### ISSUE THREAD

**Issue by wperron** [GoogleCloudPlatform/gcsfuse#765]
Hey folks 👋 I'm running gcsfuse version `c62530aa` on a GCE vm running Ubuntu 22.04. I'm mounting a bucket that contains a mix of objects that were created manually and objects that were created through BigQuery's `EXPORT DATA` feature. I can list the objects that were created manually, but if I try listing the files created by BigQuery, I get "no such file or directory". I initially thought it might have to do with the amount of objects in the folder (about 250k objects, totalling a little over 3TiB) but I also tested it out with a smaller export of a single file weighing a few KiBs and same error.

Here's the output from gcsfuse with debug flags running in foreground:

```text
fuse_debug: 2022/08/19 13:15:42.972232 Op 0x00000026        connection.go:416] <- LookUpInode (parent 1, name "REDACTED", PID 11252)
gcs: 2022/08/19 13:15:42.972373 Req              0x5: <- StatObject("REDACTED/")
gcs: 2022/08/19 13:15:42.972415 Req              0x6: <- StatObject("REDACTED")
gcs: 2022/08/19 13:15:42.993205 Req              0x6: -> StatObject("REDACTED") (20.786492ms): not retrying StatObject("REDACTED"): gcs.NotFoundError: googleapi: Error 404: No such object: REDACTED, notFound
gcs: 2022/08/19 13:15:42.996447 Req              0x5: -> StatObject("REDACTED/") (24.081294ms): not retrying StatObject("REDACTED/"): gcs.NotFoundError: googleapi: Error 404: No such object: REDACTED/, notFound
debug_fs: 2022/08/19 13:15:42.996480 LookUpInode(1, "REDACTED"): no such file or directory
fuse_debug: 2022/08/19 13:15:42.996559 Op 0x00000026        connection.go:500] -> Error: "no such file or directory"
```

I'm running gcsfuse with the following options:

```text
gcsfuse --debug_fuse --debug_gcs --debug_fs --uid 1005 --gid 1006 --foreground --limit-ops-per-sec 1000
```

Any help appreciated 🙂

**Comment by avidullu** [comment]
Could you please try with the --implicit-dirs=true flag to the gcsfuse mount command

**Comment by wperron** [comment]
Yup, that works 🤦 didn't RTFM properly, thanks for your help.
