### ISSUE TITLE
permission denied on local folder with gcsfuse

### ISSUE THREAD

**Issue by dan9thsense** [GoogleCloudPlatform/gcsfuse#767]
I tried to get gcsfuse to work, with the goal of mounting my gcs cloud bucket as a local drive on Ubuntu, just like I have my AWS S3 bucket mounted.  This is very similar to [issue 674](https://github.com/GoogleCloudPlatform/gcsfuse/issues/674)

I installed it according to these directions:
https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/installing.md

In testing, I ran into permissions problems:
gcsfuse ai-qtx gcs_cloud
2022/08/20 12:21:02.281962 Start gcsfuse/0.41.5 (Go version go1.18.4) for app "" using mount point: /home/dbarry/gcs_cloud
2022/08/20 12:21:02.295402 Opening GCS connection...
2022/08/20 12:23:53.363472 Failed to open connection: GetTokenSource: DefaultTokenSource: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
daemonize.Run: readFromProcess: sub-process: mountWithArgs: getConnWithRetry: GetTokenSource: DefaultTokenSource: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.

After trying a few things, got into the credentials stuff, created an API key, didn't work.  Created a JSON api key and that works.

With that the mount command goes through.  For example:
gcsfuse --key-file ~/keys_and_tokens/keys/gcloud_key.json ai-qtx gcs_cloud

But I am denied permission to view the folder!

Tried some more things (I setup export GOOGLE_APPLICATION_CREDENTIALS=~/keys_and_tokens/keys/gcloud_key.json in .bashrc, so I don't need that in the command line now):

gcsfuse --dir-mode 777 --file-mode 777 ai-qtx gcs_cloud
2022/08/20 13:10:29.631863 Start gcsfuse/0.41.5 (Go version go1.18.4) for app "" using mount point: /home/dbarry/gcs_cloud
2022/08/20 13:10:29.646652 Opening GCS connection...
2022/08/20 13:10:29.957897 Mounting file system "ai-qtx"...
2022/08/20 13:10:29.963623 File system has been successfully mounted.
$ cd gcs_cloud/
$ ls
ls: reading directory '.': Permission denied

And here I am stuck.

I ran 
gcsfuse --foreground --debug_fuse --debug_fs --debug_gcs --debug_http ai-qtx gcs_cloud
and the debug output is attached:
[gcpfuse_debug_log.txt](https://github.com/GoogleCloudPlatform/gcsfuse/files/9410374/gcpfuse_debug_log.txt)

I looked up the permissions error and see that I may need roles of storage.admin and storage.object.admin)
but I doubt that is the problem, since gsutil works OK.

However, if that is the issue, how do I add those roles?

**Comment by vadlakondaswetha** [comment]
Error message from the logs:
bucket-access@quantumtx.iam.gserviceaccount.com does not have storage.objects.get access to the Google Cloud Storage object.

GCSFuse is trying to access GCS using the service account creds: **bucket-access@quantumtx.iam.gserviceaccount.com**. Can you give required permissions to this service account to access the GCS bucket. 

gsutil might be using your creds to connect to GCS whereas GCSFuse is using service account mentioned in json file.

**Comment by dan9thsense** [comment]
"Can you give required permissions to this service account to access the GCS bucket."

How do I do that?  As I mentioned, it looks like it needs roles of storage.admin and storage.object.admin, but I don't know how to add those.

**Comment by vadlakondaswetha** [comment]
You can set it via UI or via command line
https://cloud.google.com/iam/docs/granting-changing-revoking-access#iam-view-access-console

example: https://docs.cloudera.com/HDPDocuments/HDP2/HDP-2.6.5/bk_cloud-data-access/content/edit-bucket-permissions.html

**Comment by dan9thsense** [comment]
Those are good ideas and links, thanks for the input.  However, storage_admin was already set for the service account and I don't see any options for storage.object.admin or anything else that looked related.

I did add roles such as "owner" but it didn't help.  Still get permission denied when trying to read files in the folder.

**Comment by vadlakondaswetha** [comment]
If you are setting it via UI, the role will be under
Cloud Storage > Storage Object Admin

By the way its called storage.objectAdmin not storage.object.admin
![image](https://user-images.githubusercontent.com/101323867/186347220-98b2d2fd-9c8b-4a6c-a022-abe909f6194d.png)

**Comment by dan9thsense** [comment]
Ah, found it, thanks.  There are two entries, storage.objectAdmin and storage.Admin Unfortunately, both were already set.

storage.Admin
26 assigned permissions
firebase.projects.get
orgpolicy.policy.get
resourcemanager.projects.get
resourcemanager.projects.list
storage.buckets.create
storage.buckets.createTagBinding
storage.buckets.delete
storage.buckets.deleteTagBinding
storage.buckets.get
storage.buckets.getIamPolicy
storage.buckets.list
storage.buckets.listEffectiveTags
storage.buckets.listTagBindings
storage.buckets.setIamPolicy
storage.buckets.update
storage.multipartUploads.abort
storage.multipartUploads.create
storage.multipartUploads.list
storage.multipartUploads.listParts
storage.objects.create
storage.objects.delete
storage.objects.get
storage.objects.getIamPolicy
storage.objects.list
storage.objects.setIamPolicy
storage.objects.update

storage.objectAdmin 
14 assigned permissions
orgpolicy.policy.get
resourcemanager.projects.get
resourcemanager.projects.list
storage.multipartUploads.abort
storage.multipartUploads.create
storage.multipartUploads.list
storage.multipartUploads.listParts
storage.objects.create
storage.objects.delete
storage.objects.get
storage.objects.getIamPolicy
storage.objects.list
storage.objects.setIamPolicy
storage.objects.update

**Comment by dan9thsense** [comment]
I may have found the problem.  The overall project account has these permissions, but the service account may not.  There is another service account in the project that does have the needed permissions.

"Cloud Storage Service Account
Each project has an associated Cloud Storage service account."

Our project already had a Cloud Storage Service Account with the needed permissions,  but now there is an additional service account for this new part of the project.  Somehow I have to get cloud storage permission for this service account or figure out how to apply the existing service account to this new part of the project.

**Comment by vadlakondaswetha** [comment]
you can go into cloud storage > buckets > select your bucket > permissions > ADD.
Then you can add the permissions for any service account.

**Comment by vadlakondaswetha** [comment]
alternatively you can generate key for the the service account which have the needed permissions and use that to mount the gcs bucket.
IAM & Admin > Service accounts > select the service account > keys > Add Key > Create new key

**Comment by dan9thsense** [comment]
And that was the trick!  I did that and now it works.  @vadlakondaswetha Thanks so much for your help with this.
