### ISSUE TITLE
Open File Descriptors

### ISSUE THREAD

**Issue by kris-fogle** [GoogleCloudPlatform/gcsfuse#774]
I'm using gcsfuse to periodically sync files from a server to a bucket. We have defined a tmp_dir that is 200GB in size, however the system reports the disk is full after gcsfuse runs as a service uninterrupted for a few days.

This appears to be due to file descriptors being left open after the files are deleted from the temp directory. Running df -h shows the disk is full, but no files are actually listed on the temp directory. 

Running lsof +L1 lists hundreds of files under the temp directory with the deleted status.

 - OS: Ubuntu 18.04.6 LTS
 - Platform VM
 - Version 0.41.5

**Comment by avidullu** [comment]
Can you please specify the flags that you are using to bring up gcsfuse?

**Comment by kris-fogle** [comment]
/usr/bin/gcsfuse --foreground -o allow_other,nonempty --implicit-dirs --temp-dir /mnt/gcs_tmp --uid 1002 --gid 1003 --file-mode 0770 --dir-mode 0770

**Comment by avidullu** [comment]
Can you please provide a bit more detail about how the sync files operations are being performed?

Do you mount a bucket locally, keep adding files to it and delete them at some frequency? Or delete an entire directory?

If you just do the operation for a single file i.e. start gcsfuse, sync a single file and then delete it do you observe the same file descriptors with lsof?

Can you enable some logs via --debug_fs --debug_fuse --debug_invariants --debug_mutex for a small set of files and post the logs here (or via --log-file and --log-format=json)

It'll help us reproduce the issue at our end and understand the issue better.

**Comment by sethiay** [comment]
Marking the issue as closed, given last response was more than 30 days ago. @kris-fogle, please feel free to open this issue and share details as mentioned in https://github.com/GoogleCloudPlatform/gcsfuse/issues/774#issuecomment-1233889557.
