### ISSUE TITLE
only some bucket folders mounted, others are missing or empty

### ISSUE THREAD

**Issue by dan9thsense** [GoogleCloudPlatform/gcsfuse#775]
After installing gcsfuse on both a local and a GCP instance,  I get the bucket to mount, but only a subset of the folders in the bucket show up.  And, in some of the ones that show up, their contents are empty.

Happens with both Ubuntu 18.04 and Ubuntu 20.04.

I cannot find anything that distinguish's the folders that show up from the ones that do not.

**Comment by dan9thsense** [comment]
After installing gcsfuse on both a local and a GCP instance,  I get the bucket to mount, but only a subset of the folders in the bucket show up.  And, in some of the ones that show up, their contents are empty.

Happens with both Ubuntu 18.04 and Ubuntu 20.04.

I cannot find anything that distinguish's the folders that show up from the ones that do not.

I have credentials setup, so the command is simply:
gcsfuse bucket local_gcp_bucket

I tried running with debugs: 
gcsfuse --foreground --debug_fuse --debug_fs --debug_gcs --debug_http gcp_bucket local_gcp_bucket

but it failed to mount with those options.

**Comment by dan9thsense** [comment]
Here is the console output from the debug run:

[gcsfuse_debug_output.txt](https://github.com/GoogleCloudPlatform/gcsfuse/files/9440908/gcsfuse_debug_output.txt)

**Comment by avidullu** [comment]
Could you retry with --implicit-dirs=true flag set?

**Comment by dan9thsense** [comment]
That did the trick.  They all show up now.  @avidullu Thanks!
