### ISSUE TITLE
GCSFUSE with Cloud Run getting fuse device not found error

### ISSUE THREAD

**Issue by WYGIN** [GoogleCloudPlatform/gcsfuse#787]
According to docs on [Google](https://cloud.google.com/run/docs/tutorials/network-filesystems-fuse) we can run Cloud Run with GCSFUSE.
but i am getting following error
```
Mounting GCS Fuse.
Using mount point: /var/lib/postgresql/data
Opening GCS connection...
Opening bucket...
Mounting file system...
daemonize.Run: readFromProcess: sub-process: mountWithArgs: mountWithConn: Mount: mount: running fusermount: exit status 1

stderr:
fusermount: fuse device not found, try 'modprobe fuse' first
```
I tried everything i found on internet but nothing useful.
> --privileged
> --cap-add SYS_ADMIN --device /dev/fuse 

But i dont know where to add them.
GCloud run deploy CLI too don't support such commands.
My docker Container don't have `/dev/fuse` file and i am unable add it to my container.
I tried adding `--cap-add SYS_ADMIN --device /dev/fuse ` in cloudbuild.yaml file with
```
gcloud run deploy --args="--cap-add SYS_ADMIN --device /dev/fuse" ...
```
But seems not working
Any helpful comments appreciated

**Comment by avidullu** [comment]
Have you also posted this question to the Cloud Run support team on [stackoverflow](https://stackoverflow.com/questions/tagged/google-cloud-run)? they seem to have a tag with the support and also [this question](https://stackoverflow.com/questions/70407189/unable-to-mount-bucket-with-gcsfuse-on-cloud-run) comes close to what you're observing as well.

**Comment by avidullu** [comment]
I'm not very sure about the gVisor but seems they have an [open issue](https://github.com/google/gvisor/issues/3678) for the same which hasn't got much traction. You may want to post this question to the gVisor github/stackoverflow.

**Comment by PaulWeb** [comment]
I've faced this problem and switching to gen2 solved it. Also I tried to run like in your example with SYS_ADMIN but it didn't work work with gen1.

**Comment by raj-prince** [comment]
Thanks @PaulWeb for the confirmation!

Closing this issue, since we have a solution using `--execution-environment gen2` which is also specified in [this](https://cloud.google.com/run/docs/tutorials/network-filesystems-fuse#ship-code) google doc.
