### ISSUE TITLE
mount.gcsfuse accepts flag `experimental_local_file_cache` as a string flag

### ISSUE THREAD

**Issue by songjiaxun** [GoogleCloudPlatform/gcsfuse#788]
**Describe the bug**
The flag [`experimental_local_file_cache`](https://github.com/GoogleCloudPlatform/gcsfuse/blob/93be0283a31070b17bb1a36e2884bc87fa8db4f4/tools/mount_gcsfuse/main.go#L103) should treated as a bool flag, not a string flag.

**Comment by avidullu** [comment]
Will be fixed in next release.
