### ISSUE TITLE
gcsfuse left my mount point in a crazy state

### ISSUE THREAD

**Issue by squee1945** [GoogleCloudPlatform/gcsfuse#79]
So, I have very little to go on, but look at the state of my mount point:

```
$ ls -l
ls: cannot access bucket: Transport endpoint is not connected
total 60M
d????????? ? ?       ?          ?            ? bucket
```

Can't delete it either:

```
$ sudo rmdir bucket
rmdir: failed to remove `bucket': Device or resource busy
```

Has anyone seen this? How can I provide more detail?

**Comment by jacobsa** [comment]
This looks like the gcsfuse process was killed somehow but you didn't unmount the file system. You didn't mention what system you're running on, but try one of these:

    sudo umount bucket
    fusermount -u bucket

Sometimes fuse gets wedged and refuses to unmount until you abort the fuse session. Here's a one liner that will abort all fuse file systems currently mounted (be careful):

    for t in /sys/fs/fuse/connections/*/abort; do echo 1 > $t; done

**Comment by jacobsa** [comment]
(Closing because I think this is just the way fuse and Linux/OS X mounting work. Let me know if it appears to be gcsfuse doing something wrong, though.)
