### ISSUE TITLE
Installation documentation issues

### ISSUE THREAD

**Issue by douwekiela** [GoogleCloudPlatform/gcsfuse#800]
**Describe the bug**
I followed the installation instructions verbatim on Debian bullseye and got an error about a missing Release file:

```
$ export GCSFUSE_REPO=gcsfuse-`lsb_release -c -s`
$ echo "deb http://packages.cloud.google.com/apt $GCSFUSE_REPO main" | sudo tee /etc/apt/sources.list.d/gcsfuse.list
$ curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
deb http://packages.cloud.google.com/apt gcsfuse-bullseye main
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2537  100  2537    0     0   154k      0 --:--:-- --:--:-- --:--:--  154k
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
OK
$ sudo apt update
Hit:1 http://packages.cloud.google.com/apt cloud-sdk-bullseye InRelease
Hit:2 http://packages.cloud.google.com/apt google-cloud-packages-archive-keyring-bullseye InRelease
Hit:3 http://deb.debian.org/debian bullseye InRelease
Hit:4 http://security.debian.org/debian-security bullseye-security InRelease
Ign:5 http://packages.cloud.google.com/apt gcsfuse-bullseye InRelease
Hit:6 http://packages.cloud.google.com/apt google-compute-engine-bullseye-stable InRelease
Hit:7 http://deb.debian.org/debian bullseye-updates InRelease
Err:8 http://packages.cloud.google.com/apt gcsfuse-bullseye Release
  404  Not Found [IP: 74.125.202.100 80]
Hit:9 http://deb.debian.org/debian bullseye-backports InRelease
Reading package lists... Done
E: The repository 'http://packages.cloud.google.com/apt gcsfuse-bullseye Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

Then I tried to install the .deb via dpkg, but the URL is incorrect and needs to be updated with what is in https://github.com/GoogleCloudPlatform/gcsfuse/releases. It says to install from `https://github.com/GoogleCloudPlatform/gcsfuse/releases/download/v%400.41.6/gcsfuse_0.41.6_amd64.deb` but the correct URL is `https://github.com/GoogleCloudPlatform/gcsfuse/releases/download/v0.41.6/gcsfuse_0.41.6_amd64.deb`.

**To Collect more Debug logs**
Try installing gcsfuse on a recent GCP Debian VM.

**System (please complete the following information):**
Linux my-machine 5.10.0-17-cloud-amd64 #1 SMP Debian 5.10.136-1 (2022-08-13) x86_64 GNU/Linux
 - OS: Debian bullseye
 - Platform: VM

**Comment by avidullu** [comment]
This is a known issue and we are working on it.
Currently to continue with the installation you can change the GCSFUSE_REPO to below and continue with the rest of the instructions and you will be able to use GCSFuse.
`export GCSFUSE_REPO=gcsfuse-buster`

**Comment by avidullu** [comment]
Should work now.
