### ISSUE TITLE
Cannot write file larger than 16Gb

### ISSUE THREAD

**Issue by bsergean** [GoogleCloudPlatform/gcsfuse#806]
**Describe the bug**
I am trying to write a large file (20G) to a mounted GCS folder, but the upload stop making any progress once I am at around 16G, as if there was some kind of system limit around that size.

**System**
 - OS: [Ubuntu 18.04]
 - Platform [VM]
 - Version [0.41.6 (Go version go1.18.4)]

**Comment by raj-prince** [comment]
Hi @bsergean,

I also tried to simulate the same workflow. I have uploaded a 20GB file to GCS bucket using gcsfuse. It took around 10-12 minutes and uploaded successfully.

**System Info I tried:**

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic
Version 0.41.6 (Go version go1.18.4)

We need more information regarding this issue. Can you please check or provide the logs by mounting the gcsfuse with **--foreground --debug_fuse --debug_fs --debug_gcs --debug_http**  flags and try uploading the 20GB file again? This would help us more in resolving the issue.

**Comment by bsergean** [comment]
Thanks a.lot for giving this a try !
I will try again today ; I have some progress report, but maybe it’s poorly implemented and lie when telling the progress is almost done while it isn’t.

**Comment by raj-prince** [comment]
Sure, please keep us posted, will wait for the update. Thanks!
