### ISSUE TITLE
GCSfuse doesn't sync all the sub-directories

### ISSUE THREAD

**Issue by danvimeo** [GoogleCloudPlatform/gcsfuse#829]
**Bug description:**
I use gcsfuse to mount a GCS bucket into a GKE pod, and the 3rd level of the sub-directories is not synced.

**To Collect more Debug logs**
e.g in GCS we have a bucket with the following structure: `gs://bucket/dir1/dir2/dir3`

I don't see `dir3` on or any of its files on my mnt path.
This is the same for all the directories in the 3rd level.
When I run `mkdir -p /mnt/test/dir1/dir2/dir3` I see the folder and all of its files.

**System**
 - OS: Ubuntu 16.04.7 LTS
 - Platform: Kubernetes
 - Version gcsfuse version 0.41.7 (Go version go1.18.4)

**Additional context**
I saw the same issue with gcsfuse version 0.28.1 (Go version go1.9.7)
[issue 491](https://github.com/GoogleCloudPlatform/gcsfuse/issues/491)

**Comment by vadlakondaswetha** [comment]
Did you try mounting GCSFuse with --implicit-dirs flag (https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/semantics.md#implicit-directories).

**Comment by danvimeo** [comment]
with --implicit-dirs flag the mout fails

**Comment by vadlakondaswetha** [comment]
Can you share the logs of gcsfuse by enabling --debug_gcs, --debug_fuse, --debug_fs, --debug_http flags

**Comment by sethiay** [comment]
Closing the issue since we haven't heard back from the customer.
