### ISSUE TITLE
The repository 'http://packages.cloud.google.com/apt gcsfuse-jammy Release' does not have a Release file.

### ISSUE THREAD

**Issue by cboneti** [GoogleCloudPlatform/gcsfuse#838]
**Describe the bug**
Following the instructions [here](https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/installing.md#ubuntu-and-debian-latest-releases) does not work for Ubuntu 2204 as present on GCP image family (family: ubuntu-2204-lts, project: ubuntu-os-cloud). 
```
The repository 'http://packages.cloud.google.com/apt gcsfuse-jammy Release' does not have a Release file.
```

**To Collect more Debug logs**

    1  export GCSFUSE_REPO=gcsfuse-`lsb_release -c -s`
    2  echo "deb http://packages.cloud.google.com/apt $GCSFUSE_REPO main" | sudo tee /etc/apt/sources.list.d/gcsfuse.list
    3  cat /etc/apt/sources.list.d/gcsfuse.list
    4  sudo apt-get update

This results in: 
```
Err:5 http://packages.cloud.google.com/apt gcsfuse-jammy Release           
  404  Not Found [IP: 173.194.193.101 80]
Hit:6 http://security.ubuntu.com/ubuntu jammy-security InRelease
Reading package lists... Done                        
E: The repository 'http://packages.cloud.google.com/apt gcsfuse-jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**System (please complete the following information):**
 - OS: Ubuntu 22.04
 - Platform: VM: n2-standard-2

**Comment by Tulsishah** [comment]
We have updated our configuration. you can check it now it is working.

**Comment by cboneti** [comment]
Thanks, we tested it and it all works fine.
