### ISSUE TITLE
exec: "fusermount": executable file not found in $PATH

### ISSUE THREAD

**Issue by mbookman** [GoogleCloudPlatform/gcsfuse#84]
Trying to use gcsfuse on GCE, I get: 

2015/06/26 19:13:56.422166 mount: Mount: bazilfuse.Mount: fusermount: exec: "fusermount": executable file not found in $PATH

So I installed "fuse":

sudo apt-get install fuse

We should list this as a dependency in the documentation.

FWIW, my gcfuse setup script for a clean GCE install with the debian-7-backports image is:

#!/bin/bash

set -o errexit
set -o nounset

if ! test -f /bin/fusermount; then
  sudo apt-get update
  sudo apt-get install --yes fuse
fi

if ! test -d /usr/local/go; then
  # First install GO
  readonly VERSION=1.4.2
  readonly OS=linux
  readonly ARCH=amd64

  readonly GOFILE=go$VERSION.$OS-$ARCH.tar.gz

  curl -O https://storage.googleapis.com/golang/${GOFILE}
  sudo tar -C /usr/local -xzf ${GOFILE}

fi
export PATH=$PATH:/usr/local/go/bin

\# Now install git
if ! which git; then
  sudo apt-get update
  sudo apt-get install --yes git
fi

\# Now install gcsfuse
GOPATH=${HOME}/go/gcsfuse go get github.com/googlecloudplatform/gcsfuse

**Comment by jacobsa** [comment]
This is in the docs, [here](https://github.com/googlecloudplatform/gcsfuse/blob/master/docs/installing.md#fuse). Is it missing somewhere else?

By the way, consider using `ubuntu-15-04`, which is considerably less ancient.

**Comment by mbookman** [comment]
Wow. I skimmed^H^H^H^H^H^H^Hread the README.md several times and missed the pointers to the prerequisites. Also I had seen installing.md, but the first heading at the top was regarding MacOS, and I neglected to read further.

I just submitted PR https://github.com/GoogleCloudPlatform/gcsfuse/pull/85 with some suggested formatting changes. 

Thanks Aaron!
