### ISSUE TITLE
Web Server(Nginx) can not write in mount dir

### ISSUE THREAD

**Issue by Mr-Buding** [GoogleCloudPlatform/gcsfuse#872]
Hello.
           I mounted the bucket to compute engine vm via gcsfuse and then ran the nginx program in the vm. Normally the nginx program writes the cache to the directory, i.e. the mounted bucket, using the proxy_cache directive.
          However, I have a problem that nginx can create cache files in the filesystem under the bucket directory, but the size of the cache file is always 0B. client requests keep getting "Miss cache" status.
           So it seems that after mounting with gcsfuse, the Nginx application can only create cache files, but cannot write to them.

My vm environment is.
Machine type: n2-standard-2
CPU platform: Intel Cascade Lake
Architecture: x86/64
System: ubuntu-1804

In addition, gcsfuse has specified a service account with owner privileges via the --key-file directive, and the nginx program has been run with the root user.

For example, the following debug log is an empty file (8/2b/0a7ed71cddee71b9276a0d72a030f2b8) created in the bucket after a client request and not written to the cache. What could be the cause of this possibility?

**Comment by Mr-Buding** [comment]
https://storage.googleapis.com/cloud_cdn_cache_bucket/debug_log.txt

Here is the debug log obtained by the command --debug_fuse --debug_fs --debug_gcs --debug_http -foreground.

**Comment by Tulsishah** [comment]
In the gcsfuse logs we don't find any read or write calls after the file creation. so we suspect there would be some another app/cache/program layer which is handling read or write calls. 

Just a follow up question do you also see this issue with normal file system(not gcsfuse mounted) ?

**Comment by Mr-Buding** [comment]
> In the gcsfuse logs we don't find any read or write calls after the file creation. so we suspect there would be some another app/cache/program layer which is handling read or write calls.
> 
> Just a follow up question do you also see this issue with normal file system(not gcsfuse mounted) ?

 Hello, thank you very much for your reply. 
I have tested it: on a machine without gcsfuse mounted, the same Nginx application can create and write cache files normally.

**Comment by raj-prince** [comment]
We have a complete answer for this issue.
Please refere: https://stackoverflow.com/questions/74918407/nginx-cannot-write-cache-content-to-the-gcsfuse-mount-directory

**Comment by sethiay** [comment]
After having internal discussion, we think that this is not a gcsfuse issue as the calls are not coming to GCSFuse. Please re-open if you face any issues related to GCSFuse.
