### ISSUE TITLE
Add a flag for an explicit credentials key file

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcsfuse#90]
`gcsfuse --help` doesn't show me any flag I can pass to set a path to a credentials (`.json`) file... What do I do?

**Comment by jacobsa** [comment]
The official [application default credentials](https://developers.google.com/identity/protocols/application-default-credentials#howtheywork) flow gets this from an environment variable (`GOOGLE_APPLICATION_CREDENTIALS`). This is discussed in the documentation on mounting [here](https://github.com/GoogleCloudPlatform/gcsfuse/blob/c01f87a80d38ca4703eb0de320872960d648f859/docs/mounting.md#credentials). Let me know if you have suggestions for making the documentation clearer.

**Comment by jgeewax** [comment]
Err... What if I want to be explicit in the call? Seems weird that the only
way to pass in creds is to set the env variable.....

Can we add a flag to pass in a keyfile path ... ?

**Comment by jacobsa** [comment]
I've just gone with what is nominally _the_ flow for Google applications; I'm wary of straying from that. Is it not explicit enough for you to stick it in the invocation like this?

```bash
GOOGLE_APPLICATION_CREDENTIALS=key.json gcsfuse my-bucket /mount/point
```

**Comment by jacobsa** [comment]
(By the way, I think the idea is that you shouldn't often be doing this, and instead should be using GCE service account credentials most of the time.)

**Comment by jgeewax** [comment]
This isn't straying. We do this in gcloud-* also.

Seems like the line setting the env var might be better as a command line
flag for the binary.... No?

**Comment by jacobsa** [comment]
Sorry, what is gcloud-*? Can you link to some examples?

**Comment by jgeewax** [comment]
Check GoogleCloudPlatform/gcloud-node

**Comment by jacobsa** [comment]
I guess you're talking about the `keyFilename` property in config structs, as documented [here](https://googlecloudplatform.github.io/gcloud-node/#/authorization)? I suppose it makes sense to have an analogous flag, if only to ensure that it's discoverable in the help text. Okay.

**Comment by jgeewax** [comment]
Woo :+1: !
