### ISSUE TITLE
Unable to use borg with gcsfuse

### ISSUE THREAD

**Issue by mcaceresb** [GoogleCloudPlatform/gcsfuse#942]
**Describe the bug**

I use `borg` to create backups that I store on google cloud, mounted via `gcsfuse`. Sometime last year this stopped working, and whenever I try to use `borg` I get the error `failed to acquire lock (timeout).`

**To Collect more Debug logs**

```
gcsfuse home-backup /home/mauricio/home-backup
cd /home/mauricio/home-backup
borg init --encryption=repokey test
```

I ran this with options `--debug_fuse --debug_fs --debug_gcs --debug_http --foreground` and got his log file: [gcsfuse-borg.log](https://github.com/GoogleCloudPlatform/gcsfuse/files/10777780/gcsfuse-borg.log). I can see that `borg` tries to create `lock.exclusive` and then cannot find the file; however, at least locally, the files do get created (and then disappear). At the end of the process, `borg` is able to create some files (including some files that the log says were not found, like `config` and `README`).

**System (please complete the following information):**
 - Arch Linux (6.1.11-arch1-1)
 - Version 0.41.10-1

**Additional context**
I initially reported this issue in borgbackup/borg/issues/7366 but it was suggested this was a `gcsfuse` issue, so I am reporting it here.

**Comment by vadlakondaswetha** [comment]
From the logs, i can see its trying to create lock.exclusive using rename operation:

`
{"name":"root","levelname":"DEBUG","severity":"DEBUG","message":"fuse_debug: Op 0x0000009c        connection.go:416] \u003c- Rename (PID 96224, old_parent 2, old_name \"lock.exclusive.jmfwjagk.tmp\", new_parent 2, new_name \"lock.exclusive\")
{"name":"root","levelname":"DEBUG","severity":"DEBUG","message":"fuse_debug: Op 0x0000009c        connection.go:500] -\u003e Error: \"too many open files\"
`



Can you set rename-dir-limit flag to appropriate value while doing the mount.
https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/flags.go#L128
https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/semantics.md#missing-features

**Comment by mcaceresb** [comment]
@vadlakondaswetha Thank you; this worked.
