### ISSUE TITLE
gcsfuse would not return

### ISSUE THREAD

**Issue by akcchoi** [GoogleCloudPlatform/gcsfuse#97]
Hi all,

I'm trying to mount GCS storage on a compute/VM instance following the instruction here:
https://cloud.google.com/storage/docs/gcs-fuse

Compute instance runs on pre-built Debian Jessie image.

When I try to use gcsfuse to mount, the program would not return:

andykc_choi@fuse-1:~$ gcsfuse ac_test1 gcs2015/07/31 07:48:11.556418 Warning: low file rlimit of 1024 will cause cached content to be frequently evicted. Consider raising with `ulimit -n`.2015/07/31 07:48:11.634597 File system has been successfully mounted.

I ran strace and it does not seem to be stuck with a system call:
clock_gettime(CLOCK_REALTIME, {1438328923, 204555874}) = 0clock_gettime(CLOCK_MONOTONIC, {698, 650900621}) = 0clock_gettime(CLOCK_REALTIME, {1438328923, 204587260}) = 0clock_gettime(CLOCK_MONOTONIC, {698, 650941000}) = 0clock_gettime(CLOCK_REALTIME, {1438328923, 204629249}) = 0write(3, "\316S\1\0\0\1\0\0\0\0\0\0\10metadata\6google\10int"..., 42) = 42read(3, 0xc82008e400, 512) = -1 EAGAIN (Resource temporarily unavailable)futex(0xc82002aa08, FUTEX_WAKE, 1) = 1futex(0xb806a0, FUTEX_WAIT, 0, NULL2015/07/31 07:48:43.208059 Warning: low file rlimit of 1024 will cause cached content to be frequently evicted. Consider raising with `ulimit -n`.2015/07/31 07:48:43.282860 File system has been successfully mounted.

/dev/fuse seems to be set correctly:
crw-rw---T 1 root fuse 10, 229 Jul 31 07:39 /dev/fuse

User group membership seems to be ok:
andykc_choi@fuse-1:~$ sudo adduser andykc_choi fuseThe user `andykc_choi' is already a member of `fuse'.

Would anyone has some insight?

Many thanks,
Andy

**Comment by jacobsa** [comment]
It's intended that `gcsfuse` doesn't return control; it doesn't daemonize itself, and stays in the foreground until the file system is unmounted and it exits. If you want it to become a daemon, you should use a wrapper such as [daemon](http://libslack.org/daemon/). See [mounting.md](https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/mounting.md) for more documentation.
