### ISSUE TITLE
Installation failing in Docker using google CloudRun example code  

### ISSUE THREAD

**Issue by reidadam** [GoogleCloudPlatform/gcsfuse#976]
**Describe the bug**
Installation now failing using example from https://cloud.google.com/run/docs/tutorials/network-filesystems-fuse#defining_your_environment_configuration_with_the_dockerfile

Seems to be a problem since version 0.42.0

**DOCKERFILE**
```
FROM python:3.10-buster

RUN set -e; \
    apt-get update -y && apt-get install -y \
    tini \
    lsb-release; \
    gcsFuseRepo=gcsfuse-`lsb_release -c -s`; \
    echo "deb http://packages.cloud.google.com/apt $gcsFuseRepo main" | \
    tee /etc/apt/sources.list.d/gcsfuse.list; \
    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | \
    apt-key add -; \
    apt-get update; \
    apt-get install -y gcsfuse \
    && apt-get clean
```

1. Create a dockerfile with the content above
2. run `docker build -t cloudrun_example:latest  --no-cache  .`
3. see error in logs

```
#0 22.00 Preparing to unpack .../gcsfuse_0.42.0_amd64.deb ...
#0 22.01 # This to enforce logrotate to run as root/adm. In ubuntu distributions, the
#0 22.01 # ownership of the file created via rsyslog is syslog hence, we need to add
#0 22.01 # this explicitly.
#0 22.01 su root adm
#0 22.01 
#0 22.01 # packages drop hourly log rotation information into this directory
#0 22.01 include /etc/logrotate.hourly.d
#0 22.02 tee: /etc/cron.hourly/gcsfuse-logrotate: No such file or directory
#0 22.02 #!/bin/bash
#0 22.02 test -x /usr/sbin/logrotate || exit 0
#0 22.02 /usr/sbin/logrotate /etc/logrotate.hourly.conf
#0 22.02 Please install linux package - cron
#0 22.02 dpkg: error processing archive /var/cache/apt/archives/gcsfuse_0.42.0_amd64.deb (--unpack):
#0 22.02  new gcsfuse package pre-installation script subprocess returned error exit status 1
#0 22.04 Errors were encountered while processing:
#0 22.04  /var/cache/apt/archives/gcsfuse_0.42.0_amd64.deb
```

**System (please complete the following information):**
 - OS: [Ubuntu 20.04]
 - Platform [Docker]
 - Version [gcsfuse_0.42.0_amd64.deb]

**Additional context**
gcsfuse_0.41.2_amd64.deb works

**Comment by Tulsishah** [comment]
Thanks, @reidadam, for reaching out to us. Currently, we are working on it. We will let you know after the fix.

**Comment by aamarques** [comment]
Same here

**Comment by jordan-loopla** [comment]
Honestly, I thought I was going crazy, thank god it's not just me 🤣

**Comment by aartiukh** [comment]
Temp workaround 

```
ENV GCS_FUSE_VERSION=0.41.12

RUN curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add - && \
    curl -LJO "https://github.com/GoogleCloudPlatform/gcsfuse/releases/download/v${GCS_FUSE_VERSION}/gcsfuse_${GCS_FUSE_VERSION}_amd64.deb" && \
    apt-get -y install fuse && \
    dpkg -i "gcsfuse_${GCS_FUSE_VERSION}_amd64.deb"
```

**Comment by v1p** [comment]
> Temp workaround
> 
> ```dockerfile
> ENV GCS_FUSE_VERSION=0.41.12
> 
> RUN curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add - && \
>     curl -LJO "https://github.com/GoogleCloudPlatform/gcsfuse/releases/download/v${GCS_FUSE_VERSION}/gcsfuse_${GCS_FUSE_VERSION}_amd64.deb" && \
>     apt-get -y install fuse && \
>     dpkg -i "gcsfuse_${GCS_FUSE_VERSION}_amd64.deb"
> ```

Thanks @aartiukh 
Locking the version is the right thing to do 👍

**Comment by koi8** [comment]
Same problem with centos 7 image. If I also install `cronie` (as a new `cron` requirement) it fails with another systemd related error. And of course I don't want to have systemd in the docker image:
```
Logrotate config for gcsfuse updated successfully!
Syslog config for gcsfuse updated successfully!
Failed to get D-Bus connection: Operation not permitted
error: %pre(gcsfuse-0.42.0-1.x86_64) scriptlet failed, exit status 1
```

**Comment by raj-prince** [comment]
Apologies for the inconvenience here and thanks for bringing this up!!

Issue is fixed in the latest release package. Please let us know, if anyone still facing the issue.
