### ISSUE TITLE
Add "gcsfuse" to the tags for the StackExchange support process

### ISSUE THREAD

**Issue by judkowitz** [GoogleCloudPlatform/gcsfuse#98]

**Comment by judkowitz** [comment]
Also, please remove the google-cloud-storage tag.

**Comment by judkowitz** [comment]
More issues here with the text.

1) The text should say ServerFault, not StackExchange

2) The link to the tagged questions does not work in the questions/tagged URL.  The + between two tags does not work.  The site throws away the + and everything after it only using the first tag.   Actual queries do allow multiple tags.  So, the link should be
http://serverfault.com/search?q=google-cloud-platform+gcsfuse

**Comment by jacobsa** [comment]
The link does appear to work from my end—I see only questions tagged with both `google-cloud-platform` and `google-cloud-storage`. But I'll change it to use `gcsfuse` instead.

**Comment by judkowitz** [comment]
Hmmm...   You seem to be correct.  No idea why that did not work for me before.  But, it works now as you say it does.   I guess we can go with the original idea
http://serverfault.com/questions/tagged/gcsfuse+google-cloud-platform
