### ISSUE TITLE
Pod is getting restart once during gcsfuse mount + Secret manager property loading in Spring Boot.

### ISSUE THREAD

**Issue by ramesh-krishnan-metro** [GoogleCloudPlatform/gcsfuse#987]
**Describe the bug**
The pod is getting restarted once during gcsfuse mount + Secret manager property loading in Spring Boot. 
After the first restart, Pod is coming into a running state, the no issue. But 1 Restart status is not convenient to see at all times.

`apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-file
  namespace: mquality
  labels:
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: spring-file
  template:
    metadata:
      labels:
        app: spring-file
    spec:
      serviceAccountName: workload-identity-ksa
      automountServiceAccountToken: false
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
      terminationGracePeriodSeconds: 60
      containers:
      - name: spring-file
        image: eu.gcr.io/<gcp_project>/spring-file:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        livenessProbe:
          failureThreshold: 7
          httpGet:
            httpHeaders:
            - name: Authorization
              value: Basic ZHVtbXk6ZHVtbXk
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 90
          successThreshold: 1
          timeoutSeconds: 15
        readinessProbe:
          failureThreshold: 7
          httpGet:
            httpHeaders:
            - name: Authorization
              value: Basic ZHVtbXk6ZHVtbXk
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 15
        securityContext:
          privileged: true
          capabilities:
            add:
              - SYS_ADMIN
        lifecycle:
          postStart:
            exec:
              command:
                - /bin/sh
                - -c
                - mkdir -p /mnt && gcsfuse my-app-bucket-store /mnt
          preStop:
            exec:
              command:
                - /bin/sh
                - -c
                - sleep 60 && fusermount -u /mnt`
Spring boot Secret Manager property access
in application.properties.

`spring.cloud.gcp.secretmanager.enabled=true

esourcing.username=${sm://APP_USERNAME}
esourcing.password=${sm://APP_PASSWORD}`

**To Collect more Debug logs**
1. Please make sure you have no other security, monitoring, background processes which can offend the FUSE process running. Possibly reproduce under a fresh/clean installation.
2. Please rerun with --debug_fuse --debug_fs --debug_gcs --debug_http --foreground as additional flags to enable debug logs.
3. Monitor the logs and please capture screenshots or copy the relevant logs to a file (can use --log-format and --log-file as well).
4. Attach the screenshot or the logs file to the bug report here.
5. If you're using gcsfuse with any other library/tool/process please list out the steps you took to reproduce the issue.

**System (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04]
 - Platform [VM, Kubernetes]
 - Version [e.g. 0.41]

**Additional context**

**Comment by raj-prince** [comment]
Hi @ramesh-krishnan-metro,

I don't see the restart logs. Can you please add more details to simulate the behavior?

Also, if possible can you please attach the gcsfuse-logs for the first mount and mount after restart. To enable the gcsfuse logs you can pass `--debug_fuse --debug_fs --debug_gcs` while mounting the bucket.

Thanks,
Prince

**Comment by ramesh-krishnan-metro** [comment]
Hi @raj-prince

Thanks for looking into, here is the log.

spring-file-64c4595b9f-w9ngb   2/2     Running       **1 (102s ago)**    108s


`Events:
  Type     Reason               Age   From               Message
  ----     ------               ----  ----               -------
  Normal   Scheduled            56s   default-scheduler  Successfully assigned mquality/spring-file-8555955ffb-2f4g6 to gke-app-gke-cluster-default-pool-3bb429a5-f1r2
  Normal   Pulled               55s   kubelet            Container image "docker.io/istio/proxyv2:1.16.2" already present on machine
  Normal   Created              55s   kubelet            Created container istio-init
  Normal   Started              55s   kubelet            Started container istio-init
  Normal   Pulled               53s   kubelet            Successfully pulled image "eu.gcr.io/lustrous-bus-376910/spring-file:latest" in 408.898335ms
  Warning  FailedPostStartHook  44s   kubelet            Exec lifecycle hook ([/bin/sh -c mkdir -p /mnt && gcsfuse -o rw -o allow_other -file-mode=777 -dir-mode=777 --foreground --debug_gcs --debug_http --debug_fuse --debug_invariants my-app-bucket-store /mnt]) for Container "spring-file" in Pod "spring-file-8555955ffb-2f4g6_mquality(eefcaade-5811-42b2-8db2-5bf2ccb6d60e)" failed - error: command '/bin/sh -c mkdir -p /mnt && gcsfuse -o rw -o allow_other -file-mode=777 -dir-mode=777 --foreground --debug_gcs --debug_http --debug_fuse --debug_invariants my-app-bucket-store /mnt' exited with 137: 2023/03/09 13:55:42.516894 Opening GCS connection...
2023/03/09 13:55:42.542159 Retrying ListObjects("") after error of type *url.Error ("Get \"https://www.googleapis.com/storage/v1/b/my-app-bucket-store/o?maxResults=1&projection=full\": Get \"http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdevstorage.full_control\": dial tcp 169.254.169.254:80: connect: connection refused") in 779.41µs
2023/03/09 13:55:42.543595 Retrying ListObjects("") after error of type *url.Error ("Get \"https://www.googleapis.com/storage/v1/b/my-app-bucket-store/o?maxResults=1&projection=full\": Get \"http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdevstorage.full_control\": dial tcp 169.254.169.254:80: connect: connection refused") in 153.551µs
2023/03/09 13:55:42.544913 Retrying ListObjects("") after error of type *url.Error ("Get \"https://www.googleapis.com/storage/v1/b/my-app-bucket-store/o?maxResults=1&projection=full\": Get \"http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdevstorage.full_control\": dial tcp 169.254.169.254:80: connect: connection refused") in 2.145821ms
2023/03/09 13:55:42.548675 Retrying ListObjects("") after error of type *url.Error ("Get \"https://www.googleapis.com/storage/v1/b/my-app-bucket-store/o?maxResults=1&projection=full\": Get \"http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdevstorage.full_control\": dial tcp 169.254.169.254:80: connect: connection refused") in 3.010051ms
2023/03/09 13:55:42.552353 Retrying ListObjects("") after error of type *url.Error ("Get \"https://www.googleapis.com/storage/v1/b/my-app-bucket-store/o?maxResults=1&projection=full\": Get \"http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdevstorage.full_control\": dial tcp 169.254.169.254:80: connect: connection refused") in 15.113937ms
2023/03/09 13:55:42.568961 Retrying ListObjects("") after error of type *url.Error ("Get \"https://www.googleapis.com/storage/v1/b/my-app-bucket-store/o?maxResults=1&projection=full\": Get \"http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdevstorage.full_control\": dial tcp 169.254.169.254:80: connect: connection refused") in 5.16732ms
2023/03/09 13:55:42.575826 Retrying ListObjects("") after error of type *url.Error ("Get \"https://www.googleapis.com/storage/v1/b/my-app-bucket-store/o?maxResults=1&projection=full\": Get \"http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdevstorage.full_control\": dial tcp 169.254.169.254:80: connect: connection refused") in 16.969758ms
2023/03/09 13:55:42.593594 Retrying ListObjects("") after error of type *url.Error ("Get \"https://www.googleapis.com/storage/v1/b/my-app-bucket-store/o?maxResults=1&projection=full\": Get \"http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdevstorage.full_control\": dial tcp 169.254.169.254:80: connect: connection refused") in 83.776148ms
2023/03/09 13:55:42.678294 Retrying ListObjects("") after error of type *url.Error ("Get \"https://www.googleapis.com/storage/v1/b/my-app-bucket-store/o?maxResults=1&projection=full\": Get \"http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdevstorage.full_control\": dial tcp 169.254.169.254:80: connect: connection refused") in 255.117216ms
2023/03/09 13:55:42.933993 Retrying ListObjects("") after error of type *url.Error ("Get \"https://www.googleapis.com/storage/v1/b/my-app-bucket-store/o?maxResults=1&projection=full\": Get \"http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdevstorage.full_control\": dial tcp 169.254.169.254:80: connect: connection refused") in 416.279449ms
2023/03/09 13:55:43.352975 Retrying ListObjects("") after error of type *url.Error ("Get \"https://www.googleapis.com/storage/v1/b/my-app-bucket-store/o?maxResults=1&projection=full\": Get \"http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdevstorage.full_control\": dial tcp 169.254.169.254:80: connect: connection refused") in 488.398084ms
2023/03/09 13:55:43.848723 Retrying ListObjects("") after error of type *url.Error ("Get \"https://www.googleapis.com/storage/v1/b/my-app-bucket-store/o?maxResults=1&projection=full\": Get \"http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdevstorage.full_control\": dial tcp 169.254.169.254:80: connect: connection refused") in 263.669287ms
2023/03/09 13:55:44.113923 Retrying ListObjects("") after error of type *url.Error ("Get \"https://www.googleapis.com/storage/v1/b/my-app-bucket-store/o?maxResults=1&projection=full\": Get \"http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdevstorage.full_control\": dial tcp 169.254.169.254:80: connect: connection refused") in 1.476491574s
2023/03/09 13:55:45.598733 Retrying ListObjects("") after error of type *url.Error ("Get \"https://www.googleapis.com/storage/v1/b/my-app-bucket-store/o?maxResults=1&projection=full\": Get \"http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdevstorage.full_control\": dial tcp 169.254.169.254:80: connect: connection refused") in 7.958458836s
, message: "2023/03/09 13:55:42.516804 Using mount point: /mnt\n\nWARNING: gcsfuse invoked as root. This will cause all files to be owned by\nroot. If this is not what you intended, invoke gcsfuse as the user that will\nbe interacting with the file system.\n2023/03/09 13:55:42.541838 Set up root directory for bucket my-app-bucket-store\n2023/03/09 13:55:42.541869 OpenBucket(\"my-app-bucket-store\", \"\")\ngcs: 2023/03/09 13:55:42.541882 Req              0x0: <- ListObjects(\"\")\n2023/03/09 13:55:42.516894 Opening GCS connection...\n2023/03/09 13:55:42.542159 Retrying ListObjects(\"\") after error of type *url.Error (\"Get \\\"https://www.googleapis.com/storage/v1/b/my-app-bucket-store/o?maxResults=1&projection=full\\\": Get \\\"http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdevstorage.full_control\\\": dial tcp 169.254.169.254:80: connect: connection refused\") in 779.41µs\n2023/03/09 13:55:42.543595 Retrying ListObjects(\"\") after error of type *url.Error (\"Get \\\"https://www.googleapis.com/storage/v1/b/my-app-bucket-store/o?maxResults=1&projection=full\\\": Get \\\"http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdevstorage.full_control\\\": dial tcp 169.254.169.254:80: connect: connection refused\") in 153.551µs\n2023/03/09 13:55:42.544913 Retrying ListObjects(\"\") after error of type *url.Error (\"Get \\\"https://www.googleapis.com/storage/v1/b/my-app-bucket-store/o?maxResults=1&projection=full\\\": Get \\\"http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdevstorage.full_control\\\": dial tcp 169.254.169.254:80: connect: connection refused\") in 2.145821ms\n2023/03/09 13:55:42.548675 Retrying ListObjects(\"\") after error of type *url.Error (\"Get \\\"https://www.googleapis.com/storage/v1/b/my-app-bucket-store/o?maxResults=1&projection=full\\\": Get \\\"http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdevstorage.full_control\\\": dial tcp 169.254.169.254:80: connect: connection refused\") in 3.010051ms\n2023/03/09 13:55:42.552353 Retrying ListObjects(\"\") after error of type *url.Error (\"Get \\\"https://www.googleapis.com/storage/v1/b/my-app-bucket-store/o?maxResults=1&projection=full\\\": Get \\\"http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdevstorage.full_control\\\": dial tcp 169.254.169.254:80: connect: connection refused\") in 15.113937ms\n2023/03/09 13:55:42.568961 Retrying ListObjects(\"\") after error of type *url.Error (\"Get \\\"https://www.googleapis.com/storage/v1/b/my-app-bucket-store/o?maxResults=1&projection=full\\\": Get \\\"http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdevstorage.full_control\\\": dial tcp 169.254.169.254:80: connect: connection refused\") in 5.16732ms\n2023/03/09 13:55:42.575826 Retrying ListObjects(\"\") after error of type *url.Error (\"Get \\\"https://www.googleapis.com/storage/v1/b/my-app-bucket-store/o?maxResults=1&projection=full\\\": Get \\\"http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdevstorage.full_control\\\": dial tcp 169.254.169.254:80: connect: connection refused\") in 16.969758ms\n2023/03/09 13:55:42.593594 Retrying ListObjects(\"\") after error of type *url.Error (\"Get \\\"https://www.googleapis.com/storage/v1/b/my-app-bucket-store/o?maxResults=1&projection=full\\\": Get \\\"http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdevstorage.full_control\\\": dial tcp 169.254.169.254:80: connect: connection refused\") in 83.776148ms\n2023/03/09 13:55:42.678294 Retrying ListObjects(\"\") after error of type *url.Error (\"Get \\\"https://www.googleapis.com/storage/v1/b/my-app-bucket-store/o?maxResults=1&projection=full\\\": Get \\\"http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdevstorage.full_control\\\": dial tcp 169.254.169.254:80: connect: connection refused\") in 255.117216ms\n2023/03/09 13:55:42.933993 Retrying ListObjects(\"\") after error of type *url.Error (\"Get \\\"https://www.googleapis.com/storage/v1/b/my-app-bucket-store/o?maxResults=1&projection=full\\\": Get \\\"http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdevstorage.full_control\\\": dial tcp 169.254.169.254:80: connect: connection refused\") in 416.279449ms\n2023/03/09 13:55:43.352975 Retrying ListObjects(\"\") after error of type *url.Error (\"Get \\\"https://www.googleapis.com/storage/v1/b/my-app-bucket-store/o?maxResults=1&projection=full\\\": Get \\\"http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdevstorage.full_control\\\": dial tcp 169.254.169.254:80: connect: connection refused\") in 488.398084ms\n2023/03/09 13:55:43.848723 Retrying ListObjects(\"\") after error of type *url.Error (\"Get \\\"https://www.googleapis.com/storage/v1/b/my-app-bucket-store/o?maxResults=1&projection=full\\\": Get \\\"http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdevstorage.full_control\\\": dial tcp 169.254.169.254:80: connect: connection refused\") in 263.669287ms\n2023/03/09 13:55:44.113923 Retrying ListObjects(\"\") after error of type *url.Error (\"Get \\\"https://www.googleapis.com/storage/v1/b/my-app-bucket-store/o?maxResults=1&projection=full\\\": Get \\\"http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdevstorage.full_control\\\": dial tcp 169.254.169.254:80: connect: connection refused\") in 1.476491574s\n2023/03/09 13:55:45.598733 Retrying ListObjects(\"\") after error of type *url.Error (\"Get \\\"https://www.googleapis.com/storage/v1/b/my-app-bucket-store/o?maxResults=1&projection=full\\\": Get \\\"http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdevstorage.full_control\\\": dial tcp 169.254.169.254:80: connect: connection refused\") in 7.958458836s\n"
  Normal   Pulling            44s (x2 over 54s)  kubelet  Pulling image "eu.gcr.io/lustrous-bus-376910/spring-file:latest"
  Normal   Killing            44s                kubelet  FailedPostStartHook
  Warning  FailedPreStopHook  44s                kubelet  Exec lifecycle hook ([/bin/sh -c sleep 60 && fusermount -u /mnt]) for Container "spring-file" in Pod "spring-file-8555955ffb-2f4g6_mquality(eefcaade-5811-42b2-8db2-5bf2ccb6d60e)" failed - error: rpc error: code = Unknown desc = failed to exec in container: failed to create exec "d5c31075d7f87d306b05355a7dfe44339baaaf0c0e986c3894db47bcbeef2b31": cannot exec in a stopped state: unknown, message: ""
  Normal   Pulled             44s                kubelet  Container image "docker.io/istio/proxyv2:1.16.2" already present on machine
  Normal   Created            44s                kubelet  Created container istio-proxy
  Normal   Started            44s                kubelet  Started container istio-proxy
  Normal   Created            43s (x2 over 53s)  kubelet  Created container spring-file
  Normal   Started            43s (x2 over 53s)  kubelet  Started container spring-file
  Warning  Unhealthy          43s                kubelet  Readiness probe failed: Get "http://10.32.0.16:15021/healthz/ready": dial tcp 10.32.0.16:15021: connect: connection refused
  Normal   Pulled             43s                kubelet  Successfully pulled image "eu.gcr.io/lustrous-bus-376910/spring-file:latest" in 474.978509ms`

**Comment by raj-prince** [comment]
Hi @ramesh-krishnan-metro,

I don't see any logs for successful mounting of gcsfuse, all we can see we are getting connection refuse issue. Mostly, restart is happening at GKE level based on the failure. 

Is there any way to setup the same environment using docker container? It would be good if you provide the steps for that. In the mean time, I'll try to reproduce this.

Here, the main question is - why are we getting connection refusing in mounting process? Could you please try doing curl or wget on the url in the logs and see if any issue with connection?

Thanks!
Prince.

**Comment by ramesh-krishnan-metro** [comment]
hi @raj-prince , i committed sample application here : https://github.com/rameshkrishnanme/spring-gcs-secret-manager-issue. please try to deploy in kubernetes and check.

**Comment by raj-prince** [comment]
Hi @ramesh-krishnan-metro,

Before that, can you please check why **"dial tcp 169.254.169.254:80: connect: connection refused"** error is coming? Did you try using with **curl** command?

-Prince

**Comment by raj-prince** [comment]
Hi @ramesh-krishnan-metro,

I tried to create the GKE cluster deployments from the code you shared, but not able see the issue and logs you shared. This is due to I have limited knowledge of GKE cluster/deployments.

It would be good if you could provide the instructions/commands to create the cluster and how we can narrow down to the issues in the GKE deployment environments.

Specifically,
1. Command to create the cluster?
2. Command to apply the deployment config?
3. Command to access the pods on which gcsfuse is failing the first time?
4. How to access the logs of the pods on which gcsfuse is running?

Also, Did you get time to see why `connection refused` is coming? Since, this got fixed automatically after first restart, it seems like some network configuration is not applied correctly till the first mount process. It is more about the network issue and very less likely that issue is in the GCSFuse. You might try curl command to connect with GCS [List object endpoint](https://cloud.google.com/storage/docs/json_api/v1/buckets/list), instead of mounting via GCSFuse.

Regards,
Prince Kumar.

**Comment by raj-prince** [comment]
Just to add: the recommended approach to use GCSFuse in Kubernetes environment is through Cloud Storage Fuse CSI driver.
Please checkout [this](https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/cloud-storage-fuse-csi-driver) .

And please refer [this](https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/cloud-storage-fuse-csi-driver#troubleshooting) in case you face any issues.
