### ISSUE TITLE
gcsfuse 0.42.1 cannot find directory/file

### ISSUE THREAD

**Issue by keith-plant** [GoogleCloudPlatform/gcsfuse#989]
Hi,

I am running a Python service on a Kubernetes cluster. The service needs to be able to pull zip files from a cloud bucket and extract from that zip file. The service uses "zipfile" to do this. 

Using gcsfuse 0.41.12 this worked without issue. The file paths that are used look like : "/directory/directory/file.zip" and the service account has sufficient permissions to view the directory and object

After (automatically) being upgraded to 0.42.1 the read operation now returns 'FileNotFoundError: [Errno 2] No such file or directory: /directory/directory/file.zip'

gcsfuse is run with the "--implicit-dirs" flag

When trying to start gcsfuse 0.42.1 the following output is shown:

```
INFO 2023-03-06T06:03:38.239582862Z [resource.labels.containerName: otm] 2023/03/06 06:03:38.238221 Start gcsfuse/0.42.1 (Go version go1.19.5) for app "" using mount point: /eo-products-incoming

INFO 2023-03-06T06:03:38.285830092Z [resource.labels.containerName: otm] 2023/03/06 06:03:38.273728 Opening GCS connection...

ERROR 2023-03-06T06:03:38.482864510Z [resource.labels.containerName: otm] daemonize.Run: readFromProcess: Decode: EOF
```

 - Platform: Kubernetes
 - Version: 0.42.1

**Comment by keith-plant** [comment]
I should add that downgrading to 0.41.12 fixed the issue

**Comment by raj-prince** [comment]
Hi @keith-plant, 

Thanks for reaching out!

It seems like mounting is not successful. Can you please share the gcsfuse logs? To enable the gcsfuse-logs you need to pass '--debug_fs --debug_fuse --debug_gcs --log-file=<file_name> --log-format=text' flags while mounting.

Also, passing `--enable-storage-client-library=false' flag might resolve this issue. You can give it a try instead of downgrading. Please let us know, the behavior in this scenario.

Regards,
Prince

**Comment by raj-prince** [comment]
Hi @keith-plant,

Could you please provide the logs for this? We are in the process fixing similar issue - but in this case we are getting proper error message. Just wanted to make sure about that, it would be a great help if you will provide the log message for this. Thanks a lot!!

-Prince

**Comment by keith-plant** [comment]
Hi,

My apologies the for slow response. 

Before diving into the logs, if we use the suggest parameter "--enable-storage-client-library=false" then everything seems to run as expected. (I can provide the logs for this as well, if needed)

Without that flag, and after running with the suggest debug flags: “--debug_fs --debug_fuse --debug_gcs --log-file=/etc/gcsfuse.log --log-format=text“ there wasn't much to show, as it seems to have stopped before writing the logfile. Only the parameter "--foreground" brought some light into the darkness:

`exec gcsfuse --debug_fs --debug_fuse --debug_gcs --log-file=/etc/gcsfuse.log --log-format=text --foreground --implicit-dirs $BUCKET_NAME /bucket-name

 

panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa889ff]

 

goroutine 1 [running]:

[github.com/googlecloudplatform/gcsfuse/internal/storage/storageutil.convertACLRuleToObjectAccessControl(..](http://github.com/googlecloudplatform/gcsfuse/internal/storage/storageutil.convertACLRuleToObjectAccessControl(..).)

        /tmp/build_gcsfuse_gopath3986937209/src/[github.com/googlecloudplatform/gcsfuse/internal/storage/storageutil/object_attrs.go:48](http://github.com/googlecloudplatform/gcsfuse/internal/storage/storageutil/object_attrs.go:48)

[github.com/googlecloudplatform/gcsfuse/internal/storage/storageutil.ObjectAttrsToBucketObject(0xc0008e0000)](http://github.com/googlecloudplatform/gcsfuse/internal/storage/storageutil.ObjectAttrsToBucketObject(0xc0008e0000))

        /tmp/build_gcsfuse_gopath3986937209/src/[github.com/googlecloudplatform/gcsfuse/internal/storage/storageutil/object_attrs.go:58](http://github.com/googlecloudplatform/gcsfuse/internal/storage/storageutil/object_attrs.go:58) +0x5ff

[github.com/googlecloudplatform/gcsfuse/internal/storage.(*bucketHandle).ListObjects(0xc000862660](http://github.com/googlecloudplatform/gcsfuse/internal/storage.(*bucketHandle).ListObjects(0xc000862660), {0x11648d0, 0xc00013c0c8}, 0xc000100aa0)

        /tmp/build_gcsfuse_gopath3986937209/src/[github.com/googlecloudplatform/gcsfuse/internal/storage/bucket_handle.go:245](http://github.com/googlecloudplatform/gcsfuse/internal/storage/bucket_handle.go:245) +0x2aa

[github.com/googlecloudplatform/gcsfuse/vendor/github.com/jacobsa/gcloud/gcs.(*debugBucket).ListObjects(0xc0007ea2a0](http://github.com/googlecloudplatform/gcsfuse/vendor/github.com/jacobsa/gcloud/gcs.(*debugBucket).ListObjects(0xc0007ea2a0), {0x11648d0, 0xc00013c0c8}, 0xc000100aa0)

        /tmp/build_gcsfuse_gopath3986937209/src/[github.com/googlecloudplatform/gcsfuse/vendor/github.com/jacobsa/gcloud/gcs/debug_bucket.go:207](http://github.com/googlecloudplatform/gcsfuse/vendor/github.com/jacobsa/gcloud/gcs/debug_bucket.go:207) +0x16b

[github.com/googlecloudplatform/gcsfuse/vendor/github.com/jacobsa/gcloud/gcs/gcscaching.(*fastStatBucket).ListObjects(0xc0000aacc0](http://github.com/googlecloudplatform/gcsfuse/vendor/github.com/jacobsa/gcloud/gcs/gcscaching.(*fastStatBucket).ListObjects(0xc0000aacc0), {0x11648d0?, 0xc00013c0c8?}, 0xc00088f101?)

        /tmp/build_gcsfuse_gopath3986937209/src/[github.com/googlecloudplatform/gcsfuse/vendor/github.com/jacobsa/gcloud/gcs/gcscaching/fast_stat_bucket.go:219](http://github.com/googlecloudplatform/gcsfuse/vendor/github.com/jacobsa/gcloud/gcs/gcscaching/fast_stat_bucket.go:219) +0x34

[github.com/googlecloudplatform/gcsfuse/internal/gcsx.(*bucketManager).SetUpBucket(0xc000452360](http://github.com/googlecloudplatform/gcsfuse/internal/gcsx.(*bucketManager).SetUpBucket(0xc000452360), {0x11648d0, 0xc00013c0c8}, {0x7ffc43e6fe6e?, 0xc000134428?})

        /tmp/build_gcsfuse_gopath3986937209/src/[github.com/googlecloudplatform/gcsfuse/internal/gcsx/bucket_manager.go:248](http://github.com/googlecloudplatform/gcsfuse/internal/gcsx/bucket_manager.go:248) +0x5c4

[github.com/googlecloudplatform/gcsfuse/internal/fs.NewFileSystem({0x11648d0](http://github.com/googlecloudplatform/gcsfuse/internal/fs.NewFileSystem(%7B0x11648d0), 0xc00013c0c8}, 0xc00059f5e8)

        /tmp/build_gcsfuse_gopath3986937209/src/[github.com/googlecloudplatform/gcsfuse/internal/fs/fs.go:167](http://github.com/googlecloudplatform/gcsfuse/internal/fs/fs.go:167) +0x47a

[github.com/googlecloudplatform/gcsfuse/internal/fs.NewServer({0x11648d0](http://github.com/googlecloudplatform/gcsfuse/internal/fs.NewServer(%7B0x11648d0)?, 0xc00013c0c8?}, 0xc00088f5e8)

        /tmp/build_gcsfuse_gopath3986937209/src/[github.com/googlecloudplatform/gcsfuse/internal/fs/server.go:28](http://github.com/googlecloudplatform/gcsfuse/internal/fs/server.go:28) +0x2f

main.mountWithConn({0x11648d0, 0xc00013c0c8}, {0x7ffc43e6fe6e, 0x24}, {0x7ffc43e6fe93, 0x15}, 0xc0004c09a0, 0x203000?, {0x1159d80, 0xc000014110}, ...)

        /tmp/build_gcsfuse_gopath3986937209/src/[github.com/googlecloudplatform/gcsfuse/mount.go:122](http://github.com/googlecloudplatform/gcsfuse/mount.go:122) +0x4ba

main.mountWithArgs({0x7ffc43e6fe6e, 0x24}, {0x7ffc43e6fe93, 0x15}, 0xc0004c09a0, 0xc00059f788?)

        /tmp/build_gcsfuse_gopath3986937209/src/[github.com/googlecloudplatform/gcsfuse/main.go:205](http://github.com/googlecloudplatform/gcsfuse/main.go:205) +0x2d2

main.runCLIApp(0x1836d30?)

        /tmp/build_gcsfuse_gopath3986937209/src/[github.com/googlecloudplatform/gcsfuse/main.go:369](http://github.com/googlecloudplatform/gcsfuse/main.go:369) +0xf25

main.run.func1(0x1?)

        /tmp/build_gcsfuse_gopath3986937209/src/[github.com/googlecloudplatform/gcsfuse/main.go:404](http://github.com/googlecloudplatform/gcsfuse/main.go:404) +0x25

[github.com/googlecloudplatform/gcsfuse/vendor/github.com/urfave/cli.HandleAction({0xcd6640](http://github.com/googlecloudplatform/gcsfuse/vendor/github.com/urfave/cli.HandleAction(%7B0xcd6640)?, 0xc00006e2a0?}, 0xc0000c48c0?)

        /tmp/build_gcsfuse_gopath3986937209/src/[github.com/googlecloudplatform/gcsfuse/vendor/github.com/urfave/cli/app.go:526](http://github.com/googlecloudplatform/gcsfuse/vendor/github.com/urfave/cli/app.go:526) +0x50

[github.com/googlecloudplatform/gcsfuse/vendor/github.com/urfave/cli.(*App).Run(0xc0000c48c0](http://github.com/googlecloudplatform/gcsfuse/vendor/github.com/urfave/cli.(*App).Run(0xc0000c48c0), {0xc000138000, 0xa, 0xa})

        /tmp/build_gcsfuse_gopath3986937209/src/[github.com/googlecloudplatform/gcsfuse/vendor/github.com/urfave/cli/app.go:286](http://github.com/googlecloudplatform/gcsfuse/vendor/github.com/urfave/cli/app.go:286) +0x7ca

main.run()

        /tmp/build_gcsfuse_gopath3986937209/src/[github.com/googlecloudplatform/gcsfuse/main.go:408](http://github.com/googlecloudplatform/gcsfuse/main.go:408) +0xcb

main.main()

        /tmp/build_gcsfuse_gopath3986937209/src/[github.com/googlecloudplatform/gcsfuse/main.go:426](http://github.com/googlecloudplatform/gcsfuse/main.go:426) +0x4a

command terminated with exit code 2`

**Comment by sethiay** [comment]
Thanks @keith-plant for sharing the logs. We are working on fix for this and planning to release it with the next GCSFuse release. We will update here once fixed.

**Comment by sethiay** [comment]
The fix for this issue has been released in the latest GCSFuse release i.e. [v0.42.2](https://github.com/GoogleCloudPlatform/gcsfuse/releases/tag/v0.42.2). With GCSFuse v0.42.2, you can skip passing --enable-storage-client-library=false flag.
Marking this issue as closed. Please feel free to re-open in case you face the same issue again.

Thanks for your patience !
